#!/bin/sh
### BEGIN INIT INFO
# Provides:          dietpi-service
# Required-Start:    $local_fs
# Should-Start:
# Required-Stop:     $local_fs
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       DietPi boot shutdown reboot.
### END INIT INFO

#-- commands for update --
#update-rc.d -f dietpi-service remove
#rm /etc/init.d/dietpi-service
#cp /DietPi/dietpi/conf/dietpi-service /etc/init.d/dietpi-service
#chmod +x /etc/init.d/dietpi-service
#update-rc.d dietpi-service defaults 00 80

NAME="dietpi-service"

DietPi_Ramlog_Save(){

	#save directory structure of /var/log (so we can re-create them after tmpfs mounts /var/log)
	find /var/log -type d > /DietPi/dietpi/.log_directories

}

DietPi_Ramlog_Load(){

	#write directory structure back to /var/log
	if [ -f /DietPi/dietpi/.log_directories ]; then
		while read line           
		do           
			mkdir -p "$line" &> /dev/null
		done < /DietPi/dietpi/.log_directories

	#Create default structure
	else
		mkdir -p /var/log/apt &> /dev/null
		mkdir -p /var/log/fsck &> /dev/null
	fi

}

start(){

	#Copy DietPi to ramdisk
	if [ ! -f /DietPi/.ramdisk ]; then 

		#Copy DietPi globals/scripts to RAM
		echo "DietPi: Starting Ramdisk"
		/boot/dietpi/dietpi-ramdisk 0

		#Generate active flag
		echo -e "0" > /DietPi/.ramdisk

		#DietPi Ramlog
		echo "DietPi: Starting DietPi-Ramlog"
		DietPi_Ramlog_Load
 		
		#start bootup
		/DietPi/dietpi/boot
	fi

}

stop(){

	#Copy DietPi back to Disk 
	if [ -f /DietPi/.ramdisk ]; then

		#Run DietPi logclear/backup if required (from cron job)
		/etc/cron.hourly/dietpi

		#DietPi Ramlog
		echo "DietPi: Stopping DietPi-Ramlog"
		DietPi_Ramlog_Save

		#remove active flag.
		echo "DietPi: Stopping Ramdisk"
		rm /DietPi/.ramdisk &> /dev/null
		
		#Copy DietPi globals/scripts back to DISK
		/DietPi/dietpi/dietpi-ramdisk 1
	fi

}

remove(){
    stop
    update-rc.d -f "$NAME" remove
    rm -fv "$0"
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	remove)
		remove
	;;
	restart)
		stop
		start
	;;
	*)
		echo "Usage: $0 {start|stop}"
	;;
esac