#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Raspimjpeg control Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	# Info:
	# - Location /etc/raspimjpeg_init
	# - Allows service control for Raspimjpeg and PHP schedule, used by RPI Camera Web
	# - Called from /DietPi/dietpi/dietpi-services
	#
	#////////////////////////////////////

	Raspimjeg_Stop(){
		killall -w raspimjpeg &> /dev/null
		killall -w php &> /dev/null
	}

	Raspimjeg_Start(){
		mkdir -p /dev/shm/mjpeg
		chown www-data:www-data /dev/shm/mjpeg
		chmod 777 /dev/shm/mjpeg

		sleep 1
		sudo -u www-data raspimjpeg > /dev/null &

		sleep 1
		sudo -u www-data php /var/www/dietpicam/schedule.php > /dev/null &
	}

	if [ "$1" = "stop" ] || [ "$1" = "restart" ]; then
		Raspimjeg_Stop
	fi

	if [ "$1" = "start" ] || [ "$1" = "restart" ]; then
		Raspimjeg_Start
	fi

	exit

}