#!/bin/bash
{
	#////////////////////////////////////
	# DietPi ntp control Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	# Info:
	# - Enables us to use NTP -q (quit when done) command. Saving 3.18mb ram.
	# why? = When NTPd runs as a system service, it hangs boot when the -q command is used with no internet access (ntp BUG).
	# - Location /etc/ntp_init
	# - Allows "bug free" service control for NTPd
	# - Called from /boot/dietpi/dietpi-services
	# - Called from /etc/cron.daily/ntp
	#
	#////////////////////////////////////

	INPUT=$1

	Ntp_Stop(){
		killall ntpd &> /dev/null
	}

	Ntp_Start(){
		ntpd -gq &> /dev/null &
	}

	if [ "$1" = "stop" ] || [ "$1" = "restart" ]; then
		Ntp_Stop
	fi

	if [ "$1" = "start" ] || [ "$1" = "restart" ]; then
		Ntp_Stop
		Ntp_Start
	fi

	exit

}