#!/bin/bash
#////////////////////////////////////
# DietPi OpenTyrian Run Script
#
#////////////////////////////////////
# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
#
# Info:
# - Starts OpenTyrian 
# - Starts X if not already running
#
# Usage:
# /boot/dietpi/conf/opentyrian_run
#////////////////////////////////////

#Xserver already running
if (($(pidof X) >= 0)); then
	/usr/local/games/opentyrian/opentyrian -t /usr/local/games/opentyrian/data
#No X (init X server)
else
	xinit /usr/local/games/opentyrian/opentyrian -t /usr/local/games/opentyrian/data
fi