#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Cron.Daily script
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location: /etc/cron.daily/dietpi
	#
	#////////////////////////////////////

	#----------------------------------------------------------------
	# Main Loop
	#----------------------------------------------------------------
	# Sync system time, if mode 2 (daily) is detected
	grep -q '^[[:blank:]]*CONFIG_NTP_MODE=2' /boot/dietpi.txt && /boot/dietpi/func/run_ntpd 1
	#----------------------------------------------------------------
	# Check for DietPi updates
	grep -q '^[[:blank:]]*CONFIG_CHECK_DIETPI_UPDATES=1' /boot/dietpi.txt && /boot/dietpi/dietpi-update 2
	#----------------------------------------------------------------
	# Refresh DietPi MOTD
	if [[ -f '/boot/dietpi/.dietpi-banner' ]] && grep -q '^[[:blank:]]*aENABLED\[12\]=1' /boot/dietpi/.dietpi-banner; then

		curl -sSL https://dietpi.com/motd > /tmp/.dietpi_motd

	fi
	#----------------------------------------------------------------
	# DietPi-Sync daily
	if [[ -f '/boot/dietpi/.dietpi-sync_settings' ]] && grep -q '^[[:blank:]]*SYNC_CRONDAILY=1' /boot/dietpi/.dietpi-sync_settings; then

		/boot/dietpi/dietpi-sync 1

	fi
	#----------------------------------------------------------------
	exit
	#----------------------------------------------------------------
} > /dev/null
