#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Cron.Daily script
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location /etc/cron.daily/dietpi
	#
	#////////////////////////////////////

	#----------------------------------------------------------------
	# Main Loop
	#----------------------------------------------------------------
	#Time sync update, if mode 2 (daily) is detected
	if grep -qi '^[[:blank:]]*CONFIG_NTP_MODE=2' /DietPi/dietpi.txt; then

		/DietPi/dietpi/func/run_ntpd &> /dev/null &

	fi
	#----------------------------------------------------------------
	#check for dietpi updates
	if grep -qi '^[[:blank:]]*CONFIG_CHECK_DIETPI_UPDATES=1' /DietPi/dietpi.txt; then

		/DietPi/dietpi/dietpi-update 2 &> /dev/null &

	fi
	#----------------------------------------------------------------
	#DietPi-Sync daily
	if [[ -f /DietPi/dietpi/.dietpi-sync_settings ]] &&
		(( $(sed -n 5p /DietPi/dietpi/.dietpi-sync_settings) == 1 )); then

		/DietPi/dietpi/dietpi-sync 1 &> /dev/null &

	fi
	#----------------------------------------------------------------
	exit
	#----------------------------------------------------------------
}
