#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Cron.Daily script
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location: /etc/cron.daily/dietpi
	#
	#////////////////////////////////////

	#----------------------------------------------------------------
	# Main Loop
	#----------------------------------------------------------------
	# Sync system time if mode 2 (daily) is detected
	grep -q '^[[:blank:]]*CONFIG_NTP_MODE=2' /boot/dietpi.txt && /boot/dietpi/func/run_ntpd 1
	#----------------------------------------------------------------
	# Check for DietPi and/or updates
	if grep -q '^[[:blank:]]*CONFIG_CHECK_DIETPI_UPDATES=1' /boot/dietpi.txt
	then
		/boot/dietpi/dietpi-update 2
	else
		mode=$(sed -n '/^[[:blank:]]*CONFIG_CHECK_DIETPI_UPDATES=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
		[[ -f '/run/dietpi/.apt_updates' ]] && rm /run/dietpi/.apt_updates
		[[ $mode == [12] ]] && G_AGUP && count=$(apt -qq list --upgradeable | wc -l) && (( $count )) && echo $count > /run/dietpi/.apt_updates
		[[ $mode == 2 ]] && (( $count )) && G_AGUG &> /var/tmp/dietpi/logs/dietpi-upgrade_apt.log && rm /run/dietpi/.apt_updates
	fi
	#----------------------------------------------------------------
	# Refresh DietPi MOTD
	if [[ -f '/boot/dietpi/.dietpi-banner' ]] && grep -q '^[[:blank:]]*aENABLED\[12\]=1' /boot/dietpi/.dietpi-banner
	then
		curl -sSfL https://dietpi.com/motd > /run/dietpi/.dietpi_motd
	fi
	#----------------------------------------------------------------
	# DietPi-Sync daily
	if [[ -f '/boot/dietpi/.dietpi-sync_settings' ]] && grep -q '^[[:blank:]]*SYNC_CRONDAILY=1' /boot/dietpi/.dietpi-sync_settings
	then
		/boot/dietpi/dietpi-sync 1
	fi
	#----------------------------------------------------------------
	exit
	#----------------------------------------------------------------
} > /dev/null
