# DO NOT EDIT THIS FILE
#
# Please edit /boot/dietpiEnv.txt to set supported parameters
#
# If you must, edit /boot/boot.cmd and recompile /boot/boot.scr with:
# mkimage -C none -A arm64 -T script -d /boot/boot.cmd /boot/boot.scr

# Default values
setenv rootdev "/dev/mmcblk2p1"
setenv rootfstype "ext4"
setenv consoleargs "console=ttySAC0,115200 console=tty1"
setenv verbosity "4"
setenv docker_optimizations "off"

# Load addresses
setenv fdt_addr_r "0x48000000"
setenv ramdisk_addr_r "0x49000000"
setenv kernel_addr_r "0x4a000000"

# Load dietpiEnv.txt
if test -e ${devtype} ${devnum} ${prefix}dietpiEnv.txt; then
	ext4load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}dietpiEnv.txt
	env import -t ${kernel_addr_r} ${filesize}
fi

# Define kernel command-line arguments
setenv bootargs "root=${rootdev} rootfstype=${rootfstype} rootwait ${consoleargs} loglevel=${verbosity} consoleblank=0 systemd.unified_cgroup_hierarchy=0 usb-storage.quirks=${usbstoragequirks} ${extraargs}"

# Add bootargs for Docker
if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=memory swapaccount=1"; fi

# Load device tree, initramfs and kernel
ext4load ${devtype} ${devnum} ${fdt_addr} ${prefix}dtb/nexell/${fdtfile}
ext4load ${devtype} ${devnum} ${ramdisk_addr_r} ${prefix}uInitrd
ext4load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}Image

# Boot
booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}
