#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - change_hostname
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Used to change hostname on system
	# - no exit code return, or status.
	#
	# Usage:
	# - /DietPi/dietpi/func/change_hostname sNEWHOSTNAME
	#////////////////////////////////////

	#Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
	LANG=en_GB.UTF-8

	#/////////////////////////////////////////////////////////////////////////////////////
	#Change Hostname
	#/////////////////////////////////////////////////////////////////////////////////////
	HOSTNAME_CURRENT=$(cat /etc/hostname)
	HOSTNAME_NEW=$1

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	sed -i "s/$HOSTNAME_CURRENT/$HOSTNAME_NEW/g" /etc/hosts
	sed -i "s/$HOSTNAME_CURRENT/$HOSTNAME_NEW/g" /etc/hostname

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}