#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - change_hostname
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Used to change hostname on system
	# - no exit code return, or status.
	#
	# Usage:
	# - /DietPi/dietpi/func/change_hostname sNEWHOSTNAME
	#////////////////////////////////////
	#Import DietPi-Globals ---------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	G_CHECK_ROOT_USER
	G_CHECK_ROOTFS_RW
	export G_PROGRAM_NAME='DietPi-Change_hostname'
	G_INIT
	#Import DietPi-Globals ---------------------------------------------------------------

	#/////////////////////////////////////////////////////////////////////////////////////
	#Change Hostname
	#/////////////////////////////////////////////////////////////////////////////////////
	HOSTNAME_NEW="$1"

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	cat << _EOF_ > /etc/hosts
127.0.0.1 localhost
127.0.1.1 $HOSTNAME_NEW
_EOF_

	cat << _EOF_ > /etc/hostname
$HOSTNAME_NEW
_EOF_

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}