#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - check_connection
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Used to check a url connection is valid with wget spider
	# - Timeout and Retry count prevents endless waiting if HTTP request is delayed/broken .
	# - Returns exit code 0 if successful
	#
	# Usage:
	# - /DietPi/dietpi/func/check_connection sURL
	#////////////////////////////////////

	#Import DietPi-Globals ---------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	#Import DietPi-Globals ---------------------------------------------------------------

	INTERNET_ADDRESS=$1
	TIMEOUT=10
	RETRYCOUNT=2

	EXIT_CODE=0

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	dietpi-notify 2 "Testing connection to $INTERNET_ADDRESS"
	dietpi-notify 2 "Max duration of $(($TIMEOUT * $RETRYCOUNT)) seconds, please wait..."

	wget -q --spider --timeout="$TIMEOUT" --tries="$RETRYCOUNT" "$INTERNET_ADDRESS"

	#--no-check-certificate
	#https://github.com/Fourdee/DietPi/issues/352#issuecomment-221013166

	EXIT_CODE=$?
	dietpi-notify -1 $EXIT_CODE "Connection test |"

	#-----------------------------------------------------------------------------------
	#return exit code
	exit $EXIT_CODE
	#-----------------------------------------------------------------------------------
}