#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - check_connection
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Used to check a url connection is valid with wget spider
	# - Timeout and Retry count prevents endless waiting if HTTP request is delayed/broken .
	# - Returns exit code 0 if successful
	#
	# Usage:
	# - /DietPi/dietpi/func/check_connection sURL
	#////////////////////////////////////

	INTERNET_ADDRESS=$1
	TIMEOUT=8
	RETRYCOUNT=2

	EXIT_CODE=0

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	echo -e "\nTesting connection to $INTERNET_ADDRESS, please wait..... "

	wget -q --spider --timeout="$TIMEOUT" --tries="$RETRYCOUNT" "$INTERNET_ADDRESS"

	EXIT_CODE=$?
	if (( $EXIT_CODE == 0 )); then
		#Inform user
		echo -e "Successful!\n"
	fi

	# #Curl Test
	# EXIT_CODE=1
	# if (( $(curl --head --connect-timeout "$TIMEOUT" "$INTERNET_ADDRESS" | grep -ci -m1 200) )); then
		# EXIT_CODE=0
	# fi
	#-----------------------------------------------------------------------------------
	#return exit code
	exit $EXIT_CODE
	#-----------------------------------------------------------------------------------
}