#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - Creates a MySql database
	#////////////////////////////////////
	# Created by Daniel Knight / daniel_haze@hotmail.com / dietpi.com
	#////////////////////////////////////
	# Usage:
	# - /DietPi/dietpi/func/create_mysql_db DATABASE_NAME MYSQL_ROOT_PW DATABASE_USER DATABASE_PW
	#
	# Drop database:
	# - mysqladmin -u root -pdietpi drop phpbb3 -f
	#////////////////////////////////////

	#Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
	LANG=en_GB.UTF-8

	DATABASE_NAME="$1"
	MYSQL_ROOT_PW="$2"
	DATABASE_USER="$3"
	DATABASE_PW="$4"

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////

	#Start sql if not running.
	service mysql start &> /dev/null

	echo -e "\n DietPi: Creating MySql DB for $DATABASE_NAME"

	#Generate DB
	mysql -u root -p$MYSQL_ROOT_PW -e "create database \`$DATABASE_NAME\`;GRANT ALL PRIVILEGES ON \`$DATABASE_NAME\`.* TO $DATABASE_USER@localhost IDENTIFIED BY '$DATABASE_PW';FLUSH PRIVILEGES;"

	if (( $? == 0 )); then
		echo -e " $DATABASE_NAME created | \e[32mOk\e[0m"
	else
		echo -e " Create database $DATABASE_NAME | \e[31mFailed\e[0m"
	fi

	echo -e ""
	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}