#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - Creates a MySql database
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#////////////////////////////////////
	# Usage:
	# - /DietPi/dietpi/func/create_mysql_db DATABASE_NAME MYSQL_ROOT_PW DATABASE_USER DATABASE_PW
	#
	# Drop database:
	# - mysqladmin -u root -pdietpi drop phpbb3 -f
	#////////////////////////////////////

	DATABASE_NAME="$1"
	MYSQL_ROOT_PW="$2"
	DATABASE_USER="$3"
	DATABASE_PW="$4"

	#Import DietPi-Globals ---------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	G_CHECK_ROOT_USER
	export G_PROGRAM_NAME='DietPi-Create_MySQL_DB'
	#Import DietPi-Globals ---------------------------------------------------------------

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////

	#Start MySQL if not running.
	service mysql start &> /dev/null

	G_DIETPI-NOTIFY 2 "Creating MariaDB database: $DATABASE_NAME"

	#Generate DB
	# 'identified by' can overwrite unix_socket authentication, thus just use this for non-root users.
	grant_privileges=''
	[ "$DATABASE_USER" == 'root' ] || grant_privileges="grant all privileges on \`$DATABASE_NAME\`.* to $DATABASE_USER@localhost identified by '$DATABASE_PW';flush privileges"
	mysql -uroot -e "create database \`$DATABASE_NAME\`;$grant_privileges"

	G_DIETPI-NOTIFY -1 "$?" "Creating MariaDB database: $DATABASE_NAME |"

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}
