#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel_haze@hotmail.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Enables/disables Wifi/BT modules. Also controls internal adapters on some devices (eg: RPI3)
	#
	# Usage:
	# - /DietPi/dietpi/func/dietpi-set_wifi_bt sADAPTER iSTATE
	#////////////////////////////////////

	#Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
	LANG=en_GB.UTF-8

	HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)

	ADAPTER=$(echo -e "$1" | tr '[:upper:]' '[:lower:]') # bluetooth/wifi
	STATE=$2 # 0=disable | 1=enable

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	#WiFi
	if [ "$ADAPTER" = "wifi" ]; then

		rm /etc/modprobe.d/disable_wifi.conf &> /dev/null

		aWIFI_MODULES=()

		# - All
		aWIFI_MODULES=("cfg80211")

		# + RPi 3
		aWIFI_MODULES+=("brcmfmac") #RPi 3 onboard WiFi
		aWIFI_MODULES+=("brcmutil") #RPi 3 onboard WiFi

		# + Pine A64
		aWIFI_MODULES+=("8723bs") #PineA64 addon WiFi/BT board.

		# - Disable
		if (( ! $STATE )); then

			#cfg80211 last
			for ((i=$(( ${#aWIFI_MODULES[@]} - 1 )); i>=0; i--))
			do
				modprobe -rf "${aWIFI_MODULES[$i]}" 2> /dev/null
				echo -e "blacklist ${aWIFI_MODULES[$i]}" >> /etc/modprobe.d/disable_wifi.conf
			done

		# - Enable
		else

			#cfg80211 first
			for ((i=0; i<${#aWIFI_MODULES[@]}; i++))
			do
				modprobe "${aWIFI_MODULES[$i]}" 2> /dev/null
			done

			# - Delay. Without this, kernel reports wifi device not found with RPi 3 and Pine A64 addon board, when ran straight after this script.
			echo -e "Please wait, enabling WiFi Modules..."
			sleep 3

		fi

		unset aWIFI_MODULES

	#-----------------------------------------------------------------------------------
	#BT
	elif [ "$ADAPTER" = "bluetooth" ]; then

		# - Disable
		if (( ! $STATE )); then

			systemctl stop bluetooth
			systemctl disable bluetooth

			# - all
			modprobe -rf bnep

			# + RPi 3
			if (( $HW_MODEL == 3 )); then
				systemctl stop hciuart
				systemctl disable hciuart

				modprobe -rf hci_uart
				modprobe -rf btbcm
			fi

			modprobe -rf bluetooth

			cat << _EOF_ > /etc/modprobe.d/disable_bt.conf
#DietPi - Disable Bluetooth modules. Use dietpi-config > advanced to enable bluetooth.
blacklist bluetooth
blacklist bnep #RPi 3
blacklist hci_uart #RPi 3
blacklist btbcm #RPi 3
_EOF_

		# - Enable
		else

			rm /etc/modprobe.d/disable_bt.conf &> /dev/null

			# - all
			modprobe bnep

			# + RPi 3
			if (( $HW_MODEL == 3 )); then
				modprobe hci_uart
				modprobe btbcm
			fi

			modprobe bluetooth

			systemctl enable bluetooth
			systemctl start bluetooth

			# + RPi 3
			if (( $HW_MODEL == 3 )); then

				systemctl enable hciuart

				#Start service again, if it fails: https://github.com/Fourdee/DietPi/issues/376#issuecomment-230149754
				loop_count=0
				max_count=3
				while (( $(systemctl start hciuart;echo $?) != 0 ))
				do

					if (( $loop_count >= $max_count )); then
						echo -e "\nERROR: hciuart failed to start after $loop_count attempts\n"
						break
					else
						echo -e "\nINFO: hciuart failed to start. Attempting to restart it...\n"
						((loop_count++))
						sleep 1
					fi

				done

				#/usr/bin/hciattach /dev/serial1 bcm43xx 921600 noflow -

			fi

		fi

	fi
	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}
