#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - Setup and apply DietPi smbclient details
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Menu system that allows users to change Samba Client details stored in dietpi.txt and automatically mount.
	# - Applies details to /etc/fstab
	# - Mounts to /mnt/samba if successful
	#
	# Usage:
	# - /DietPi/dietpi/func/dietpi-set_smbclient	= Menu
	# - /DietPi/dietpi/func/dietpi-set_smbclient 1	= Apply and mount using settings in dietpi.txt
	#////////////////////////////////////

	#Import DietPi-Globals ---------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	G_CHECK_ROOT_USER
	export G_PROGRAM_NAME='DietPi-Set_smbclient'
	G_INIT
	#Import DietPi-Globals ---------------------------------------------------------------

	#Grab Input
	INPUT=0
	if (( $(G_CHECK_VALIDINT $1) )); then

		INPUT=$1

	fi

	#/////////////////////////////////////////////////////////////////////////////////////
	#smbclient data
	#/////////////////////////////////////////////////////////////////////////////////////
	samba_clientname=$(grep -m1 '^CONFIG_SMBCLIENT_COMPUTERNAME=' /DietPi/dietpi.txt | sed 's/.*=//')
	samba_clientshare=$(grep -m1 '^CONFIG_SMBCLIENT_SHARENAME=' /DietPi/dietpi.txt | sed 's/.*=//')
	samba_clientusename=$(grep -m1 '^CONFIG_SMBCLIENT_USERNAME=' /DietPi/dietpi.txt | sed 's/.*=//')
	samba_clientpassword=$(grep -m1 '^CONFIG_SMBCLIENT_PASSWORD=' /DietPi/dietpi.txt | sed 's/.*=//')

	Apply_And_Mount(){

		#NB: Convert spaces into '\040': https://github.com/Fourdee/DietPi/issues/1201#issuecomment-339720271
		local space_to_040=$(echo -e "$samba_clientshare" | sed 's/ /\\\\040/g')

		#Apply to fstab
		sed -i "/\/mnt\/samba/c\\/\/$samba_clientname\/$space_to_040 \/mnt\/samba cifs username=$samba_clientusename,password=$samba_clientpassword,iocharset=utf8,sec=ntlm,nofail  0  0" /etc/fstab

		#Mount up
		systemctl daemon-reload
		mount -a

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	#Menu
	if (( $INPUT == 0 )); then

		G_WHIP_DEFAULT_ITEM="$samba_clientname"
		G_WHIP_INPUTBOX 'Please enter the fileservers IP address\n - eg: 192.168.0.2'
		if (( $? == 0 )); then

			samba_clientname=$G_WHIP_RETURNED_VALUE

			G_WHIP_DEFAULT_ITEM="$samba_clientshare"
			G_WHIP_INPUTBOX 'Please enter the fileservers shared folder name\n - eg: MySharedFolder'
			if (( $? == 0 )); then

				samba_clientshare=$G_WHIP_RETURNED_VALUE

				#Username
				G_WHIP_DEFAULT_ITEM="$samba_clientusename"
				G_WHIP_INPUTBOX 'Please enter the fileservers username\n - eg: JoeBloggs'
				if (( $? == 0 )); then

					samba_clientusename=$G_WHIP_RETURNED_VALUE

					#Password
					G_WHIP_DEFAULT_ITEM="$samba_clientpassword"
					G_WHIP_INPUTBOX 'Please enter the fileservers password\n - eg: LetMeIn\n - (NOTICE) This will be stored with no encryption'
					if (( $? == 0 )); then

						samba_clientpassword=$G_WHIP_RETURNED_VALUE

						#Unmount if connected
						printf '\ec' # clear current terminal screen
						echo -e "\n\n Attempting mount, please wait...."
						umount /mnt/samba &> /dev/null

						#Save to Dietpi.txt
						sed -i "/CONFIG_SMBCLIENT_COMPUTERNAME/c\CONFIG_SMBCLIENT_COMPUTERNAME=$samba_clientname" /DietPi/dietpi.txt
						sed -i "/CONFIG_SMBCLIENT_SHARENAME/c\CONFIG_SMBCLIENT_SHARENAME=$samba_clientshare" /DietPi/dietpi.txt
						sed -i "/CONFIG_SMBCLIENT_USERNAME/c\CONFIG_SMBCLIENT_USERNAME=$samba_clientusename" /DietPi/dietpi.txt
						sed -i "/CONFIG_SMBCLIENT_PASSWORD/c\CONFIG_SMBCLIENT_PASSWORD=$samba_clientpassword" /DietPi/dietpi.txt

						Apply_And_Mount

					fi

				fi

			fi

		fi

	#-----------------------------------------------------------------------------------
	#Apply and mount. Using settings from dietpi.txt
	elif (( $INPUT == 1 )); then

		Apply_And_Mount

	fi

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}
