#!/bin/bash
{
	#////////////////////////////////////
	# DietPi
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#////////////////////////////////////
	#
	# Info:
	# - Obtains the optimal MTU size.
	#////////////////////////////////////

	URL='www.google.com'
	MTU_SIZE=1500
	SUCCESS=0

	#-----------------------------------------------------------------------------------
	echo -e "DietPi - MTU optimal size tool\n - Finding optimal MTU size, please wait..."
	while (($SUCCESS == 0))
	do
		if (( $(ping -c 1 -s $MTU_SIZE -M do $URL | grep -ci -m1 '+1 error') == 0 ));then
			SUCCESS=1
			echo -e "\nCompleted:\n - MTU optimal size = $MTU_SIZE\n"
		elif (( $MTU_SIZE <= 0 )); then
			echo -e "\nERROR:\n - Failed to find MTU size\n"
		else
			((MTU_SIZE--))
		fi
	done

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}