#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - Setup and apply DietPi smbclient details
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Menu system that allows users to change Samba Client details stored in dietpi.txt and automatically mount.
	# - Applies details to /etc/fstab
	# - Mounts to /mnt/samba if successful
	#
	# Usage:
	# - /DietPi/dietpi/func/dietpi-set_smbclient	= Menu
	# - /DietPi/dietpi/func/dietpi-set_smbclient 1	= Apply and mount using settings in dietpi.txt
	#////////////////////////////////////

	#Import DietPi-Globals ---------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	G_CHECK_ROOT_USER
	export G_PROGRAM_NAME='DietPi-Set_smbclient'
	G_INIT
	#Import DietPi-Globals ---------------------------------------------------------------

	#Grab Input
	INPUT=0
	if G_CHECK_VALIDINT $1; then

		INPUT=$1

	fi

	#/////////////////////////////////////////////////////////////////////////////////////
	#smbclient data
	#/////////////////////////////////////////////////////////////////////////////////////
	SAMBA_CLIENTNAME=$(grep -m1 '^CONFIG_SMBCLIENT_COMPUTERNAME=' /DietPi/dietpi.txt | sed 's/.*=//')
	SAMBA_CLIENTSHARE=$(grep -m1 '^CONFIG_SMBCLIENT_SHARENAME=' /DietPi/dietpi.txt | sed 's/.*=//')
	SAMBA_CLIENTUSENAME=$(grep -m1 '^CONFIG_SMBCLIENT_USERNAME=' /DietPi/dietpi.txt | sed 's/.*=//')
	SAMBA_CLIENTPASSWORD=$(grep -m1 '^CONFIG_SMBCLIENT_PASSWORD=' /DietPi/dietpi.txt | sed 's/.*=//')
	FP_MOUNT_TARGET=${FP_MOUNT_TARGET:-/mnt/samba}

	Apply_And_Mount(){

		G_AG_CHECK_INSTALL_PREREQ smbclient cifs-utils

		#NB: Convert spaces into '\040': https://github.com/Fourdee/DietPi/issues/1201#issuecomment-339720271
		local space_to_040=$(echo -e "$SAMBA_CLIENTSHARE" | sed 's/ /\\\\040/g')

		#Mount now
		mkdir -p $FP_MOUNT_TARGET

		G_RUN_CMD_INFO_ONLY=1 G_RUN_CMD mount -t cifs -o username=$SAMBA_CLIENTUSENAME,password=$SAMBA_CLIENTPASSWORD //$SAMBA_CLIENTNAME/$space_to_040 $FP_MOUNT_TARGET
		if (( ! $G_ERROR_HANDLER_EXITCODE_RETURN )); then

			#Apply to fstab
			sed -i "\#[[:space:]]$FP_MOUNT_TARGET[[:space:]]#d" /etc/fstab
			cat << _EOF_ >> /etc/fstab
//$SAMBA_CLIENTNAME/$space_to_040 $FP_MOUNT_TARGET cifs username=$SAMBA_CLIENTUSENAME,password=$SAMBA_CLIENTPASSWORD,iocharset=utf8,vers=1.0,nofail 0 0
_EOF_
			systemctl daemon-reload

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	#Menu
	if (( $INPUT == 0 )); then

		G_WHIP_DEFAULT_ITEM="$SAMBA_CLIENTNAME"
		G_WHIP_INPUTBOX 'Please enter the fileservers IP address\n - eg: 192.168.0.2'
		if (( $? == 0 )); then

			SAMBA_CLIENTNAME=$G_WHIP_RETURNED_VALUE

			G_WHIP_DEFAULT_ITEM="$SAMBA_CLIENTSHARE"
			G_WHIP_INPUTBOX 'Please enter the fileservers shared folder name\n - eg: MySharedFolder'
			if (( $? == 0 )); then

				SAMBA_CLIENTSHARE=$G_WHIP_RETURNED_VALUE

				#Username
				G_WHIP_DEFAULT_ITEM="$SAMBA_CLIENTUSENAME"
				G_WHIP_INPUTBOX 'Please enter the fileservers username\n - eg: JoeBloggs'
				if (( $? == 0 )); then

					SAMBA_CLIENTUSENAME=$G_WHIP_RETURNED_VALUE

					#Password
					G_WHIP_DEFAULT_ITEM="$SAMBA_CLIENTPASSWORD"
					G_WHIP_INPUTBOX 'Please enter the fileservers password\n - eg: LetMeIn\n - (NOTICE) This will be stored with no encryption'
					if (( $? == 0 )); then

						SAMBA_CLIENTPASSWORD=$G_WHIP_RETURNED_VALUE

						#Unmount if connected
						printf '\ec' # clear current terminal screen
						echo -e "\n\n Attempting mount, please wait...."
						umount /mnt/samba &> /dev/null

						#Save to Dietpi.txt
						sed -i "/CONFIG_SMBCLIENT_COMPUTERNAME/c\CONFIG_SMBCLIENT_COMPUTERNAME=$SAMBA_CLIENTNAME" /DietPi/dietpi.txt
						sed -i "/CONFIG_SMBCLIENT_SHARENAME/c\CONFIG_SMBCLIENT_SHARENAME=$SAMBA_CLIENTSHARE" /DietPi/dietpi.txt
						sed -i "/CONFIG_SMBCLIENT_USERNAME/c\CONFIG_SMBCLIENT_USERNAME=$SAMBA_CLIENTUSENAME" /DietPi/dietpi.txt
						sed -i "/CONFIG_SMBCLIENT_PASSWORD/c\CONFIG_SMBCLIENT_PASSWORD=$SAMBA_CLIENTPASSWORD" /DietPi/dietpi.txt

						Apply_And_Mount

					fi

				fi

			fi

		fi

	#-----------------------------------------------------------------------------------
	#Apply and mount. Using settings from dietpi.txt
	elif (( $INPUT == 1 )); then

		Apply_And_Mount

	fi

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}
