#!/bin/bash

	#////////////////////////////////////
	# DietPi Banner Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - filename /DietPi/dietpi/func/dietpi-banner
	# - Checks /DietPi/dietpi/.update_available
	#
	# Usage:
	# - dietpi-banner 0 = top section only
	# - dietpi-banner 1 = top section and credits + clear
	#////////////////////////////////////

	# Import DietPi-Globals --------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	G_PROGRAM_NAME='DietPi-Banner'
	G_INIT
	# Import DietPi-Globals --------------------------------------------------------------

	disable_error=1 G_CHECK_VALIDINT "$1" && INPUT=$1 || INPUT=0

	#/////////////////////////////////////////////////////////////////////////////////////
	# Globals
	#/////////////////////////////////////////////////////////////////////////////////////
	DIETPI_VERSION="$G_DIETPI_VERSION_CORE.$G_DIETPI_VERSION_SUB.$G_DIETPI_VERSION_RC"
	[[ $G_GITBRANCH != 'master' ]] && DIETPI_VERSION+=" ($G_GITBRANCH)"

	Update_Ip_Address(){

		/DietPi/dietpi/func/obtain_network_details

	}

	#####
	aOBTAIN=(

		'sed -n 3p /DietPi/dietpi/.network' 								#0: 'Active IP adapter'
		'sed -n 4p /DietPi/dietpi/.network'									#1: 'LAN IP address'
		'wget -q -O- --timeout=2 --tries=1 https://dietpi.com/myip.php' 	#2: 'WAN IP address'

	)

	aENABLED=()
	aDESCRIPTION=(

		'Device model'
		'CPU Temp'
		'LAN IP'
		'WAN IP'
		'Freespace (RootFS)'
		'Freespace (DietPi Userdata)'
		'Display DietPi credits?'
		'Display DietPi useful commands?'

	)

	FP_SAVEFILE='/DietPi/dietpi/.dietpi-banner'

	Load(){

		for ((i=0; i<${#aDESCRIPTION[@]}; i++))
		do

			aENABLED[$i]=0

		done

		#Default enabled options?? aENABLED[0]=1

		[[ -f $FP_SAVEFILE ]] && . $FP_SAVEFILE

	}

	Save(){

		[[ -f $FP_SAVEFILE ]] && rm $FP_SAVEFILE

		for ((i=0; i<${#aENABLED[@]}; i++))
		do

			echo -e "aENABLED[$i]=${aENABLED[$i]}" >> $FP_SAVEFILE

		done

	}

	Menu_Main(){

		G_WHIP_CHECKLIST_ARRAY=()

		for ((i=0; i<${#aDESCRIPTION[@]}; i++))
		do

			local state='off'
			(( ${aENABLED[$i]} == 1 )) && state='on'

			aENABLED[$i]=0

			G_WHIP_CHECKLIST_ARRAY+=($i "${aDESCRIPTION[$i]}" $state)

		done

		if G_WHIP_CHECKLIST "Please select options to enable in $G_PROGRAM_NAME display"; then

			for i in ${G_WHIP_RETURNED_VALUE[@]}
			do

				aENABLED[$i]=1

			done

		fi

	}

	UPDATE_AVAILABLE=0
	UPDATE_AVAILABLE_VERSION='' # -1 = image required, other value = latest version
	Obtain_Update_Available(){

		# Update Available?
		if [[ -f '/DietPi/dietpi/.update_available' ]]; then

			UPDATE_AVAILABLE=1
			UPDATE_AVAILABLE_VERSION=$(</DietPi/dietpi/.update_available)

		fi

	}

	Print_Header(){

		local green_line=' \e[38;5;154m─────────────────────────────────────────────────────\e[0m'
		local green_bullet='\e[38;5;154m -\e[0m'

		# Update Available?
		Obtain_Update_Available
		local text_update_available_date=''
		if (( $UPDATE_AVAILABLE )); then

			if [[ $UPDATE_AVAILABLE_VERSION == '-1' ]]; then

				text_update_available_date='\e[1;33mImage available\e[0m'

			else

				text_update_available_date='\e[1;33mUpdate available\e[0m'

			fi

		else

			text_update_available_date=$(date +"%R - %a %x")

		fi

		echo -e "\
$green_line
 \e[1mDietPi v$DIETPI_VERSION\e[0m \e[90m| $text_update_available_date\e[0m
$green_line"

		local index=0
		index=0; (( ${aENABLED[$index]} )) && echo -e "$green_bullet \e[1m${aDESCRIPTION[$index]} \e[90m| $G_HW_MODEL_DESCRIPTION\e[0m"
		index=1; (( ${aENABLED[$index]} )) && echo -e "$green_bullet \e[1m${aDESCRIPTION[$index]} \e[90m| $(print_full_info=1 G_OBTAIN_CPU_TEMP)\e[0m"
		index=2; (( ${aENABLED[$index]} )) && echo -e "$green_bullet \e[1m${aDESCRIPTION[$index]} \e[90m| $(${aOBTAIN[1]}) ($(${aOBTAIN[0]}))\e[0m"
		index=3; (( ${aENABLED[$index]} )) && echo -e "$green_bullet \e[1m${aDESCRIPTION[$index]} \e[90m| $(${aOBTAIN[2]})\e[0m"

		index=4; if (( ${aENABLED[$index]} )); then

			local freespace=$(G_CHECK_FREESPACE /)
			# - Show GiB if > 9999 MiB
			(( $freespace > 9999 )) && freespace="$(( $freespace / 1024 )) GiB" || freespace+=' MiB'
			freespace="$freespace"
			echo -e "$green_bullet \e[1m${aDESCRIPTION[$index]} \e[90m| $freespace\e[0m"

		fi
		index=5; if (( ${aENABLED[$index]} )); then

			local freespace=$(G_CHECK_FREESPACE /mnt/dietpi_userdata)
			# - Show GiB if > 9999 MiB
			(( $freespace > 9999 )) && freespace="$(( $freespace / 1024 )) GiB" || freespace+=' MiB'
			freespace="$freespace"
			echo -e "$green_bullet \e[1m${aDESCRIPTION[$index]} \e[90m| $freespace\e[0m"

		fi

		echo -e "$green_line\n"

	}

	Credits_Print(){

		echo -e '\e[90m DietPi Team     : MichaIng (lead), Daniel Knight (founder)\e[0m'

		local fp_prep_info='/DietPi/dietpi/.prep_info'
		if [[ -f $fp_prep_info ]]; then

			local image_creator=$(sed -n 1p $fp_prep_info)
			local preimage_name=$(sed -n 2p $fp_prep_info)
			[[ $image_creator == '0' ]] && image_creator='DietPi Core Team'

			echo -e "\e[90m Image           : $image_creator (pre-image: $preimage_name)\e[0m"

			unset IMAGE_ADDITIONAL_CREDITS

		fi

		echo -e '\e[90m Web             : https://DietPi.com | https://twitter.com/dietpi_
 Patreon Legends : PINE64 community
 Donate          : https://DietPi.com/#donate'

		local image_additional_credits=$(sed -n 8p /DietPi/dietpi/.hw_model)
		[[ $image_additional_credits ]] && echo -e "\n\ Device image possible thanks to: $image_additional_credits"

		echo -e ' DietPi Hosting  : Powered by https://MyVirtualServer.com\e[0m'

		# Update available?
		if (( $UPDATE_AVAILABLE )); then

			if [[ $UPDATE_AVAILABLE_VERSION = '-1' ]]; then

				echo -e '\n\e[1;31m Updated DietPi image is available, please download it:\e[0m\n https://dietpi.com/download\n'

			else

				echo -e "\e[1m dietpi-update\e[0m    = \e[1;31mRun now to update DietPi (from v$DIETPI_VERSION to v$UPDATE_AVAILABLE_VERSION).\e[0m"

			fi

		fi

		echo ''

	}

	Useful_Commands_Print(){

		echo -e '\e[1m dietpi-launcher\e[0m  = All the DietPi programs in one place.
\e[1m dietpi-config\e[0m    = Feature rich configuration tool for your device.
\e[1m dietpi-software\e[0m  = Select optimized software for installation.
\e[1m htop\e[0m             = Resource monitor.
\e[1m cpu\e[0m              = Shows CPU information and stats.\n'

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////

	#-----------------------------------------------------------------------------------
	Load
	#-----------------------------------------------------------------------------------

	if (( $INPUT == 0 )); then

		Print_Header

	elif (( $INPUT == 1 )); then

		printf '\ec' # clear current terminal screen
		Print_Header
		(( ${aENABLED[6]} )) && Credits_Print
		(( ${aENABLED[7]} )) && Useful_Commands_Print

	elif (( $INPUT == 2 )); then

		Menu_Main

		printf '\ec' # clear current terminal screen
		Print_Header
		(( ${aENABLED[6]} )) && Credits_Print
		(( ${aENABLED[7]} )) && Useful_Commands_Print


	fi

	#-----------------------------------------------------------------------------------
	Save
	#-----------------------------------------------------------------------------------
	exit 0
	#-----------------------------------------------------------------------------------
