#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - Setup and apply DietPi curlftpfs details
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Used to change curlftpfs details stored in dietpi.txt.
	# - Applies details to /etc/fstab
	# - Mounts to /mnt/ftp_client if successful
	# - no exit code return, or status.
	#
	# Usage:
	# - /DietPi/dietpi/func/dietpi-set_curlftpfs
	#////////////////////////////////////

	#/////////////////////////////////////////////////////////////////////////////////////
	#Obtain Pi/Odroid Model and distro
	#/////////////////////////////////////////////////////////////////////////////////////
	HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)
	HW_MODEL_DESCRIPTION=$(sed -n 2p /DietPi/dietpi/.hw_model)
	DISTRO=$(sed -n 3p /DietPi/dietpi/.hw_model)

	#/////////////////////////////////////////////////////////////////////////////////////
	#curlftpfs data
	#/////////////////////////////////////////////////////////////////////////////////////
	OPTION=0
	CHOICE=0
	curlftpfs_clientaddress=$(cat /DietPi/dietpi.txt | grep -m1 'curlftpfs_clientaddress' | sed 's/curlftpfs_clientaddress=//g')
	curlftpfs_clientusername=$(cat /DietPi/dietpi.txt | grep -m1 'curlftpfs_clientusername' | sed 's/curlftpfs_clientusername=//g')
	curlftpfs_clientpassword=$(cat /DietPi/dietpi.txt | grep -m1 'curlftpfs_clientpassword' | sed 's/curlftpfs_clientpassword=//g')

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	OPTION=$(whiptail --inputbox "Please enter the FTP server URL or IP address\n - eg: fuzon.co.uk" 9 65 "$curlftpfs_clientaddress" --title "CurlFTPfs Setup" 3>&1 1>&2 2>&3)
	CHOICE=$?
	if (( $CHOICE == 0 )); then
		curlftpfs_clientaddress=$OPTION

		#Username
		OPTION=$(whiptail --inputbox "Please enter the FTP username\n - eg: JoeBloggs" 9 65 "$curlftpfs_clientusername" --title "CurlFTPfs Setup" 3>&1 1>&2 2>&3)
		CHOICE=$?
		if (( $CHOICE == 0 )); then
			curlftpfs_clientusername=$OPTION

			#Password
			OPTION=$(whiptail --inputbox "Please enter the FTP password\n - eg: LetMeIn\n - (NOTICE) This will be stored with no encryption" 9 65 "$curlftpfs_clientpassword" --title "CurlFTPfs Setup" 3>&1 1>&2 2>&3)
			CHOICE=$?
			if (( $CHOICE == 0 )); then
				curlftpfs_clientpassword=$OPTION

				#Unmount if connected
				clear
				echo -e "\n\n Attempting mount, please wait...."
				umount /mnt/ftp_client &> /dev/null

				#Save to Dietpi.txt
				sed -i "/curlftpfs_clientaddress/c\curlftpfs_clientaddress=$curlftpfs_clientaddress" /DietPi/dietpi.txt
				sed -i "/curlftpfs_clientusername/c\curlftpfs_clientusername=$curlftpfs_clientusername" /DietPi/dietpi.txt
				sed -i "/curlftpfs_clientpassword/c\curlftpfs_clientpassword=$curlftpfs_clientpassword" /DietPi/dietpi.txt

				#Apply to fstab

				#Wheezy
				if (( $DISTRO == 1 )); then
					sed -i "/\/mnt\/ftp_client/c\curlftpfs#$curlftpfs_clientusername:$curlftpfs_clientpassword@$curlftpfs_clientaddress \/mnt\/ftp_client fuse auto,allow_other,direct_io,transform_symlinks,user,uid=1000 0  0" /etc/fstab
				#Ubuntu
				elif (( $DISTRO == 2 )); then
					sed -i "/\/mnt\/ftp_client/c\curlftpfs#$curlftpfs_clientusername:$curlftpfs_clientpassword@$curlftpfs_clientaddress \/mnt\/ftp_client fuse auto,allow_other,direct_io,transform_symlinks,user,uid=1000,nobootwait 0  0" /etc/fstab
				#Jessie
				elif (( $DISTRO == 3 )); then
					sed -i "/\/mnt\/ftp_client/c\curlftpfs#$curlftpfs_clientusername:$curlftpfs_clientpassword@$curlftpfs_clientaddress \/mnt\/ftp_client fuse auto,allow_other,direct_io,transform_symlinks,user,uid=1000 0  0" /etc/fstab
				fi

				#Mount up
				mount -a &> /dev/null

			fi
		fi
	fi

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}