#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - Applys WiFi country code to system.
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel_haze@hotmail.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Usage:
	# - /DietPi/dietpi/func/dietpi-set_wificountrycode 			= Apply stored value (wifi_country_code) in dietpi.txt to system. 00 if not set.
	# - /DietPi/dietpi/func/dietpi-set_wificountrycode XX		= Changes stored value(wifi_country_code) in dietpi.txt, and system confs with new country code, applys country code to system
	#
	#////////////////////////////////////

	#Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
	LANG=en_GB.UTF-8

	INPUT=$1

	#Pull saved country code from dietpi.txt if set.
	WIFI_COUNTRYCODE=$(cat /DietPi/dietpi.txt | grep -m1 '^wifi_country_code=' | sed 's/.*=//')
	WIFI_COUNTRYCODE=${WIFI_COUNTRYCODE:-00}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main
	#/////////////////////////////////////////////////////////////////////////////////////
	#Use country code from command input. Implies new setting.
	if [ -n "$INPUT" ]; then
		WIFI_COUNTRYCODE="$INPUT"

		# - Apply value to DietPi.txt
		sed -i "/^wifi_country_code=/c\wifi_country_code=$WIFI_COUNTRYCODE" /DietPi/dietpi.txt

	fi

	# - Save country code to known system configs.
	echo -e "REGDOMAIN=$WIFI_COUNTRYCODE" > /etc/default/crda
	echo -e "options cfg80211 ieee80211_regdom=$WIFI_COUNTRYCODE" > /etc/modprobe.d/cfg80211.conf

	#Activate country code
	iw reg set "$WIFI_COUNTRYCODE"
	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}