#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - Enables control and applies settings for specific hardware.
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Usage:
	FP_SCRIPT='/DietPi/dietpi/func/dietpi-set_hardware'
	AVAIABLE_COMMANDS="
Available commands
$FP_SCRIPT		rpi3_usb_boot		enable
$FP_SCRIPT		rpi-camera		enable/disable
$FP_SCRIPT		gpumemsplit		64/128/256 #RPi only
$FP_SCRIPT		remoteir		odroid_remote/justboom_ir_remote
$FP_SCRIPT		eth-forcespeed		10/100/1000/disable
$FP_SCRIPT		rpi-opengl		vc4-kms-v3d/vc4-fkms-v3d/disable
$FP_SCRIPT		i2c			enable/disable/khz
$FP_SCRIPT		wificountrycode		GB/US/DE
$FP_SCRIPT		wifimodules		enable/disable/onboard_enable/onboard_disable
$FP_SCRIPT		enableipv6		enable/disable
$FP_SCRIPT		preferipv4		enable/disable
$FP_SCRIPT		bluetooth		enable/disable
$FP_SCRIPT		serialconsole		enable/disable
$FP_SCRIPT		soundcard 		target_card (non-matching name for reset to default) add '-eq' to target_card string, enable alsa eq on card. HW:x,x (specify target card and device index eg: HW:9,1)
$FP_SCRIPT		lcdpanel		target_panel (none to remove all)
"
	#////////////////////////////////////

	#Grab Inputs
	INPUT_DEVICE_NAME="${1,,}"
	INPUT_DEVICE_VALUE="${2,,}"
	# - support for 0/1 inputs for enable/disable
	if [[ $INPUT_DEVICE_VALUE == '1' ]]; then

		INPUT_DEVICE_VALUE='enable'

	elif [[ $INPUT_DEVICE_VALUE == '0' ]]; then

		INPUT_DEVICE_VALUE='disable'

	fi

	#Import DietPi-Globals ---------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	G_PROGRAM_NAME='DietPi-Set_Hardware'
	G_CHECK_ROOT_USER
	G_CHECK_ROOTFS_RW
	G_INIT
	#Import DietPi-Globals ---------------------------------------------------------------

	if (( $G_HW_MODEL < 10 )); then

		FP_RPI_CONFIG='/DietPi/config.txt'
		#Semi support non-dietpi Raspbian
		[[ -f $FP_RPI_CONFIG ]] || FP_RPI_CONFIG='/boot/config.txt'

	fi

	EXIT_CODE=0

	HW_ONBOARD_WIFI=$(sed -n 10p /DietPi/dietpi/.hw_model)

	Unknown_Input_Name(){

		EXIT_CODE=1
		G_DIETPI-NOTIFY 2 "Unknown input name ($INPUT_DEVICE_NAME). Nothing has been applied."

		echo -e "$AVAIABLE_COMMANDS"

	}

	Unknown_Input_Mode(){

		EXIT_CODE=1
		G_DIETPI-NOTIFY 2 "Unknown input value ($INPUT_DEVICE_VALUE). Nothing has been applied."

		echo -e "$AVAIABLE_COMMANDS"

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	#rpi-camera
	#/////////////////////////////////////////////////////////////////////////////////////
	RPi_Camera_Main(){

		# - int, assume RPi
		if [[ $INPUT_DEVICE_VALUE == 'enable' ]]; then

			# - Enable RPi Camera module
			G_CONFIG_INJECT 'start_x=' 'start_x=1' $FP_RPI_CONFIG

			# - v4l2 module (motioneye /dev/video0)
			G_CONFIG_INJECT 'bcm2835-v4l2' 'bcm2835-v4l2' /etc/modules

			# - requires 128MB memory split min.
			if (( $(grep -m1 'gpu_mem_' $FP_RPI_CONFIG | sed 's/^.*=//g') < 128 )); then

				local tmp=$INPUT_DEVICE_VALUE
				INPUT_DEVICE_VALUE=128

				Gpu_Memory_Split_Main

				INPUT_DEVICE_VALUE=$tmp
				unset tmp

			fi

		elif [[ $INPUT_DEVICE_VALUE == 'disable' ]]; then

			G_CONFIG_INJECT 'start_x=' 'start_x=0' $FP_RPI_CONFIG
			sed -i '/bcm2835-v4l2/d' /etc/modules

		else

			Unknown_Input_Mode

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	#rpi3_usb_boot
	#/////////////////////////////////////////////////////////////////////////////////////
	RPi_USB_Boot_Main(){

		if [[ $INPUT_DEVICE_VALUE == 'enable' ]]; then

			G_CONFIG_INJECT 'program_usb_boot_mode=' 'program_usb_boot_mode=1' $FP_RPI_CONFIG

			cat << _EOF_ > /etc/systemd/system/dietpi-rm_program_usb_boot_mode.service
[Unit]
Description=dietpi-rm_program_usb_boot_mode.service
After=dietpi-boot.service

[Service]
Type=simple
RemainAfterExit=yes
ExecStartPre=/bin/sed -i '/program_usb_boot_mode=/d' $FP_RPI_CONFIG
ExecStartPre=/bin/systemctl disable dietpi-rm_program_usb_boot_mode
ExecStart=/bin/systemctl daemon-reload

[Install]
WantedBy=multi-user.target
_EOF_
systemctl daemon-reload
systemctl enable dietpi-rm_program_usb_boot_mode

		elif [[ $INPUT_DEVICE_VALUE == 'disable' ]]; then

			sed -i '/program_usb_boot_mode=/d' $FP_RPI_CONFIG

		else

			Unknown_Input_Mode

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	#gpumemsplit
	#/////////////////////////////////////////////////////////////////////////////////////
	Gpu_Memory_Split_Main(){

		# - int, assume RPi
		if disable_error=1 G_CHECK_VALIDINT $INPUT_DEVICE_VALUE; then

			G_CONFIG_INJECT 'gpu_mem_256=' "gpu_mem_256=$INPUT_DEVICE_VALUE" $FP_RPI_CONFIG
			G_CONFIG_INJECT 'gpu_mem_512=' "gpu_mem_512=$INPUT_DEVICE_VALUE" $FP_RPI_CONFIG
			G_CONFIG_INJECT 'gpu_mem_1024=' "gpu_mem_1024=$INPUT_DEVICE_VALUE" $FP_RPI_CONFIG

		else

			Unknown_Input_Mode

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	#remoteir
	#/////////////////////////////////////////////////////////////////////////////////////
	RemoteIR_Prereqs(){

		# - LIRC
		G_AG_CHECK_INSTALL_PREREQ lirc

	}

	RemoteIR_Reset_All(){

		# - Disable JustBoom
		if (( $G_HW_MODEL < 10 )); then

			systemctl stop justboom-ir-mpd.service
			systemctl disable justboom-ir-mpd.service
			rm /etc/systemd/system/justboom-ir-mpd.service

			sed -i '/dtoverlay=lirc-rpi/d' $FP_RPI_CONFIG
			sed -i '/dtparam=gpio_in_pin=25/d' $FP_RPI_CONFIG

		# - Disable odroids
		elif (( $G_HW_MODEL < 20 )); then

			systemctl stop odroid-remote
			systemctl disable odroid-remote
			rm /etc/systemd/system/odroid-remote.service

		fi

	}

	RemoteIR_Main(){

		if [[ $INPUT_DEVICE_VALUE == 'odroid_remote' ]]; then

			RemoteIR_Prereqs
			RemoteIR_Reset_All &> /dev/null

			# - xu4 Cloudshell
			if (( $G_HW_MODEL == 11 )); then

				# - modules
				local string='options gpioplug_ir_recv gpio_nr=24 active_low=1'
				G_CONFIG_INJECT "$string" "$string" /etc/modprobe.d/odroid-cloudshell.conf

				string="gpio-ir-recv"
				G_CONFIG_INJECT "$string" "$string" /etc/modules

				string="gpioplug-ir-recv"
				G_CONFIG_INJECT "$string" "$string" /etc/modules

			# - c1/c2
			elif (( $G_HW_MODEL == 10 || $G_HW_MODEL == 12 )); then

				# - Module
				G_CONFIG_INJECT 'meson_ir' 'meson_ir' /etc/modules

			fi

			# - All
			# - SystemD
			systemctl disable lirc
			rm /etc/init.d/lirc
			cat << _EOF_ > /etc/systemd/system/odroid-remote.service
[Unit]
Description=Odroid Remote C1/C2/XU4

[Service]
Type=forking
ExecStartPre=/bin/bash -c 'mkdir -p /var/run/lirc'
ExecStart=/usr/sbin/lircd --output=/run/lirc/lircd --driver=default --device=/dev/lirc0 --uinput

[Install]
WantedBy=multi-user.target
_EOF_
			systemctl daemon-reload
			systemctl enable odroid-remote.service

			#	Lircd conf for Odroid Remote
			cat << _EOF_ > /etc/lirc/lircd.conf
begin remote

  name lircd.conf
  bits 16
  flags SPACE_ENC|CONST_LENGTH
  eps 30
  aeps 100

  header 9000 4500
  one 563 1688
  zero 563 564
  ptrail 563
  pre_data_bits 16
  pre_data 0x4DB2
  repeat 9000 2250
  toggle_bit_mask 0x0
      begin codes

          KEY_LEFT 0x9966
          KEY_RIGHT 0x837C
          KEY_UP 0x53AC
          KEY_DOWN 0x4BB4
          KEY_ENTER 0x738C
          KEY_HOME 0x41BE
          KEY_MUTE 0x11EE
          KEY_MENU 0xA35C
          KEY_BACK 0x59A6
          KEY_VOLUMEDOWN 0x817E
          KEY_VOLUMEUP 0x01FE
          KEY_POWER 0x3BC4

      end codes

end remote
_EOF_

		elif [[ $INPUT_DEVICE_VALUE == 'justboom_ir_remote' ]]; then

			RemoteIR_Prereqs
			RemoteIR_Reset_All &> /dev/null

			cat << _EOF_ >> $FP_RPI_CONFIG
dtoverlay=lirc-rpi
dtparam=gpio_in_pin=25
_EOF_

			cat << _EOF_ > /etc/lirc/hardware.conf
LIRCD_ARGS="--uinput"
LOAD_MODULES=true
DRIVER="default"
DEVICE="/dev/lirc0"
MODULES="lirc_rpi"
LIRCD_CONF=""
LIRCMD_CONF=""
_EOF_

			cat << _EOF_ > /etc/lirc/lircd.conf
begin remote

  name  lircd.conf
  bits            5
  flags RC5|CONST_LENGTH
  eps            30
  aeps          100

  one           921   855
  zero          921   855
  plead         936
  pre_data_bits   8
  pre_data       0xA0
  gap          114211
  toggle_bit_mask 0x800

  suppress_repeat 5
  duty_cycle 300

  begin codes

        KEY_HOME 0x10
        KEY_POWER 0x11
        KEY_MUTE 0x12
        KEY_LEFT 0x13
        KEY_RIGHT 0x14
        KEY_ENTER 0x15
        KEY_MENU 0x16
        KEY_BACK 0x17
        KEY_VOLUMEDOWN 0x18
        KEY_VOLUMEUP 0x19
        KEY_UP 0x1A
        KEY_DOWN 0x1B

      end codes

end remote
_EOF_

			# + MPD control
			G_AG_CHECK_INSTALL_PREREQ mpc

			cat << _EOF_ > ~/.lircrc
begin
prog = irexec
button = KEY_ENTER
config = mpc toggle
end
begin
prog = irexec
button = KEY_VOLUMEUP
config = mpc volume +2
end
begin
prog = irexec
button = KEY_VOLUMEDOWN
config = mpc volume -2
end
begin
prog = irexec
button = KEY_RIGHT
config = mpc next
end
begin
prog = irexec
button = KEY_LEFT
config = mpc prev
end
begin
prog = irexec
button = KEY_UP
config = mpc seek +00:00:10
end
begin
prog = irexec
button = KEY_DOWN
config = mpc seek -00:00:10
end
begin
prog = irexec
button = KEY_BACK
config = mpc repeat on
end
begin
prog = irexec
button = KEY_MENU
config = mpc repeat off
end
_EOF_

			#	service
			cat << _EOF_ > /etc/systemd/system/justboom-ir-mpd.service
[Unit]
Description=justboom-ir-mpd
After=sound.target lirc.service

[Service]
User=$USER
Type=simple

ExecStart=/usr/bin/irexec

[Install]
WantedBy=default.target
_EOF_
			systemctl daemon-reload
			systemctl enable justboom-ir-mpd.service
			systemctl start justboom-ir-mpd.service

		elif [[ $INPUT_DEVICE_VALUE == 'none' ]]; then

			RemoteIR_Reset_All &> /dev/null

		else

			Unknown_Input_Mode

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	#Ethernet force link speed
	#/////////////////////////////////////////////////////////////////////////////////////
	Eth_Force_Speed_Main(){

		if (( $INPUT_DEVICE_VALUE > 0 )); then

			local eth_force_speed=$INPUT_DEVICE_VALUE
			local eth_adapter="eth$(sed -n 1p /DietPi/dietpi/.network)"

			cat << _EOF_ > /etc/systemd/system/ethtool_force_speed.service
[Unit]
Description=ethtool force speed
After=network-online.target

[Service]
Type=oneshot
ExecStart=/sbin/ethtool -s $eth_adapter speed $eth_force_speed duplex full autoneg off

[Install]
WantedBy=ifup@$eth_adapter.service
_EOF_
			systemctl daemon-reload
			systemctl enable ethtool_force_speed.service
			systemctl start ethtool_force_speed.service

		elif [[ $INPUT_DEVICE_VALUE == 'disable' ]]; then #0 is converted to 'disabled'

			rm /etc/systemd/system/ethtool_force_speed.service &> /dev/null
			systemctl daemon-reload

		else

			Unknown_Input_Mode

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	#RPi openGL
	#/////////////////////////////////////////////////////////////////////////////////////
	RPi_OpenGL_Main(){

		#Always remove previous vc4 overlay entry
		sed -i '/dtoverlay=vc4-/d' $FP_RPI_CONFIG

		if [[ $INPUT_DEVICE_VALUE == "vc4-"* ]]; then

			#RPi 2/3+ only
			if (( $G_HW_MODEL >= 2 && $G_HW_MODEL < 10 )); then

				# - GL packages
				G_AG_CHECK_INSTALL_PREREQ libgl1-mesa-dri libgles2-mesa mesa-utils

				echo -e "\ndtoverlay=$INPUT_DEVICE_VALUE" >> $FP_RPI_CONFIG

				# - set 1080p by default
				G_CONFIG_INJECT 'framebuffer_width=' 'framebuffer_width=1920' $FP_RPI_CONFIG
				G_CONFIG_INJECT 'framebuffer_height=' 'framebuffer_height=1080' $FP_RPI_CONFIG

			else

				G_DIETPI-NOTIFY 1 'OpenGL requires an RPi 2 or higher'
				sleep 2

			fi

		elif [[ $INPUT_DEVICE_VALUE == 'disable' ]]; then

			echo -e 'already done' &> /dev/null

		else

			Unknown_Input_Mode

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# lcdpanel eg: All non-HDMI/VGA based displays and monitors.
	#/////////////////////////////////////////////////////////////////////////////////////
	Lcd_Panel_Not_Available_For_Device(){

		EXIT_CODE=1
		G_DIETPI-NOTIFY 2 "$INPUT_DEVICE_VALUE is not available for this device. Nothing has been applied."

	}

	Lcd_Panel_Main(){

		local update_dietpitxt=1

		if [[ $INPUT_DEVICE_VALUE == 'odroid-lcd35' ]]; then

			Lcd_Panel_OdroidLCD35_Enable

		elif [[ $INPUT_DEVICE_VALUE == 'waveshare32' ]]; then

			Lcd_Panel_Waveshare32_Enable

		elif [[ $INPUT_DEVICE_VALUE == 'odroid-cloudshell' ]]; then

			Lcd_Panel_Odroidcloudshell_Enable

		elif [[ ${INPUT_DEVICE_VALUE,,} == 'esp01215e' ]]; then

			Lcd_Panel_ESP01215E_Enable

		#disable all
		elif [[ $INPUT_DEVICE_VALUE == 'none' ]]; then

			Lcd_Panel_Waveshare32_Disable
			Lcd_Panel_Odroidcloudshell_Disable
			Lcd_Panel_OdroidLCD35_Disable
			Lcd_Panel_ESP01215E_Disable

		else

			update_dietpitxt=0
			Unknown_Input_Mode

		fi

		#Update dietpi.txt entry?
		if (( $update_dietpitxt )); then

			G_CONFIG_INJECT 'CONFIG_LCDPANEL=' "CONFIG_LCDPANEL=$INPUT_DEVICE_VALUE" /DietPi/dietpi.txt

		fi

	}

	Lcd_Panel_ESP01215E_Enable(){

		G_CONFIG_INJECT 'framebuffer_width=' 'framebuffer_width=1024' $FP_RPI_CONFIG
		G_CONFIG_INJECT 'framebuffer_height=' 'framebuffer_height=600' $FP_RPI_CONFIG
		G_CONFIG_INJECT 'SOFTWARE_CHROMIUM_RES_X=' "SOFTWARE_CHROMIUM_RES_X=1024" /DietPi/dietpi.txt
		G_CONFIG_INJECT 'SOFTWARE_CHROMIUM_RES_Y=' "SOFTWARE_CHROMIUM_RES_Y=600" /DietPi/dietpi.txt
		G_CONFIG_INJECT 'hdmi_force_hotplug=' 'hdmi_force_hotplug=1' $FP_RPI_CONFIG
		G_CONFIG_INJECT 'hdmi_group=' 'hdmi_group=2' $FP_RPI_CONFIG
		G_CONFIG_INJECT 'hdmi_mode=' 'hdmi_mode=87' $FP_RPI_CONFIG
		G_CONFIG_INJECT 'hdmi_cvt=' 'hdmi_cvt=1024 600 60 6 0 0 0' $FP_RPI_CONFIG
		G_CONFIG_INJECT 'hdmi_drive=' 'hdmi_drive=1' $FP_RPI_CONFIG

	}

	Lcd_Panel_ESP01215E_Disable(){

		G_CONFIG_INJECT 'hdmi_force_hotplug=' '#hdmi_force_hotplug=1' $FP_RPI_CONFIG
		G_CONFIG_INJECT 'hdmi_group=' '#hdmi_group=2' $FP_RPI_CONFIG
		G_CONFIG_INJECT 'hdmi_mode=' '#hdmi_mode=87' $FP_RPI_CONFIG
		G_CONFIG_INJECT 'hdmi_cvt=' '#hdmi_cvt=1024 600 60 6 0 0 0' $FP_RPI_CONFIG
		G_CONFIG_INJECT 'hdmi_drive=' '#hdmi_drive=1' $FP_RPI_CONFIG

	}

	Lcd_Panel_Xorg_All_Enable(){

		#Xinput calibrator, fbset for con2fbmap
		G_AG_CHECK_INSTALL_PREREQ fbset xinput-calibrator xserver-xorg-input-evdev

		mkdir -p /etc/X11/xorg.conf.d

		# - Create desktop icon for xcalibration
		#	NB: libinput replaces this in start menu

	}

	# - Waveshare32
	Lcd_Panel_Waveshare32_Enable_X11(){

		cat << _EOF_ > /etc/X11/xorg.conf.d/99-waveshare32_xorg.conf
Section "Device"
        Identifier      "Allwinner A10/A13 FBDEV"
        Driver          "fbdev"
        Option          "fbdev" "/dev/fb1"

        Option          "SwapbuffersWait" "true"
EndSection
_EOF_

		cat << _EOF_ > /etc/X11/xorg.conf.d/99-waveshare32_calibration.conf
Section "InputClass"
Identifier      "calibration"
MatchProduct    "ADS7846 Touchscreen"
Option  "Calibration"   "219 3835 3984 219"
Option  "SwapAxes"      "1"
Driver "evdev"
EndSection
_EOF_

	}

	Lcd_Panel_Waveshare32_Enable(){

		#Disable 1st to reset any existing installations:
		Lcd_Panel_Waveshare32_Disable

		#RPi
		if (( $G_HW_MODEL < 10 )); then

			# + X11
			Lcd_Panel_Xorg_All_Enable
			Lcd_Panel_Waveshare32_Enable_X11

			wget https://dietpi.com/downloads/conf/waveshare32b-overlay.dtb -O /boot/overlays/waveshare32b.dtbo

			#consoleblank=0 no effect
			sed -i 's/rootwait/rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo/' /boot/cmdline.txt

			G_CONFIG_INJECT 'dtparam=i2c_arm=' 'dtparam=i2c_arm=on' $FP_RPI_CONFIG
			G_CONFIG_INJECT 'dtparam=spi=' 'dtparam=spi=on' $FP_RPI_CONFIG

			# - Set FB to match res
			G_CONFIG_INJECT 'framebuffer_width=' 'framebuffer_width=320' $FP_RPI_CONFIG
			G_CONFIG_INJECT 'framebuffer_height=' 'framebuffer_height=240' $FP_RPI_CONFIG
			G_CONFIG_INJECT 'SOFTWARE_CHROMIUM_RES_X=' "SOFTWARE_CHROMIUM_RES_X=320" /DietPi/dietpi.txt
			G_CONFIG_INJECT 'SOFTWARE_CHROMIUM_RES_Y=' "SOFTWARE_CHROMIUM_RES_Y=240" /DietPi/dietpi.txt

			cat << _EOF_ >> $FP_RPI_CONFIG

#Waveshare 32 LCD
dtoverlay=waveshare32b:rotate=270
_EOF_

			# - Swap input axis
			sed -i '/"SwapAxes"/c\        Option  "SwapAxes"      "1"' /etc/X11/xorg.conf.d/99-waveshare32_calibration.conf

			# - Move fb0 xorg.conf out the way: https://github.com/Fourdee/DietPi/issues/767
			mv /usr/share/X11/xorg.conf.d/99-fbturbo.conf /usr/share/X11/99-fbturbo.conf

		#Odroids
		elif (( $G_HW_MODEL >= 10 && $G_HW_MODEL < 20 )); then

			# + X11
			Lcd_Panel_Xorg_All_Enable
			Lcd_Panel_Waveshare32_Enable_X11

			#con2fbmap, maps console (1) to panel(2). Run during boot.
			cat << _EOF_ > /etc/systemd/system/con2fbmap.service
[Unit]
Description=con2fbmap

[Service]
Type=oneshot
ExecStart=/bin/con2fbmap 1 2
ExecStop=/bin/con2fbmap 1 0

RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
_EOF_
			systemctl daemon-reload
			systemctl enable con2fbmap

			echo 'spicc' >> /etc/modules
			echo 'fbtft_device' >> /etc/modules

			cat << _EOF_ > /etc/modprobe.d/waveshare32.conf
options fbtft_device name=odroidc_tft32 rotate=270 gpios=reset:116,dc:115 speed=32000000 cs=0
_EOF_

			#x11
			cat << _EOF_ > /etc/X11/xorg.conf.d/99-waveshare32_xorg.conf
Section "Device"
	Identifier      "FBDEV"
	Driver          "fbdev"
	Option          "fbdev" "/dev/fb2"

	#Option          "SwapbuffersWait" "true"
EndSection

_EOF_

		else

			Lcd_Panel_Not_Available_For_Device

		fi


	}

	Lcd_Panel_Waveshare32_Disable(){

		#all
		rm /etc/X11/xorg.conf.d/99-waveshare32_calibration.conf &> /dev/null
		rm /etc/X11/xorg.conf.d/99-waveshare32_xorg.conf &> /dev/null
		rm /usr/share/applications/xinput_calibrator.desktop &> /dev/null

		#RPi
		if (( $G_HW_MODEL < 10 )); then

			rm /boot/overlays/waveshare32b.dtbo  &> /dev/null
			sed -i 's/ fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo//' /boot/cmdline.txt

			sed -i '/Waveshare 32 LCD/d' $FP_RPI_CONFIG
			sed -i '/dtoverlay=waveshare32b/d' $FP_RPI_CONFIG
			sed -i '/dtoverlay=ads7846,cs=1,penirq=17/d' $FP_RPI_CONFIG
			sed -i '/dtoverlay=w1-gpio-pullup,gpiopin=4,extpullup=1/d' $FP_RPI_CONFIG

			# - Leave these enabled, just incase the user has other hardware that may use them.
			#sed -i "/dtparam=i2c_arm=/c\dtparam=i2c_arm=on" $FP_RPI_CONFIG
			#sed -i "/dtparam=spi=/c\dtparam=spi=on" $FP_RPI_CONFIG

			# - Move fb0 xorg.conf back: https://github.com/Fourdee/DietPi/issues/767
			mv /usr/share/X11/99-fbturbo.conf /usr/share/X11/xorg.conf.d/99-fbturbo.conf &> /dev/null

		#Odroids
		elif (( $G_HW_MODEL >= 10 && $G_HW_MODEL < 20 )); then

			rm /etc/systemd/system/con2fbmap.service &> /dev/null
			systemctl daemon-reload

			rm /etc/modprobe.d/waveshare32.conf &> /dev/null
			sed -i '/^spicc/d' /etc/modules
			sed -i '/^fbtft_device/d' /etc/modules

		fi

	}

	# - Odroid Cloudshell
	Lcd_Panel_Odroidcloudshell_Enable(){

		cat << _EOF_ > /etc/modprobe.d/odroid-cloudshell.conf
options fbtft_device name=hktft9340 busnum=1 rotate=270
_EOF_

		echo 'spi_s3c64xx' >> /etc/modules
		echo 'fbtft_device' >> /etc/modules
		echo 'fbtft_device' >> /etc/modules #XU4 4.9 workaround: https://github.com/Fourdee/DietPi/issues/926#issuecomment-299480918

	}

	Lcd_Panel_Odroidcloudshell_Disable(){

		rm /etc/modprobe.d/odroid-cloudshell.conf
		sed -i '/^spi_s3c64xx/d' /etc/modules
		sed -i '/^fbtft_device/d' /etc/modules

		##Cant run it on the fly, locks up device.
		#root@DietPi-XU4:~# modprobe -rf spi_s3c64xx
		#root@DietPi-XU4:~# modprobe -rf fbtft_device
		#Segmentation fault

	}

	# - Odroid LCD 3.5
	Lcd_Panel_OdroidLCD35_Enable(){

		if (( $G_HW_MODEL >= 10 && $G_HW_MODEL < 20 )); then

			#Reset to disabled:
			Lcd_Panel_OdroidLCD35_Disable

			Lcd_Panel_Xorg_All_Enable

			cat << _EOF_ > /etc/modprobe.d/odroid-lcd35.conf
options fbtft_device name=flexpfb rotate=90
options flexfb chip=ili9488
_EOF_

			local amodules=(

				'fbtft_device'
				'flexfb'
				'sx865x'

			)

			# - C1/2
			if (( $G_HW_MODEL != 11 )); then

				amodules+=('aml_i2c')
				amodules+=('pwm-meson')
				amodules+=('pwm-ctrl')

			fi

			for i in ${!amodules[@]}
			do

				# - Enable modules now, as we need to detect pwm path for service
				G_RUN_CMD modprobe ${amodules[$i]}
				G_CONFIG_INJECT "${amodules[$i]}" "${amodules[$i]}" /etc/modules

			done

			unset amodules

			#Service
			# - XU4
			if (( $G_HW_MODEL == 11 )); then

				cat << _EOF_ > /etc/systemd/system/odroid-lcd35.service
[Unit]
Description=Odroid LCD 3.5

[Path]
PathExists=/dev/fb2

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/setterm -blank 0 -powersave off
ExecStart=/bin/con2fbmap 1 2
StandardOutput=tty

[Install]
WantedBy=multi-user.target
_EOF_

			# - C1/2
			else

				# Detect correct control files: https://github.com/Fourdee/DietPi/issues/2256
				local fp_control='/sys/devices/platform/pwm-ctrl'
				[[ -e '/sys/devices/pwm-ctrl/enable0' ]] && fp_control='/sys/devices/pwm-ctrl'

				cat << _EOF_ > /etc/systemd/system/odroid-lcd35.service
[Unit]
Description=Odroid LCD 3.5

[Path]
PathExists=/dev/fb2

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c 'echo 500000 > $fp_control/freq0'
ExecStart=/bin/bash -c 'echo 1 > $fp_control/enable0'
ExecStart=/bin/bash -c 'echo 1023 > $fp_control/duty0'
ExecStart=/usr/bin/setterm -blank 0 -powersave off
ExecStart=/bin/con2fbmap 1 2
StandardOutput=tty

[Install]
WantedBy=multi-user.target
_EOF_

			fi
			systemctl daemon-reload
			systemctl enable odroid-lcd35.service

			#XORG
			rm /etc/X11/xorg.conf.d/exynos.conf #XU4

			mkdir -p /etc/X11/xorg.conf.d
			cat << _EOF_ > /etc/X11/xorg.conf.d/99-odroid-lcd35.conf
Section "Device"
    Identifier    "C fbdev"
    Driver        "fbdev"
    Option        "fbdev" "/dev/fb2"
EndSection
_EOF_

			# - default calibration
			cat << _EOF_ > /etc/X11/xorg.conf.d/99-calibration.conf
Section "InputClass"
        Identifier      "calibration"
        MatchProduct    "SX865X Touchscreen"
        Option  "Calibration"   "3854 155 3880 262"
        Option  "SwapAxes"      "0"
EndSection
_EOF_

		else

			Lcd_Panel_Not_Available_For_Device

		fi


	}

	Lcd_Panel_OdroidLCD35_Disable(){

		rm /etc/X11/xorg.conf.d/99-calibration.conf
		rm /etc/modprobe.d/odroid-lcd35.conf
		rm /etc/systemd/system/odroid-lcd35.service
		rm /etc/X11/xorg.conf.d/99-odroid-lcd35.conf
		systemctl daemon-reload

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# i2c
	#/////////////////////////////////////////////////////////////////////////////////////
	# Currently only for RPi.
	I2c_Main(){

		if [[ $INPUT_DEVICE_VALUE == 'enable' ]]; then

			#Check/install pre-reqs
			G_AG_CHECK_INSTALL_PREREQ python-smbus i2c-tools

			#Kernel modules
			# - Remove all previous line references (includes commented ones)
			sed -i '/i2c-bcm2708/d' /etc/modules &> /dev/null
			sed -i '/i2c-dev/d' /etc/modules &> /dev/null
			# - Add modules
			G_CONFIG_INJECT 'i2c-bcm2708' 'i2c-bcm2708' /etc/modules
			G_CONFIG_INJECT 'i2c-dev' 'i2c-dev' /etc/modules

			#Remove from blacklist (Wheezy only. Jessie doesnt exist)
			sed -i '/blacklist spi-bcm2708/d' /etc/modprobe.d/raspi-blacklist.conf &> /dev/null
			sed -i '/blacklist i2c-bcm2708/d' /etc/modprobe.d/raspi-blacklist.conf &> /dev/null

			#config.txt
			G_CONFIG_INJECT 'dtparam=i2c_arm=' 'dtparam=i2c_arm=on' $FP_RPI_CONFIG
			G_CONFIG_INJECT 'dtparam=i2c1=' 'dtparam=i2c1=on' $FP_RPI_CONFIG

			#DietPi-Software, set installed
			sed -i '/^aSOFTWARE_INSTALL_STATE\[72\]=/c\aSOFTWARE_INSTALL_STATE\[72\]=2' /DietPi/dietpi/.installed

		elif [[ $INPUT_DEVICE_VALUE == 'disable' ]]; then

			sed -i '/i2c-bcm2708/d' /etc/modules &> /dev/null
			sed -i '/i2c-dev/d' /etc/modules &> /dev/null
			G_CONFIG_INJECT 'dtparam=i2c_arm=' 'dtparam=i2c_arm=off' $FP_RPI_CONFIG
			G_CONFIG_INJECT 'dtparam=i2c1=' 'dtparam=i2c1=off' $FP_RPI_CONFIG
			G_CONFIG_INJECT 'i2c_arm_baudrate=' 'i2c_arm_baudrate=100000' $FP_RPI_CONFIG

		#Set baudrate (khz) | valid int
		elif disable_error=1 G_CHECK_VALIDINT $INPUT_DEVICE_VALUE 2 10000000; then

			G_CONFIG_INJECT 'i2c_arm_baudrate=' "i2c_arm_baudrate=$(( $INPUT_DEVICE_VALUE * 1000 ))" $FP_RPI_CONFIG

			#inform user
			INPUT_DEVICE_VALUE+="Khz"

		else

			Unknown_Input_Mode

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# bluetooth
	#/////////////////////////////////////////////////////////////////////////////////////

	Bluetooth_Main(){

		local aBLUETOOTH_MODULES=()

		aBLUETOOTH_MODULES=('bluetooth')
		aBLUETOOTH_MODULES+=('bnep')

		aBLUETOOTH_MODULES+=('btbcm') # rpi3 broadcom onboard

		aBLUETOOTH_MODULES+=('rfcomm') # BPi pro/m2+ and others
		aBLUETOOTH_MODULES+=('hidp') # BPi pro/m2+ and others

		aBLUETOOTH_MODULES+=('hci_uart')

		rm /etc/modprobe.d/disable_bt.conf &> /dev/null

		# - Disable
		if [[ $INPUT_DEVICE_VALUE == 'disable' ]]; then

			# + all Broadcom-based models that need brcm_patchram_plus
			if (( $G_HW_MODEL == 61 || $G_HW_MODEL == 62 )); then

				systemctl stop brcm_patchram_plus 2> /dev/null
				systemctl disable brcm_patchram_plus 2> /dev/null

			fi

			# + RPi 3 (apply to all, as pi-bluetooth package is default installed on all RPi's now)
			#	+ Asus TB
			if (( $G_HW_MODEL < 10 || $G_HW_MODEL == 52 )); then

				systemctl stop hciuart
				systemctl disable hciuart

			fi

			#bluetooth last
			systemctl stop bluetooth 2> /dev/null
			systemctl disable bluetooth 2> /dev/null

			for ((i=$(( ${#aBLUETOOTH_MODULES[@]} - 1 )); i>=0; i--))
			do

				modprobe -rf "${aBLUETOOTH_MODULES[$i]}" 2> /dev/null
				echo -e "blacklist ${aBLUETOOTH_MODULES[$i]}" >> /etc/modprobe.d/disable_bt.conf

			done

			#Purge packages
			if (( $G_DIETPI_INSTALL_STAGE >= 0 )); then

				G_AGP bluetooth bluez-firmware
				G_AGA

			fi

		# - Enable
		elif [[ $INPUT_DEVICE_VALUE == 'enable' ]]; then

			#Pre-Reqs
			G_AG_CHECK_INSTALL_PREREQ bluetooth bluez-firmware
			if (( $G_HW_MODEL < 10 )); then

				G_AG_CHECK_INSTALL_PREREQ pi-bluetooth

			fi

			#bluetooth first
			for ((i=0; i<${#aBLUETOOTH_MODULES[@]}; i++))
			do

				modprobe "${aBLUETOOTH_MODULES[$i]}" 2> /dev/null

			done

			# + all Broadcom-based models that need brcm_patchram_plus
			if (( $G_HW_MODEL == 61 || $G_HW_MODEL == 62 )); then

				systemctl enable brcm_patchram_plus 2> /dev/null
				G_RUN_CMD systemctl start brcm_patchram_plus

			fi

			systemctl enable bluetooth 2> /dev/null
			G_RUN_CMD systemctl start bluetooth

			#	+ RPi / Asus TB
			if (( $G_HW_MODEL < 10 || $G_HW_MODEL == 52 )); then

				systemctl enable hciuart
				G_RUN_CMD systemctl start hciuart

			fi

		else

			Unknown_Input_Mode

		fi

		unset aBLUETOOTH_MODULES

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Network
	#/////////////////////////////////////////////////////////////////////////////////////

	Enable_IPv6(){

		if [[ ! -d /proc/sys/net/ipv6 ]]; then

			G_DIETPI-NOTIFY 1 'IPv6 is not supported or disabled on kernel level. Aborting...'
			EXIT_CODE=1
			return

		elif [[ $INPUT_DEVICE_VALUE == 'enable' ]]; then

			[[ -f /etc/sysctl.d/dietpi-disable_ipv6.conf ]] && rm /etc/sysctl.d/dietpi-disable_ipv6.conf
			# - Apply to current session:
			#	- "all" => all existing interfaces
			#	- "default" => all future interfaces
			echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6
			echo 0 > /proc/sys/net/ipv6/conf/default/disable_ipv6
			# - Add IPv6 specific host entries
			G_CONFIG_INJECT '::1[[:blank:]]' '::1 localhost ip6-localhost ip6-loopback' /etc/hosts
			G_CONFIG_INJECT 'ff02::1[[:blank:]]' 'ff02::1 ip6-allnodes' /etc/hosts
			G_CONFIG_INJECT 'ff02::2[[:blank:]]' 'ff02::2 ip6-allrouters' /etc/hosts
			# - dietpi.txt entry
			G_CONFIG_INJECT 'CONFIG_ENABLE_IPV6=' 'CONFIG_ENABLE_IPV6=1' /DietPi/dietpi.txt

		elif [[ $INPUT_DEVICE_VALUE == 'disable' ]]; then

			echo -e 'net.ipv6.conf.all.disable_ipv6=1\nnet.ipv6.conf.default.disable_ipv6=1' > /etc/sysctl.d/dietpi-disable_ipv6.conf
			sysctl -qp /etc/sysctl.d/dietpi-disable_ipv6.conf
			# - Comment IPv6 specific host entries
			sed -i 's/^::1[[:blank:]]/#::1 /' /etc/hosts
			sed -i 's/^ff02::1[[:blank:]]/#ff02::1 /' /etc/hosts
			sed -i 's/^ff02::2[[:blank:]]/#ff02::2 /' /etc/hosts
			# - dietpi.txt entry
			G_CONFIG_INJECT 'CONFIG_ENABLE_IPV6=' 'CONFIG_ENABLE_IPV6=0' /DietPi/dietpi.txt
			# - Stop preferring IPv4, if IPv6 is disabled, to reduce obsolete/confusing entries
			INPUT_DEVICE_VALUE='disable' Prefer_IPv4

		else

			Unknown_Input_Mode
			return

		fi

		# Failsafe: Comment "disable_ipv6" entries in all other sysctl config files
		local i=''
		for i in /etc/sysctl.conf /etc/sysctl.d/*
		do

			[[ ! -f $i || $i == *'dietpi-disable_ipv6.conf' ]] && continue
			sed -i 's/^[[:blank:]]*net.ipv6.conf.[^[:blank:]].disable_ipv6[[:blank:]]*=/#&/' $i

		done

	}

	Prefer_IPv4(){

		if [[ $INPUT_DEVICE_VALUE == 'enable' ]]; then

			# - APT force IPv4
			echo 'Acquire::ForceIPv4 "true";' > /etc/apt/apt.conf.d/99-dietpi-force-ipv4
			# - Wget prefer IPv4
			G_CONFIG_INJECT 'prefer-family[[:blank:]]*=' 'prefer-family = IPv4' /etc/wgetrc
			# - dietpi.txt entry
			G_CONFIG_INJECT 'CONFIG_PREFER_IPV4=' 'CONFIG_PREFER_IPV4=1' /DietPi/dietpi.txt

		elif [[ $INPUT_DEVICE_VALUE == 'disable' ]]; then

			# - APT allow IPv6
			[[ -f /etc/apt/apt.conf.d/99-dietpi-force-ipv4 ]] && rm /etc/apt/apt.conf.d/99-dietpi-force-ipv4
			# - Wget back to default
			sed -i 's/^[[:blank:]]*prefer-family[[:blank:]]*=/#&/' /etc/wgetrc
			# - dietpi.txt entry
			G_CONFIG_INJECT 'CONFIG_PREFER_IPV4=' 'CONFIG_PREFER_IPV4=0' /DietPi/dietpi.txt

		else

			Unknown_Input_Mode
			return

		fi

		# Failsafe: Comment "ForceIPv[46]" entries in all other APT config files
		local i=''
		for i in /etc/apt/apt.conf.d/*
		do

			[[ ! -f $i || $i == *'99-dietpi-force-ipv4' ]] && continue
			sed -i 's/^[[:blank:]]*Acquire::ForceIPv[46][[:blank:]]*=/#&/' $i

		done

	}

	Wifi_Modules_Main(){

		local aWIFI_MODULES=()

		# - All
		aWIFI_MODULES=('cfg80211')

		#NB: we need to start doing these device specific via $G_HW_MODEL index. This prevents unnecessary modules getting loaded.
		# + RPi 3
		aWIFI_MODULES+=('brcmfmac') #onboard WiFi
		aWIFI_MODULES+=('brcmutil') #onboard WiFi

		# + BPi Pro
		aWIFI_MODULES+=('ap6211') #onboard

		# + OrangePi Zero
		if (( $G_HW_MODEL == 32 )); then

			aWIFI_MODULES+=('xradio_wlan')

		# + OrangePi Plus/K1Plus
		elif (( $G_HW_MODEL == 34 || $G_HW_MODEL == 67 )); then

			aWIFI_MODULES+=('8189es')

		# + Pine A64 / PB / Asus tinker board (onboard)
		elif (( $G_HW_MODEL == 40 || $G_HW_MODEL == 44 || $G_HW_MODEL == 52  )); then

			aWIFI_MODULES+=('8723bs')

		# + NanoPi NEO Air / Zero 2+
		elif (( $G_HW_MODEL == 35 || $G_HW_MODEL == 64 )); then

			#4.9 uses brcm, only enable dhd for 3.x
			if [[ ! -d '/boot/dtb' ]]; then

				aWIFI_MODULES+=('dhd')

			fi

		fi

		# + NanoPi T3
		aWIFI_MODULES+=('bcmdhd')

		# - Disable
		if [[ $INPUT_DEVICE_VALUE == 'disable' ]]; then

			rm /etc/modprobe.d/disable_wifi.conf &> /dev/null

			#cfg80211 last
			for ((i=$(( ${#aWIFI_MODULES[@]} - 1 )); i>=0; i--))
			do

				modprobe -rf "${aWIFI_MODULES[$i]}" 2> /dev/null
				echo -e "blacklist ${aWIFI_MODULES[$i]}" >> /etc/modprobe.d/disable_wifi.conf

			done

		# - Enable
		elif [[ $INPUT_DEVICE_VALUE == 'enable' ]]; then

			# - Install prereqs
			local pre_req_packages='crda iw rfkill wireless-tools wpasupplicant'

			G_AG_CHECK_INSTALL_PREREQ $pre_req_packages
			if (( $? != 0 )); then

				exit 1

			fi

			rm /etc/modprobe.d/disable_wifi.conf &> /dev/null

			# - Disable known powersaving options for specific chipsets
			echo 'options 8192cu rtw_power_mgnt=0' > /etc/modprobe.d/8192cu.conf
			echo 'options 8188eu rtw_power_mgnt=0' > /etc/modprobe.d/8188eu.conf
			echo 'options 8189es rtw_power_mgnt=0' > /etc/modprobe.d/8189es.conf #OPi Plus
			echo 'options 8723bs rtw_power_mgnt=0' > /etc/modprobe.d/8723bs.conf #PineA64
			echo 'options wlan_8192eu rtw_power_mgnt=0' > /etc/modprobe.d/wlan_8192eu.conf # Sparky/Allo WiFi

			#cfg80211 first
			for ((i=0; i<${#aWIFI_MODULES[@]}; i++))
			do

				modprobe "${aWIFI_MODULES[$i]}" 2> /dev/null

			done

			# - Delay. Without this, kernel reports wifi device not found with RPi 3 and Pine A64 addon board, when ran straight after this script.
			G_DIETPI-NOTIFY 2 'Please wait, enabling WiFi Modules...'
			# - Had to up the delay from 3 seconds to 8 seconds on WPA2-Enterprise, otherwise still get device not found error.
			sleep 8

			# + RPi 3+, unlock scan+wifi https://github.com/Fourdee/DietPi/issues/1627
			rfkill unblock wifi &> /dev/null

			#Update our networking file (refresh active wlan index)
			/DietPi/dietpi/func/obtain_network_details

		elif [[ $INPUT_DEVICE_VALUE == 'onboard_enable' ]]; then

			#NB: Requires reboot
			#NB: Do not change filenames, -f check used by DietPi-Config to obtain state

			rm /etc/modprobe.d/disable_wifi_rpi3_onboard.conf &> /dev/null

		elif [[ $INPUT_DEVICE_VALUE == 'onboard_disable' ]]; then

			#NB: Requires reboot
			#NB: Do not change filenames, -f check used by DietPi-Config to obtain state

			# - RPi 3/ZeroW
			echo -e "blacklist brcmfmac" > /etc/modprobe.d/disable_wifi_rpi3_onboard.conf
			echo -e "blacklist brcmutil" >> /etc/modprobe.d/disable_wifi_rpi3_onboard.conf

		else

			Unknown_Input_Mode

		fi

		unset aWIFI_MODULES

	}

	Wifi_Countrycode_Main(){

		#Use country code from command input. Implies new setting.
		if [[ $INPUT_DEVICE_VALUE ]]; then

			# - Apply value to DietPi.txt
			G_CONFIG_INJECT 'CONFIG_WIFI_COUNTRY_CODE=' "CONFIG_WIFI_COUNTRY_CODE=${INPUT_DEVICE_VALUE^^}" /DietPi/dietpi.txt

			# - Update wpa_supplicant.conf
			if [[ -f '/etc/wpa_supplicant/wpa_supplicant.conf' ]]; then

				G_CONFIG_INJECT 'country=' "country=${INPUT_DEVICE_VALUE^^}" /etc/wpa_supplicant/wpa_supplicant.conf

			fi

		else

			Unknown_Input_Mode

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# serialconsole
	#/////////////////////////////////////////////////////////////////////////////////////

	MAX_SERIAL_CONSOLES=2

	Serial_Main(){

		#-------------------------------------------------------------------------------------
		#Enable
		if [[ $INPUT_DEVICE_VALUE == 'enable' ]]; then

			#systemctl enable serial-getty@*.service # Wildcard does not work, we need to specify each possible tty device name
			#systemctl enable serial-getty@ttyAMA[0-9].service # Number wildcards do not work, we need to specify each possible tty device number

			G_DIETPI-NOTIFY 2 'Enabling known serial-getty services, please wait...'
			systemctl unmask serial-getty@tty.service 2> /dev/null
			systemctl enable serial-getty@tty.service 2> /dev/null
			for ((i=0; i<=$MAX_SERIAL_CONSOLES; i++))
			do

				# - unmask v6.3+
				systemctl unmask serial-getty@ttyAMA$i.service 2> /dev/null
				systemctl unmask serial-getty@ttySAC$i.service 2> /dev/null
				systemctl unmask serial-getty@ttyS$i.service 2> /dev/null
				#systemctl unmask serial-getty@ttyFIQ$i.service 2> /dev/null #:https://github.com/Fourdee/DietPi/issues/1829#issuecomment-398302497


				# - Enable v6.2-
				systemctl enable serial-getty@ttyAMA$i.service 2> /dev/null
				systemctl enable serial-getty@ttySAC$i.service 2> /dev/null
				systemctl enable serial-getty@ttyS$i.service 2> /dev/null
				#systemctl enable serial-getty@ttyFIQ$i.service 2> /dev/null #:https://github.com/Fourdee/DietPi/issues/1829#issuecomment-398302497

				# - Allow root login for known TTY's not in /etc/securetty by default
				#	NanoPC-T4
				G_CONFIG_INJECT "^ttyFIQ$i" "ttyFIQ$i" /etc/securetty

			done

			#Device Specific:
			# - RPi
			if (( $G_HW_MODEL < 10 )); then

				G_CONFIG_INJECT 'enable_uart=' 'enable_uart=1' /DietPi/config.txt

			# - Odroid C1
			elif (( $G_HW_MODEL == 10 )); then

				sed -i '/^setenv condev/c\setenv condev "console=tty0 console=ttyS0,115200n8"' /DietPi/boot.ini

			# - Odroid XU4
			elif (( $G_HW_MODEL == 11 )); then

				if ! grep -qi 'console=ttySAC2,115200n8 ' /DietPi/boot.ini; then

					sed -i 's/console=tty1 /console=tty1 console=ttySAC2,115200n8 /' /DietPi/boot.ini

				fi

			# - Odroid C2
			elif (( $G_HW_MODEL == 12 )); then

				sed -i '/^setenv condev/c\setenv condev "console=tty0 console=ttyS0,115200n8"' /DietPi/boot.ini

			# - Pine A64
			elif (( $G_HW_MODEL == 40 )); then

				if ! grep -qi 'console=ttyS0,115200n8 ' /DietPi/uEnv.txt; then

					sed -i 's/console=tty0 /console=tty0 console=ttyS0,115200n8 /' /DietPi/uEnv.txt

				fi

			fi

			# - Update dietpi.txt global var
			G_CONFIG_INJECT 'CONFIG_SERIAL_CONSOLE_ENABLE=' 'CONFIG_SERIAL_CONSOLE_ENABLE=1' /DietPi/dietpi.txt


		#-------------------------------------------------------------------------------------
		#Disable
		elif [[ $INPUT_DEVICE_VALUE == 'disable' ]]; then

			#Disable services. Although, this seems to have no effect on the cmdline.txt boot.ini etc serial console entries. They run regardless. But lets do it for consistency.
			G_DIETPI-NOTIFY 2 'Disabling known serial-getty services, please wait...'
			systemctl disable serial-getty@tty.service 2> /dev/null
			systemctl mask serial-getty@tty.service 2> /dev/null
			for ((i=0; i<=$MAX_SERIAL_CONSOLES; i++))
			do

				# Disable first, to remove symlink from /etc/systemd/system/getty.target.wants/
				systemctl disable serial-getty@ttyAMA$i.service 2> /dev/null
				systemctl disable serial-getty@ttySAC$i.service 2> /dev/null
				systemctl disable serial-getty@ttyS$i.service 2> /dev/null
				#systemctl disable serial-getty@ttyFIQ$i.service 2> /dev/null #:https://github.com/Fourdee/DietPi/issues/1829#issuecomment-398302497

				systemctl mask serial-getty@ttyAMA$i.service 2> /dev/null
				systemctl mask serial-getty@ttySAC$i.service 2> /dev/null
				systemctl mask serial-getty@ttyS$i.service 2> /dev/null
				#systemctl mask serial-getty@ttyFIQ$i.service 2> /dev/null #:https://github.com/Fourdee/DietPi/issues/1829#issuecomment-398302497

			done

			#Device Specific:
			# - RPi
			if (( $G_HW_MODEL < 10 )); then

				sed -i 's/console=ttyAMA0,115200 //' /boot/cmdline.txt #Replaced by enable_uart=

				G_CONFIG_INJECT 'enable_uart=' 'enable_uart=0' /DietPi/config.txt

			# - Odroid C1/C2
			elif (( $G_HW_MODEL == 10 || $G_HW_MODEL == 12 )); then

				G_CONFIG_INJECT 'setenv condev' 'setenv condev "console=tty0"' /DietPi/boot.ini

			# - Odroid XU4
			elif (( $G_HW_MODEL == 11 )); then

				sed -i 's/console=ttySAC2,115200n8 //' /DietPi/boot.ini

			# - Pine A64
			elif (( $G_HW_MODEL == 40 )); then

				sed -i 's/console=ttyS0,115200n8 //' /DietPi/uEnv.txt

			fi

			# - Update dietpi.txt global var
			G_CONFIG_INJECT 'CONFIG_SERIAL_CONSOLE_ENABLE=' 'CONFIG_SERIAL_CONSOLE_ENABLE=0' /DietPi/dietpi.txt

		else

			Unknown_Input_Mode

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# soundcard
	#/////////////////////////////////////////////////////////////////////////////////////
	#NB: When adding a new dtoverlay soundcard, we must add the dtoverlay name for deletion in Soundcard_Reset_RPi()
	SOUNDCARD_TARGET_CARD=0
	SOUNDCARD_TARGET_DEVICE=0
	ALSA_EQ_ENABLED=0

	#Disable all soundcards and revert back to default output if available.
	Soundcard_Reset_All(){

		SOUNDCARD_TARGET_CARD=0
		SOUNDCARD_TARGET_DEVICE=0
		ALSA_EQ_ENABLED=0

		#Remove previous asound.conf
		rm /etc/asound.conf &> /dev/null

		# - Pre-Reqs for any soundcard
		G_AG_CHECK_INSTALL_PREREQ alsa-utils

		#	Intel sound firmware
		if grep 'vendor_id' /proc/cpuinfo | grep -qi 'intel'; then

			G_AG_CHECK_INSTALL_PREREQ firmware-intel-sound

		fi

		#HW specific
		# - RPI
		if (( $G_HW_MODEL < 10 )); then

			Soundcard_Reset_RPi

		# - Odroid
		elif (( $G_HW_MODEL >= 10 && $G_HW_MODEL < 20 )); then

			Soundcard_Reset_Odroid

		# - OPi Zero (H2+)
		elif (( $G_HW_MODEL == 32 )); then

			Soundcard_Reset_H2

		# - H3
		elif (( $G_HW_CPUID == 1 )); then

			Soundcard_Reset_H3

		# - Pine a64
		elif (( $G_HW_MODEL == 40 )); then

			Soundcard_Reset_PineA64

		# - BPi Pro
		elif (( $G_HW_MODEL == 51 )); then

			Soundcard_Reset_BPi_Pro

		#Sparky SBC
		elif (( $G_HW_MODEL == 70 )); then

			Soundcard_Reset_SparkySBC

		#ASUS
		elif (( $G_HW_MODEL == 52 )); then

			Soundcard_Reset_Asus

		fi

	}

	Soundcard_Reset_RPi(){

		# - Add dtparam=audio=off
		#	as of 4.4 kernel: https://github.com/Fourdee/DietPi/issues/327
		G_CONFIG_INJECT 'dtparam=audio=' 'dtparam=audio=off' $FP_RPI_CONFIG

		# - Remove known soundcard dtoverlays
		sed -i '/dtoverlay=rpi-bcm2835/d' $FP_RPI_CONFIG
		sed -i '/dtoverlay=hifiberry/d' $FP_RPI_CONFIG
		sed -i '/dtoverlay=iqaudio/d' $FP_RPI_CONFIG
		sed -i '/dtoverlay=justboom/d' $FP_RPI_CONFIG
		sed -i '/dtoverlay=allo-/d' $FP_RPI_CONFIG
		sed -i '/dtoverlay=rpi-dac/d' $FP_RPI_CONFIG
		sed -i '/dtoverlay=i-sabre-k2m/d' $FP_RPI_CONFIG
		sed -i '/dtoverlay=dionaudio/d' $FP_RPI_CONFIG
		sed -i '/dtoverlay=googlevoicehat-soundcard/d' $FP_RPI_CONFIG
		sed -i '/dtoverlay=applepi/d' $FP_RPI_CONFIG

		# - Remove i2s maps
		sed -i '/dtoverlay=i2s-mmap/d' $FP_RPI_CONFIG
		sed -i '/dtparam=i2s=/d' $FP_RPI_CONFIG

		#	onboard blacklist module
		echo 'blacklist snd-bcm2835' > /etc/modprobe.d/rpi-bcm2708.conf

		G_CONFIG_INJECT 'avoid_pwm_pll=' 'avoid_pwm_pll=1' $FP_RPI_CONFIG

		# - Disable forced analogue out
		systemctl disable rpi-bcm2835_forced_3.5mm.service &> /dev/null
		rm /etc/systemd/system/rpi-bcm2835_forced_3.5mm.service &> /dev/null
		systemctl daemon-reload
		#	Return Auto
		amixer -c 0 cset numid=3 0 &> /dev/null

	}

	Soundcard_Reset_Odroid(){

		rm /var/lib/dietpi/postboot.d/c2_smp.sh &> /dev/null

		# - hifi shield plus
		sed -i '/snd-soc-pcm5102/d' /etc/modules
		sed -i '/snd-soc-odroid-dac/d' /etc/modules

		# - hifi shield 2
		sed -i '/snd-soc-pcm512x/d' /etc/modules
		sed -i '/snd-soc-pcm512x-i2c/d' /etc/modules
		sed -i '/snd-soc-odroid-dac2/d' /etc/modules

		if [[ -f '/etc/systemd/system/odroid-hifishield2.service' ]]; then

			rm /etc/systemd/system/odroid-hifishield2.service
			systemctl daemon-reload

		fi

	}

	Soundcard_Reset_H2(){

		#set 3.5mm
		amixer set -c 0 'Audio lineout' unmute &> /dev/null

	}

	Soundcard_Reset_H3(){

		#set hdmi
		amixer set -c 0 'Audio lineout' mute &> /dev/null

		SOUNDCARD_TARGET_CARD=1

	}

	Soundcard_Reset_Asus(){

		#set hdmi
		SOUNDCARD_TARGET_CARD=1

	}

	Soundcard_Reset_SparkySBC(){

		sed -i '/snd-soc-allo-piano-dac/d' /etc/modules

		# - HDMI
		SOUNDCARD_TARGET_DEVICE=1
		amixer -c 0 sset 'audio output mode switch' 'hdmi'

		# Disable USB 1.1 compat
		sed -i 's/aotg.aotg1_speed=1/aotg.aotg1_speed=0/' /DietPi/uEnv.txt

		# - auto unmute
		rm /var/lib/dietpi/postboot.d/sparky_unmute.sh &> /dev/null

	}

	Soundcard_Reset_PineA64(){

		rm /etc/modules-load.d/pine64-audiojack.conf
		SOUNDCARD_TARGET_CARD=1

	}

	Soundcard_Reset_BPi_Pro(){

		#3.5mm: https://github.com/Fourdee/DietPi/issues/732#issuecomment-275915919
		SOUNDCARD_TARGET_CARD=0

		amixer sset 'Left Mixer Left DAC' off
		amixer sset 'Power Amplifier' 62
		amixer sset 'Power Amplifier DAC' on
		amixer sset 'Power Amplifier Mixer' off
		amixer sset 'Power Amplifier Mute' on
		amixer sset 'Right Mixer Left DAC' off
		amixer sset 'Right Mixer Right DAC' off

	}

	Soundcard_Main(){

		#-----------------------------------------------------------------------------
		#Always reset soundcards and revert back to HDMI
		Soundcard_Reset_All
		#-----------------------------------------------------------------------------
		#Apply specific asound.confs and additional settings

		# - ALSA EQ enabled?
		if [[ $INPUT_DEVICE_VALUE == *'-eq' ]]; then

			ALSA_EQ_ENABLED=1

			# - remove -eq from string so it doesn't get sent as a dtoverlay= on rpi and dietpi.txt entry
			INPUT_DEVICE_VALUE=$(echo -e "$INPUT_DEVICE_VALUE" | sed 's/-eq//g')

		fi

		# - Update DietPi global soundcard var
		sed -i "/^CONFIG_SOUNDCARD=/c\CONFIG_SOUNDCARD=$INPUT_DEVICE_VALUE" /DietPi/dietpi.txt

		# - RPi: Enable DTPARAM audio setting
		if (( $G_HW_MODEL < 10 )); then

			# - Enable dtparam audio
			G_CONFIG_INJECT 'dtparam=audio=' 'dtparam=audio=on' $FP_RPI_CONFIG

		fi

		#Cards
		case "$INPUT_DEVICE_VALUE" in

			#ALL: ----------------------------------------------------------------------

			#Specify card + device indexs
			hw:*)

				echo -e "$INPUT_DEVICE_VALUE"
				local split=$(echo -e "$INPUT_DEVICE_VALUE" | sed 's/,/ /g' | sed 's/hw://g' | sed 's/-eq//g')
				SOUNDCARD_TARGET_CARD=$(echo -e "$split" | awk '{print $1}' )
				SOUNDCARD_TARGET_DEVICE=$(echo -e "$split" | awk '{print $2}' )

			;;

			usb-dac*)

				# - detect card
				local usb_detection_card_index=$(aplay -l | grep -m1 'USB Audio' | awk '{print $2}' | sed 's/://g')
				if disable_error=1 G_CHECK_VALIDINT $usb_detection_card_index; then

					SOUNDCARD_TARGET_CARD=$usb_detection_card_index

					# - Sparky unmute all (re: @sudeep)
					if (( $G_HW_MODEL == 70 )); then

						#	USB 1.1 compat mode (Sparky currently)
						if [[ $INPUT_DEVICE_VALUE == 'usb-dac-1.1' ]]; then

							sed -i 's/aotg.aotg1_speed=0/aotg.aotg1_speed=1/' /DietPi/uEnv.txt

						fi

						cat << _EOF_ > /var/lib/dietpi/postboot.d/sparky_unmute.sh
#!/bin/bash
for x in \`amixer controls | grep layback\`
do

    amixer cset "\${x}" 100% &> /dev/null

done
alsactl store &> /dev/null
_EOF_

					#https://github.com/Fourdee/DietPi/issues/2101
					elif (( $G_HW_MODEL == 12 )); then

						cat << _EOF_ > /var/lib/dietpi/postboot.d/c2_smp.sh
#!/bin/bash
echo 4 > /proc/irq/63/smp_affinity
echo 8 > /proc/irq/62/smp_affinity
_EOF_

					fi

				# - Not found
				else

					G_DIETPI-NOTIFY 1 "Unable to find a USB-DAC on system."
					EXIT_CODE=1

					# - Reset
					G_CONFIG_INJECT 'CONFIG_SOUNDCARD=' 'CONFIG_SOUNDCARD=none' /DietPi/dietpi.txt

				fi

				SOUNDCARD_TARGET_DEVICE=0

			;;

			#RPi (dtoverlay)
			#	rpi-bcm2835
			#	rpi-bcm2835-ultrahq
			#	rpi-bcm2835-3.5mm
			#	rpi-bcm2835-ultrahq-3.5mm
			rpi-bcm2835*)

				# - remove from blacklist to enable:
				rm /etc/modprobe.d/rpi-bcm2708.conf

				# - Enable HQ audio
				G_CONFIG_INJECT 'avoid_pwm_pll=' 'avoid_pwm_pll=0' $FP_RPI_CONFIG

				# - Expermental UltraHQ audio: https://www.raspberrypi.org/forums/viewtopic.php?p=907075#p907075
				if [[ $INPUT_DEVICE_VALUE == *'ultrahq'* ]]; then

					sed -i '/avoid_pwm_pll=/c\avoid_pwm_pll=2' $FP_RPI_CONFIG

				fi

				# - Force 3.5mm out?
				if [[ $INPUT_DEVICE_VALUE == *'3.5mm'* ]]; then

					cat << _EOF_ > /etc/systemd/system/rpi-bcm2835_forced_3.5mm.service
[Unit]
Description=Forces sound through 3.5mm analogue
Before=sound.target
After=dietpi-boot.service dietpi-ramdisk.service dietpi-ramlog.service

[Service]
Type=simple
RemainAfterExit=yes

ExecStart=/usr/bin/amixer -c 0 cset numid=3 1

[Install]
WantedBy=multi-user.target
_EOF_
					systemctl daemon-reload
					systemctl enable rpi-bcm2835_forced_3.5mm.service
					systemctl start rpi-bcm2835_forced_3.5mm.service

				fi

			;;

			#RPi (dtoverlay)
			#	hifiberry-dac
			#	hifiberry-dacplus
			#	hifiberry-digi
			#	hifiberry-digi-pro
			#	hifiberry-amp
			hifiberry-*)

				# - enable dtoverlay
				echo -e "\ndtoverlay=$INPUT_DEVICE_VALUE" >> $FP_RPI_CONFIG

			;;

			#RPi (dtoverlay)
			#	googlevoicehat-soundcard
			googlevoicehat-soundcard*)

				# - enable dtoverlay
				cat << _EOF_ >> $FP_RPI_CONFIG
dtoverlay=$INPUT_DEVICE_VALUE
dtoverlay=i2s-mmap
dtparam=i2s=on
_EOF_

			;;

			#RPi (dtoverlay)
			#	JustBoom-dac: DAC HAT, Amp HAT, DAC Zero and Amp Zero
			#	JustBoom-digi: Digi HAT and Digi Zero
			justboom-*)

				# - enable dtoverlay
				echo -e "\ndtoverlay=$INPUT_DEVICE_VALUE" >> $FP_RPI_CONFIG

			;;

			#RPi (dtoverlay)
			#	allo-piano-dac-pcm512x-audio
			#	allo-piano-dac-plus-pcm512x-audio (2.1)
			allo-piano-dac*)

				if [[ ! -d '/lib/firmware/allo' ]]; then

					INSTALL_URL_ADDRESS='https://github.com/allocom/piano-firmware/archive/master.zip'
					G_CHECK_URL "$INSTALL_URL_ADDRESS"
					wget "$INSTALL_URL_ADDRESS" -O package.zip
					unzip -o package.zip
					rm package.zip
					cp -R piano-firmware-master/lib/firmware/allo /lib/firmware/
					rm -R piano-firmware-master

				fi

				echo -e "\ndtoverlay=$INPUT_DEVICE_VALUE" >> $FP_RPI_CONFIG

			;;

			#Sparky SBC (module)
			#	snd-soc-allo-piano-dac
			#	snd-soc-allo-piano-dac-plus (2.1)
			snd-soc-allo-piano-dac*)

				if [[ ! -d '/lib/firmware/allo' ]]; then

					INSTALL_URL_ADDRESS='https://raw.githubusercontent.com/sparky-sbc/sparky-test/master/piano-firmware/piano-firmware.tar'
					G_CHECK_URL "$INSTALL_URL_ADDRESS"
					wget "$INSTALL_URL_ADDRESS" -O package.tar

					tar -xvf package.tar -C /lib/
					rm package.tar

				fi

				echo -e "$INPUT_DEVICE_VALUE" >> /etc/modules
				SOUNDCARD_TARGET_CARD=1
				SOUNDCARD_TARGET_DEVICE=0
				amixer -c 0 sset 'audio output mode switch' 'i2s'

			;;

			#Sparky SBC
			#	allo-cheapo-analogue	#3.5mm/RCA
			#	allo-cheapo-optical	#Optical out
			allo-cheapo*)

				SOUNDCARD_TARGET_CARD=0
				SOUNDCARD_TARGET_DEVICE=0

				# - Vol
				amixer –c 0 set 'DAC PA' 35

				if [[ $INPUT_DEVICE_VALUE == 'allo-cheapo-analogue' ]]; then

					amixer -c 0 sset 'audio output mode switch' 'i2s'

				else

					amixer -c 0 sset 'audio output mode switch' 'spdif'
					SOUNDCARD_TARGET_DEVICE=2

				fi

			;;

			#RPi (dtoverlay)
			#	allo-boss-dac-pcm512x-audio
			#	allo-digione
			#	allo-katana-dac-audio
			allo-*)

				# - enable dtoverlay
				echo -e "\ndtoverlay=$INPUT_DEVICE_VALUE" >> $FP_RPI_CONFIG

				if [[ $INPUT_DEVICE_VALUE == 'allo-katana-dac-audio' && ! -d '/var/www/allo' ]]; then

					G_RPI_UPDATE

				fi

			;;

			#RPi (dtoverlay)
			#	rpi-dac
			rpi-dac)

				# - enable dtoverlay
				echo -e "\ndtoverlay=$INPUT_DEVICE_VALUE" >> $FP_RPI_CONFIG

			;;

			#AudioPhonics I-Sabre-K2M (dtoverlay)
			#	i-sabre-k2m
			i-sabre-k2m)

				# - Sourcebuild
				if [[ ! -f '/var/lib/dietpi/.G_RPI_UPDATE' ]]; then

					G_RPI_UPDATE
					G_CONFIG_INJECT 'CONFIG_SOUNDCARD=' 'CONFIG_SOUNDCARD=none' /DietPi/dietpi.txt
					G_WHIP_MSG "Stage 1 completed (ni-sabre-k2m_build):\n\nThe device will now reboot.\n\nOnce rebooted, please run dietpi-config > Audio Options again. Reselect the soundcard (i-sabre-k2m) to complete installation."
					reboot

				fi

				if [[ ! -f '/var/lib/dietpi/.compiled_i-sabre-k2m' ]]; then

					local install_url_address='https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source'
					G_CHECK_URL "$install_url_address"
					G_AG_CHECK_INSTALL_PREREQ python build-essential git device-tree-compiler gcc-4.9 g++-4.9

					mkdir -p $HOME/i-sabre-k2m_build
					cd $HOME/i-sabre-k2m_build
					wget "$install_url_address" -O /usr/bin/rpi-source
					chmod +x /usr/bin/rpi-source
					/usr/bin/rpi-source -q --tag-update
					rpi-source -d . --skip-gcc

					install_url_address='https://dietpi.com/downloads/sourcebuild/I-Sabre-K2M.7z'
					G_CHECK_URL "$install_url_address"
					wget "$install_url_address" -O package.7z
					7z x -y package.7z
					rm package.7z

					G_RUN_CMD make
					G_RUN_CMD make modules_install
					G_RUN_CMD make dtbs
					G_RUN_CMD make install_dtbo

					cd $HOME
					rm -R i-sabre-k2m_build

					> /var/lib/dietpi/.compiled_i-sabre-k2m

				fi

				# - enable dtoverlay
				echo -e "\ndtoverlay=$INPUT_DEVICE_VALUE" >> $FP_RPI_CONFIG

			;;

			#RPi (dtoverlay)
			#	applepi-dac
			applepi*)

				# - enable dtoverlay
				echo -e "\ndtoverlay=$INPUT_DEVICE_VALUE" >> $FP_RPI_CONFIG

			;;

			iqaudio-*)

				# - enable dtoverlay
				echo -e "\ndtoverlay=$INPUT_DEVICE_VALUE" >> $FP_RPI_CONFIG

			;;

			#dionaudio-loco
			#dionaudio-loco-v2
			dionaudio-loco*)

				# - enable dtoverlay
				echo -e "\ndtoverlay=$INPUT_DEVICE_VALUE" >> $FP_RPI_CONFIG

			;;

			#Odroid -------------------------------------------------------------------------------
			odroid-hifishield-plus)

				G_CONFIG_INJECT 'snd-soc-pcm5102' 'snd-soc-pcm5102' /etc/modules
				G_CONFIG_INJECT 'snd-soc-odroid-dac' 'snd-soc-odroid-dac' /etc/modules

				SOUNDCARD_TARGET_CARD=1

			;;

			odroid-hifishield-2)

				G_CONFIG_INJECT 'aml_i2c' 'aml_i2c' /etc/modules
				G_CONFIG_INJECT 'snd-soc-pcm512x' 'snd-soc-pcm512x' /etc/modules
				G_CONFIG_INJECT 'snd-soc-pcm512x-i2c' 'snd-soc-pcm512x-i2c' /etc/modules
				G_CONFIG_INJECT 'snd-soc-odroid-dac2' 'snd-soc-odroid-dac2' /etc/modules

				SOUNDCARD_TARGET_CARD=1

				cat << _EOF_ > /etc/systemd/system/odroid-hifishield2.service
[Unit]
Description=odroid-hifishield2
After=local-fs.target

[Service]
Type=oneshot
RemainAfterExit=yes

ExecStart=/bin/bash -c 'echo pcm5242 0x4c > /sys/class/i2c-adapter/i2c-1/new_device'
ExecStart=/bin/bash -c 'amixer -c 1 sset Analogue 0'
ExecStart=/bin/bash -c 'amixer -c 1 sset Digital 201'
ExecStart=/bin/bash -c 'amixer -c 1 sset Deemphasis on'

[Install]
WantedBy=sound.target
_EOF_
				systemctl daemon-reload
				systemctl enable odroid-hifishield2.service

			;;

			#H2 -------------------------------------------------------------------------------
			h2-hdmi)

				amixer set -c 0 'Audio lineout' mute &> /dev/null
				SOUNDCARD_TARGET_CARD=1

			;;

			#H3 -------------------------------------------------------------------------------
			h3-analogue)

				amixer set -c 0 'Audio lineout' unmute &> /dev/null
				SOUNDCARD_TARGET_CARD=0

			;;

			#Pine A64 -------------------------------------------------------------------------------
			pine64-analogue)

				cat << _EOF_ > /etc/modules-load.d/pine64-audiojack.conf
sunxi_codec
sunxi_i2s
sunxi_sndcodec
_EOF_

				SOUNDCARD_TARGET_CARD=0

			;;

			#Rock64 -------------------------------------------------------------------------------
			rock64-analogue)

				SOUNDCARD_TARGET_CARD=1

			;;

			#NanoPi M2/M3 -------------------------------------------------------------------------------
			s5pxx18-hdmi)

				SOUNDCARD_TARGET_CARD=1

			;;

			#Asus tinker -------------------------------------------------------------------------------
			asus-tb-analogue)

				SOUNDCARD_TARGET_CARD=0
				SOUNDCARD_TARGET_DEVICE=2

			;;

		esac

		# - Apply asound.conf
		if [[ $INPUT_DEVICE_VALUE == 'googlevoicehat-soundcard'* ]]; then

			cat << _EOF_ > /etc/asound.conf
pcm.softvol {
    type softvol
    slave.pcm dmix
    control {
        name Master
        card 0
    }
}

pcm.micboost {
    type route
    slave.pcm dsnoop
    ttable {
        0.0 30.0
        1.1 30.0
    }
}

pcm.!default {
    type asym
    playback.pcm "plug:softvol"
    capture.pcm "plug:micboost"
}

ctl.!default {
    type hw
    card 0
}
_EOF_

		elif (( $ALSA_EQ_ENABLED )); then

			cat << _EOF_ > /etc/asound.conf
ctl.eq {
    type equal
    controls "$HOME/.alsaequal.bin"
}

pcm.plugequal {
    type equal
    slave.pcm "plughw:$SOUNDCARD_TARGET_CARD,$SOUNDCARD_TARGET_DEVICE"
    controls "$HOME/.alsaequal.bin"
}

pcm.!default {
    type plug
    slave.pcm plugequal
    slave.channels 2
}

ctl.!default {
    type hw
    card $SOUNDCARD_TARGET_CARD
}
_EOF_

			G_AG_CHECK_INSTALL_PREREQ libasound2-plugin-equal

		else

			cat << _EOF_ > /etc/asound.conf
pcm.!default {
    type hw
    card $SOUNDCARD_TARGET_CARD
    device $SOUNDCARD_TARGET_DEVICE
}
ctl.!default {
    type hw
    card $SOUNDCARD_TARGET_CARD
}
_EOF_

		fi

	}


	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	#info

	G_DIETPI-NOTIFY 3 "$G_PROGRAM_NAME" "$INPUT_DEVICE_NAME ($INPUT_DEVICE_VALUE)"

	#-----------------------------------------------------------------------------------
	if [[ $INPUT_DEVICE_NAME == 'soundcard' ]]; then

		Soundcard_Main

	elif [[ $INPUT_DEVICE_NAME == 'serialconsole' ]]; then

		Serial_Main

	elif [[ $INPUT_DEVICE_NAME == 'bluetooth' ]]; then

		Bluetooth_Main

	elif [[ $INPUT_DEVICE_NAME == 'wifimodules' ]]; then

		Wifi_Modules_Main

	elif [[ $INPUT_DEVICE_NAME == 'enableipv6' ]]; then

		Enable_IPv6

	elif [[ $INPUT_DEVICE_NAME == 'preferipv4' ]]; then

		Prefer_IPv4

	elif [[ $INPUT_DEVICE_NAME == 'wificountrycode' ]]; then

		Wifi_Countrycode_Main

	elif [[ $INPUT_DEVICE_NAME == 'i2c' ]]; then

		I2c_Main

	elif [[ $INPUT_DEVICE_NAME == 'lcdpanel' ]]; then

		Lcd_Panel_Main

	elif [[ $INPUT_DEVICE_NAME == 'rpi-opengl' ]]; then

		RPi_OpenGL_Main

	elif [[ $INPUT_DEVICE_NAME == 'eth-forcespeed' ]]; then

		Eth_Force_Speed_Main

	elif [[ $INPUT_DEVICE_NAME == 'remoteir' ]]; then

		RemoteIR_Main

	elif [[ $INPUT_DEVICE_NAME == 'gpumemsplit' ]]; then

		Gpu_Memory_Split_Main

	elif [[ $INPUT_DEVICE_NAME == 'rpi-camera' ]]; then

		RPi_Camera_Main

	elif [[ $INPUT_DEVICE_NAME == 'rpi3_usb_boot' ]]; then

		RPi_USB_Boot_Main

	else

		Unknown_Input_Name

	fi

	#-----------------------------------------------------------------------------------
	G_DIETPI-NOTIFY -1 $EXIT_CODE "$INPUT_DEVICE_NAME $INPUT_DEVICE_VALUE |"
	#-----------------------------------------------------------------------------------
	exit $EXIT_CODE
	#-----------------------------------------------------------------------------------
}
