#!/bin/bash
{
	#////////////////////////////////////
	# DietPi RAMLOG Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Saves /var/log/* atrributes and ownerships during shutdown to $FP_DIETPI_RAMLOG_SAVE
	# - Restores /var/log/* atrributes and ownerships during boot from $FP_DIETPI_RAMLOG_SAVE
	# - Uses cp with preserve ownership and attributes only. This generates blank file if required (ramlog) without override existing file data (non-ramlog).
	#
	# Usage:
	# - /DietPi/dietpi/func/dietpi-ramlog 0			= Startup Phase (restores /var/log)
	# - /DietPi/dietpi/func/dietpi-ramlog 1			= Shutdown Phase (saves /var/log)
	#////////////////////////////////////

	#-------------------------------------------------------------------------------------
	#. /DietPi/dietpi/func/dietpi-globals	# Not compatible until dietpi-preboot.service and overkill for the purpose of this script.
	#export LC_ALL=en_GB.UTF-8		# Not needed, as we do not parse any external command and "date" is allowed to be in user locale format.
	#cd $HOME				# "cd: HOME not set" error and not needed, since we do not create any tmp files.
	#-------------------------------------------------------------------------------------

	INPUT=-1 # Use no valid default to prevent accidental removal of storage or recovery of intentionally removed files.
	[[ $1 =~ ^-?[0-9]+$ ]] && INPUT=$1

	EXIT_CODE=0

	PROGRAM_NAME='DietPi-RAMlog'
	FP_DIETPI_RAMLOG_SAVE='/var/tmp/dietpi/logs/dietpi-ramlog_store'

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////

	# Startup Phase (restore /var/log directory structure and files)
	if (( $INPUT == 0 )); then

		echo "$(date) | $PROGRAM_NAME: Startup - Restoring log folder structure to RAMdisk..."

		# - Set bit permission
		chmod 775 /var/log

		# - Apply previous attributes and ownerships. Generates empty file if it doesnt exist.
		[[ -d $FP_DIETPI_RAMLOG_SAVE ]] && cp -R -p --attributes-only $FP_DIETPI_RAMLOG_SAVE/. /var/log/
		EXIT_CODE=$?; if (( $EXIT_CODE )); then

			echo "$(date) | $PROGRAM_NAME: Startup failed with exit code $EXIT_CODE"

		else

			echo "$(date) | $PROGRAM_NAME: Startup completed"

		fi

	# Shutdown Phase (saves /var/log directory structure and filenames)
	elif (( $INPUT == 1 )); then

		echo "$(date) | $PROGRAM_NAME: Shutdown - Saving log folder structure to disk..."

		# - Clear previous storage data
		if [[ -d $FP_DIETPI_RAMLOG_SAVE ]]; then

			rm -R $FP_DIETPI_RAMLOG_SAVE/* &> /dev/null

		# - Create dir
		else

			mkdir -p $FP_DIETPI_RAMLOG_SAVE

		fi

		# - Copy logfile attributes and ownership to storage (not file contents)
		cp -R -p --attributes-only /var/log/. $FP_DIETPI_RAMLOG_SAVE/
		EXIT_CODE=$?; if (( $EXIT_CODE )); then

			echo "$(date) | $PROGRAM_NAME: Shutdown failed with exit code $EXIT_CODE"

		else

			echo "$(date) | $PROGRAM_NAME: Shutdown completed"

		fi

	# Unknown argument
	else

		echo "$(date) | $PROGRAM_NAME: Unknown argument: $INPUT. Aborting..."
		EXIT_CODE=1

	fi

	#-----------------------------------------------------------------------------------
	exit $EXIT_CODE
	#-----------------------------------------------------------------------------------
}
