#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - Enables control and applies settings for specific software and configs.
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Usage:
	#
	# - /DietPi/dietpi/func/dietpi-set_software			useradd_dietpi		0=delete / 1=create
	# - /DietPi/dietpi/func/dietpi-set_software			apt-mirror			url/default
	#////////////////////////////////////

	#Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
	LANG=en_GB.UTF-8

	INPUT_MODE_NAME="$1"
	INPUT_MODE_VALUE="$2"

	#support for 0/1 inputs for enable/disable
	if [ "$INPUT_MODE_VALUE" = "1" ]; then

		INPUT_MODE_VALUE='enable'

	elif [ "$INPUT_MODE_VALUE" = "0" ]; then

		INPUT_MODE_VALUE='disable'

	fi

	EXIT_CODE=0

	HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)
	DISTRO=$(sed -n 3p /DietPi/dietpi/.hw_model)

	Unknown_Input_Name(){

		EXIT_CODE=1
		/DietPi/dietpi/func/dietpi-notify 2 "Unknown input name ($INPUT_MODE_NAME). Nothing has been applied."

	}

	Unknown_Input_Mode(){

		EXIT_CODE=1
		/DietPi/dietpi/func/dietpi-notify 2 "Unknown input value ($INPUT_MODE_VALUE). Nothing has been applied."

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Set Apt Mirror
	#/////////////////////////////////////////////////////////////////////////////////////
	AptMirror_Main(){

		if [ -n "$INPUT_MODE_VALUE" ]; then

			local apt_distro='jessie' #3
			if (( $DISTRO == 4 )); then

				apt_distro='stretch'

			fi

			# - Set defaults?
			if [ "$INPUT_MODE_VALUE" = "default" ]; then

				if (( $HW_MODEL < 10 )); then

					INPUT_MODE_VALUE='http://mirror.ox.ac.uk/sites/archive.raspbian.org/archive/raspbian'

				else

					INPUT_MODE_VALUE='http://ftp.debian.org/debian/'

				fi

			fi

			# - Set raspbian
			if (( $HW_MODEL < 10 )); then

				cat << _EOF_ > /etc/apt/sources.list
deb $INPUT_MODE_VALUE $apt_distro main contrib non-free rpi
_EOF_

				#	Update dietpi.txt entry
				sed -i "/Apt_Raspbian_Mirror=/c\Apt_Raspbian_Mirror=$INPUT_MODE_VALUE" /DietPi/dietpi.txt

			# - Set debian
			else

					cat << _EOF_ > /etc/apt/sources.list
deb $INPUT_MODE_VALUE $apt_distro main contrib non-free
deb $INPUT_MODE_VALUE $apt_distro-updates main contrib non-free
deb http://security.debian.org $apt_distro/updates main contrib non-free
deb $INPUT_MODE_VALUE $apt_distro-backports main contrib non-free
_EOF_

				#	Update dietpi.txt entry
				sed -i "/Apt_Debian_Mirror=/c\Apt_Debian_Mirror=$INPUT_MODE_VALUE" /DietPi/dietpi.txt

			fi

		else

			Unknown_Input_Mode

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Add DietPi user
	#/////////////////////////////////////////////////////////////////////////////////////
	Useradd_DietPi_Main(){

		if [ -n "$INPUT_MODE_VALUE" ]; then

			# - Delete
			if [ "$INPUT_MODE_VALUE" = "0" ]; then

				userdel -f dietpi

			# - Create
			elif [ "$INPUT_MODE_VALUE" = "1" ]; then

				mkdir -p /home
				useradd -m dietpi
				chpasswd <<< "dietpi:$(cat /DietPi/dietpi.txt | grep -m1 '^AUTO_Global_Password=' | sed 's/.*=//')"

				cat << _EOF_ > /home/dietpi/.bashrc
sudo /DietPi/dietpi/login
_EOF_
				chown -R dietpi:dietpi /home/dietpi

				#	Allow sudo without pw
				if (( ! $(cat /etc/sudoers | grep -ci -m1 '^dietpi') )); then

					echo -e "\dietpi ALL=NOPASSWD: ALL\n" >> /etc/sudoers

				fi

				#	Same groups as user pi
				usermod -a -G input,netdev,spi,i2c,gpio,tty,users,games,plugdev,video,audio,sudo,cdrom,dialout,adm dietpi

				#	+ allow access to www-data
				usermod -a -G www-data dietpi

			fi

		else

			Unknown_Input_Mode

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	#info

	/DietPi/dietpi/func/dietpi-notify 3 DietPi-Set_Software "$INPUT_MODE_NAME ($INPUT_MODE_VALUE)"

	#-----------------------------------------------------------------------------------
	if [ "$INPUT_MODE_NAME" = "apt-mirror" ]; then

		AptMirror_Main

	elif [ "$INPUT_MODE_NAME" = "useradd_dietpi" ]; then

		Useradd_DietPi_Main

	else

		Unknown_Input_Name

	fi

	#-----------------------------------------------------------------------------------
	/DietPi/dietpi/func/dietpi-notify -1 $EXIT_CODE "$INPUT_MODE_NAME $INPUT_MODE_VALUE |"
	#-----------------------------------------------------------------------------------
	exit $EXIT_CODE
	#-----------------------------------------------------------------------------------
}