#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - Applys settings for selected soundcard.
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Usage:
	# - /DietPi/dietpi/func/dietpi-set_soundcard none 			= Disable all soundcards
	# - /DietPi/dietpi/func/dietpi-set_soundcard matching_name 	= Enable soundcard
	#////////////////////////////////////

	INPUT=$1
	#Exit path if no string input
	if [ -z "$INPUT" ]; then
		echo -e "Error: Check sourcecode for inputs"
		exit
	fi

	HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)

	#/////////////////////////////////////////////////////////////////////////////////////
	# Func
	#/////////////////////////////////////////////////////////////////////////////////////
	#RPi - Disable all soundcards
	Reset_RPi(){

		# - Sanity | Add snd-bcm2835 module reference if it doesnt exist
		if (( $(cat /etc/modules | grep -ci -m1 'snd-bcm2835') == 0 )); then
			echo -e "#snd-bcm2835" >> /etc/modules
		fi

		# - Disable snd-bcm2835 + HQ audio
		sed -i "/snd-bcm2835/c\#snd-bcm2835" /etc/modules
		sed -i '/avoid_pwm_pll=/c\avoid_pwm_pll=1' /DietPi/config.txt

		# - Remove previous asound.conf
		rm /etc/asound.conf &> /dev/null

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------
	#RPI
	if (( $HW_MODEL < 10 )); then

		# - Always reset soundcards
		Reset_RPi

		# - Always apply selected soundcard
		sed -i "/dtoverlay=/c\#dtoverlay=$INPUT" /DietPi/config.txt

		case "$INPUT" in

			# - Apply hardware specific asound.confs and additional settings
			rpi-bcm2835)
				# - Enable snd-bcm2835 + HQ audio
				sed -i "/snd-bcm2835/c\snd-bcm2835" /etc/modules
				sed -i '/avoid_pwm_pll=/c\avoid_pwm_pll=0' /DietPi/config.txt
			;;

			#hifiberry-dac
			#hifiberry-dacplus
			#hifiberry-digi
			#hifiberry-amp
			hifiberry-*)
				cat << _EOF_ > /etc/asound.conf
pcm.!default {
type hw
card 0
}
ctl.!default {
type hw
card 0
}
_EOF_
			;;

		esac
	fi

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}