#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - find_network_index
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Attempts to find the 1st index numbers for eth[0-9] and wlan[0-9] devices
	# - Saves the number index to "$NETFILE" for use system wide.
	#
	# $NETFILE line1
	# - eth index
	# $NETFILE line2
	# - wlan index
	#////////////////////////////////////
	
	#/////////////////////////////////////////////////////////////////////////////////////
	# Global
	#/////////////////////////////////////////////////////////////////////////////////////

	MAX_DEVICE=10
	TEMP_FILE="/tmp/find_network_index"
	NETFILE="/DietPi/dietpi/.network_device_index"
	
	ETH_INDEX=0
	WLAN_INDEX=0
	
	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	
	#grab content of ifconfig -a
	ifconfig -a > "$TEMP_FILE"
	
	#clear previous
	rm "$NETFILE" &> /dev/null
			
	#find eth[0-9]
	for ((i=0; i<$MAX_DEVICE; i++))
	do
		if (( $(cat "$TEMP_FILE" | grep -ci -m1 "eth$i") == 1 )); then
			ETH_INDEX=$i
			break
		fi
	done

	#find wlan[0-9]
	for ((i=0; i<$MAX_DEVICE; i++))
	do
		if (( $(cat "$TEMP_FILE" | grep -ci -m1 "wlan$i") == 1 )); then
			WLAN_INDEX=$i
			break
		fi
	done
	
	echo -e "$ETH_INDEX" > "$NETFILE"
	echo -e "$WLAN_INDEX" >> "$NETFILE"
	
	rm "$TEMP_FILE"

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}