#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - obtain_network_details
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Attempts to find the 1st index numbers for eth[0-9] and wlan[0-9] devices
	# - Obtains the active network adapter (eth, then wlan).
	# - Saves the above data to $NETFILE for use systemwide
	#
	# $NETFILE line1
	# - eth index
	# $NETFILE line2
	# - wlan index
	# $NETFILE line3
	# - Active adapter name (eg: eth9)
	# $NETFILE line4
	# - IP Address
	#////////////////////////////////////

	#Import DietPi-Globals ---------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	#Import DietPi-Globals ---------------------------------------------------------------

	#/////////////////////////////////////////////////////////////////////////////////////
	# Global
	#/////////////////////////////////////////////////////////////////////////////////////

	MAX_DEVICE=10
	TEMP_FILE="/tmp/find_network_index"
	NETFILE="/DietPi/dietpi/.network"

	ACTIVE_DEVICE="eth0"
	ETH_INDEX=0
	WLAN_INDEX=0
	IP_ADDRESS="Disconnected"

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////

	#grab content of ifconfig -a
	ifconfig -a > "$TEMP_FILE"

	#clear previous
	rm "$NETFILE" &> /dev/null

	#find eth[0-9]
	for ((i=0; i<$MAX_DEVICE; i++))
	do
		if (( $(cat "$TEMP_FILE" | grep -ci -m1 "eth$i") == 1 )); then
			ETH_INDEX=$i
			break
		fi
	done

	#find wlan[0-9]
	for ((i=0; i<$MAX_DEVICE; i++))
	do
		if (( $(cat "$TEMP_FILE" | grep -ci -m1 "wlan$i") == 1 )); then
			WLAN_INDEX=$i
			break
		fi
	done

	#-----------------------------------------------------------------------------------
	#Find active network device
	# - eth takes priority, if both eth wlan are active.
	ip r > "$TEMP_FILE"
	if (( $( cat "$TEMP_FILE" | grep -ci -m1 "eth$ETH_INDEX") == 1 )); then
		ACTIVE_DEVICE="eth$ETH_INDEX"
	elif (( $( cat "$TEMP_FILE" | grep -ci -m1 "wlan$WLAN_INDEX") == 1 )); then
		ACTIVE_DEVICE="wlan$WLAN_INDEX"
	fi

	#-----------------------------------------------------------------------------------
	#IP address
	IP_ADDRESS=$(ifconfig "$ACTIVE_DEVICE" | grep -m1 'inet' | awk '{ print $2 }' | cut -d: -f2 )

	#-----------------------------------------------------------------------------------
	#Output to file
	cat << _EOF_ > "$NETFILE"
$ETH_INDEX
$WLAN_INDEX
$ACTIVE_DEVICE
$IP_ADDRESS
_EOF_

	#Clean up tmp files used
	rm "$TEMP_FILE"

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}
