#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - Update ntpd
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Launches NTPD time sync update
	# - 'status' Allows for status check of sucessful completion with $FP_EXIT_CODE
	#
	# Usage:
	# - /DietPi/dietpi/func/run_ntpd &
	# - /DietPi/dietpi/func/run_ntpd status 			blocking mode (max Xs), wait for exit code of NTPD and return it. Launches ntpd if process and exit file does not exist
	#////////////////////////////////////

	#Import DietPi-Globals ---------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	G_CHECK_ROOT_USER
	#Import DietPi-Globals ---------------------------------------------------------------

	INPUT_MODE=$1

	EXIT_CODE=-1

	FP_EXIT_CODE='/etc/dietpi/.ntpd_exit_status'
	NTPD_UPDATE_MODE=$(grep -m1 '^ntpd_update_mode=' /DietPi/dietpi.txt | sed 's/.*=//')

	Update_NTPD(){

		#Dont run twice
		if (( $(ps aux | grep -ci -m1 '[[:space:]][n]tpd[[:space:]]') )); then

			G_DIETPI-NOTIFY 2 "NTPD: is already running"

		else

			#clear status file
			if [ -f "$FP_EXIT_CODE" ]; then

				rm "$FP_EXIT_CODE"

			fi

			#NTPD: run, exit when updated.
			if (( $NTPD_UPDATE_MODE >= 1 && $NTPD_UPDATE_MODE <= 3 )); then

				G_DIETPI-NOTIFY 2 "NTPD: Running time sync update ($NTPD_UPDATE_MODE)"
				ntpd -gq -l /var/log/ntpd.log &> /dev/null
				EXIT_CODE=$?

			#systemD-timesyncd/other method: assume status is ok
			else

				G_DIETPI-NOTIFY 0 "NTPD: non-NTPD mode detected. Completed"
				EXIT_CODE=0

			fi

			# - log status of completion, prevent software installs: https://github.com/Fourdee/DietPi/issues/786
			echo $EXIT_CODE > "$FP_EXIT_CODE"

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	if [ "$INPUT_MODE" = "status" ]; then

		#NTPD:
		if (( $NTPD_UPDATE_MODE >= 1 && $NTPD_UPDATE_MODE <= 3 )); then

			MAX_LOOPS=30
			CURRENT_LOOP=1
			while (( $CURRENT_LOOP <= $MAX_LOOPS ))
			do

				#	Update NTPD if its not running, and, no exit file exists
				if [ ! -f "$FP_EXIT_CODE" ] && (( ! $(ps aux | grep -ci -m1 '[[:space:]][n]tpd[[:space:]]') )); then

					G_DIETPI-NOTIFY 2 "NTPD: Has not yet been launched, running now, please wait..."
					Update_NTPD &
					sleep 1

				elif [ -f "$FP_EXIT_CODE" ]; then

					EXIT_CODE=$(cat "$FP_EXIT_CODE")
					break

				else

					G_DIETPI-NOTIFY 2 "NTPD: Waiting for completion of time sync ($CURRENT_LOOP/$MAX_LOOPS)"
					sleep 1
					((CURRENT_LOOP++))

				fi

			done

		#systemD-timesyncd/other method: assume status is ok
		else

			G_DIETPI-NOTIFY 0 "NTPD: non-NTPD mode detected. Completed"
			EXIT_CODE=0

		fi

	#Run NTPD
	else

		Update_NTPD

	fi
	#-----------------------------------------------------------------------------------
	#Always return status
	G_DIETPI-NOTIFY -1 $EXIT_CODE 'NTPD: time sync |'
	if (( $EXIT_CODE != 0 )); then

		G_DIETPI-NOTIFY 2 "NTPD: Please check the log file for more information:"
		G_DIETPI-NOTIFY 2 "NTPD: /var/log/ntpd.log"

	fi
	#-----------------------------------------------------------------------------------
	#return exit code
	exit $EXIT_CODE
	#-----------------------------------------------------------------------------------
}