#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Function:
	# - Update ntpd
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Launches NTPD time sync update
	# - 'status' Allows for status check of sucessful completion with $FP_EXIT_CODE
	#
	# Usage:
	# - /DietPi/dietpi/func/run_ntpd &
	# - /DietPi/dietpi/func/run_ntpd status 			blocking mode (max Xs), wait for exit code of NTPD and return it
	#////////////////////////////////////

	#Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
	LANG=en_GB.UTF-8

	INPUT_MODE=$1

	EXIT_CODE=-1

	FP_EXIT_CODE='/etc/dietpi/.ntpd_exit_status'
	NTPD_UPDATE_MODE=0

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	if [ "$INPUT_MODE" = "status" ]; then

		MAX_LOOPS=15
		CURRENT_LOOP=1
		while (( $CURRENT_LOOP <= $MAX_LOOPS ))
		do

			if [ -f "$FP_EXIT_CODE" ]; then

				EXIT_CODE=$(cat "$FP_EXIT_CODE")
				/DietPi/dietpi/func/dietpi-notify -1 $EXIT_CODE 'NTPD: time sync,'
				break

			else

				/DietPi/dietpi/func/dietpi-notify 2 "NTPD: Waiting for completion of time sync ($CURRENT_LOOP/$MAX_LOOPS)"
				sleep 1
				((CURRENT_LOOP++))

			fi

		done

	#Run NTPD if enabled
	else

		#clear status file
		if [ -f "$FP_EXIT_CODE" ]; then

			rm "$FP_EXIT_CODE"

		fi

		NTPD_UPDATE_MODE=$(cat /DietPi/dietpi.txt | grep -m1 '^ntpd_update_mode=' | sed 's/.*=//')

		#NTPD: run, exit when updated.
		if (( $NTPD_UPDATE_MODE >= 1 && $NTPD_UPDATE_MODE <= 3 )); then

			/DietPi/dietpi/func/dietpi-notify 2 "NTPD: Running time sync update (+thread)"
			killall -w ntpd &> /dev/null
			ntpd -gq -l /var/log/ntpd.log &> /dev/null
			EXIT_CODE=$?

		#systemD-timesyncd/other method: assume status is ok
		else

			/DietPi/dietpi/func/dietpi-notify 0 "NTPD: non-NTPD mode detected. Completed"
			EXIT_CODE=0
			echo $EXIT_CODE > "$FP_EXIT_CODE"

		fi

		# - log status of completion, prevent software installs: https://github.com/Fourdee/DietPi/issues/786
		echo $EXIT_CODE > "$FP_EXIT_CODE"

	fi
	#-----------------------------------------------------------------------------------
	#return exit code
	exit $EXIT_CODE
	#-----------------------------------------------------------------------------------
}