ODROIDC-UBOOT-CONFIG

# Console device(s) for boot and kernel logs
setenv condev "console=tty1 console=ttyAML0,115200n8"

# Boot arguments
setenv bootargs "root=/dev/mmcblk0p1 rootfstype=ext4 rootwait fsck.repair=yes ${condev} net.ifnames=0"

# Booting
fatload mmc 0:1 0x20800000 uImage
fatload mmc 0:1 0x22000000 uInitrd
fatload mmc 0:1 0x21800000 dtb/meson8b-odroidc1.dtb

fdt addr 21800000

bootm 0x20800000 0x22000000 0x21800000
