#!/bin/bash
#////////////////////////////////////
# DietPi CPU Gov Script
#
#////////////////////////////////////
# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
#
#////////////////////////////////////
#
# Info:
# - Runs at boot up /etc/dietpi/boot
# - Sets CPU govener to Ondemand
# - Sets CPU ondemand up threshold (eg: percentage of CPU usage required to throttle up)
#////////////////////////////////////

#/////////////////////////////////////////////////////////////////////////////////////
# Main Loop
#/////////////////////////////////////////////////////////////////////////////////////
#Set Ondemand (cpu0, does apply to all cores)
echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
#echo interactive > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
#echo conservative > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

#Set User stored value
CPU_UP_THROTTLE_PERCENT=$(cat /boot/dietpi.txt | grep 'cpu_usage_throttle_up' | sed 's/cpu_usage_throttle_up=//g')
echo "$CPU_UP_THROTTLE_PERCENT" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold