#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Survey Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=20
	# - Sends DietPi statistics to FTP server (eg: what programs are installed, hardware model)
	# - Allows the DietPi project to focus on areas based on popularity.
	# - No private data is sent. Noone can indentify you.
	# - Runs when user installs software using dietpi-software
	#
	# You can opt out of dietpi-survey by running:
	# echo -e "0" > /DietPi/dietpi/.dietpi-survey
	# echo -e "1" >> /DietPi/dietpi/.dietpi-survey
	#
	# File Sent format:
	# $SOURCE_FILENAME.txt
	#////////////////////////////////////
	SURVEY_VERSION=2
	SURVEY_SENTCOUNT=1

	UNIQUE_ID="x"
	SEND_DATA=1

	DIETPI_VERSION=$(cat /DietPi/dietpi/.version)
	HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)

	FTP_ADDR="fuzon.co.uk"
	FTP_USER="dietpi-survey"
	FTP_PASS="raspberry13"

	SOURCE_FILENAME="filename"

	Update_FileName_Format(){
		SOURCE_FILENAME="$UNIQUE_ID-$DIETPI_VERSION-$HW_MODEL".txt
	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////

	#Read data from .dietpi-survey file
	if [ -f /DietPi/dietpi/.dietpi-survey ]; then
		SEND_DATA=$(sed -n 1p /DietPi/dietpi/.dietpi-survey)
		SURVEY_SENTCOUNT=$(sed -n 2p /DietPi/dietpi/.dietpi-survey)
	#Create new file
	else
		echo -e "1" >> /DietPi/dietpi/.dietpi-survey
		echo -e "1" >> /DietPi/dietpi/.dietpi-survey
	fi

	#Check if we have a working internet connection beforehand
	/DietPi/dietpi/func/check_connection 10 2 "google.com"
	if (( $? == 0 )); then

		#Obtain active network adapter.
		/DietPi/dietpi/func/obtain_network_details
		active_network_adapter=$(sed -n 3p /DietPi/dietpi/.network)

		#Get unique ID by using mac address
		UNIQUE_ID=$( ifconfig -a | grep -m1 "$active_network_adapter" | awk '{print $NF}' | sed 's/://g')

	#No Network hardware found, unable to use MAC address as UUID, abort.
	else
		SEND_DATA=0
	fi

	#create file and send over FTP
	if (( $SEND_DATA == 1 )); then

		#Grab filename to use
		Update_FileName_Format

		#Generate text file for upload
		cd /DietPi/dietpi

		#START of File -----------------------------------------------------

		echo -e "-------------------------" >> "$SOURCE_FILENAME"
		echo -e "DietPi-Survey V$SURVEY_VERSION" >> "$SOURCE_FILENAME"
		echo -e "-------------------------" >> "$SOURCE_FILENAME"

		echo -e "Upload Count   : $SURVEY_SENTCOUNT" >> "$SOURCE_FILENAME"
		echo -e "DietPi Version : $(cat /DietPi/dietpi/.version)" >> "$SOURCE_FILENAME"
		echo -e "Hardware Index : $(sed -n 1p /DietPi/dietpi/.hw_model)" >> "$SOURCE_FILENAME"
		echo -e "Hardware Name  : $(sed -n 2p /DietPi/dietpi/.hw_model)" >> "$SOURCE_FILENAME"
		echo -e "Distro Index   : $(sed -n 3p /DietPi/dietpi/.hw_model)" >> "$SOURCE_FILENAME"
		echo -e "Autoboot Index : $(cat /DietPi/dietpi/.auto_boot_index)" >> "$SOURCE_FILENAME"
		echo -e "Country        : $(curl --max-time 4 -s http://whatismycountry.com/ | sed -n 's|.*,\(.*\)</h3>|\1|p')" >> "$SOURCE_FILENAME"
		echo -e "Hostname       : $(cat /etc/hostname)" >> "$SOURCE_FILENAME"
		echo -e "\n" >> "$SOURCE_FILENAME"


		echo -e "-------------------------" >> "$SOURCE_FILENAME"
		echo -e "DietPi-Software Installed" >> "$SOURCE_FILENAME"
		echo -e "-------------------------" >> "$SOURCE_FILENAME"
		cat /DietPi/dietpi/.installed >> "$SOURCE_FILENAME"
		echo -e "\n" >> "$SOURCE_FILENAME"

		echo -e "-------------------------" >> "$SOURCE_FILENAME"
		echo -e "FileSystem" >> "$SOURCE_FILENAME"
		echo -e "-------------------------" >> "$SOURCE_FILENAME"
		df -h >> "$SOURCE_FILENAME"
		echo -e "\n" >> "$SOURCE_FILENAME"

		#END of File -----------------------------------------------------

		/DietPi/dietpi/func/check_connection 5 2 "ftp://$FTP_ADDR"
		if (( $? == 0 )); then
			#upload to server
			wput --timeout=10th-4 --tries=1 --waitretry=2 -q -B -u "$SOURCE_FILENAME" ftp://"$FTP_USER":"$FTP_PASS"@"$FTP_ADDR"
			#wput --timeout=10th-4 --tries=1 --waitretry=2 -B -u test ftp://dietpi-survey:raspberry13@fuzon.co.uk
		fi

		#clear generated temp file
		rm "$SOURCE_FILENAME"

		#Update .dietpi-survey file
		((SURVEY_SENTCOUNT++))
		rm /DietPi/dietpi/.dietpi-survey
		echo -e "$SEND_DATA" >> /DietPi/dietpi/.dietpi-survey
		echo -e "$SURVEY_SENTCOUNT" >> /DietPi/dietpi/.dietpi-survey

		cd ~/
	fi

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}