#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Explorer. Bare-bones, no frills file man
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - filename /DietPi/dietpi/dietpi-explorer
	#
	# Usage:
	# - dietpi-explorer   (menu system)
	#////////////////////////////////////

	#Import DietPi-Globals ---------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	G_CHECK_ROOT_USER
	export G_PROGRAM_NAME='DietPi-Explorer'
	G_INIT
	#Import DietPi-Globals ---------------------------------------------------------------

	CURRENT_DIRECTORY=''
	TARGET_FP=''

	CP_MODE=0 #0=CP 1=MV
	CP_SOURCE=''
	CP_TARGET=''

	Process_Copy_Move(){

		if [[ -n $CP_TARGET ]]; then

			if (( $CP_MODE == 0 )); then

				G_RUN_CMD_INFO_ONLY=1 G_RUN_CMD cp -R "$CP_SOURCE" "$CP_TARGET"/

			elif (( $CP_MODE == 1 )); then

				G_RUN_CMD_INFO_ONLY=1 G_RUN_CMD mv "$CP_SOURCE" "$CP_TARGET"/

			fi

		fi

		# - Reset for next run
		CP_SOURCE=''
		CP_TARGET=''
		CP_MODE=0

	}

	Select_Menu(){

		if [[ $TARGET_FP == '..' || $TARGET_FP == '/' ]]; then

			cd "$TARGET_FP"

		else

			echo -e "mode = $CP_MODE | CP_SOURCE = $CP_SOURCE | CP_TARGET = $CP_TARGET"


			local target_type_info='File'
			G_WHIP_MENU_ARRAY=()
			if [[ -f $TARGET_FP ]]; then

				G_WHIP_MENU_ARRAY+=('Open' " : Open '$TARGET_FP' in Nano (text edit)")

			elif [[ -d $TARGET_FP ]]; then

				target_type_info='Directory'
				G_WHIP_MENU_ARRAY+=('Open' " : Navigate to '$TARGET_FP'")

			fi

			G_WHIP_MENU_ARRAY+=('Rename' '')

			G_WHIP_MENU_ARRAY+=('Copy' '')
			G_WHIP_MENU_ARRAY+=('Move' '')

			if [[ -n $CP_SOURCE && -d $CURRENT_DIRECTORY/$TARGET_FP ]]; then

				if (( $CP_MODE == 0 )); then

					G_WHIP_MENU_ARRAY+=('Paste' " : Copy $CP_SOURCE to $CURRENT_DIRECTORY/$TARGET_FP/")

				elif (( $CP_MODE == 1 )); then

					G_WHIP_MENU_ARRAY+=('Paste' " : Move $CP_SOURCE to $CURRENT_DIRECTORY/$TARGET_FP/")

				fi

			fi

			G_WHIP_MENU_ARRAY+=('Delete' '')

			G_WHIP_DEFAULT_ITEM='Open'
			G_WHIP_MENU "$target_type_info: $CURRENT_DIRECTORY/$TARGET_FP
 - Exec permissions       : $(ls -lha /var/log/btmp | awk '{print $1}')
 - User/Group permissions : $(ls -lha /var/log/btmp | awk '{print $3}'):$(ls -lha /var/log/btmp | awk '{print $4}')
 "
			if (( $? == 0 )); then

				if [[ $G_WHIP_RETURNED_VALUE == 'Open' ]]; then

					if [[ -d $TARGET_FP ]]; then

						cd "$TARGET_FP"

					else

						nano "$TARGET_FP"

					fi

				elif [[ $G_WHIP_RETURNED_VALUE == 'Copy' ]]; then

					CP_SOURCE="$CURRENT_DIRECTORY/$TARGET_FP"
					CP_MODE=0

				elif [[ $G_WHIP_RETURNED_VALUE == 'Move' ]]; then

					CP_SOURCE="$CURRENT_DIRECTORY/$TARGET_FP"
					CP_MODE=1

				elif [[ $G_WHIP_RETURNED_VALUE == 'Paste' ]]; then

					CP_TARGET="$CURRENT_DIRECTORY/$TARGET_FP"
					Process_Copy_Move

				elif [[ $G_WHIP_RETURNED_VALUE == 'Rename' ]]; then

					G_WHIP_DEFAULT_ITEM="$TARGET_FP"
					G_WHIP_INPUTBOX "Please enter a new name for '$TARGET_FP'"
					if (( $? == 0 )); then

						G_RUN_CMD_INFO_ONLY=1 G_RUN_CMD mv "$TARGET_FP" "$G_WHIP_RETURNED_VALUE"

					fi

				elif [[ $G_WHIP_RETURNED_VALUE == 'Delete' ]]; then

					G_WHIP_YESNO "Delete $CURRENT_DIRECTORY/$TARGET_FP?"
					if (( $? == 0 )); then

						G_RUN_CMD_INFO_ONLY=1 G_RUN_CMD rm -R "$CURRENT_DIRECTORY/$TARGET_FP"

					fi

				fi

			fi

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# MENUS
	#/////////////////////////////////////////////////////////////////////////////////////
	TARGETMENUID=0

	#TARGETMENUID=0
	Menu_Main(){

		CURRENT_DIRECTORY="$PWD"
		G_WHIP_MENU_ARRAY=()

		if [[ $CURRENT_DIRECTORY == '/' ]]; then

			CURRENT_DIRECTORY=''

		else

			G_WHIP_MENU_ARRAY=(

				'..' 'Previous Directory'
				'/' 'Root Directory'

			)

		fi

		for item in "$CURRENT_DIRECTORY"/*
		do

			if [[ -f $item ]]; then

				G_WHIP_MENU_ARRAY+=( "${item##*/}" " : $(wc -c < $item) Bytes" )

			elif [[ $item != *'/*' ]]; then

				G_WHIP_MENU_ARRAY+=( "${item##*/}" '' )

			fi

		done

		G_WHIP_BUTTON_CANCEL_TEXT='Exit'
		G_WHIP_DEFAULT_ITEM="$TARGET_FP"
		G_WHIP_MENU "$CURRENT_DIRECTORY"
		if (( $? == 0 )); then

			TARGET_FP="$G_WHIP_RETURNED_VALUE"

			Select_Menu

		else

			Menu_Exit

		fi

	}

	Menu_Exit(){

		G_WHIP_SIZE_X_MAX=50
		G_WHIP_YESNO "Exit $G_PROGRAM_NAME?"
		if (( ! $? )); then

			#exit
			TARGETMENUID=-1

		else

			#Return to Main Menu
			TARGETMENUID=0

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#Start Menu
	while (( $TARGETMENUID > -1 )); do

		printf '\ec' # clear current terminal screen

		if (( $TARGETMENUID == 0 )); then

			Menu_Main

		fi

	done

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}
