#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Banner Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - filename /boot/dietpi/dietpi-banner
	#////////////////////////////////////

	#dietpi-banner 0 = top section only
	#dietpi-banner 1 = top section and credits

	INPUT=$1

	#/////////////////////////////////////////////////////////////////////////////////////
	#Obtain Hardware Description
	#/////////////////////////////////////////////////////////////////////////////////////
	HW_MODEL_DESCRIPTION=$(sed -n 2p /tmp/dietpi/.hw_model)

	Hardware_Model_Print(){
		echo -e " V$DIETPI_VERSION | $HW_MODEL_DESCRIPTION \n \e[38;5;93m───────────────────────────────\e[0m"
	}

	#/////////////////////////////////////////////////////////////////////////////////////
	#Obtain DietPi Current Version
	#/////////////////////////////////////////////////////////////////////////////////////
	DIETPI_VERSION=$(cat /tmp/dietpi/.version)

	#/////////////////////////////////////////////////////////////////////////////////////
	# Banner Print
	#/////////////////////////////////////////////////////////////////////////////////////
	Banner_Dietpi(){
		clear
		echo -e " \e[38;5;93m───────────────────────────────\e[0m\n \e[1mD I E T - P I\e[0m \n \e[38;5;93m───────────────────────────────\e[0m"
		Hardware_Model_Print
	}

	Credits_Print(){
		echo -e "\n Created by: Dan Knight
 Website: fuzon.co.uk / Email: daniel_haze@hotmail.com \n
 Commands:
 \e[1mdietpi-config\e[0m    = Feature rich system configuration tool.
 \e[1mdietpi-software\e[0m  = Select / Install optimized software.
 \e[1mdietpi-uninstall\e[0m = Remove DietPi Installed Software.
 \e[1mdietpi-update\e[0m    = Update DietPi to the latest version.
 \e[1mhtop\e[0m             = Resource monitor.
 "
	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	if (( $INPUT == 0 )); then
		Banner_Dietpi
	elif (( $INPUT == 1 )); then
		Banner_Dietpi
		Credits_Print
	fi

	#Run whole script in a function. Loads into memory, allows for online file patching.
	exit
}