#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Copy to Ram Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Copies our most used and global DietPi files and scripts to /tmp/
	# - /tmp/ is mounted as tmpfs (ram)
	# - This allows us to vastly reduce filesystem IO in DietPi scripts.
	#
	# Usage:
	# - Called from /boot/dietpi/boot
	#////////////////////////////////////
	
	#NB, if we want to change this location, find in files and replace /tmp/dietpi/
	#And/or use symlink folder instead.
	FILEPATH_TEMP="/tmp/dietpi/"
	
	#/////////////////////////////////////////////////////////////////////////////////////
	#Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	
	#Directory
	mkdir -p "$FILEPATH_TEMP"
	
	#Copy to tmp
	cp /boot/dietpi/.version "$FILEPATH_TEMP".version
	cp /boot/dietpi/.hw_model "$FILEPATH_TEMP".hw_model
	cp /boot/dietpi/dietpi-banner "$FILEPATH_TEMP"dietpi-banner

	exit
}