#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Cloudshell
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - TBA
	#
	# Usage:
	# - setsid sh -c 'exec /DietPi/dietpi/dietpi-cloudshell 0' &> /dev/tty1
	# dietpi-cloudshell 0/no input	= Normal
	# dietpi-cloudshell 1			= Skip intro
	# dietpi-cloudshell 2			= Config Menu
	#
	# Pre-Reqs
	# - sysstat (cpu usage mpstat)
	#////////////////////////////////////

	#Grab Input (valid interger)
	INPUT=0
	if [[ $1 =~ ^-?[0-9]+$ ]]; then
		INPUT=$1
	fi

	#PIDfile
	PID_FILE="/run/dietpi-cloudshell.pid"
	if (( $INPUT != 2 )); then
		echo $$ > $PID_FILE
	fi

	#Obtain hwmodel from dietpi system
	HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)

	CPU_CORES=$(nproc)

	#Version
	DIETPI_CLOUDSHELL_VERSION=3

	#/tmp/.* files used throughout this script.
	TEMP_FILE=0

	#/////////////////////////////////////////////////////////////////////////////////////
	# Colours
	#/////////////////////////////////////////////////////////////////////////////////////
	C_RESET="\e[0m"
	C_REVERSE="\e[7m"

	#C_BOLD makes normal text "brighter"
	C_BOLD="\e[1m"

	#Colour array
	#0 WHITE
	#1 RED
	#2 GREEN
	#3 YELLOW
	#4 BLUE
	#5 PURPLE
	#6 CYAN
	#7 TEST
	declare -a aCOLOUR=(
		"\e[39m"
		"\e[31m"
		"\e[32m"
		"\e[33m"
		"\e[34m"
		"\e[35m"
		"\e[36m"
		"\e[93m"
	)
	#${#aCOLOUR[@]}

	#user colour
	#${aCOLOUR[$USER_COLOUR_INDEX]}
	USER_COLOUR_INDEX=3

	C_PERCENT_GRAPH=0
	Percent_To_Graph(){

		#$1 = interger 0-100
		#$C_PERCENT_GRAPH = return text
		local input_value=$1

		#Cap input value
		if (( $input_value > 100 )); then
			input_value=100
		elif (( $input_value < 0 )); then
			input_value=0
		fi

		#Work out a percentage based graph
		#18 step split (18 / 100)
		if (( $input_value >= 95 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[1]}------WARNING-----$C_RESET]"
		elif (( $input_value >= 90 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[1]}-----------------$C_RESET-]"
		elif (( $input_value >= 88 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[1]}----------------$C_RESET--]"
		elif (( $input_value >= 82 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[1]}---------------$C_RESET---]"
		elif (( $input_value >= 76 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[3]}--------------$C_RESET----]"
		elif (( $input_value >= 70 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[3]}-------------$C_RESET-----]"
		elif (( $input_value >= 64 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[3]}------------$C_RESET------]"
		elif (( $input_value >= 56 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[3]}-----------$C_RESET-------]"
		elif (( $input_value >= 50 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[3]}----------$C_RESET--------]"
		elif (( $input_value >= 44 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[3]}---------$C_RESET---------]"
		elif (( $input_value >= 38 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[2]}--------$C_RESET----------]"
		elif (( $input_value >= 32 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[2]}-------$C_RESET-----------]"
		elif (( $input_value >= 26 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[2]}------$C_RESET------------]"
		elif (( $input_value >= 20 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[2]}-----$C_RESET-------------]"
		elif (( $input_value >= 15 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[2]}----$C_RESET--------------]"
		elif (( $input_value >= 10 )); then
			C_PERCENT_GRAPH=" $input_value% [$C_REVERSE${aCOLOUR[2]}---$C_RESET---------------]"
		elif (( $input_value >= 5 )); then
			C_PERCENT_GRAPH=" $input_value%  [$C_REVERSE${aCOLOUR[2]}--$C_RESET----------------]"
		else
			C_PERCENT_GRAPH=" $input_value%  [$C_REVERSE${aCOLOUR[2]}-$C_RESET-----------------]"
		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Obtain Data
	#/////////////////////////////////////////////////////////////////////////////////////
	DATE_TIME=0
	Obtain_DATE_TIME(){

		DATE_TIME=$(date +"%a %x - %R")

	}

	UPTIME=0
	Obtain_UPTIME(){

		local fSeconds=$(cat /proc/uptime | awk '{print $1}')
		#echo -e "$seconds" |

		local seconds=${fSeconds%.*}
		local minutes=0
		local hours=0
		local days=0

		while (( $seconds >= 60 )); do
			((minutes++))
			seconds=$(( $seconds - 60 ))
		done

		while (( $minutes >= 60 )); do
			((hours++))
			minutes=$(( $minutes - 60 ))
		done

		while (( $hours >= 24 )); do
			((days++))
			hours=$(( $hours - 24 ))
		done

		UPTIME="Uptime: $days Day, $hours Hour"

	}

	#CPU
	CPU_GOV=0
	CPU_TEMP=0
	C_CPUTEMP=0
	CPU_FREQ_1=0
	CPU_FREQ_2=0
	CPU_USAGE=0
	CPU_TOTALPROCESSES=0
	Obtain_CPU(){

		CPU_TOTALPROCESSES=$(ps --ppid 2 -p 2 --deselect | wc -l)
		CPU_GOV=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
		CPU_TEMP=$(( $(cat /sys/class/thermal/thermal_zone0/temp) / 1000 ))

		#Obtain colour for temps
		if (( $CPU_TEMP >= 65 )); then
			C_CPUTEMP=${aCOLOUR[1]}
		elif (( $CPU_TEMP >= 50 )); then
			C_CPUTEMP=${aCOLOUR[3]}
		elif (( $CPU_TEMP >= 35 )); then
			C_CPUTEMP=${aCOLOUR[2]}
		else
			C_CPUTEMP=${aCOLOUR[4]}
		fi

		CPU_FREQ_1=$(( $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq) / 1000 ))
		CPU_FREQ_2="N/A"

		#Unique additional freq readout for Odroid XU4 (octo, 2nd quad set)
		if (( $HW_MODEL == 11 )); then
			CPU_FREQ_2=$(( $(cat /sys/devices/system/cpu/cpu4/cpufreq/scaling_cur_freq) / 1000 ))
		fi

		CPU_USAGE=0
		TEMP_FILE="/tmp/.cpu_usage"
		#exclude top from results? risky pattern match | sed '/top/d'
		ps -xo %cpu | sed '1d' > "$TEMP_FILE"
		while read -r line
		do
			CPU_USAGE=$(echo | awk "{print $CPU_USAGE + $line}")
		done < $TEMP_FILE
		rm $TEMP_FILE

		#ps returns usage of each core, so we devide the total by #n cores
		CPU_USAGE=$(echo | awk "{print $CPU_USAGE / $CPU_CORES}")
		#convert to interger and graph it
		Percent_To_Graph $(printf %.0f $CPU_USAGE)
		CPU_USAGE=$C_PERCENT_GRAPH

	}

	#Storage
	STORAGE_FLASH_TOTAL=0
	STORAGE_FLASH_USED=0
	STORAGE_FLASH_FREE=0
	STORAGE_FLASH_PERCENT=0
	STORAGE_FLASH_PATH=0

	STORAGE_USB_TOTAL=0
	STORAGE_USB_USED=0
	STORAGE_USB_FREE=0
	STORAGE_USB_PERCENT=0
	STORAGE_USB_PATH="/mnt/usb_1"

	Obtain_STORAGE(){

		#RPi
		if (( $HW_MODEL < 10 )); then
			STORAGE_FLASH_PATH="/dev/root"
		#Odroid
		elif (( $HW_MODEL >= 10 )) && (( $HW_MODEL < 20 )); then
			STORAGE_FLASH_PATH="/dev/mmcblk0p2"
		#VM
		elif (( $HW_MODEL == 20 )); then
			STORAGE_FLASH_PATH="/dev/sda1"
		fi

		TEMP_FILE="/tmp/.df"
		df -h > $TEMP_FILE

		STORAGE_FLASH_TOTAL="$( cat $TEMP_FILE | grep $STORAGE_FLASH_PATH | awk '{print $2}')B"
		STORAGE_FLASH_USED="$( cat $TEMP_FILE | grep $STORAGE_FLASH_PATH | awk '{print $3}')B"
		STORAGE_FLASH_FREE="$( cat $TEMP_FILE | grep $STORAGE_FLASH_PATH | awk '{print $4}')B"
		STORAGE_FLASH_PERCENT=$( cat $TEMP_FILE | grep $STORAGE_FLASH_PATH | awk '{print $5}' | sed 's/%//g')

		Percent_To_Graph $STORAGE_FLASH_PERCENT
		STORAGE_FLASH_PERCENT=$C_PERCENT_GRAPH

		#check for USB mount
		if (( $(cat $TEMP_FILE | grep -ci -m1 "$STORAGE_USB_PATH" ) == 1 )); then
			STORAGE_USB_TOTAL="$( cat $TEMP_FILE | grep $STORAGE_USB_PATH | awk '{print $2}')B"
			STORAGE_USB_USED="$( cat $TEMP_FILE | grep $STORAGE_USB_PATH | awk '{print $3}')B"
			STORAGE_USB_FREE="$( cat $TEMP_FILE | grep $STORAGE_USB_PATH | awk '{print $4}')B"
			STORAGE_USB_PERCENT=$( cat $TEMP_FILE | grep $STORAGE_USB_PATH | awk '{print $5}' | sed 's/%//g')

			Percent_To_Graph $STORAGE_USB_PERCENT
			STORAGE_USB_PERCENT=$C_PERCENT_GRAPH
		else
			STORAGE_USB_TOTAL="N/A"
			STORAGE_USB_USED="N/A"
			STORAGE_USB_FREE="N/A"
			STORAGE_USB_PERCENT=" Not installed."
		fi

		rm $TEMP_FILE
	}

	#DietPi
	DIETPI_VERSION_CURRENT=0
	DIETPI_UPDATE_AVAILABLE=0
	DIETPI_WEBSITE="DietPi.com"
	DIETPI_HW_DESCRIPTION="N/A"
	Obtain_DIETPIINFO(){

		#DietPi version
		DIETPI_VERSION_CURRENT="${aCOLOUR[2]}$(cat /DietPi/dietpi/.version)$C_RESET"

		#Current HW
		DIETPI_HW_DESCRIPTION=$(sed -n 2p /DietPi/dietpi/.hw_model)

		#DietPi-Update available?
		DIETPI_UPDATE_AVAILABLE="N/A"
		if [ -f /DietPi/dietpi/.update_available ]; then

			#Set current version to red
			DIETPI_VERSION_CURRENT="${aCOLOUR[1]}$(cat /DietPi/dietpi/.version)$C_RESET"

			local update_version=$(cat /DietPi/dietpi/.update_available)
			if (( $update_version > 0 )); then
				DIETPI_UPDATE_AVAILABLE="${aCOLOUR[2]}$update_version$C_RESET"

			elif (( $update_version == -1 )); then
				DIETPI_UPDATE_AVAILABLE="${aCOLOUR[2]}New Image$C_RESET"
			fi
		fi


	}

	#Network Details
	NETWORK_DETAILS_ADAPTER="eth0"
	NETWORK_DETAILS_IP_INT=0
	NETWORK_DETAILS_MAC_ADDRESS=0
	NETWORK_DETAILS_SIGNAL_STRENGTH=0
	NETWORK_DETAILS_DUPLEXSPEED=0
	NETWORK_DETAILS_HOSTNAME=0
	NETWORK_DETAILS_MODE=0 #1=dhcp, 0=static
	Obtain_NETWORK_DETAILS(){

		TEMP_FILE="/tmp/.ifconfig"

		#Hostname
		NETWORK_DETAILS_HOSTNAME=$(hostname)

		#Active network adapater.
		NETWORK_DETAILS_ADAPTER=$(sed -n 3p /DietPi/dietpi/.network)

		#Mode (dhcp/static)
		if (( $(cat /etc/network/interfaces | grep -ci -m1 "iface $NETWORK_DETAILS_ADAPTER inet dhcp") )); then
			NETWORK_DETAILS_MODE="Dhcp"
		else
			NETWORK_DETAILS_MODE="Static"
		fi

		#Ifconfig to /tmp
		ifconfig $NETWORK_DETAILS_ADAPTER > $TEMP_FILE

		#IP / MAC addresses
		NETWORK_DETAILS_IP_INT=$(cat /tmp/.ifconfig | grep -m1 'inet addr:'| cut -d: -f2 | awk '{ print $1}')
		NETWORK_DETAILS_MAC_ADDRESS=$(cat /tmp/.ifconfig | grep -m1 'HWaddr ' | awk '{ print $5}')

		#Speed/Strength
		#Wifi
		if (( $(echo $NETWORK_DETAILS_ADAPTER | grep -ci -m1 'wlan') == 1 )); then
			NETWORK_DETAILS_SIGNAL_STRENGTH="$(iwconfig $NETWORK_DETAILS_ADAPTER | grep -m1 'Signal level=' | awk '{ print $4 }' | sed 's/level=//g' | cut -f1 -d "/")%"
			NETWORK_DETAILS_DUPLEXSPEED="$(iwconfig $NETWORK_DETAILS_ADAPTER | grep -m1 'Bit Rate:' | awk '{ print $2 }' | sed 's/Rate://g')Mbit"
		#Lan
		else
			NETWORK_DETAILS_DUPLEXSPEED=$(mii-tool | awk '{print $3}')
			NETWORK_DETAILS_SIGNAL_STRENGTH="N/A"
		fi

		rm $TEMP_FILE

	}

	#Network Usage (MB)
	NETWORK_USAGE_TOTAL_SENT=0
	NETWORK_USAGE_TOTAL_RECIEVED=0
	NETWORK_USAGE_DAY_CURRENT_SENT=0
	NETWORK_USAGE_DAY_CURRENT_RECIEVED=0
	NETWORK_USAGE_DAY_PREVIOUS_SENT=0
	NETWORK_USAGE_DAY_PREVIOUS_RECIEVED=0
	NETWORK_USAGE_DAY_OF_MONTH=-1

	Obtain_NETWORK_USAGE(){

		NETWORK_USAGE_TOTAL_SENT=$(( $(cat /sys/class/net/$NETWORK_DETAILS_ADAPTER/statistics/tx_bytes) / 1000000 ))
		NETWORK_USAGE_TOTAL_RECIEVED=$(( $(cat /sys/class/net/$NETWORK_DETAILS_ADAPTER/statistics/rx_bytes) / 1000000 ))

		#Has the day changed? Also runs on init.
		local dayofmonth=$(date +"%d")
		if (( $NETWORK_USAGE_DAY_OF_MONTH != $dayofmonth )); then
			#Update previous day values to current
			NETWORK_USAGE_DAY_PREVIOUS_SENT=$NETWORK_USAGE_TOTAL_SENT
			NETWORK_USAGE_DAY_PREVIOUS_RECIEVED=$NETWORK_USAGE_TOTAL_RECIEVED
			NETWORK_USAGE_DAY_OF_MONTH=$dayofmonth

		fi

		#Work out todays usage
		NETWORK_USAGE_DAY_CURRENT_SENT=$(( $NETWORK_USAGE_TOTAL_SENT - $NETWORK_USAGE_DAY_PREVIOUS_SENT ))
		NETWORK_USAGE_DAY_CURRENT_RECIEVED=$(( $NETWORK_USAGE_TOTAL_RECIEVED - $NETWORK_USAGE_DAY_PREVIOUS_RECIEVED ))

	}

	#Memory
	MEMORY_TOTAL=0
	MEMORY_FREE=0
	MEMORY_USED=0
	MEMORY_CACHED=0
	MEMORY_PERCENT=0
	MEMORY_SWAPTOTAL=0
	MEMORY_SWAPUSED=0
	MEMORY_SWAPFREE=0
	MEMORY_SWAPERCENT=0
	Obtain_MEMORY(){

		#Write to temp
		TEMP_FILE="/tmp/.mem"
		free -m -o > $TEMP_FILE

		#RAM MB
		MEMORY_TOTAL=$(cat $TEMP_FILE | grep -m1 'Mem: ' | awk '{print $2}')
		#Grab values and seperate cache from "used and free" results.
		MEMORY_CACHED=$(cat $TEMP_FILE | grep -m1 'Mem: ' | awk '{print $7}')
		MEMORY_USED=$(( $(cat $TEMP_FILE | grep -m1 'Mem: ' | awk '{print $3}') - $MEMORY_CACHED ))
		MEMORY_FREE=$(( $(cat $TEMP_FILE | grep -m1 'Mem: ' | awk '{print $4}') + $MEMORY_CACHED ))
		MEMORY_PERCENT=$(echo | awk "{print $MEMORY_USED / $MEMORY_TOTAL * 100}")

		#convert to interger and graph it
		Percent_To_Graph $(printf %.0f $MEMORY_PERCENT)
		MEMORY_PERCENT=$C_PERCENT_GRAPH

		#SWAP MB
		MEMORY_SWAPTOTAL=$(cat $TEMP_FILE | grep -m1 'Swap: ' | awk '{print $2}')
		MEMORY_SWAPUSED=$(cat $TEMP_FILE | grep -m1 'Swap: ' | awk '{print $3}')
		MEMORY_SWAPFREE=$(cat $TEMP_FILE | grep -m1 'Swap: ' | awk '{print $4}')
		MEMORY_SWAPERCENT=$( echo | awk "{print $MEMORY_SWAPUSED / $MEMORY_SWAPTOTAL * 100}")

		#convert to interger and graph it
		Percent_To_Graph $(printf %.0f $MEMORY_SWAPERCENT)
		MEMORY_SWAPERCENT=$C_PERCENT_GRAPH

		rm $TEMP_FILE

	}

	#PI-HOLE STATS!
	PIHOLE_QUERY_COUNT=0
	PIHOLE_TOTAL_ADS=0
	PIHOLE_PERCENT_ADS=0
	PIHOLE_TOTAL_DOMAINS=0
	PIHOLE_LAST_DOMAIN_BLOCKED=0
	Obtain_PIHOLE(){

		local pihole_log_file="/var/log/pihole.log"

		#Lets pull the total number of blocked domains only once during 1st run, its quite cpu intensive.
		if (( $PIHOLE_TOTAL_DOMAINS == 0 )); then
			if [ -f /etc/pihole/gravity.list ]; then
				PIHOLE_TOTAL_DOMAINS=$(wc -l /etc/pihole/gravity.list | awk '{print $1}')
			else
				PIHOLE_TOTAL_DOMAINS="Not Installed"
			fi

		fi

		local today=$(date "+%b %e")

		PIHOLE_QUERY_COUNT=$(cat "$pihole_log_file" | grep "$today" | awk '/query/ {print $7}' | wc -l)
		#Prevent / 0 on percentage
		if (( $PIHOLE_QUERY_COUNT <= 0 )); then
			PIHOLE_QUERY_COUNT=1
		fi

		PIHOLE_TOTAL_ADS=$(cat "$pihole_log_file" | grep "$today" | awk '/\/etc\/pihole\/gravity.list/ {print $7}' | wc -l)
		PIHOLE_PERCENT_ADS=$(echo | awk "{print $PIHOLE_TOTAL_ADS / $PIHOLE_QUERY_COUNT * 100}")

		#convert to interger and graph it
		Percent_To_Graph $(printf %.0f $PIHOLE_PERCENT_ADS)
		PIHOLE_PERCENT_ADS=$C_PERCENT_GRAPH

		#Get last blocked domain
		if (( $PIHOLE_TOTAL_ADS == 0 )); then
			PIHOLE_LAST_DOMAIN_BLOCKED="None"
		else
			PIHOLE_LAST_DOMAIN_BLOCKED=$(tac /var/log/pihole.log | grep -m1 'gravity.list' | awk '{print $6}' | cut -c 1-24 )
		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Scene Settings
	#/////////////////////////////////////////////////////////////////////////////////////
	#Run
	RUN_LOOP=1
	RUN_INTRO=0
	if (( $INPUT == 0 )); then
		RUN_INTRO=1
	fi

	#SCENE INDEXS
	SCENE_CURRENT=2
	SCENE_MAX=7
	SCENE_HARDLIMIT=10 # This must be higher than SCENE_MAX. If we need more than 10, modify save/read file, and whiptail scenes menu

	#Refresh rate (every X seconds)
	REFRESH_RATE=5

	#Enabled Scenes
	aEnabledScenes=()
	for ((i=0; i<$SCENE_HARDLIMIT; i++))
	do
		aEnabledScenes+=(1)
	done

	#/////////////////////////////////////////////////////////////////////////////////////
	# Scenes Update
	#/////////////////////////////////////////////////////////////////////////////////////

	Run_Intro(){

	   #'--------------------------'
		clear

		local -a aAnimation=(
			'                          '
			'i         -              c'
			'P  i      -            c l'
			't  P  i   -          c l o'
			'e  t  P  i-        c l o u'
			'i  e  t Pi-    c l o u d s'
			'D  i  etPi-  c l o u d s h'
			'  D  ietPi-c l o u d s h e'
			'    DietPi-cl o u d s h e '
			'    DietPi-clou d s h e l '
			'    DietPi-clouds h e l l '
			'    DietPi-cloudshe l l   '
			'    DietPi-cloudshell     '
		)

		local -a aBar=(
			' '
			'  '
			'    '
			'       '
			'         '
			'            '
			'               '
			'                 '
			'                    '
			'                      '
			'                        '
			'                         '
			'                          '

		)

		for ((i=0; i<${#aAnimation[@]}; i++))
		do

			clear
			echo -e "$C_RESET"
			echo -e ""
			echo -e ""
			echo -e ""
			echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}${aAnimation[$i]}"
			echo -e "$C_RESET          v$DIETPI_CLOUDSHELL_VERSION"
			echo -e ""
			echo -e "       Loading..."
			echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE${aBar[$i]}"

			sleep 0.27
		done

		#delete[] array
		unset aAnimation
		unset aBar

		sleep 0.1

	}

	#Top banner
	BANNER_PRINT=0
	BANNER_MODE=0
	Update_Banner(){

		#Banner Modes
		if (( $BANNER_MODE == 0 )); then
			BANNER_PRINT="DietPi - Cloudshell v$DIETPI_CLOUDSHELL_VERSION"
		elif (( $BANNER_MODE == 1 )); then
			Obtain_DATE_TIME
			BANNER_PRINT=$DATE_TIME
		elif (( $BANNER_MODE == 2 )); then
			Obtain_UPTIME
			BANNER_PRINT=$UPTIME
		fi

		#Set next index
		((BANNER_MODE++))

		#Cap
		if (( $BANNER_MODE >= 3 )); then
			BANNER_MODE=0
		fi

	}

	#CPU
	Update_Scene_0(){

		#Update data
		Obtain_CPU

		#Clear screen
		clear

		#Banner
		echo -e "$C_RESET $BANNER_PRINT"
		#
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE CPU Usage:               "
		echo -e "$C_RESET$CPU_USAGE"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE CPU Stats:               "
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Temp      ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $C_CPUTEMP$CPU_TEMP'c"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Processes ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $CPU_TOTALPROCESSES"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Governor  ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $CPU_GOV"

		#XU3/4 unique octo quad sets
		if (( $HW_MODEL == 11 )); then
			echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Freq 0-3  ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $CPU_FREQ_1 mhz"
			echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Freq 4-7  ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $CPU_FREQ_2 mhz"

		#Generic CPU hardware
		else
			echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Freq      ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $CPU_FREQ_1 mhz"
		fi

	}

	#Storage
	Update_Scene_1(){

		#Update data
		Obtain_STORAGE

		#Clear screen
		clear

		#Banner
		echo -e "$C_RESET $BANNER_PRINT"
		#
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE Flash Storage:           "
		echo -e "$C_RESET$STORAGE_FLASH_PERCENT"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Used: $C_RESET$STORAGE_FLASH_USED / $STORAGE_FLASH_TOTAL"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Free: $C_RESET$STORAGE_FLASH_FREE"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE USB Storage:             "
		echo -e "$C_RESET$STORAGE_USB_PERCENT"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Used: $C_RESET$STORAGE_USB_USED / $STORAGE_USB_TOTAL"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Free: $C_RESET$STORAGE_USB_FREE"

	}

	#DietPi
	Update_Scene_2(){

		#Update data
		Obtain_DIETPIINFO

		#Clear screen
		clear

		#Banner
		echo -e "$C_RESET $BANNER_PRINT"
		#
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE DietPi:                  "
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Version   ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $DIETPI_VERSION_CURRENT"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Updates   ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $DIETPI_UPDATE_AVAILABLE"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Device    ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $DIETPI_HW_DESCRIPTION"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Website   ${aCOLOUR[$USER_COLOUR_INDEX]}:$C_RESET  $DIETPI_WEBSITE"

	}

	#NETWORK DETAILS
	Update_Scene_3(){

		#Update data
		Obtain_NETWORK_DETAILS

		#Clear screen
		clear

		#Banner
		echo -e "$C_RESET $BANNER_PRINT"
		#
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE Network Details:         "
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} IP      : $C_RESET$NETWORK_DETAILS_IP_INT"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Mode    : $C_RESET$NETWORK_DETAILS_MODE"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Adapter : $C_RESET$NETWORK_DETAILS_ADAPTER"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Duplex  : $C_RESET$NETWORK_DETAILS_DUPLEXSPEED"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Signal  : $C_RESET$NETWORK_DETAILS_SIGNAL_STRENGTH"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Hostname: $C_RESET$NETWORK_DETAILS_HOSTNAME"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} MAC: $C_RESET$NETWORK_DETAILS_MAC_ADDRESS"

	}

	#NETWORK USAGE
	Update_Scene_4(){

		#Update data
		Obtain_NETWORK_USAGE

		#Clear screen
		clear

		#Banner
		echo -e "$C_RESET $BANNER_PRINT"
		#
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE Network Usage (TOTAL):   "
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Sent     : $C_RESET$NETWORK_USAGE_TOTAL_SENT MB"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Recieved : $C_RESET$NETWORK_USAGE_TOTAL_RECIEVED MB"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE Network Usage (TODAY):   "
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Sent     : $C_RESET$NETWORK_USAGE_DAY_CURRENT_SENT MB"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Recieved : $C_RESET$NETWORK_USAGE_DAY_CURRENT_RECIEVED MB"

	}

	#Memory
	Update_Scene_5(){

		#Update data
		Obtain_MEMORY

		#Clear screen
		clear

		#Banner
		echo -e "$C_RESET $BANNER_PRINT"
		#
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE Memory Usage (RAM):      "
		echo -e "$C_RESET$MEMORY_PERCENT"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Used: $C_RESET$MEMORY_USED MB / $MEMORY_TOTAL MB"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Free: $C_RESET$MEMORY_FREE MB"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE Memory Usage (SWAP):     "
		echo -e "$C_RESET$MEMORY_SWAPERCENT"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Used: $C_RESET$MEMORY_SWAPUSED MB / $MEMORY_SWAPTOTAL MB"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Free: $C_RESET$MEMORY_SWAPFREE MB"

	}

	#Pi-hole
	Update_Scene_6(){

		#Update data
		Obtain_PIHOLE

		#Clear screen
		clear

		#Banner
		echo -e "$C_RESET $BANNER_PRINT"
		#
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE Pi-hole stats (TODAY):   "
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Ads Blocked: $C_RESET$PIHOLE_TOTAL_ADS"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} DNS Queries: $C_RESET$PIHOLE_QUERY_COUNT"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]} Blocked Domains: $C_RESET$PIHOLE_TOTAL_DOMAINS"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE % of traffic = Ads:      "
		echo -e "$C_RESET$PIHOLE_PERCENT_ADS"
		echo -e "$C_RESET${aCOLOUR[$USER_COLOUR_INDEX]}$C_REVERSE Last domain blocked:     "
		echo -e "$C_RESET $PIHOLE_LAST_DOMAIN_BLOCKED"

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Settings File
	#/////////////////////////////////////////////////////////////////////////////////////
	#Define Location
	FILEPATH_SETTINGS="/DietPi/dietpi/.dietpi-cloudshell"

	Read_Settings_File(){

		#0-9	Core Settings
		REFRESH_RATE=$(sed -n 1p $FILEPATH_SETTINGS)
		USER_COLOUR_INDEX=$(sed -n 2p $FILEPATH_SETTINGS)
		STORAGE_USB_PATH=$(sed -n 3p $FILEPATH_SETTINGS)

		#10-19	Enabled Scenes
		local sed_index=11
		for ((i=0; i<$SCENE_MAX; i++))
		do
			aEnabledScenes[$i]=$(sed -n "$sed_index"p $FILEPATH_SETTINGS)
			((sed_index++))
		done

	}

	Write_Settings_File(){

		#0-9	Core Settings
		echo -e "$REFRESH_RATE" > $FILEPATH_SETTINGS
		echo -e "$USER_COLOUR_INDEX" >> $FILEPATH_SETTINGS
		echo -e "$STORAGE_USB_PATH" >> $FILEPATH_SETTINGS
		echo -e "" >> $FILEPATH_SETTINGS
		echo -e "" >> $FILEPATH_SETTINGS
		echo -e "" >> $FILEPATH_SETTINGS
		echo -e "" >> $FILEPATH_SETTINGS
		echo -e "" >> $FILEPATH_SETTINGS
		echo -e "" >> $FILEPATH_SETTINGS
		echo -e "" >> $FILEPATH_SETTINGS

		#10-19	Enabled Scenes
		for ((i=0; i<$SCENE_HARDLIMIT; i++))
		do
			echo -e "${aEnabledScenes[$i]}" >> $FILEPATH_SETTINGS
		done

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Init
	#/////////////////////////////////////////////////////////////////////////////////////
	Init(){

		#--------------------------------------------------------------------------------
		#Load Settings file. Generate if required.
		if [ ! -f "$FILEPATH_SETTINGS" ]; then
			Write_Settings_File
		else
			Read_Settings_File
		fi

		#--------------------------------------------------------------------------------
		#VM disable CPU scene
		if (( $HW_MODEL == 20 )); then
			aEnabledScenes[0]=0
		fi

		#--------------------------------------------------------------------------------
		#Check and disable scenes if software is not installed:
		# 6 Pi-hole
		if [ ! -f /etc/pihole/gravity.list ]; then
			aEnabledScenes[6]=0

			#Save settings to disable scene
			Write_Settings_File
		fi

		#--------------------------------------------------------------------------------
		#Ensure we have at least 1 Scene enabled in the settings file.
		local enabled_scene=0
		for ((i=0; i<$SCENE_MAX; i++))
		do
			if (( "${aEnabledScenes[$i]}" == 1 )); then
				enabled_scene=1
				break
			fi
		done

		#No Scenes selected! Override user setting and enable at least 1 scene (dietpi)
		if (( $enabled_scene == 0 )); then

			aEnabledScenes[2]=1
			SCENE_CURRENT=2

			#Save settings to prevent re-occuring
			Write_Settings_File

		fi

		#--------------------------------------------------------------------------------
		#Start Display system if we are not running menu.
		if (( $INPUT != 2 )); then

			#prevent sleep - moved to login
			#set font - moved to login
			#Disable Cursor - moved to login

			#Start Intro
			if (( $RUN_INTRO == 1 )); then
				Run_Intro
			fi

			#Set Nice to +10 (not critical)
			renice -n 10 $$ &> /dev/null
		fi

	}

	#Unused function (contains code to restart / test dietpi-cloudshell)
	Test(){

		#Commands to restart DietPi-Cloudshell
		killall dietpi-cloudshell
		/DietPi/dietpi/dietpi-cloudshell 0 &> /dev/tty1 &

		#Reset Config
		rm /DietPi/dietpi/.dietpi-cloudshell
		killall dietpi-cloudshell
		/DietPi/dietpi/dietpi-cloudshell 0 &> /dev/tty1 &

		#test non-dietpi system
		mv /DietPi/dietpi.txt /DietPi/dietpi.bak
		killall dietpi-cloudshell
		/DietPi/dietpi/dietpi-cloudshell 0 &> /dev/tty1 &
		mv /DietPi/dietpi.bak /DietPi/dietpi.txt

		#Launch in current screen/terminal
		killall dietpi-cloudshell
		/DietPi/dietpi/dietpi-cloudshell 1
		#/DietPi/dietpi/dietpi-cloudshell 0

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Apply new Config
	#/////////////////////////////////////////////////////////////////////////////////////
	#Applies new config file and restarts DietPi-Cloudshell on tty1
	Apply_Config(){

		#kill current dietpi-cloudshell display process
		if [ -f "$PID_FILE" ]; then
			kill $(cat "$PID_FILE")
		fi

		Write_Settings_File

		#Start her up
		#/DietPi/dietpi/dietpi-cloudshell 0 &> /dev/tty1 &
		#Start her up (no intro)
		/DietPi/dietpi/dietpi-cloudshell 1 &> /dev/tty1 &
		sleep 0.1

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Menu System
	#/////////////////////////////////////////////////////////////////////////////////////
	WHIP_BACKTITLE="- DietPi-Cloudshell v$DIETPI_CLOUDSHELL_VERSION -"
	WHIP_TITLE='- DietPi-Cloudshell -'
	WHIP_QUESTION=0
	CHOICE=0
	TARGETMENUID=0

	Menu_Exit(){
			WHIP_TITLE='Exit DietPi-Cloudshell?'
			WHIP_QUESTION='Exit DietPi-Cloudshell configuration tool?'
			whiptail --title "$WHIP_TITLE" --yesno "$WHIP_QUESTION" --backtitle "$WHIP_TITLE" --yes-button "Ok" --no-button "Back" --defaultno 9 55
			CHOICE=$?
			if (( $CHOICE == 0 )); then
				#exit
				TARGETMENUID=-1
			else
				#Return to Main Menu
				TARGETMENUID=0
			fi
	}

	#TARGETMENUID=0
	Menu_Main(){

		TARGETMENUID=0
		WHIP_TITLE='- DietPi-Cloudshell -'
		WHIP_QUESTION='Configure DietPi-Cloudshell'

		OPTION=$(whiptail --title "$WHIP_TITLE" --backtitle "$WHIP_BACKTITLE" --menu "$WHIP_QUESTION" --cancel-button "Exit" 10 60 3 \
		"Colour" "Change the colour scheme." \
		"Update Rate" "Control the time between screen updates." \
		"Scenes" "Toggle which scenes are shown."  3>&1 1>&2 2>&3)

		CHOICE=$?
		if (( $CHOICE == 0 )); then
			case "$OPTION" in
				Colour)
					TARGETMENUID=1
				;;
				"Update Rate")
					TARGETMENUID=2
				;;
				Scenes)
					TARGETMENUID=3
				;;
			esac
		else
			Menu_Exit
		fi

	}

	#TARGETMENUID=1
	Menu_Colour(){

		TARGETMENUID=1

		#Colour array
		#0 WHITE
		#1 RED
		#2 GREEN
		#3 YELLOW
		#4 BLUE
		#5 PURPLE
		#6 CYAN
		WHIP_TITLE='- Options : Colour -'
		WHIP_QUESTION='Select your colour scheme.'
		OPTION=$(whiptail --title "$WHIP_TITLE" --backtitle "$WHIP_BACKTITLE" --menu "$WHIP_QUESTION" --cancel-button "Back" --default-item "$USER_COLOUR_INDEX" 15 45 7 \
		"0" "White" \
		"1" "Red" \
		"2" "Green" \
		"3" "Yellow (Default)" \
		"4" "Blue" \
		"5" "Purple" \
		"6" "Cyan"  3>&1 1>&2 2>&3)

		CHOICE=$?
		if (( $CHOICE == 0 )); then

			if (( $OPTION != $USER_COLOUR_INDEX )); then
				USER_COLOUR_INDEX=$OPTION
				Apply_Config &> /dev/null
			fi

		else
			TARGETMENUID=0
		fi

	}

	#TARGETMENUID=2
	Menu_UpdateRate(){

		TARGETMENUID=2

		WHIP_TITLE='- Options : Update Rate -'
		WHIP_QUESTION='Change the delay between scene changes and updates.'
		OPTION=$(whiptail --title "$WHIP_TITLE" --backtitle "$WHIP_BACKTITLE" --menu "$WHIP_QUESTION" --cancel-button "Back" --default-item "$REFRESH_RATE" 15 55 7 \
		"3" "Seconds" \
		"5" "Seconds (Default)" \
		"10" "Seconds" \
		"20" "Seconds" \
		"30" "Seconds" \
		"45" "Seconds" \
		"60" "Seconds" 3>&1 1>&2 2>&3)

		CHOICE=$?
		if (( $CHOICE == 0 )); then

			if (( $OPTION != $REFRESH_RATE )); then
				REFRESH_RATE=$OPTION
				Apply_Config &> /dev/null
			fi

		else
			TARGETMENUID=0
		fi

	}

	#TARGETMENUID=3
	Menu_SceneSelection(){

		#Return to main menu
		TARGETMENUID=0

		#Get on/off whilptail status
		local aWhiptailLine=()
		local OnOff_Status="on"
		for ((i=0; i<$SCENE_MAX; i++))
		do
			#On/Off status
			OnOff_Status="on"
			if (( ${aEnabledScenes[$i]} == 0 )); then
				OnOff_Status="off"
			fi

			#Define options
			if (( $i == 0 )); then
				aWhiptailLine+=("$i" "CPU: Temperatures, Usage, frequency and more." "$OnOff_Status")
			elif (( $i == 1 )); then
				aWhiptailLine+=("$i" "Storage: Usage information for Flash and USB drives" "$OnOff_Status")
			elif (( $i == 2 )); then
				aWhiptailLine+=("$i" "DietPi: Information, stats and updates for DietPi." "$OnOff_Status")
			elif (( $i == 3 )); then
				aWhiptailLine+=("$i" "Network Details: Ip address, Speeds, Signal and more." "$OnOff_Status")
			elif (( $i == 4 )); then
				aWhiptailLine+=("$i" "Network Usage: Bandwidth usage (sent / recieved)." "$OnOff_Status")
			elif (( $i == 5 )); then
				aWhiptailLine+=("$i" "Memory: Stats for RAM and Swapfile usage." "$OnOff_Status")
			elif (( $i == 6 )); then
				aWhiptailLine+=("$i" "Pi-hole: Stats for Pi-hole. Total Ads blocked etc." "$OnOff_Status")
			else
				aWhiptailLine+=("New" "Unknown" "$OnOff_Status")
			fi

		done

		WHIP_TITLE='- Options : Scene Selection -'
		WHIP_QUESTION='Please use the spacebar to toggle which scenes are active.'
		whiptail --title "$WHIP_TITLE" --checklist "$WHIP_QUESTION" --backtitle "$WHIP_TITLE" --separate-output 14 75 7 "${aWhiptailLine[@]}" 2>/tmp/dietpi-cloudshell_scenelist
		CHOICE=$?

		if (( $CHOICE == 0 )); then
			for ((i=0; i<$SCENE_HARDLIMIT; i++))
			do
				aEnabledScenes[$i]=0
				if (( $(cat /tmp/dietpi-cloudshell_scenelist | grep -ci -m1 "$i") == 1 )); then
					aEnabledScenes[$i]=1
				fi

			done

			#Save
			Apply_Config

		fi

		#Clean up temp files
		rm /tmp/dietpi-cloudshell_scenelist &> /dev/null

		#Delete[] array
		unset aWhiptailLine

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# MAIN
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	#Init
	Init
	#-----------------------------------------------------------------------------------
	#Run config menu
	if (( $INPUT == 2 )); then

		#--------------------------------------------------------------------------------------
		#Start DietPi Menu
		while (( $TARGETMENUID > -1 )); do

			clear

			Read_Settings_File

			if (( $TARGETMENUID == 0 )); then
				Menu_Main
			elif (( $TARGETMENUID == 1 )); then
				Menu_Colour
			elif (( $TARGETMENUID == 2 )); then
				Menu_UpdateRate
			elif (( $TARGETMENUID == 3 )); then
				Menu_SceneSelection
			fi
		done

	#Run DietPi-Cloudshell
	else

		#-----------------------------------------------------------------------------------
		#Loop
		while (( $RUN_LOOP == 1 ))
		do

			#Update enabled scenes
			if (( ${aEnabledScenes[$SCENE_CURRENT]} == 1 )); then

				Update_Banner
				Update_Scene_$SCENE_CURRENT

				#Apply refresh rate delay
				sleep $REFRESH_RATE

			fi

			#Scene Switcher
			((SCENE_CURRENT++))

			#Cap
			if (( $SCENE_CURRENT >= $SCENE_MAX )); then
				SCENE_CURRENT=0
			fi

		done
	fi

	#-----------------------------------------------------------------------------------
	#Delete[] Global arrays
	unset aCOLOUR
	unset aEnabledScenes
	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}