#!/bin/bash

	#////////////////////////////////////
	# DietPi Banner Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - filename /DietPi/dietpi/dietpi-banner
	# - Checks /DietPi/dietpi/.update_available
	#////////////////////////////////////

	#dietpi-banner 0 = top section only
	#dietpi-banner 1 = top section and credits

	INPUT=0
	if [[ $1 =~ ^-?[0-9]+$ ]]; then
		INPUT=$1
	fi

	#/////////////////////////////////////////////////////////////////////////////////////
	#Get current version
	#/////////////////////////////////////////////////////////////////////////////////////
	DIETPI_VERSION=$(cat /DietPi/dietpi/.version)

	#/////////////////////////////////////////////////////////////////////////////////////
	#Top section additional Text. Update available / MOTD etc
	#/////////////////////////////////////////////////////////////////////////////////////
	TEXT_TOP=""
	UPDATE_AVAILABLE=0

	#/////////////////////////////////////////////////////////////////////////////////////
	#Obtain Hardware Description
	#/////////////////////////////////////////////////////////////////////////////////////
	HW_MODEL_DESCRIPTION=$(sed -n 2p /DietPi/dietpi/.hw_model)

	Hardware_Model_Print(){
		echo -e " V$DIETPI_VERSION \e[90m| $HW_MODEL_DESCRIPTION\e[0m\n \e[38;5;93m───────────────────────────────────────\e[0m"
	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Banner Print
	#/////////////////////////////////////////////////////////////////////////////////////

	Banner_TopText_Extras(){

		#Update Available
		if [ -f /DietPi/dietpi/.update_available ]; then
			UPDATE_AVAILABLE=$(cat /DietPi/dietpi/.update_available)

			if (( $UPDATE_AVAILABLE > 0 )); then
				TEXT_TOP="\e[90m|\e[0m \e[91mUpdate available\e[0m"
			elif (( $UPDATE_AVAILABLE == -1 )); then
				TEXT_TOP="\e[90m|\e[0m \e[91mImage available\e[0m"
			fi

		#Use TEXT_TOP for storing helpful info
		else
			#Helpful mode
			TEXT_TOP="\e[90m| $(date +"%R | %a %x")\e[0m"
		fi
	}

	Banner_Dietpi(){
		clear
		echo -e " \e[38;5;93m───────────────────────────────────────\e[0m\n \e[1mDietPi\e[0m $TEXT_TOP \n \e[38;5;93m───────────────────────────────────────\e[0m"
		#echo -e " \e[38;5;93m───────────────────────────────────────\e[0m\n \e[1mD I E T - P I\e[0m $TEXT_TOP \n \e[38;5;93m───────────────────────────────────────\e[0m"
		Hardware_Model_Print
	}

	Credits_Print(){
		echo -e ""
		echo -e "\e[90m Created by: Dan Knight\e[0m"
		echo -e "\e[90m Web:        dietpi.com\e[0m"
		echo -e "\e[90m Twitter:    twitter.com/dietpi_\e[0m"
		echo -e "\e[90m IRC:        freenode #dietpi"
		echo -e "\e[90m Donations:  http://goo.gl/DCY1vq\e[0m"
		echo -e "\e[90m DietPi is a free product and relies on your donations for funding.\e[0m"
		echo -e "\e[90m Show your support for DietPi and help keep it running.\e[0m"
		echo -e ""
		echo -e "\e[1m dietpi-config\e[0m    = Feature rich system configuration tool."
		echo -e "\e[1m dietpi-software\e[0m  = Select / Install optimized software."
		echo -e "\e[1m dietpi-uninstall\e[0m = Remove DietPi Installed Software."
		#Update available
		if (( $UPDATE_AVAILABLE > 0 )); then
			echo -e "\e[1m dietpi-update\e[0m    = \e[91mRun now to update DietPi (from V$DIETPI_VERSION to V$UPDATE_AVAILABLE).\e[0m"
		elif (( $UPDATE_AVAILABLE == -1 )); then
			echo -e "\n\e[91m An updated DietPi image is available, please goto:\e[0m\n http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=9#p9\n"
		fi
		echo -e "\e[1m dietpi-bugreport\e[0m = Found an issue or bug? Let us know!"
		echo -e "\e[1m htop\e[0m             = Resource monitor."
		echo -e "\e[1m cpu\e[0m              = Shows CPU information and stats."
		echo -e ""
	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	if (( $INPUT == 0 )); then
		Banner_TopText_Extras
		Banner_Dietpi

	elif (( $INPUT == 1 )); then
		Banner_TopText_Extras
		Banner_Dietpi
		Credits_Print
	fi

	#-----------------------------------------------------------------------------------
