#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Bug Report Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Called from G_ERROR_HANDLER
	# - filename /DietPi/dietpi/dietpi-bugreport
	# - Generates UUID_BUGNUMBER.zip and uploads to dietpi.com
	# Usage:
	# - /DietPi/dietpi/dietpi-bugreport 1				#Automated send of bug report
	#////////////////////////////////////

	#Import DietPi-Globals ---------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	G_CHECK_ROOT_USER
	G_CHECK_ROOTFS_RW
	export G_PROGRAM_NAME='DietPi-Bugreport'
	G_INIT
	G_USER_INPUTS=0
	#Import DietPi-Globals ---------------------------------------------------------------

	INPUT=0
	G_CHECK_VALIDINT $1 && INPUT=$1

	# - byte
	UPLOAD_FILESIZE_LIMIT=10000000
	UPLOAD_FILESIZE=0

	UNIQUE_ID_HW=$(sed -n 5p /DietPi/dietpi/.hw_model)

	FTP_ADDR='dietpi.com'
	FTP_USER='dietpi-survey'
	FTP_PASS='inactive_tba'

	FILEPATH_TEMP='/tmp/dietpi-bugreport'
	FILE_GENERATED_ZIP='bugreport.7z'

	Generate_Zip_File(){

		#----------------------------------------------------------------
		#Define zip settings (level 9 compression etc)
		FILE_GENERATED_ZIP="$UNIQUE_ID_HW.7z"
		7z_settings='-spf -t7z'
		#----------------------------------------------------------------
		#List of commands we want to run and redirect to zip
		acommand_list=(

			'ls -lha /var/log'
			'dpkg -l'
			'ifconfig -a'
			'ip a'
			'lsusb'
			'cat /proc/cpuinfo'
			'ps aux'
			'blkid'
			'mount'
			'df -h'
			"ls /etc/rc*.d/"
			'cut -d: -f1 /etc/passwd'
			'locale'
			'ls -lha /mnt' #dietpi userdata location
			'dmesg'
			'lsmod'
			"systemctl status *.service -l"
			"systemctl status *.mount -l"
			'/DietPi/dietpi/dietpi-services status'

		)

		[[ -f br_cmd_out.txt ]] && rm br_cmd_out.txt

		for ((i=0; i<${#acommand_list[@]}; i++))
		do

			echo -e "\n----------\n${acommand_list[$i]}:\n----------" >> br_cmd_out.txt
			${acommand_list[$i]} >> br_cmd_out.txt

		done

		unset acommand_list

		#list of files and/or folders we want to zip
		local afile_list=(

			# - command output file
			'br_cmd_out.txt'

			# - logs
			"/var/log/*"

			# - DietPi scripts / logs
			"/DietPi/*"
			'/boot/dietpi.txt'
			'/boot/config.txt'
			"/boot/dietpi/*"
			"/tmp/.G*"
			"/var/tmp/dietpi/logs/*"

			# - /var/lib/dietpi
			"/var/lib/dietpi/*"

			# - confs
			#	- bash shell
			'/etc/bash.bashrc'
			"/etc/bashrc.d/*"
			'/root/.bashrc'
			"/home/*/.bashrc"
			#	- login shell
			'/etc/profile'
			"/etc/profile.d/*"
			'/root/.profile'
			"/home/*/.profile"

			'/etc/rc.local'
			'/etc/X11/xorg.conf'
			'/etc/asound.conf'
			'/etc/network/interfaces'
			'/etc/fstab'
			'/etc/sysctl.conf'
			"/etc/sysctl.d/*"

			# - Services
			"/etc/init.d/*"
			"/etc/systemd/system/*"
			"/lib/systemd/system/*"

			# - APT
			'/etc/apt/sources.list'
			"/etc/apt/sources.list.d/*"

		)

		[[ -f $FILE_GENERATED_ZIP ]] && rm "$FILE_GENERATED_ZIP"
		7z a "$7z_settings" "$FILE_GENERATED_ZIP" ${afile_list[@]}

	}

	Create_Bug_Report(){

		#----------------------------------------------------------------
		#Generate our zipped bugreport file
		Generate_Zip_File

		#----------------------------------------------------------------
		#Check upload location is online
		G_CHECK_URL "$FTP_ADDR"
		if (( ! $? )); then

			#Limit filesize
			UPLOAD_FILESIZE=$(stat -c%s "$FILE_GENERATED_ZIP")

			# - Upload
			if (( $UPLOAD_FILESIZE <= $UPLOAD_FILESIZE_LIMIT )); then

				G_DIETPI-NOTIFY 2 'Uploading bug report, please wait...'
				wput --timeout=10th-4 --tries=1 --waitretry=2 -B -u "$FILE_GENERATED_ZIP" ftp://"$FTP_USER":"$FTP_PASS"@"$FTP_ADDR"
				if (( ! $? )); then

					G_DIETPI-NOTIFY 0 "Bug report sent, reference code: $FILE_GENERATED_ZIP"

				else

					G_DIETPI-NOTIFY 1 'An error appeared while trying to upload the bug report. Please try again later or report this to DietPi forum or GitHub repo in the first place.'

				fi

			else

				G_DIETPI-NOTIFY 1 'The bug report upload archive appears to be unexpected large. The file list, that was to be uploaded, was saved to: /tmp/dietpi-bugreport-filelist\nPlease inspect and in case clean up those locations, as their size should never be that large.'
				printf "%s\n" "${afile_list[@]}" > /tmp/dietpi-bugreport-filelist

			fi

		else

			G_DIETPI-NOTIFY 1 'Failed to upload bugreport, URL offline or unreachable. Please try again later or report this to DietPi forum or GitHub repo in the first place.'

		fi

		unset afile_list

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#----------------------------------------------------------------
	if (( $INPUT == 1 )); then

		#Make Directory
		#	we need to work inside the directory as Wput cant accept /paths
		mkdir -p $FILEPATH_TEMP
		cd $FILEPATH_TEMP

		#Automated bug report send
		Create_Bug_Report

		#remove temp folder and all generated temp files
		cd "$HOME"
		rm -R $FILEPATH_TEMP &> /dev/null

	else

		G_DIETPI-NOTIFY 2 'This feature is no longer available. Now handled automatically by G_ERROR_HANDLER when an issue occurs'

	fi

	#-----------------------------------------------------------------------------------
	exit 0
	#-----------------------------------------------------------------------------------

}
