#!/bin/bash
{
	#////////////////////////////////////
	# DietPi AutoStart Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - filename /DietPi/dietpi/dietpi-autostart
	#
	# Usage:
	# - dietpi-autostart   (menu system)
	# - dietpi-autostart int (set value only)
	#////////////////////////////////////

	#Import DietPi-Globals ---------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	G_PROGRAM_NAME='DietPi-Autostart'
	G_CHECK_ROOT_USER
	G_INIT
	#Import DietPi-Globals ---------------------------------------------------------------

	#Grab Input (valid interger)
	INPUT=-1
	disable_error=1 G_CHECK_VALIDINT $1 && INPUT=$1

	#/////////////////////////////////////////////////////////////////////////////////////
	# MENUS
	#/////////////////////////////////////////////////////////////////////////////////////
	TARGETMENUID=0

	AUTO_START_INDEX=0

	Apply_Boot_Index(){

		#Always disable LightDM
		systemctl disable lightdm.service &> /dev/null

		# - Amiberry | always disable services, service launched by DietPi/login if non fastboot mode
		systemctl disable amiberry.service &> /dev/null

		if (( $G_HW_MODEL < 10 )); then

			sed -i '/^boot_delay=0/d' /DietPi/config.txt
			sed -i 's/logo.nologo//' /boot/cmdline.txt
			sed -i 's/loglevel=3//' /boot/cmdline.txt
			sed -i 's/console=tty3/console=tty1/' /boot/cmdline.txt

		fi

		# - Disable custom launch service
		rm /etc/systemd/system/dietpi-autostart_custom.service &> /dev/null

		# - Disable auto login
		rm /etc/systemd/system/getty@tty1.service.d/autologin.conf &> /dev/null

		#----------------------------------------------------------------------
		#Enable autoboot options
		#	Custom script, service without auto login: https://github.com/Fourdee/DietPi/issues/1024
		if (( $AUTO_START_INDEX == 14 )); then

			cat << _EOF_ > /etc/systemd/system/dietpi-autostart_custom.service
[Unit]
Description=DietPi autostart (Custom /var/lib/dietpi/dietpi-autostart/custom.sh)
After=dietpi-boot.service dietpi-ramdisk.service dietpi-ramlog.service dietpi-postboot.service rc-local.service
Requires=dietpi-boot.service dietpi-ramdisk.service

[Service]
Type=idle
ExecStartPre=/bin/bash -c 'echo -e "Starting DietPi-Autostart (Custom) script"'
ExecStartPre=$(which chmod) +x /var/lib/dietpi/dietpi-autostart/custom.sh
ExecStart=/bin/bash -c /var/lib/dietpi/dietpi-autostart/custom.sh
StandardOutput=tty
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
_EOF_
		systemctl enable dietpi-autostart_custom.service

		#	Uae4arm special | fast boot via enabled service
		elif (( $AUTO_START_INDEX == 6 )); then

			systemctl enable amiberry.service

			# - apply tweaks
			if (( $G_HW_MODEL < 10 )); then

				G_CONFIG_INJECT 'boot_delay=' 'boot_delay=0' /DietPi/config.txt

				if ! grep -qi ' logo.nologo' /boot/cmdline.txt; then

					sed -i 's/rootwait/rootwait logo.nologo/' /boot/cmdline.txt

				fi

				if ! grep -qi ' loglevel=3' /boot/cmdline.txt; then

					sed -i 's/rootwait/rootwait loglevel=3/' /boot/cmdline.txt

				fi

				if ! grep -qi ' console=tty3' /boot/cmdline.txt; then

					sed -i 's/console=tty1/console=tty3/' /boot/cmdline.txt

				fi

			fi

		#	Enable auto login
		elif (( $AUTO_START_INDEX > 0 )); then

			mkdir -p /etc/systemd/system/getty@tty1.service.d &> /dev/null
			cat << _EOF_ > /etc/systemd/system/getty@tty1.service.d/autologin.conf
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin root %I $TERM
_EOF_

		fi

		#Save boot index.
		echo $AUTO_START_INDEX > /DietPi/dietpi/.dietpi-autostart_index

		systemctl daemon-reload

	}

	#TARGETMENUID=0
	Menu_Main(){

		#existing boot flag
		AUTO_START_INDEX=$(</DietPi/dietpi/.dietpi-autostart_index)

		G_WHIP_MENU_ARRAY=(

			'' '●─ Local Terminal '
			'0' ': Manual login (default)'
			'7' ': Automatic login'
			'' '●─ Desktops '
			'2' ': Automatic login (recommended)'
			'16' ': LightDM login prompt'
			'' '●─ Browser Kiosk '
			'11' ': Chromium - Dedicated use, without desktop'
			'' '●─ Media '
			'1' ': Kodi'
			'10' ': CAVA Spectrum'
			'' '●─ Gaming/Emulation '
			'6' ': AmiBerry - Fast boot'
			'8' ': AmiBerry - Standard boot'
			'3' ': RetroPie'
			'9' ': DXX-Rebith - Descent 1/2'
			'4' ': OpenTyrian'
			'' '●─ Other '
			'14' ': Custom - /var/lib/dietpi/dietpi-autostart/custom.sh'
			'5' ': DietPi-Cloudshell'

		)

		G_WHIP_BUTTON_CANCEL_TEXT='Exit'
		G_WHIP_DEFAULT_ITEM=$AUTO_START_INDEX
		G_WHIP_MENU "Current AutoStart Option: $AUTO_START_INDEX\n\nNB: If your choice is not \"Console:\", please ensure required software is installed (or selected for install) in DietPi-Software."
		if (( $? == 0 )) && [[ $G_WHIP_RETURNED_VALUE ]]; then

			local choice=$G_WHIP_RETURNED_VALUE

			#AmiBerry fast boot info
			if (( $choice == 6 )); then

				G_WHIP_MSG 'AmiBerry: (Fast boot):\nA highly optimized and tweaked boot mode.\nThis mode allows for a < 2.5 second boot on a RPi 3, into AmiBerry.\n\nIf you experience boot issues with this mode, please try (Standard Boot)'

			#Chromium prompt for URL
			elif (( $choice == 11 )); then

				G_WHIP_DEFAULT_ITEM="$(grep -m1 '^[[:blank:]]*SOFTWARE_CHROMIUM_AUTOSTART_URL=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
				G_WHIP_INPUTBOX "Please enter a homepage URL to start with Chromium:\n - eg: https://google.com"
				if (( $? == 0 )); then

					G_CONFIG_INJECT 'SOFTWARE_CHROMIUM_AUTOSTART_URL=' "SOFTWARE_CHROMIUM_AUTOSTART_URL=$G_WHIP_RETURNED_VALUE" /DietPi/dietpi.txt

				fi

			#Custom info
			elif (( $choice == 14 )); then

				#	create template
				if [[ ! -f '/var/lib/dietpi/dietpi-autostart/custom.sh' ]]; then

					mkdir -p /var/lib/dietpi/dietpi-autostart
					cat << _EOF_ > /var/lib/dietpi/dietpi-autostart/custom.sh
#!/bin/bash
#---Examples---

# - Chromium
#xinit chromium

# - LXDE
#startx

# - Print hello
#echo -e "Hello"

#---Put your code below this line---

_EOF_

					G_WHIP_MSG 'A template script has been created:\n - /var/lib/dietpi/dietpi-autostart/custom.sh\n\nPlease edit this file and enter the required commands you wish to launch. DietPi will then execute this script during boot.'

				fi

			#LightDM pre-req check
			elif (( $choice == 16 )); then

				G_AG_CHECK_INSTALL_PREREQ lightdm

			fi

			#Apply Selected boot option
			AUTO_START_INDEX=$choice

			Apply_Boot_Index

		else

			#Exit
			TARGETMENUID=-1

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#Start Menu
	if (( $INPUT == -1 )); then

		while (( $TARGETMENUID > -1 )); do

			printf '\ec' # clear current terminal screen

			if (( $TARGETMENUID == 0 )); then

				Menu_Main

			fi

		done

	#Apply boot index
	elif (( $INPUT >= 0 )); then

		AUTO_START_INDEX=$INPUT
		Apply_Boot_Index

	fi

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}
