#!/bin/bash
{
	#////////////////////////////////////
	# DietPi
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#////////////////////////////////////
	#
	# Info:
	# - Generates /DietPi/dietpi/.hw_model
	# - Called from /DietPi/dietpi/boot
	#
	# - Line1 -
	# HW_MODEL 30 Orange Pi (PC)
	# HW_MODEL 20 VM
	# HW_MODEL 11 oDroid XU3/4
	# HW_MODEL 10 oDroid C1
	# HW_MODEL 2 Raspberry Pi 2 (1024mb)
	# HW_MODEL 1 Raspberry Pi 1 (512mb)
	# HW_MODEL 0 Raspberry Pi 1 (256mb)
	# - Line2 -
	# HW_MODEL_DESCRIPTION
	# - Line3 -
	# DISTRO 0 unknown
	# DISTRO 1 Debian Wheezy
	# DISTRO 2 Ubuntu 14.04 (No longer supported, left in for user message during update)
	# DISTRO 3 Jessie / Ubuntu 15.04
	# - Line4 -
	# RootFS Filepath (eg: /dev/mmc01)
	# - Line5 -
	# UUID
	#////////////////////////////////////

	#/////////////////////////////////////////////////////////////////////////////////////
	#Obtain Hardware Model index
	#/////////////////////////////////////////////////////////////////////////////////////

	HW_MODEL=0
	HW_MODEL_DESCRIPTION='Unknown Model'
	FP_HW_MODEL_INDENTIFIER='/etc/.dietpi_hw_model_identifier'
	HW_UUID=0
	HW_REVISION=0

	#Systems that use /etc/.dietpi_hw_model_identifier for HW_MODEL
	if [ -f "$FP_HW_MODEL_INDENTIFIER" ]; then

		HW_MODEL=$(sed -n 1p "$FP_HW_MODEL_INDENTIFIER")

		#OrangePi
		if (( $HW_MODEL == 30 )); then
			HW_MODEL_DESCRIPTION='Orange Pi (PC)'
			STORAGE_ROOT_PATH="/dev/mmcblk0p2"

		#VM
		elif (( $HW_MODEL == 20 )); then
			HW_MODEL_DESCRIPTION='Virtual Machine (x64)'
			STORAGE_ROOT_PATH="/dev/sda1"
		fi

	#oDroid XU3/4
	elif (( $(cat /proc/cpuinfo | grep -ci -m1 'ODROID-XU3') == 1 )); then

		HW_MODEL_DESCRIPTION='oDroid XU3/4'
		HW_MODEL=11
		STORAGE_ROOT_PATH="/dev/mmcblk0p2"

	#oDroid C1
	elif (( $(cat /proc/cpuinfo | grep -ci -m1 'ODROIDC') == 1 )); then

		HW_MODEL_DESCRIPTION='oDroid C1'
		HW_MODEL=10
		STORAGE_ROOT_PATH="/dev/mmcblk0p2"

	#RPi ARMv7
	elif (( $(cat /proc/cpuinfo | grep -ci -m1 'BCM2709') == 1 )); then

		HW_MODEL=2
		STORAGE_ROOT_PATH="/dev/root"

		#Grab model from rpi_boardinfo
		/DietPi/dietpi/misc/rpi_boardinfo 1
		HW_MODEL_DESCRIPTION="Raspberry Pi $(/DietPi/dietpi/misc/rpi_boardinfo 1)"

	#RPi ARMv6
	elif (( $(cat /proc/cpuinfo | grep -ci -m1 'BCM2708') == 1 )); then

		#As we optimize differently for 256/512MB boards,
		# - Use memory size to determine which HW_model index we will use.
		if (( $(free | awk '/^Mem:/{print $2}') > 246000 )); then
			HW_MODEL=1
		else
			HW_MODEL=0
		fi

		STORAGE_ROOT_PATH="/dev/root"

		#Grab model from rpi_boardinfo
		/DietPi/dietpi/misc/rpi_boardinfo 1
		HW_MODEL_DESCRIPTION="Raspberry Pi $(/DietPi/dietpi/misc/rpi_boardinfo 1)"

	fi

	#Get Distro Index (assume wheezy)
	DISTRO=1
	#Ubuntu 14.04
	if (( $( cat /etc/*release | grep -ci -m1 '14.04') == 1 )); then
		DISTRO=2
	#Debian Jessie
	elif (( $( cat /etc/*release | grep -ci -m1 'jessie') == 1 )); then
		DISTRO=3
	fi

	#Generate UUID if it doesnt not exist
	if [ ! -f /DietPi/dietpi/.hw_model ]; then
		HW_UUID=$(cat /proc/sys/kernel/random/uuid)
	else
		HW_UUID=$(sed -n 5p /DietPi/dietpi/.hw_model)
	fi

	#Save data
	cat << _EOF_ > /DietPi/dietpi/.hw_model
$HW_MODEL
$HW_MODEL_DESCRIPTION
$DISTRO
$STORAGE_ROOT_PATH
$HW_UUID
_EOF_
	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}