#!/bin/bash
{
	#////////////////////////////////////
	# DietPi-Software Uninstaller
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Removes DietPi installed software
	# - Use of this script is not recommended for inexperienced users, due to the nature of Linux packages and dependencies.
	# eg: Removing Xserver will also remove Kodi/Desktop etc....
	#
	# Usage:
	# - /DietPi/dietpi/dietpi-uninstall menu (runs menu)
	# - /DietPi/dietpi/dietpi-uninstall sNAME sNAME (uninstalls software)
	#////////////////////////////////////

	INPUT=$1
	VALIDINPUT=1
	
	#/////////////////////////////////////////////////////////////////////////////////////
	#Exit Paths
	#/////////////////////////////////////////////////////////////////////////////////////
	#Exit path for non-root logins.
	if (( $UID != 0 )); then
		clear
		echo -e "\n ERROR: You do not have root privileges.\n Please login as root, or, use:\n sudo dietpi-uninstall\n"
		
		exit
	fi

	#/////////////////////////////////////////////////////////////////////////////////////
	#Global
	#/////////////////////////////////////////////////////////////////////////////////////
	#Count what we have uninstalled. If >=1 autoremove will be run.
	UNINSTALLED_COUNT=0

	#/////////////////////////////////////////////////////////////////////////////////////
	#Obtain Pi/Odroid Model
	#/////////////////////////////////////////////////////////////////////////////////////

	HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)
	HW_MODEL_DESCRIPTION=$(sed -n 2p /DietPi/dietpi/.hw_model)
	DISTRO=$(sed -n 3p /DietPi/dietpi/.hw_model)
	
	#/////////////////////////////////////////////////////////////////////////////////////
	#Menu
	#/////////////////////////////////////////////////////////////////////////////////////
	WHIP_TITLE='------ DietPi-Uninstall ------'

	Menu_Uninstall(){

		#Final string which will hold all software to be removed. This can then be used as dietpi-uninstall "$string_output"
		local string_output=""

		#create temp file with list of .installed software. Remove ( 2) installed flag.
		cat /DietPi/dietpi/.installed | grep ' 2' | sed 's/ 2//g'  > /tmp/dietpi-uninstall_temp
		
		#Delete software lines not available for removal
		sed -i '/USBDRIVE/d' /tmp/dietpi-uninstall_temp
		
		#Only list the webserver stacks if installed. Else, show all WEBSERVER_OPTIONS
		local webserver_stack_installed=0
		if (( $(cat /tmp/dietpi-uninstall_temp | grep -ci -m1 'WEBSERVER_LAMP') == 1 )) || (( $(cat /tmp/dietpi-uninstall_temp | grep -ci -m1 'WEBSERVER_LASP') == 1 )); then
			sed -i '/WEBSERVER_APACHE/d' /tmp/dietpi-uninstall_temp
			webserver_stack_installed=1
		fi

		if (( $(cat /tmp/dietpi-uninstall_temp | grep -ci -m1 'WEBSERVER_LEMP') == 1 )) || (( $(cat /tmp/dietpi-uninstall_temp | grep -ci -m1 'WEBSERVER_LESP') == 1 )); then
			sed -i '/WEBSERVER_NGINX/d' /tmp/dietpi-uninstall_temp
			webserver_stack_installed=1
		fi
		
		#Hide these when a webserver stack is installed.
		if (( $webserver_stack_installed == 1 )); then
			sed -i '/WEBSERVER_MYSQL/d' /tmp/dietpi-uninstall_temp
			sed -i '/WEBSERVER_SQLITE/d' /tmp/dietpi-uninstall_temp
			sed -i '/WEBSERVER_PHP/d' /tmp/dietpi-uninstall_temp			
		fi
		
		#Read into array
		readarray installed_list_array < /tmp/dietpi-uninstall_temp

		#Create List for Whiptail
		local whiptail_list_array=()
		for ((i=0; i<${#installed_list_array[@]}; i++))
		do
			whiptail_list_array+=(${installed_list_array[$i]} "                        " "off")
		done

		#Run menu
		whiptail --title "$WHIP_TITLE" --checklist --separate-output "Use the spacebar to select the software you would like to remove." --cancel-button "Exit" --backtitle "$WHIP_TITLE" 18 60 10 "${whiptail_list_array[@]}" 2>/tmp/dietpi-uninstall_results
		while read choice
		do
			case $choice in
				*)
					#Convert lined list into a 1 line string.
					string_output+="$choice "
				;;
			esac
				
		done < /tmp/dietpi-uninstall_results
		
		#Prompt user with list of software selected for removal
		if [ "$string_output" != "" ]; then
			
			#Ask for confirmation
			whiptail --title "Uninstall Software?" --yesno "The following software will be REMOVED from your system:\n\n$string_output\n\nDo you wish to continue?" --yes-button "Ok" --no-button "Exit" --defaultno --backtitle "$WHIP_TITLE" 14 70
			CHOICE=$?
			
			#Run uninstall
			if (( $CHOICE == 0 )); then
				/DietPi/dietpi/dietpi-uninstall $string_output
			
				#inform user
				/DietPi/dietpi/dietpi-banner 0
				echo -e "\n DietPi-Uninstall completed.\n"
			fi
		fi

		#Clean up tmp files
		rm /tmp/dietpi-uninstall_temp &> /dev/null
		rm /tmp/dietpi-uninstall_results &> /dev/null

		#delete[] arrays
		unset installed_list_array
		unset whiptail_list_array

	}
	
	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////

	#----------------------------------------------------------------------
	#Check installed file exists
	if [ ! -f /DietPi/dietpi/.installed ]; then
		echo -e "/DietPi/dietpi/.installed does not exist yet. Please run dietpi-software to complete your DietPi installation."
		exit
	fi

	#----------------------------------------------------------------------
	#Menu mode
	if [ "$INPUT" = "menu" ]; then
		Menu_Uninstall

	#----------------------------------------------------------------------
	#Process all inputs and apply removal.
	else
		#----------------------------------------------------------------------
		#Make sure apt-get_update thread is finished
		/DietPi/dietpi/dietpi-apt-get_update 1
		
		#----------------------------------------------------------------------
		for INPUT in "$@"
		do
			#reset valid input
			VALIDINPUT=1
			
			#Inform User
			/DietPi/dietpi/dietpi-banner 0
			echo -e "\n Uninstalling: $INPUT \n"
		
			#----------------------------------------------------------------------
			#DIETPI SOFTWARE
			if [ "$INPUT" = "GRASSHOPPER" ]; then

				#rm -R /var/www/grasshopper

				grasshopper_directory=$(cat /DietPi/dietpi.txt | grep 'grasshopper_directory=' | sed 's/grasshopper_directory=//g' )
				rm -R "$grasshopper_directory"/documentation
				rm -R "$grasshopper_directory"/css
				rm -R "$grasshopper_directory"/db
				rm -R "$grasshopper_directory"/exec
				rm -R "$grasshopper_directory"/includes
				rm -R "$grasshopper_directory"/install
				rm -R "$grasshopper_directory"/phpliteadmin
				rm -R "$grasshopper_directory"/js
				rm -R "$grasshopper_directory"/setup
				rm -R "$grasshopper_directory"/pics
				rm -R "$grasshopper_directory"/themes
				rm "$grasshopper_directory"/favicon.ico
				rm "$grasshopper_directory"/index.php
				#PDF documentation
				rm "$grasshopper_directory"/Grasshopper*
				
				
				update-rc.d grasshopper remove
				rm /etc/init.d/grasshopper		
				
				#Probably best we leave the following installed to prevent other software from breaking.
				#apt-get purge python -y
			elif [ "$INPUT" = "DESKTOP_LXDE" ]; then
				apt-get purge lxde upower policykit-1 iceweasel p7zip-full -y
				#rm -R ~/Desktop
			elif [ "$INPUT" = "TRANSMISSION" ]; then
				apt-get purge transmission-daemon -y
			elif [ "$INPUT" = "WEBSERVER_LAMP" ]; then
				/DietPi/dietpi/dietpi-uninstall WEBSERVER_MYSQL WEBSERVER_PHP WEBSERVER_APACHE
				sed -i "/WEBSERVER_LAMP /c\WEBSERVER_LAMP 0" /DietPi/dietpi/.installed
			elif [ "$INPUT" = "WEBSERVER_LEMP" ]; then
				/DietPi/dietpi/dietpi-uninstall WEBSERVER_MYSQL WEBSERVER_PHP WEBSERVER_NGINX
				sed -i "/WEBSERVER_LEMP /c\WEBSERVER_LEMP 0" /DietPi/dietpi/.installed
			elif [ "$INPUT" = "WEBSERVER_LASP" ]; then
				/DietPi/dietpi/dietpi-uninstall WEBSERVER_SQLITE WEBSERVER_PHP WEBSERVER_APACHE
				sed -i "/WEBSERVER_LASP /c\WEBSERVER_LASP 0" /DietPi/dietpi/.installed
			elif [ "$INPUT" = "WEBSERVER_LESP" ]; then
				/DietPi/dietpi/dietpi-uninstall WEBSERVER_SQLITE WEBSERVER_PHP WEBSERVER_NGINX
				sed -i "/WEBSERVER_LESP /c\WEBSERVER_LESP 0" /DietPi/dietpi/.installed					
			elif [ "$INPUT" = "WEBSERVER_APACHE" ]; then
				apt-get purge apache2 -y
				rm /var/www/index.html
			elif [ "$INPUT" = "WEBSERVER_NGINX" ]; then
				apt-get purge nginx -y
				rm /var/www/index.html
			elif [ "$INPUT" = "WEBSERVER_MYSQL" ]; then
				apt-get purge mysql-server -y
			elif [ "$INPUT" = "WEBSERVER_SQLITE" ]; then
				apt-get purge sqlite3 -y
			elif [ "$INPUT" = "WEBSERVER_PHP" ]; then
				apt-get purge php5 libapache2-mod-php5 php5-fpm php5-mysql php5-curl php5-sqlite php-apc -y
				rm /var/www/phpinfo.php
				rm /var/www/apc.php
				rm /etc/php5/fpm/pool.d/www.conf
			elif [ "$INPUT" = "WEBSERVER_MYADMINPHP" ]; then
				apt-get purge phpmyadmin -y
			elif [ "$INPUT" = "PHPBB" ]; then
				apt-get purge phpbb3 -y
			elif [ "$INPUT" = "OWNCLOUD" ]; then
				apt-get purge owncloud -y
			elif [ "$INPUT" = "HIFI" ]; then
				apt-get purge mpd libmpdclient2 -y
				update-rc.d ympd remove
				rm /etc/init.d/ympd
				rm /usr/bin/ympd
			elif [ "$INPUT" = "KODI" ]; then
				apt-get purge kodi libcurl4-gnutls-dev -y
				rm /usr/share/applications/kodi.desktop
				rm ~/Desktop/kodi.desktop
			elif [ "$INPUT" = "RETROPIE" ]; then
				whiptail --title "DietPi-Uninstall" --msgbox "RetroPie's data and packages cannot be uninstalled by DietPi Software. This must be completed manually." 11 65
			elif [ "$INPUT" = "MINIDLNA" ]; then
				apt-get purge minidlna -y
			elif [ "$INPUT" = "VPNSERVER" ]; then
				update-rc.d vpnserver remove
				rm /etc/init.d/vpnserver
				rm -R /usr/local/vpnserver*	
				rm /usr/local/vpnserver/vpn_server.config			
			elif [ "$INPUT" = "OPENTYRIAN" ]; then
				apt-get purge ibsdl1.2debian libsdl-net1.2 -y
				rm -R /usr/local/games/opentyrian
				rm /usr/share/applications/opentyrian.desktop
				rm ~/Desktop/opentyrian.desktop
			elif [ "$INPUT" = "DIETPICAM" ]; then
				apt-get purge gpac motion -y
				rm -R /var/www/dietpicam
				rm /opt/vc/bin/raspimjpeg
				rm /usr/bin/raspimjpeg
			elif [ "$INPUT" = "DELUGE" ]; then
				apt-get purge deluged deluge-web deluge-webui -y
				rm /etc/deluge_init
				rm -R ~/.config/deluge
			elif [ "$INPUT" = "FILESERVER_PROFTP" ]; then
				apt-get purge proftpd-basic -y
			elif [ "$INPUT" = "FILESERVER_SAMBA" ]; then
				apt-get purge samba samba-common-bin -y
			elif [ "$INPUT" = "FILESERVER_VSFTPD" ]; then
				apt-get purge vsftpd -y
			elif [ "$INPUT" = "NOIPDYNDNS" ]; then
				update-rc.d noip2 remove
				rm /usr/local/bin/noip2
				rm /etc/init.d/noip2
			elif [ "$INPUT" = "RASPCONTROL" ]; then
				rm -R /var/www/raspcontrol
				rm -R /etc/raspcontrol
			elif [ "$INPUT" = "LINUXDASH" ]; then
				rm -R /var/www/linuxdash
			elif [ "$INPUT" = "PIHOLE" ]; then
				apt-get purge dnsmasq -y
				rm /etc/dnsmasq.conf
				rm /usr/local/bin/gravity.sh
				rm -R /var/www/pihole
				rm -R /etc/pihole
			elif [ "$INPUT" = "SUBSONIC" ]; then
				apt-get purge subsonic -y
				rm -R /var/subsonic &> /dev/null
				#Leave possible shared Java on system
				#apt-get purge openjdk-7-jre-headless -y

			#----------------------------------------------------------------------
			#LINUX SOFTWARE
			elif [ "$INPUT" = "VIMFULL" ]; then
				apt-get purge vim -y
			elif [ "$INPUT" = "SSHCLIENT" ]; then
				#This also removes OpenSSH server. So lets check OpenSSH server isnt installed before hand.
				if (( $(dpkg -l | grep -ci -m1 'openssh-server') == 0 )); then
					apt-get purge openssh-client -y
				#Dont remove
				else
					VALIDINPUT=0
				fi
			elif [ "$INPUT" = "SMBCLIENT" ]; then
				umount /mnt/samba &> /dev/null
				apt-get purge smbclient -y
				#Disable in fstab
				sed -i '/\/mnt\/samba/c\#\/mnt\/samba . Please use dietpi-config and the networking menu to setup this mount' /etc/fstab
				#Add info file for installation method.
				echo -e "Samba client can be installed and setup by DietPi-Config.\nSimply run: dietpi-config 8" > /mnt/samba/readme.txt

			elif [ "$INPUT" = "RPIGPIO" ]; then
				apt-get purge python-rpi.gpio python3-rpi.gpio -y
			elif [ "$INPUT" = "BUILDESSENTIAL" ]; then
				apt-get purge build-essential -y
			elif [ "$INPUT" = "GITCLIENT" ]; then
				apt-get purge git -y
			elif [ "$INPUT" = "ALSABASE" ]; then
				apt-get purge alsa-base -y
			elif [ "$INPUT" = "XSERVERXORG" ]; then
				apt-get purge xinit xauth xserver-xorg xfonts-base x11-xserver-utils x11-common x11-utils -y
				if (( $HW_MODEL == 10 )); then
					#HK driver
					apt-get purge xterm aml-libs mali-x11 xserver-xorg-video-mali -y
					#Fbturbo
					apt-get purge xserver-xorg-fbturbo-odroidc1 libump -y
				elif (( $HW_MODEL <= 2 )); then
					apt-get purge xserver-xorg-video-fbturbo xserver-xorg-video-fbdev -y
				fi
			elif [ "$INPUT" = "CURLFTPFS" ]; then
				umount /mnt/ftp_client &> /dev/null
				apt-get purge curlftpfs -y

				#Disable in fstab
				sed -i '/\/mnt\/ftp_client/c\#\/mnt\/ftp_client . Please use dietpi-config and the networking menu to setup this mount' /etc/fstab

				#Add info file for installation method.
				echo -e "FTP client mount can be installed and setup by DietPi-Config.\nSimply run: dietpi-config 8" > /mnt/ftp_client/readme.txt
				
			elif [ "$INPUT" = "SUDO_AUTH" ]; then
				apt-get purge sudo -y				
			elif [ "$INPUT" = "SSHSERVER_DROPBEAR" ]; then
				apt-get purge dropbear -y
			elif [ "$INPUT" = "SSHSERVER_OPENSSH" ]; then
				apt-get purge openssh-server openssh-blacklist* -y
			elif [ "$INPUT" = "LOGGING_RAMLOG" ]; then
				sed -i '/\/var\/log/c\#\/var\/log DietPi Ramlog Disabled' /etc/fstab
			elif [ "$INPUT" = "LOGGING_LOGROTATE" ]; then
				apt-get purge logrotate -y
			elif [ "$INPUT" = "LOGGING_RSYSLOG" ]; then
				apt-get purge rsyslog -y

			#----------------------------------------------------------------------
			#No Matching software
			else
				VALIDINPUT=0
				whiptail --title "DietPi-Uninstall" --msgbox "Invalid usage:\n- >> $INPUT << is unknown and/or not removable.\n\n- For more information and usage of DietPi-Uninstall:\nhttp://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=24&p=60#p60" 12 70
			fi
		
			#----------------------------------------------------------------------
			#Valid input. Set 0 in Dietpi's .installed file, and, log to .uninstalled file
			if (( $VALIDINPUT == 1 )); then
			
				#Update our uninstalled count
				((UNINSTALLED_COUNT++))
			
				#log to .uninstalled file
				if [ ! -f /DietPi/dietpi/.uninstalled ]; then
					echo -e "DietPi-Uninstall Software Log\n----------------------\n" > /DietPi/dietpi/.uninstalled
				fi
				echo -e "$(date)\n$INPUT\n" >> /DietPi/dietpi/.uninstalled

				#Remove from DietPi's installed list
				sed -i "s/$INPUT 2/$INPUT 0/g" /DietPi/dietpi/.installed

			fi
		done	
	fi
		
	#----------------------------------------------------------------------
	#At least one item was uninstalled
	if (( $UNINSTALLED_COUNT > 0 )); then
		#Purge
		/DietPi/dietpi/dietpi-banner 0
		echo -e "\n Removing packages that are no longer required.\n"
		apt-get autoremove --purge -y

		#Check if we need to clear DietPi choices
		dpkg -l > /DietPi/dietpi/dpkg
		if (( $(cat /DietPi/dietpi/dpkg | grep -ci -m1 'openssh-server') == 0 )) && 
			(( $(cat /DietPi/dietpi/dpkg | grep -ci -m1 'dropbear') == 0 )); then
			sed -i "/INDEX_SSHSERVER_CURRENT /c\INDEX_SSHSERVER_CURRENT 0" /DietPi/dietpi/.installed
			sed -i "/INDEX_SSHSERVER_TARGET /c\INDEX_SSHSERVER_TARGET 0" /DietPi/dietpi/.installed
		fi

		if (( $(cat /DietPi/dietpi/dpkg | grep -ci -m1 ' samba ') == 0 )) &&
			(( $(cat /DietPi/dietpi/dpkg | grep -ci -m1 'proftpd-basic') == 0 )); then
			sed -i "/INDEX_FILESERVER_CURRENT /c\INDEX_FILESERVER_CURRENT 0" /DietPi/dietpi/.installed
			sed -i "/INDEX_FILESERVER_TARGET /c\INDEX_FILESERVER_TARGET 0" /DietPi/dietpi/.installed
		fi

		if (( $(cat /etc/fstab | grep -ci -m1 '#/var/log') == 1 )) &&
			(( $(cat /DietPi/dietpi/dpkg | grep -ci -m1 'rsyslog') == 0 )) &&
			(( $(cat /DietPi/dietpi/dpkg | grep -ci -m1 'logrotate') == 0 )); then
			sed -i "/INDEX_LOGGING_CURRENT /c\INDEX_LOGGING_CURRENT 0" /DietPi/dietpi/.installed
			sed -i "/INDEX_LOGGING_TARGET /c\INDEX_LOGGING_TARGET 0" /DietPi/dietpi/.installed
		fi
		
		rm /DietPi/dietpi/dpkg
	fi

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}