#!/bin/bash
{
	#////////////////////////////////////
	# DietPi-Software Uninstaller
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Removes DietPi installed software
	# - Use of this script is not recommended due to the nature of Linux packages and dependencies.
	# eg: Removing Xserver will also remove Kodi/Desktop etc....
	#
	# Usage:
	# - /boot/dietpi/dietpi-uninstall sNAME
	#////////////////////////////////////
	
	INPUT=$1
	bVALIDINPUT=true

	#/////////////////////////////////////////////////////////////////////////////////////
	#Obtain Pi/Odroid Model
	#/////////////////////////////////////////////////////////////////////////////////////

	HW_MODEL=$(sed -n 1p /boot/dietpi/.hw_model)
	HW_MODEL_DESCRIPTION=$(sed -n 2p /boot/dietpi/.hw_model)
	DISTRO=$(sed -n 3p /boot/dietpi/.hw_model)
	
	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////

	#	whiptail --title "$DietPi-Uninstall" --yesno "Are you sure you wish to remove the following software?\n - $DIETPI_PACKAGENAME" --backtitle "$DietPi-Uninstall" --yes-button "Uninstall" --no-button "Abort" --defaultno 13 65
	#	CHOICE=$?
	#	if (( $CHOICE == 0 )); then
	#	fi

		#Check installed file exists
		if [ ! -f /boot/dietpi/.installed ]; then
			echo -e "/boot/dietpi/.installed does not exist yet. Please run dietpi-software to complete your DietPi installation."
			exit
		fi
	
		#----------------------------------------------------------------------
		#DIETPI SOFTWARE
		if [ "$INPUT" = "DESKTOP" ]; then
			apt-get purge lxde upower policykit-1 iceweasel p7zip-full -y
			#rm -R ~/Desktop
		elif [ "$INPUT" = "TRANSMISSION" ]; then
			apt-get purge transmission-daemon -y
		elif [ "$INPUT" = "WEBSERVER_APACHE" ]; then
			apt-get purge apache2 -y
			rm /var/www/index.html
		elif [ "$INPUT" = "WEBSERVER_NGINX" ]; then
			apt-get purge nginx xml-core -y
			rm /var/www/index.html
		elif [ "$INPUT" = "WEBSERVER_MYSQL" ]; then
			apt-get purge mysql-server -y
		elif [ "$INPUT" = "WEBSERVER_PHP" ]; then
			apt-get purge php5 libapache2-mod-php5 php5-fpm php5-mysql php-apc -y
			rm /var/www/phpinfo.php
			rm /var/www/apc.php
			rm /etc/php5/fpm/pool.d/www.conf
		elif [ "$INPUT" = "WEBSERVER_PHPMYADMIN" ]; then
			apt-get purge phpmyadmin -y
		elif [ "$INPUT" = "PHPBB" ]; then
			apt-get purge phpbb3 -y
		elif [ "$INPUT" = "OWNCLOUD" ]; then
			apt-get purge owncloud -y
			rm /var/lib/owncloud/data
		elif [ "$INPUT" = "YMPD" ]; then
			apt-get purge mpd libmpdclient2 -y
			update-rc.d ympd remove
			rm /etc/init.d/ympd
			rm /usr/bin/ympd
		elif [ "$INPUT" = "KODI" ]; then
			apt-get purge kodi libcurl4-gnutls-dev -y
			rm /usr/share/applications/kodi.desktop
			rm ~/Desktop/kodi.desktop
		elif [ "$INPUT" = "RETROPIE" ]; then
			echo -e "RetroPie cannot be uninstalled by DietPi Software. This must be completed manually."
		elif [ "$INPUT" = "MINIDLNA" ]; then
			apt-get purge minidlna -y
		elif [ "$INPUT" = "VPNSERVER" ]; then
			update-rc.d vpnserver remove
			rm /etc/init.d/vpnserver
			rm -R /usr/local/vpnserver*	
			rm /usr/local/vpnserver/vpn_server.config			
		elif [ "$INPUT" = "OPENTYRIAN" ]; then
			apt-get purge ibsdl1.2debian libsdl-net1.2 -y
			rm -R /usr/local/games/opentyrian
			rm /usr/share/applications/opentyrian.desktop
			rm ~/Desktop/opentyrian.desktop
		elif [ "$INPUT" = "DIETPICAM" ]; then
			apt-get purge gpac motion zip -y
			rm -R /var/www/dietpicam
			rm /opt/vc/bin/raspimjpeg
			rm /usr/bin/raspimjpeg
		elif [ "$INPUT" = "PROFTP" ]; then
			apt-get purge proftpd-basic -y
		elif [ "$INPUT" = "DELUGE" ]; then
			apt-get purge deluged deluge-web deluge-webui -y
			rm /etc/deluge_init
			rm -R ~/.config/deluge
		elif [ "$INPUT" = "SMBSERVER" ]; then
			apt-get purge samba samba-common-bin -y
		#----------------------------------------------------------------------
		#LINUX SOFTWARE
		elif [ "$INPUT" = "VIMFULL" ]; then
			apt-get purge vim vim-full -y
		elif [ "$INPUT" = "SSHCLIENT" ]; then
			apt-get purge openssh-client -y
		elif [ "$INPUT" = "SMBCLIENT" ]; then
			apt-get purge smbclient -y
		elif [ "$INPUT" = "RPIGPIO" ]; then
			apt-get purge python-rpi.gpio python3-rpi.gpio -y
		elif [ "$INPUT" = "BUILDESSENTIAL" ]; then
			apt-get purge build-essential -y
		elif [ "$INPUT" = "GITCLIENT" ]; then
			apt-get purge git -y
		elif [ "$INPUT" = "ALSABASE" ]; then
			apt-get purge alsa-base -y
		elif [ "$INPUT" = "XSERVERXORG" ]; then
			apt-get purge xinit xauth xserver-xorg xfonts-base xserver-xorg-video-fbturbo xserver-xorg-video-fbdev x11-xserver-utils -y
		elif [ "$INPUT" = "CURLFTPFS" ]; then
			apt-get purge curlftpfs -y
		elif [ "$INPUT" = "SSHSERVER_DROPBEAR" ]; then
			apt-get purge dropbear -y
		elif [ "$INPUT" = "SSHSERVER_OPENSSH" ]; then
			apt-get purge openssh-server -y
		elif [ "$INPUT" = "NOIPDYNDNS" ]; then
			update-rc.d noip2 remove
			rm /usr/local/bin/noip2
			rm /etc/init.d/noip2

		#No Matching software
		else
			bVALIDINPUT=false
			whiptail --title "DietPi-Uninstall" --msgbox "Invalid usage:\n - $INPUT is unknown, or, not removable." 10 60
		fi
	
		#Valid input, lets do it!
		if [ "$bVALIDINPUT" = "true" ]; then
		
			#log to .uninstalled file
			if [ ! -f /boot/dietpi/.uninstalled ]; then
				echo -e "DietPi-Uninstall Software Log\n----------------------\n" > /boot/dietpi/.uninstalled
			fi
			echo -e "$(date)\n$INPUT\n" >> /boot/dietpi/.uninstalled

			#Remove from DietPi's installed list
			sed -i '/'"$INPUT"' /c\'"$INPUT"' 0' /boot/dietpi/.installed
			
			#Purge
			apt-get autoremove --purge -y
		fi
	
	#Run whole script inside a function. Loads into memory, allows for online file patching.
	exit
}