#!/bin/bash
{
# --------------------------------------------
# dietpi-network
# Manage network interfaces and global network settings
# --------------------------------------------
# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
# Updated by MichaIng / micha@dietpi.com / dietpi.com
# Refactored by GitHub Copilot / github.com
# --------------------------------------------
# Location: /boot/dietpi/dietpi-network
readonly USAGE='
Usage: dietpi-network [<command>]
Available commands:
  <empty>, main                       Open the interactive top-level menu to control network settings
  <ifname>                            Open the interactive submenu for network interface <ifname>
  country                             Open the interactive WiFi country code submenu
  proxy                               Open the interactive proxy submenu
  apply <ifname> [<options>...]       Apply interface config for <ifname> and reconnect only that interface
  remove <ifname>                     Remove the DietPi drop-in config for <ifname> and ifdown the interface
  proxy enable|disable                Enable or disable the configured proxy globally
  proxy address|port|username|password <value>
                                      Apply <value> to the specified proxy setting
Available options for "apply" command:
  --enable|--disable                  Enable or disable the interface
  --dhcp|--static                     Select DHCP or static IPv4 mode
  --ip <address>[/<cidr>]             Static IPv4 address with optional CIDR netmask, else /24
  --gateway <address>                 Static IPv4 gateway
  --dns "<ip> [<ip>...]"              Static DNS server list
  --copy-current                      Copy current live IPv4/DNS values into static settings before applying
  --hotplug|--auto                    Bring up interface once detected/plugged (hotplug) or during early boot (auto)
                                      The hotplug mode is the recommended default on all systems but container guests.
                                      The auto mode can fail if the adapter is not initializing fast enough.
  --client|--hotspot                  WiFi client or hotspot mode, which defaults to client for new interfaces
  --ssid <name>                       WiFi hotspot SSID
  --key <passphrase>                  WiFi hotspot WPA passphrase
  --freq 2.4|5                        WiFi hotspot frequency band
  --channel <channel>                 WiFi hotspot channel for the selected frequency band
  --wifi4 0|1                         Enable or disable WiFi 4 / 802.11n support for hotspot mode
  --wifi5 0|1                         Enable or disable WiFi 5 / 802.11ac support for hotspot mode
  --wifi6 0|1                         Enable or disable WiFi 6 / 802.11ax support for hotspot mode
  --no-restart                        Write config only, do not reconnect the interface now
  --force                             Proceed even if a network conflict (same subnet/duplicate default route) with
                                      another enabled interface is detected, or if the interface does not exist at all.
'

. /boot/dietpi/func/dietpi-globals
readonly G_PROGRAM_NAME='dietpi-network'
G_CHECK_ROOT_USER "$@"
G_CHECK_ROOTFS_RW
G_INIT

COMMAND='menu'
ENTRY_MENU='main'
NEXT_MENU='main'

PRESERVE_SELECTED_SETTINGS=0
ACTION_VALUE=
ACTION_EXTRA=
APPLY_IFACE=
APPLY_RESTART=1
APPLY_FORCE=0
APPLY_ENABLE=
APPLY_MODE=
APPLY_COPY_CURRENT=0
APPLY_BOOT_MODE=
APPLY_ROLE=
APPLY_IP=
APPLY_GATEWAY=
APPLY_DNS=
APPLY_SSID=
APPLY_KEY=
APPLY_FREQ=
APPLY_CHANNEL=
APPLY_WIFI4=
APPLY_WIFI5=
APPLY_WIFI6=
CURRENT_IFACE=
CURRENT_IFACE_TYPE=
CURRENT_IFACE_ENABLED=1
CURRENT_IFACE_REAL=0
CURRENT_IFACE_CONNECTED=0
CURRENT_IFACE_MODE='dhcp'
CURRENT_IFACE_IP_STATIC=
CURRENT_IFACE_GATEWAY_STATIC=
CURRENT_IFACE_DNS_STATIC=
(( $G_HW_MODEL == 75 )) && CURRENT_IFACE_BOOT_MODE='auto' || CURRENT_IFACE_BOOT_MODE='allow-hotplug'
CURRENT_IFACE_IP='0.0.0.0/24'
CURRENT_IFACE_GATEWAY='0.0.0.0'
CURRENT_IFACE_SOURCE=
CURRENT_IFACE_HOTSPOT=0
CURRENT_IFACE_HOTSPOT_ACTIVE=0
CURRENT_IFACE_WIFI_SSID='Disconnected / No SSID'
CURRENT_IFACE_WIFI_BITRATE=0
CURRENT_IFACE_WIFI_SIGNAL='N/A'
CURRENT_IFACE_WIFI_AUTO_RECONNECT=0
CURRENT_WIFI_COUNTRYCODE='00'
DNS_CURRENT='0.0.0.0'
HOTSPOT_SSID=
HOTSPOT_KEY=
HOTSPOT_CHANNEL=
HOTSPOT_WIFI4=0
HOTSPOT_WIFI5=0
HOTSPOT_WIFI6=0
HOTSPOT_5G=0
HOTSPOT_5G_CHANNEL=
INTERNET_TEST_STATE=0
INTERNET_TEST_URL='https://dietpi.com/'
NET_RX_BYTE=0
NET_TX_BYTE=0
NET_RX_MB='N/A'
NET_TX_MB='N/A'
PROXY_ENABLED=0
PROXY_ADDRESS=
PROXY_PORT=
PROXY_USERNAME=
PROXY_PASSWORD=
ETH_INTERFACES=()
WIFI_INTERFACES=()

Error(){ G_DIETPI-NOTIFY 1 "$1"; exit 1; }

CIDR_From_Mask()
{
	local octet bits=0
	IFS=. read -ra octet <<< "$1"
	for octet in "${octet[@]}"
	do
		while (( $octet ))
		do
			((bits+=octet&1)) # add last bit from octet to $bits
			((octet>>=1)) # remove last bit from octet
		done
	done
	echo "$bits"
}

Get_Default_DNS()
{
	local dns=$(mawk '$1=="nameserver"{print $2}' ORS=' ' /etc/resolv.conf 2> /dev/null)
	dns=${dns% }
	echo "${dns:-9.9.9.9 149.112.112.112}" # default to Quad9 DNS
}

Get_Interfaces()
{
	ETH_INTERFACES=()
	WIFI_INTERFACES=()
	local iface
	for iface in /sys/class/net/*
	do
		[[ $iface != *'/lo' && -d $iface ]] || continue
		iface=${iface##*/}
		Interface_Is_Real "$iface" || continue
		if Interface_Is_Wifi
		then
			WIFI_INTERFACES+=("$iface")
		else
			ETH_INTERFACES+=("$iface")
		fi
	done
}

Interface_Is_Wifi(){ [[ $1 == 'wlan'[0-9]* || -d /sys/class/net/$1/wireless ]]; }
# Excludes bridges/bonds/tunnels and other non-Ethernet devices, but keeps veth-based container interfaces (e.g. LXC "host0"), which lack a backing /sys/class/net/<iface>/device path but are still real, configurable network interfaces.
Interface_Is_Real()
{
	local type
	read -r type < "/sys/class/net/$1/type" 2> /dev/null
	[[ $type == 1 ]] || return 1

	[[ -d /sys/class/net/$1/bridge || -d /sys/class/net/$1/bonding || -e /sys/class/net/$1/tun_flags ]] && return 1

	return 0
}
Wifi_Modules_Enabled(){ [[ ! -f '/etc/modprobe.d/dietpi-disable_wifi.conf' ]]; }
Onboard_Wifi_Enabled(){ [[ ! -f '/boot/firmware/config.txt' ]] || ! grep -q '^[[:blank:]]*dtoverlay=disable-wifi' /boot/firmware/config.txt; }
Onboard_Wifi_Text(){ Onboard_Wifi_Enabled && echo 'On' || echo 'Off'; }
Current_Interface_Type_Text(){ [[ $CURRENT_IFACE_TYPE == 'wifi' ]] && echo 'WiFi' || echo 'Ethernet'; }

Net_Update_UsageStats()
{
	NET_RX_BYTE=0
	NET_TX_BYTE=0
	NET_RX_MB='N/A'
	NET_TX_MB='N/A'
	[[ -f /sys/class/net/$1/statistics/rx_bytes && -f /sys/class/net/$1/statistics/tx_bytes ]] || return 1
	read -r NET_RX_BYTE < "/sys/class/net/$1/statistics/rx_bytes"
	disable_error=1 G_CHECK_VALIDINT "$NET_RX_BYTE" 1 && NET_RX_MB="$(( $NET_RX_BYTE / 1024**2 )) MiB"
	read -r NET_TX_BYTE < "/sys/class/net/$1/statistics/tx_bytes"
	disable_error=1 G_CHECK_VALIDINT "$NET_TX_BYTE" 1 && NET_TX_MB="$(( $NET_TX_BYTE / 1024**2 )) MiB"
}

Load_Proxy_Vars()
{
	[[ $http_proxy ]] || http_proxy=
	if [[ -f '/etc/bashrc.d/dietpi-proxy.sh' ]]
	then
		PROXY_ENABLED=1
		# shellcheck disable=SC1091
		. /etc/bashrc.d/dietpi-proxy.sh
	else
		PROXY_ENABLED=0
	fi

	if [[ $http_proxy ]]
	then
		PROXY_ADDRESS=${http_proxy#*//}; PROXY_ADDRESS=${PROXY_ADDRESS%:*}
		PROXY_PORT=${http_proxy##*:}
		if [[ $http_proxy == *'@'* ]]
		then
			PROXY_ADDRESS=${PROXY_ADDRESS#*@}
			PROXY_USERNAME=${http_proxy#*//}; PROXY_USERNAME=${PROXY_USERNAME%%:*}
			PROXY_PASSWORD=${http_proxy%%@*}; PROXY_PASSWORD=${PROXY_PASSWORD##*:}
		fi
	else
		PROXY_ADDRESS=$(sed -n '/^[[:blank:]]*CONFIG_PROXY_ADDRESS=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
		PROXY_PORT=$(sed -n '/^[[:blank:]]*CONFIG_PROXY_PORT=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
		PROXY_USERNAME=$(sed -n '/^[[:blank:]]*CONFIG_PROXY_USERNAME=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
		PROXY_PASSWORD=$(sed -n '/^[[:blank:]]*CONFIG_PROXY_PASSWORD=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
	fi
}

Apply_Proxy_Settings()
{
	G_CONFIG_INJECT 'CONFIG_PROXY_ADDRESS=' "CONFIG_PROXY_ADDRESS=$PROXY_ADDRESS" /boot/dietpi.txt
	G_CONFIG_INJECT 'CONFIG_PROXY_PORT=' "CONFIG_PROXY_PORT=$PROXY_PORT" /boot/dietpi.txt
	G_CONFIG_INJECT 'CONFIG_PROXY_USERNAME=' "CONFIG_PROXY_USERNAME=$PROXY_USERNAME" /boot/dietpi.txt
	GCI_PASSWORD=1 G_CONFIG_INJECT 'CONFIG_PROXY_PASSWORD=' "CONFIG_PROXY_PASSWORD=$PROXY_PASSWORD" /boot/dietpi.txt

	if (( $PROXY_ENABLED ))
	then
		if [[ $PROXY_USERNAME && $PROXY_PASSWORD ]]
		then
			echo "export {http,https,ftp}_proxy='http://$PROXY_USERNAME:$PROXY_PASSWORD@$PROXY_ADDRESS:$PROXY_PORT'" > /etc/bashrc.d/dietpi-proxy.sh || exit 1
		else
			echo "export {http,https,ftp}_proxy='http://$PROXY_ADDRESS:$PROXY_PORT'" > /etc/bashrc.d/dietpi-proxy.sh || exit 1
		fi
	else
		[[ -f '/etc/bashrc.d/dietpi-proxy.sh' ]] && G_EXEC rm /etc/bashrc.d/dietpi-proxy.sh
		unset -v {http,https,ftp}_proxy # Has no effect on current login session but for this script, e.g. connection test
	fi
}

Parse_Interface_Config()
{
	local file=$1 iface=$2 data
	[[ -f $file ]] || return 1
	data=$(mawk -v iface="$iface" '
		BEGIN{OFS="\034"}
		{
			if (inblock && $1~/^(iface|auto|allow-auto|allow-hotplug|mapping|source)$/) inblock=0
			if ($1~/^(auto|allow-auto|allow-hotplug)$/ && $2==iface) {found=1; enabled=1; bootmode=$1; next}
			if ($1=="iface" && $2==iface) {inblock=1; found=1; mode=$4; next}
			if (!inblock) next
			if ($1=="address") address=$2
			else if ($1=="netmask") netmask=$2
			else if ($1=="gateway") gateway=$2
			else if ($1=="dns-nameservers") {dns=""; for(i=2;i<=NF;i++) dns=dns (dns?" ":"") $i}
			else if ($0=="up iptables-restore < /etc/iptables.ipv4.nat") hotspot=1
		}
		END{print found,enabled,bootmode,mode,address,netmask,gateway,dns,hotspot}
	' "$file") || return 1
	IFS=$'\034' read -r PARSE_FOUND PARSE_ENABLED PARSE_BOOT_MODE PARSE_MODE PARSE_ADDRESS PARSE_NETMASK PARSE_GATEWAY PARSE_DNS PARSE_HOTSPOT <<< "$data"
	(( $PARSE_FOUND )) || return 1
	return 0
}

Get_Interface_Stored_Settings()
{
	local iface=$1
	CURRENT_IFACE_SOURCE=
	CURRENT_IFACE_ENABLED=1
	(( $G_HW_MODEL == 75 )) && CURRENT_IFACE_BOOT_MODE='auto' || CURRENT_IFACE_BOOT_MODE='allow-hotplug'
	CURRENT_IFACE_MODE='dhcp'
	CURRENT_IFACE_IP_STATIC='192.168.0.100/24'
	CURRENT_IFACE_GATEWAY_STATIC='192.168.0.1'
	CURRENT_IFACE_DNS_STATIC=$(Get_Default_DNS)
	CURRENT_IFACE_HOTSPOT=0

	if Parse_Interface_Config "/etc/network/interfaces.d/$iface.conf" "$iface"
	then
		CURRENT_IFACE_SOURCE="/etc/network/interfaces.d/$iface.conf"

	elif Parse_Interface_Config '/etc/network/interfaces' "$iface"
	then
		CURRENT_IFACE_SOURCE='/etc/network/interfaces'
	else
		return 0
	fi

	CURRENT_IFACE_ENABLED=${PARSE_ENABLED:-0}
	[[ $PARSE_BOOT_MODE ]] && CURRENT_IFACE_BOOT_MODE=$PARSE_BOOT_MODE
	[[ $PARSE_MODE == 'static' ]] && CURRENT_IFACE_MODE='static'
	if [[ $PARSE_ADDRESS ]]
	then
		CURRENT_IFACE_IP_STATIC=$PARSE_ADDRESS
		[[ $CURRENT_IFACE_IP_STATIC == */* ]] || CURRENT_IFACE_IP_STATIC+="/$(CIDR_From_Mask "${PARSE_NETMASK:-255.255.255.0}")"
	fi
	[[ $PARSE_GATEWAY ]] && CURRENT_IFACE_GATEWAY_STATIC=$PARSE_GATEWAY
	[[ $PARSE_DNS ]] && CURRENT_IFACE_DNS_STATIC=$PARSE_DNS
	CURRENT_IFACE_HOTSPOT=${PARSE_HOTSPOT:-0}
}

Load_Hotspot_Settings()
{
	if [[ -f '/etc/hostapd/hostapd.conf' ]]
	then
		HOTSPOT_SSID=$(sed -n '/^[[:blank:]]*ssid=/{s/^[^=]*=//p;q}' /etc/hostapd/hostapd.conf)
		HOTSPOT_KEY=$(sed -n '/^[[:blank:]]*wpa_passphrase=/{s/^[^=]*=//p;q}' /etc/hostapd/hostapd.conf)
		HOTSPOT_WIFI4=$(grep -cm1 '^[[:blank:]]*ieee80211n=1$' /etc/hostapd/hostapd.conf)
		HOTSPOT_WIFI5=$(grep -cm1 '^[[:blank:]]*ieee80211ac=1$' /etc/hostapd/hostapd.conf)
		HOTSPOT_WIFI6=$(grep -cm1 '^[[:blank:]]*ieee80211ax=1$' /etc/hostapd/hostapd.conf)
		HOTSPOT_5G=$(grep -cm1 '^[[:blank:]]*hw_mode=a$' /etc/hostapd/hostapd.conf)
		HOTSPOT_5G_CHANNEL=$(sed -n '/^[[:blank:]]*channel=/{s/^[^=]*=//p;q}' /etc/hostapd/hostapd.conf)
		HOTSPOT_CHANNEL=$(sed -n '/^[[:blank:]]*channel=/{s/^[^=]*=//p;q}' /etc/hostapd/hostapd.conf)
	fi
	if (( $HOTSPOT_5G ))
	then
		[[ $HOTSPOT_5G_CHANNEL ]] || HOTSPOT_5G_CHANNEL=$(sed -n '/^[[:blank:]]*SOFTWARE_WIFI_HOTSPOT_5G_CHANNEL=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
		[[ $HOTSPOT_5G_CHANNEL ]] || HOTSPOT_5G_CHANNEL=36
	else
		[[ $HOTSPOT_CHANNEL ]] || HOTSPOT_CHANNEL=$(sed -n '/^[[:blank:]]*SOFTWARE_WIFI_HOTSPOT_CHANNEL=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
		[[ $HOTSPOT_CHANNEL ]] || HOTSPOT_CHANNEL=3
	fi
	[[ $HOTSPOT_SSID ]] || HOTSPOT_SSID='DietPi-Hotspot'
	[[ $HOTSPOT_KEY ]] || HOTSPOT_KEY='dietpihotspot'
}

Load_Interface_State()
{
	local iface=$1
	CURRENT_IFACE=$iface
	Interface_Is_Real "$iface" && CURRENT_IFACE_REAL=1 || CURRENT_IFACE_REAL=0
	Interface_Is_Wifi "$iface" && CURRENT_IFACE_TYPE='wifi' || CURRENT_IFACE_TYPE='eth'
	CURRENT_IFACE_CONNECTED=0
	CURRENT_IFACE_IP='0.0.0.0/24'
	CURRENT_IFACE_GATEWAY='0.0.0.0'
	CURRENT_IFACE_WIFI_SSID='Disconnected / No SSID'
	CURRENT_IFACE_WIFI_BITRATE=0
	CURRENT_IFACE_WIFI_SIGNAL='N/A'
	CURRENT_IFACE_WIFI_AUTO_RECONNECT=0
	CURRENT_IFACE_HOTSPOT=0
	CURRENT_IFACE_HOTSPOT_ACTIVE=0
	DNS_CURRENT=$(Get_Default_DNS)
	(( $PRESERVE_SELECTED_SETTINGS )) || Get_Interface_Stored_Settings "$iface"

	if (( $CURRENT_IFACE_REAL ))
	then
		CURRENT_IFACE_CONNECTED=$(ip -o r l dev "$iface" 2> /dev/null | grep -vcm1 '[[:blank:]]linkdown')
		if (( $CURRENT_IFACE_CONNECTED ))
		then
			CURRENT_IFACE_IP=$(ip -br -f inet a s "$iface" 2> /dev/null | mawk '{print $3}')
			CURRENT_IFACE_GATEWAY=$(ip r l dev "$iface" 0/0 2> /dev/null | mawk '{print $3;exit}')
		fi
	fi

	if [[ $CURRENT_IFACE_TYPE == 'wifi' ]]
	then
		# Only the WiFi interface referenced by hostapd can expose the single global hotspot configuration.
		[[ -f '/etc/hostapd/hostapd.conf' ]] && grep -q "^[[:blank:]]*interface=$iface$" /etc/hostapd/hostapd.conf && CURRENT_IFACE_HOTSPOT=1
		if (( $CURRENT_IFACE_CONNECTED ))
		then
			CURRENT_IFACE_WIFI_SSID=$(iw dev "$iface" link 2> /dev/null | mawk '$1=="SSID:"{print $2;exit}')
			[[ $CURRENT_IFACE_WIFI_SSID ]] || CURRENT_IFACE_WIFI_SSID='Disconnected / No SSID'
			CURRENT_IFACE_WIFI_BITRATE=$(iw dev "$iface" link 2> /dev/null | mawk '$1$2=="txbitrate:"{print $3;exit}')
			[[ $CURRENT_IFACE_WIFI_BITRATE ]] || CURRENT_IFACE_WIFI_BITRATE=0
			local signal=$(iw dev "$iface" link 2> /dev/null | mawk '$1=="signal:"{print $2;exit}')
			if disable_error=1 G_CHECK_VALIDINT "$signal" -500 -1
			then
				CURRENT_IFACE_WIFI_SIGNAL="$signal dBm"

			elif [[ $signal ]]
			then
				CURRENT_IFACE_WIFI_SIGNAL="$signal %"
			fi
		fi
		systemctl -q is-active dietpi-wifi-monitor && CURRENT_IFACE_WIFI_AUTO_RECONNECT=1 || CURRENT_IFACE_WIFI_AUTO_RECONNECT=0
		if (( $CURRENT_IFACE_HOTSPOT ))
		then
			Load_Hotspot_Settings
			systemctl -q is-active hostapd && CURRENT_IFACE_HOTSPOT_ACTIVE=1 || CURRENT_IFACE_HOTSPOT_ACTIVE=0
			CURRENT_WIFI_COUNTRYCODE=$(sed -n '/^[[:blank:]]*country_code=/{s/^[^=]*=//p;q}' /etc/hostapd/hostapd.conf)

		elif [[ -f '/etc/wpa_supplicant/wpa_supplicant.conf' ]]
		then
			CURRENT_WIFI_COUNTRYCODE=$(sed -n '/^[[:blank:]]*country=/{s/^[^=]*=//p;q}' /etc/wpa_supplicant/wpa_supplicant.conf)
		fi
		[[ $CURRENT_WIFI_COUNTRYCODE ]] || CURRENT_WIFI_COUNTRYCODE=$(iw reg get 2> /dev/null | mawk -F'[ :]' '/country/{print $2;exit}')
		[[ $CURRENT_WIFI_COUNTRYCODE ]] || CURRENT_WIFI_COUNTRYCODE='00'
	else
		# Ethernet cannot be a hotspot
		CURRENT_IFACE_HOTSPOT=0
	fi
}

Remove_Interface_From_Main_File()
{
	local iface=$1 config='/etc/network/interfaces' tmp
	[[ $iface && -f $config ]] || return 0
	tmp=$(mktemp) || exit 1
	mawk -v iface="$iface" '
		function top(line){return line ~ /^[[:blank:]]*(iface|auto|allow-hotplug|mapping|source)([[:blank:]]|$)/}
		{
			if (skip)
			{
				if (top($0)) skip=0
				else next
			}
			if ($0 ~ "^[[:blank:]]*#?[[:blank:]]*(allow-hotplug|auto)[[:blank:]]+" iface "([[:blank:]]|$)") next
			if ($0 ~ "^[[:blank:]]*iface[[:blank:]]+" iface "([[:blank:]]|$)") {skip=1; next}
			print
		}
	' "$config" > "$tmp" && G_EXEC_NOEXIT=1 G_EXEC mv "$tmp" "$config"
	[[ -f $tmp ]] && G_EXEC rm "$tmp"
}

Update_ResolvConf_Fallback()
{
	(( $CURRENT_IFACE_ENABLED )) || return 0
	[[ $CURRENT_IFACE_MODE == 'static' ]] || return 0
	(( $CURRENT_IFACE_DNS_STATIC )) || return 0
	command -v resolvconf > /dev/null && return 0
	> /etc/resolv.conf
	local server
	for server in $CURRENT_IFACE_DNS_STATIC
	do
		echo "nameserver $server" >> /etc/resolv.conf
	done
}

Write_Interface_Config()
{
	local iface=$CURRENT_IFACE
	local fp="/etc/network/interfaces.d/$iface.conf"
	local gateway_line dns_line

	# WiFi Hotspot requires a static IP, but must not have a gateway or DNS
	if (( $CURRENT_IFACE_HOTSPOT ))
	then
		CURRENT_IFACE_MODE='static'

	elif [[ $CURRENT_IFACE_MODE == 'static' ]]
	then
		[[ $CURRENT_IFACE_GATEWAY_STATIC ]] && gateway_line="gateway $CURRENT_IFACE_GATEWAY_STATIC"
		[[ $CURRENT_IFACE_DNS_STATIC ]] && command -v resolvconf > /dev/null && dns_line="dns-nameservers $CURRENT_IFACE_DNS_STATIC"
	fi

	# Header
	local content="# Location: $fp"$'\n''# Generated with: dietpi-network'
	(( $CURRENT_IFACE_ENABLED )) && content+=$'\n'"$CURRENT_IFACE_BOOT_MODE $iface"
	content+=$'\n'"iface $iface inet $CURRENT_IFACE_MODE"

	# Static IP
	if [[ $CURRENT_IFACE_MODE == 'static' ]]
	then
		content+=$'\n'"address $CURRENT_IFACE_IP_STATIC"
		[[ $gateway_line ]] && content+=$'\n'"$gateway_line"
		[[ $dns_line ]] && content+=$'\n'"$dns_line"
	fi

	# WiFi
	if [[ $CURRENT_IFACE_TYPE == 'wifi' ]]
	then
		content+=$'\n''wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf'

		# Disable power savings mode if supported
		if iw dev "$iface" set power_save on 2> /dev/null && iw dev "$iface" set power_save off 2> /dev/null
		then
			content+=$'\n'"pre-up iw dev $iface set power_save off || true"
			content+=$'\n'"post-down iw dev $iface set power_save on || true"
		fi

		# WiFi Hotspot
		if (( $CURRENT_IFACE_HOTSPOT ))
		then
			content+=$'\n''up iptables-restore < /etc/iptables.ipv4.nat'
			content+=$'\n''up ip6tables-restore < /etc/iptables.ipv6.nat'
			[[ -f '/etc/hostapd/hostapd.conf' ]] && G_CONFIG_INJECT 'interface=' "interface=$iface" /etc/hostapd/hostapd.conf
			[[ -f '/etc/default/isc-dhcp-server' ]] && G_CONFIG_INJECT 'INTERFACESv4=' "INTERFACESv4=\"$iface\"" /etc/default/isc-dhcp-server
		fi
	fi

	# Write config
	[[ -f '/etc/network/interfaces.d' ]] || G_EXEC mkdir -p /etc/network/interfaces.d
	echo "$content" > "$fp" || exit 1
	grep -q '^source interfaces\.d/\*$' /etc/network/interfaces || G_CONFIG_INJECT 'source interfaces.d/' 'source interfaces.d/*' /etc/network/interfaces

	Remove_Interface_From_Main_File "$iface"
	Update_ResolvConf_Fallback
}

Restart_Interface()
{
	local iface=$1

	# WiFi Hotspot: Stop DHCP server and hostapd before restarting interface
	(( $CURRENT_IFACE_HOTSPOT )) && G_EXEC systemctl stop isc-dhcp-server hostapd

	G_DIETPI-NOTIFY 2 "Restarting $iface, please wait ..."

	# Only try to configure if this is Ethernet, a hotspot, or an SSID has been configured
	if (( $CURRENT_IFACE_ENABLED )) && { [[ $CURRENT_IFACE_TYPE != 'wifi' || $CURRENT_IFACE_HOTSPOT == 1 ]] || grep -q '^network=' /etc/wpa_supplicant/wpa_supplicant.conf 2> /dev/null; }
	then
		journalctl -fn 0 -u "ifup@$iface" &
		G_EXEC_NOHALT=1 G_EXEC_OUTPUT=1 G_EXEC systemctl restart "ifup@$iface"
		kill -15 %%
	else
		ifdown --force "$iface" 2> /dev/null
	fi

	# WiFi Hotspot: Restart DHCP server and hostapd
	(( $CURRENT_IFACE_HOTSPOT )) && G_EXEC systemctl start hostapd isc-dhcp-server

	G_SLEEP 2
	Load_Interface_State "$iface"
	G_DIETPI-NOTIFY 0 "$iface restarted"
}

Copy_Current_To_Static()
{
	(( $CURRENT_IFACE_CONNECTED )) || return 0
	CURRENT_IFACE_IP_STATIC=$CURRENT_IFACE_IP
	CURRENT_IFACE_GATEWAY_STATIC=$CURRENT_IFACE_GATEWAY
	CURRENT_IFACE_DNS_STATIC=$DNS_CURRENT
}

Change_StaticIp()
{
	G_WHIP_INPUTBOX_REGEX='^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]+)?$'
	G_WHIP_INPUTBOX_REGEX_TEXT='be a valid IPv4 address with optional netmask CIDR notation, e.g. "192.168.0.100" or "192.168.0.100/24"'
	G_WHIP_DEFAULT_ITEM=$CURRENT_IFACE_IP_STATIC
	G_WHIP_INPUTBOX "Please enter a new static $(Current_Interface_Type_Text) IP address, optionally in CIDR notation to define a subnet mask other than the default /24 (255.255.255.0), e.g.: 192.168.0.100/24" || return 0
	CURRENT_IFACE_IP_STATIC=$G_WHIP_RETURNED_VALUE
	[[ $CURRENT_IFACE_IP_STATIC == */* ]] || CURRENT_IFACE_IP_STATIC+='/24'
}

Change_StaticGateway()
{
	G_WHIP_INPUTBOX_REGEX='.*'
	G_WHIP_DEFAULT_ITEM=${CURRENT_IFACE_GATEWAY_STATIC:-${CURRENT_IFACE_IP_STATIC%.*}.1}
	G_WHIP_INPUTBOX "Please enter a new static $(Current_Interface_Type_Text) gateway address. You can leave this empty if this interface shall not be used for Internet access." || return 0
	CURRENT_IFACE_GATEWAY_STATIC=$G_WHIP_RETURNED_VALUE
}

Change_StaticDns()
{
	G_WHIP_DEFAULT_ITEM=$CURRENT_IFACE_DNS_STATIC
	G_WHIP_MENU_ARRAY=("$CURRENT_IFACE_DNS_STATIC" ': Your current DNS server')
	local gateway=$(G_GET_NET -q gateway)
	[[ $gateway ]] && G_WHIP_MENU_ARRAY+=("$gateway" ': Use local router as DNS server (recommended)')
	ss -uln 2> /dev/null | grep -q ':53[[:blank:]]' && G_WHIP_MENU_ARRAY+=('127.0.0.1' ': Use local Pi-hole/AdGuard Home/Unbound')
	G_WHIP_MENU_ARRAY+=(
		'Custom' ': Manually enter your DNS server'
		'' '●─ Public DNS providers '
		'1.1.1.1 1.0.0.1' ': Cloudflare'
		'9.9.9.9 149.112.112.112' ': Quad9'
		'8.8.8.8 8.8.4.4' ': Google'
		'208.67.222.222 208.67.220.220' ': OpenDNS'
		'209.244.0.3 209.244.0.4' ': Level3'
		'216.146.35.35 216.146.36.36' ': Dyn'
		'37.235.1.174 37.235.1.177' ': FreeDNS'
		'64.6.64.6 64.6.65.6' ': Verisign'
		'84.200.69.80 84.200.70.40' ': DNS.WATCH'
	)
	G_WHIP_MENU 'Please select a DNS server, or choose "Custom" for manual entry:' || return 0
	if [[ $G_WHIP_RETURNED_VALUE == 'Custom' ]]
	then
		G_WHIP_INPUTBOX_REGEX='^([0-9]{1,3}\.){3}[0-9]{1,3}( ([0-9]{1,3}\.){3}[0-9]{1,3})?$'
		G_WHIP_INPUTBOX_REGEX_TEXT='be one or two space-separated valid IPv4 address, e.g. "9.9.9.9" or "9.9.9.9 149.112.112.112"'
		G_WHIP_DEFAULT_ITEM=$CURRENT_IFACE_DNS_STATIC
		G_WHIP_INPUTBOX "Please enter one or two space-separated DNS server addresses.
 - E.g.:    9.9.9.9 149.112.112.112
 - Current: $CURRENT_IFACE_DNS_STATIC" || return 0
	fi
	CURRENT_IFACE_DNS_STATIC=$G_WHIP_RETURNED_VALUE
}

Change_WifiCountryCode()
{
	G_WHIP_MENU_ARRAY=(
		'GB' ': Great Britain'
		'DE' ': Germany'
		'US' ': United States'
		'JP' ': Japan'
		'CN' ': China'
		'IN' ': India'
		'Manual' ': Enter a custom country code'
	)
	G_WHIP_DEFAULT_ITEM=$CURRENT_WIFI_COUNTRYCODE
	G_WHIP_BUTTON_CANCEL_TEXT='Cancel'
	G_WHIP_MENU 'Please select your country to enable WiFi channels and power ratings allowed in your region.
\nNB: Verify the active code with:\n# iw reg get' || return 0
	if [[ $G_WHIP_RETURNED_VALUE == 'Manual' ]]
	then
		G_WHIP_INPUTBOX_REGEX='^[[:upper:]][[:upper:]]$'
		G_WHIP_INPUTBOX_REGEX_TEXT='a 2 capital letter country code'
		G_WHIP_DEFAULT_ITEM=$CURRENT_WIFI_COUNTRYCODE
		G_WHIP_INPUTBOX 'Please enter a 2 capital letter country code: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2' || return 0
	fi
	CURRENT_WIFI_COUNTRYCODE=$G_WHIP_RETURNED_VALUE
	/boot/dietpi/func/dietpi-set_hardware wificountrycode "$CURRENT_WIFI_COUNTRYCODE"
}

Change_BootMode()
{
	G_WHIP_MENU_ARRAY=(
		'Hotplug' ': Bring up interface once adapter is detected/plugged'
		'Auto' ': Bring up interface during early boot'
	)
	G_WHIP_DEFAULT_ITEM=${CURRENT_IFACE_BOOT_MODE#allow-}
	G_WHIP_MENU 'Please select how the interface should be brought up at boot.
\nNB: The auto mode can fail if the adapter is not initializing fast enough. And it won'\''t bring the interface back up automatically, when the adapter is physically detected and re-attached. We hence recommend the hotplug mode.
Only exception are container guest systems, where the hotplug mode cannot usually work, as it is triggered by udev events about added (detected) network adapters.' || return 0
	[[ $G_WHIP_RETURNED_VALUE == 'Auto' ]] && CURRENT_IFACE_BOOT_MODE='auto' || CURRENT_IFACE_BOOT_MODE='allow-hotplug'
}

Apply_Hotspot_Settings()
{
	G_CONFIG_INJECT 'SOFTWARE_WIFI_HOTSPOT_SSID=' "SOFTWARE_WIFI_HOTSPOT_SSID=$HOTSPOT_SSID" /boot/dietpi.txt
	GCI_PASSWORD=1 G_CONFIG_INJECT 'SOFTWARE_WIFI_HOTSPOT_KEY=' "SOFTWARE_WIFI_HOTSPOT_KEY=$HOTSPOT_KEY" /boot/dietpi.txt
	G_CONFIG_INJECT 'SOFTWARE_WIFI_HOTSPOT_CHANNEL=' "SOFTWARE_WIFI_HOTSPOT_CHANNEL=$HOTSPOT_CHANNEL" /boot/dietpi.txt
	G_CONFIG_INJECT 'SOFTWARE_WIFI_HOTSPOT_WIFI4=' "SOFTWARE_WIFI_HOTSPOT_WIFI4=$HOTSPOT_WIFI4" /boot/dietpi.txt
	G_CONFIG_INJECT 'SOFTWARE_WIFI_HOTSPOT_WIFI5=' "SOFTWARE_WIFI_HOTSPOT_WIFI5=$HOTSPOT_WIFI5" /boot/dietpi.txt
	G_CONFIG_INJECT 'SOFTWARE_WIFI_HOTSPOT_WIFI6=' "SOFTWARE_WIFI_HOTSPOT_WIFI6=$HOTSPOT_WIFI6" /boot/dietpi.txt
	G_CONFIG_INJECT 'SOFTWARE_WIFI_HOTSPOT_5G=' "SOFTWARE_WIFI_HOTSPOT_5G=$HOTSPOT_5G" /boot/dietpi.txt
	G_CONFIG_INJECT 'SOFTWARE_WIFI_HOTSPOT_5G_CHANNEL=' "SOFTWARE_WIFI_HOTSPOT_5G_CHANNEL=$HOTSPOT_5G_CHANNEL" /boot/dietpi.txt
	[[ -f '/etc/hostapd/hostapd.conf' ]] || { G_WHIP_MSG '[FAILED] /etc/hostapd/hostapd.conf does not exist, cannot apply WiFi hotspot settings'; return 1; }
	G_CONFIG_INJECT 'ssid=' "ssid=$HOTSPOT_SSID" /etc/hostapd/hostapd.conf
	G_CONFIG_INJECT 'wpa_passphrase=' "wpa_passphrase=$HOTSPOT_KEY" /etc/hostapd/hostapd.conf
	G_CONFIG_INJECT 'ieee80211n=' "ieee80211n=$HOTSPOT_WIFI4" /etc/hostapd/hostapd.conf
	G_CONFIG_INJECT 'ieee80211ac=' "ieee80211ac=$HOTSPOT_WIFI5" /etc/hostapd/hostapd.conf
	G_CONFIG_INJECT 'ieee80211ax=' "ieee80211ax=$HOTSPOT_WIFI6" /etc/hostapd/hostapd.conf '^ieee80211ac'
	if (( $HOTSPOT_WIFI4 || $HOTSPOT_WIFI5 || $HOTSPOT_WIFI6 ))
	then
		G_CONFIG_INJECT 'wmm_enabled=' 'wmm_enabled=1' /etc/hostapd/hostapd.conf
	else
		G_CONFIG_INJECT 'wmm_enabled=' 'wmm_enabled=0' /etc/hostapd/hostapd.conf
	fi
	if (( $HOTSPOT_5G ))
	then
		G_CONFIG_INJECT 'hw_mode=' 'hw_mode=a' /etc/hostapd/hostapd.conf
		G_CONFIG_INJECT 'channel=' "channel=$HOTSPOT_5G_CHANNEL" /etc/hostapd/hostapd.conf
	else
		G_CONFIG_INJECT 'hw_mode=' 'hw_mode=g' /etc/hostapd/hostapd.conf
		G_CONFIG_INJECT 'channel=' "channel=$HOTSPOT_CHANNEL" /etc/hostapd/hostapd.conf
	fi
}

IP_To_Int()
{
	local a b c d
	IFS=. read -r a b c d <<< "$1"
	echo $(( (a<<24) + (b<<16) + (c<<8) + d ))
}

Subnets_Overlap()
{
	local ip1=${1%/*} p1=${1#*/} ip2=${2%/*} p2=${2#*/}
	[[ $1 == */* ]] || p1=32
	[[ $2 == */* ]] || p2=32
	local i1=$(IP_To_Int "$ip1") i2=$(IP_To_Int "$ip2") p=$(( p1 < p2 ? p1 : p2 ))
	local mask=$(( p == 0 ? 0 : ( 0xFFFFFFFF << ( 32 - p ) ) & 0xFFFFFFFF ))
	(( ( $i1 & $mask ) == ( $i2 & $mask ) ))
}

# Determine the enabled state, mode, static/live subnet and gateway of another interface, without touching the CURRENT_IFACE_* state of the interface currently being configured.
Get_Iface_Effective_Net()
{
	local iface=$1 enabled=0 mode='dhcp' cidr='' gateway=''
	Parse_Interface_Config "/etc/network/interfaces.d/$iface.conf" "$iface" ||
		Parse_Interface_Config '/etc/network/interfaces' "$iface" ||
			PARSE_ENABLED=0 PARSE_MODE='dhcp' PARSE_ADDRESS='' PARSE_NETMASK='' PARSE_GATEWAY=''

	enabled=${PARSE_ENABLED:-0}
	[[ $PARSE_MODE == 'static' ]] && mode='static'
	if [[ $mode == 'static' && $PARSE_ADDRESS ]]
	then
		cidr=$PARSE_ADDRESS
		[[ $cidr == */* ]] || cidr+="/$(CIDR_From_Mask "${PARSE_NETMASK:-255.255.255.0}")"
	fi
	gateway=$PARSE_GATEWAY
	if (( $enabled ))
	then
		local live=$(ip -br -f inet a s "$iface" 2> /dev/null | mawk '{print $3}')
		[[ $live && ! $cidr ]] && cidr=$live
		local live_gateway=$(ip r l dev "$iface" 0/0 2> /dev/null | mawk '{print $3;exit}')
		[[ $live_gateway && ! $gateway ]] && gateway=$live_gateway
	fi
	echo "$enabled|$mode|$cidr|$gateway"
}

Disable_Conflicting_Interface()
{
	local iface=$1 fp
	for fp in "/etc/network/interfaces.d/$iface.conf" '/etc/network/interfaces'
	do
		[[ -f $fp ]] || continue
		G_EXEC_NOEXIT=1 G_EXEC sed --follow-symlinks -i "/^[[:blank:]]*\(allow-hotplug\|auto\)[[:blank:]]\+$iface\([[:blank:]]\|\$\)/s/^/#/" "$fp"
	done
	ifdown --force "$iface" 2> /dev/null
	G_DIETPI-NOTIFY 2 "Disabled interface \"$iface\" to resolve network conflict"
}

# Avoid two enabled interfaces on the same subnet (asymmetric routing risk) or two default routes (DHCP usually assigns one, in addition to any configured static gateway)
Check_Network_Conflicts()
{
	(( $APPLY_FORCE )) && return 0 # skip check if settings are to be applied anyway
	(( $CURRENT_IFACE_ENABLED )) || return 0
	[[ $CURRENT_IFACE_MODE == 'static' || $CURRENT_IFACE_MODE == 'dhcp' ]] || return 0
	local iface o_enabled o_cidr o_gateway reason
	for iface in /sys/class/net/*
	do
		[[ $iface != *'/lo' && -d $iface ]] || continue
		iface=${iface##*/}
		[[ $iface == "$CURRENT_IFACE" ]] && continue
		# Only consider real Ethernet-like or WiFi adapters, same as Get_Interfaces()
		Interface_Is_Real "$iface" || continue

		IFS='|' read -r o_enabled _ o_cidr o_gateway < <(Get_Iface_Effective_Net "$iface")
		(( $o_enabled )) || continue
		if [[ $CURRENT_IFACE_MODE == 'static' && $CURRENT_IFACE_IP_STATIC && $o_cidr ]] && Subnets_Overlap "$CURRENT_IFACE_IP_STATIC" "$o_cidr"
		then
			reason="already uses the same subnet ($o_cidr) as the static IP address about to be assigned to \"$CURRENT_IFACE\" ($CURRENT_IFACE_IP_STATIC)"

		elif [[ $CURRENT_IFACE_MODE == 'dhcp' && $o_gateway ]]
		then
			reason="already has a default gateway ($o_gateway) assigned, while \"$CURRENT_IFACE\" is about to be enabled with DHCP, which usually also assigns a default route"
		else
			continue
		fi

		G_WHIP_MENU_ARRAY=(
			'Ignore' ': Proceed and keep both interfaces enabled (NOT recommended)'
			'Disable' ": Disable \"$iface\" and proceed"
		)
		G_WHIP_MENU "[WARNING] Network conflict detected:\n\nInterface \"$iface\" $reason.\n\nHaving two enabled interfaces on the same subnet, or two default routes, can cause asymmetric traffic and break connectivity (e.g. to a connected SSH client).\n\nPlease select how to proceed:" || return 1
		[[ $G_WHIP_RETURNED_VALUE == 'Disable' ]] && Disable_Conflicting_Interface "$iface"
	done
	return 0
}

Apply_Current_Interface()
{
	[[ $CURRENT_IFACE ]] || return 1
	if [[ $CURRENT_IFACE_TYPE == 'wifi' ]]
	then
		if (( $CURRENT_IFACE_HOTSPOT ))
		then
			(( ${#HOTSPOT_KEY} > 7 )) || { G_DIETPI-NOTIFY 1 'WiFi hotspot key must have at least 8 characters.'; return 1; }
			Apply_Hotspot_Settings
		else
			(( $CURRENT_IFACE_ENABLED )) || G_EXEC_NOEXIT=1 G_EXEC systemctl disable --now dietpi-wifi-monitor
		fi
	fi
	Check_Network_Conflicts || return 1
	Write_Interface_Config
	PRESERVE_SELECTED_SETTINGS=0 # load settings in interface menu from config files again, now that we have written them
	(( $1 )) && Restart_Interface "$CURRENT_IFACE"
}

Interface_Menu_Title()
{
	local title
	if [[ $CURRENT_IFACE_TYPE == 'wifi' ]]
	then
		if (( $CURRENT_IFACE_HOTSPOT ))
		then
			title="WiFi Hotspot: $CURRENT_IFACE"
		else
			title="WiFi Interface: $CURRENT_IFACE"
		fi
	else
		title="Ethernet Interface: $CURRENT_IFACE"
	fi
	[[ $CURRENT_IFACE_SOURCE == '/etc/network/interfaces' ]] && title+=' (will be migrated from /etc/network/interfaces to its own drop-in on apply)'
	echo "$title"
}

Return_From_Submenu(){ [[ $ENTRY_MENU == "$1" ]] && NEXT_MENU='exit' || NEXT_MENU='main'; }

Interface_Status_Text()
{
	local iface=$1 type=$2 enabled='Off' mode='DHCP' connected='Disconnected'
	CURRENT_IFACE=
	Get_Interface_Stored_Settings "$iface"
	(( $CURRENT_IFACE_ENABLED )) && enabled='On'
	[[ $CURRENT_IFACE_MODE == 'static' ]] && mode='Static'
	CURRENT_IFACE_CONNECTED=$(ip -o r l dev "$iface" 2> /dev/null | grep -vcm1 '[[:blank:]]linkdown')
	(( $CURRENT_IFACE_CONNECTED )) && connected='Connected'
	[[ $type == 'wifi' && -f '/etc/hostapd/hostapd.conf' ]] && grep -q "^[[:blank:]]*interface=$iface$" /etc/hostapd/hostapd.conf && connected='Hotspot'
	echo "[$enabled] (${CURRENT_IFACE_BOOT_MODE#allow-}) | $mode | $connected"
}

Menu_Main()
{
	Get_Interfaces
	Load_Proxy_Vars
	local wifi_modules_text='On' ipv6_enabled=1 ipv6_text='On' internet_text='Run internet connection test' proxy_state='[Off]' iface
	Wifi_Modules_Enabled || wifi_modules_text='Off'
	grep -q '^[[:blank:]]*CONFIG_ENABLE_IPV6=0' /boot/dietpi.txt && ipv6_enabled=0 ipv6_text='Off'
	case $INTERNET_TEST_STATE in
		1) internet_text='[Failure] | Offline';;
		2) internet_text='[Success] | Online';;
		*) :;;
	esac
	(( $PROXY_ENABLED )) && proxy_state="[On] | $PROXY_ADDRESS:$PROXY_PORT"

	G_WHIP_MENU_ARRAY=()
	if (( ${#ETH_INTERFACES[@]} ))
	then
		G_WHIP_MENU_ARRAY+=('' '●─ Ethernet Interfaces ')
		for iface in "${ETH_INTERFACES[@]}"
		do
			G_WHIP_MENU_ARRAY+=("$iface" ": $(Interface_Status_Text "$iface" 'eth')")
		done
	fi
	if (( ${#WIFI_INTERFACES[@]} ))
	then
		G_WHIP_MENU_ARRAY+=('' '●─ WiFi Interfaces ')
		for iface in "${WIFI_INTERFACES[@]}"
		do
			G_WHIP_MENU_ARRAY+=("$iface" ": $(Interface_Status_Text "$iface" 'wifi')")
		done
	fi
	G_WHIP_MENU_ARRAY+=(
		'' '●─ Global Options '
		'WiFi modules' ": [$wifi_modules_text]"
	)
	(( ${G_HW_ONBOARD_WIFI:-0} )) && G_WHIP_MENU_ARRAY+=('Onboard WiFi' ": [$(Onboard_Wifi_Text)]")
	[[ -d '/proc/sys/net/ipv6' ]] && G_WHIP_MENU_ARRAY+=('IPv6' ": [$ipv6_text]")
	G_WHIP_MENU_ARRAY+=(
		'Proxy' ": $proxy_state"
		'Test' ": $internet_text"
	)
	G_WHIP_MENU "Hardware : $G_HW_MODEL_NAME" || { NEXT_MENU='exit'; return 0; }
	case $G_WHIP_RETURNED_VALUE in
		'WiFi modules')
			if Wifi_Modules_Enabled
			then
				/boot/dietpi/func/dietpi-set_hardware wifimodules disable
				[[ $(dpkg-query -s 'iw' 'wpasupplicant' 'wireless-regdb' 2> /dev/null) ]] || return 0
				G_WHIP_BUTTON_CANCEL_TEXT='Skip' G_WHIP_YESNO 'Would you like to purge all WiFi related APT packages?\n\nAffected packages: iw wpasupplicant wireless-regdb' && G_AGP 'iw' 'wpasupplicant' 'wireless-regdb'
			else
				/boot/dietpi/func/dietpi-set_hardware wifimodules enable
			fi
		;;
		'Onboard WiFi')
			if Onboard_Wifi_Enabled
			then
				/boot/dietpi/func/dietpi-set_hardware wifimodules onboard_disable
			else
				/boot/dietpi/func/dietpi-set_hardware wifimodules onboard_enable
			fi
		;;
		'IPv6') /boot/dietpi/func/dietpi-set_hardware enableipv6 $(( ! $ipv6_enabled ));;
		'Proxy') NEXT_MENU='proxy';;
		'Test') Menu_Test;;
		*) NEXT_MENU="iface:$G_WHIP_RETURNED_VALUE";;
	esac
}

Menu_Test()
{
	G_WHIP_DEFAULT_ITEM=$INTERNET_TEST_URL
	G_WHIP_INPUTBOX 'Please enter a URL address to test, e.g.: https://dietpi.com' || return 0
	INTERNET_TEST_URL=$G_WHIP_RETURNED_VALUE
	if G_EXEC_NOHALT=1 G_CHECK_URL "$INTERNET_TEST_URL"
	then
		INTERNET_TEST_STATE=2
	else
		INTERNET_TEST_STATE=1
	fi
}

Menu_Proxy()
{
	Load_Proxy_Vars
	local state_text='Off'
	(( $PROXY_ENABLED )) && state_text='On'
	G_WHIP_MENU_ARRAY=(
		'State' ": [$state_text]"
		'Address' ": [$PROXY_ADDRESS]"
		'Port' ": [$PROXY_PORT]"
		'Username' ": [$PROXY_USERNAME]"
		'Password' ": [$PROXY_PASSWORD]"
	)
	G_WHIP_MENU 'Please select an option to adjust. Logout and login for changes to take effect.' || { Return_From_Submenu 'proxy'; return 0; }
	case $G_WHIP_RETURNED_VALUE in
		'State') (( $PROXY_ENABLED )) && PROXY_ENABLED=0 || PROXY_ENABLED=1;;
		'Address') G_WHIP_DEFAULT_ITEM=$PROXY_ADDRESS; G_WHIP_INPUTBOX 'Please enter the proxy URL or IP address\n - eg: MyProxy.com' && PROXY_ADDRESS=$G_WHIP_RETURNED_VALUE || return 0;;
		'Port') G_WHIP_DEFAULT_ITEM=$PROXY_PORT; G_WHIP_INPUTBOX 'Please enter the proxy port number\n - eg: 1234' && PROXY_PORT=$G_WHIP_RETURNED_VALUE || return 0;;
		'Username') G_WHIP_DEFAULT_ITEM=$PROXY_USERNAME; G_WHIP_INPUTBOX_REGEX='.*' G_WHIP_INPUTBOX 'Please enter the proxy username\n - Leave blank if not required' && PROXY_USERNAME=$G_WHIP_RETURNED_VALUE || return 0;;
		'Password') G_WHIP_DEFAULT_ITEM=$PROXY_PASSWORD; G_WHIP_INPUTBOX_REGEX='.*' G_WHIP_INPUTBOX 'Please enter the proxy password\n - Leave blank if not required' && PROXY_PASSWORD=$G_WHIP_RETURNED_VALUE || return 0;;
		*) :;;
	esac
	Apply_Proxy_Settings
}

Menu_Interface()
{
	local iface=$1
	[[ -d /sys/class/net/$iface ]] || { G_WHIP_MSG "Network interface '$iface' was not detected."; Return_From_Submenu "iface:$iface"; return 0; }
	Load_Interface_State "$iface"
	Net_Update_UsageStats "$iface"
	local title=$(Interface_Menu_Title)
	if [[ $CURRENT_IFACE_TYPE == 'eth' ]]
	then
		local speed='auto (default)'
		[[ -f '/etc/systemd/system/ethtool_force_speed.service' ]] && grep -q "^WantedBy=ifup@$iface.service" /etc/systemd/system/ethtool_force_speed.service && speed=$(mawk '/^ExecStart=/{print $5;exit}' /etc/systemd/system/ethtool_force_speed.service)
		G_WHIP_MENU_ARRAY=(
			'' '●─ DHCP/STATIC IP '
			'Change Mode' ": [${CURRENT_IFACE_MODE^^}]"
		)
		[[ $CURRENT_IFACE_MODE == 'static' ]] && G_WHIP_MENU_ARRAY+=(
			'Copy' ': Copy current address to static'
			'Static IP' ": [$CURRENT_IFACE_IP_STATIC]"
			'Static Gateway' ": [$CURRENT_IFACE_GATEWAY_STATIC]"
			'Static DNS' ": [$CURRENT_IFACE_DNS_STATIC]"
		)
		G_WHIP_MENU_ARRAY+=(
			'' '●─ Additional Options '
			'Link Speed' ": [$speed]"
			'Boot Mode' ": [${CURRENT_IFACE_BOOT_MODE#allow-}]"
			'' '●─ Toggle State '
			'Disable' ': Disable Ethernet adapter'
			'Remove' ': Remove this Ethernet adapter'\''s configuration entirely'
			'' '●─ Apply '
			'Apply' ': Save all changes and restart this interface'
		)
		G_WHIP_MENU "${title}\nUsage   : Sent = $NET_TX_MB | Received = $NET_RX_MB\nAddress : $CURRENT_IFACE_IP | Gateway: $CURRENT_IFACE_GATEWAY | DNS: $DNS_CURRENT" || { Return_From_Submenu "iface:$iface"; return 0; }
		case $G_WHIP_RETURNED_VALUE in
			'Change Mode') [[ $CURRENT_IFACE_MODE == 'dhcp' ]] && CURRENT_IFACE_MODE='static' || CURRENT_IFACE_MODE='dhcp';;
			'Copy') Copy_Current_To_Static;;
			'Static IP') Change_StaticIp;;
			'Static Gateway') Change_StaticGateway;;
			'Static DNS') Change_StaticDns;;
			'Link Speed')
				G_AG_CHECK_INSTALL_PREREQ ethtool
				ip l s "$iface" up # enable link, sometimes needed for ethtool to fetch data
				G_WHIP_MENU_ARRAY=('0' ': Auto-negotiation (default, recommended)')
				while read -r item
				do
					item=${item//[^0-9]}
					[[ $item ]] && G_WHIP_MENU_ARRAY+=("$item" ": Force $item Mbit link speed")
				done < <(ethtool "$iface" | sed -n '/Supported link modes:/,/^[[:blank:]]*[[:alpha:]]/p' | head -n -1 | mawk '{print $NF}')
				if (( ${#G_WHIP_MENU_ARRAY[@]} > 2 ))
				then
					G_WHIP_MENU 'Please select a supported Ethernet link speed to force or auto-negotiation:' || return 0
				else
					G_WHIP_MENU_ARRAY+=(
						10 ': Force 10 Mbit link speed'
						100 ': Force 100 Mbit link speed'
						1000 ': Force 1000 Mbit link speed'
						2500 ': Force 2500 Mbit link speed'
					)
					G_WHIP_MENU 'WARNING: Supported link speeds for this adapter could not be obtained. Forcing an unsupported link speed might break connctivity.
\nPlease select an Ethernet link speed to force or auto-negotiation:'
				fi
				/boot/dietpi/func/dietpi-set_hardware eth-forcespeed "$G_WHIP_RETURNED_VALUE" "$iface"
			;;
			'Boot Mode') Change_BootMode;;
			'Disable') G_WHIP_YESNO 'Would you like to disable this Ethernet adapter?' && CURRENT_IFACE_ENABLED=0 && Apply_Current_Interface 1 && Return_From_Submenu "iface:$iface";;
			'Remove') G_WHIP_YESNO 'Would you like to remove this Ethernet adapter'\''s configuration entirely?\n\nUnlike "Disable", this removes the DietPi drop-in config file, so the interface can be freshly reconfigured later.' && { Remove_Interface_Config "$iface"; Return_From_Submenu "iface:$iface"; };;
			'Apply') G_WHIP_YESNO 'Apply settings and reconnect this Ethernet interface now?' && Apply_Current_Interface 1;;
			*) :;;
		esac
	else
		local description="${title}\nUsage   : Sent = $NET_TX_MB | Received = $NET_RX_MB\n"
		G_WHIP_MENU_ARRAY=('' '●─ Basic Options ')
		if (( $CURRENT_IFACE_HOTSPOT ))
		then
			local status='Offline' hotspot_state_text='[Off] | Select to turn on hotspot'
			(( $CURRENT_IFACE_HOTSPOT_ACTIVE )) && status='Online' hotspot_state_text='[On] | Select to turn off hotspot'
			description+="Status  : $status"
			local hotspot_n_text='Off' hotspot_ac_text='Off' hotspot_ax_text='Off' hotspot_freq_text='2.4' hotspot_channel_text=$HOTSPOT_CHANNEL
			(( $HOTSPOT_WIFI4 )) && hotspot_n_text='On'
			(( $HOTSPOT_WIFI5 )) && hotspot_ac_text='On'
			(( $HOTSPOT_WIFI6 )) && hotspot_ax_text='On'
			if (( $HOTSPOT_5G ))
			then
				hotspot_freq_text='5'
				hotspot_channel_text=$HOTSPOT_5G_CHANNEL
			fi
			G_WHIP_MENU_ARRAY+=(
				'SSID' ": [$HOTSPOT_SSID]"
				'Key' ": [$HOTSPOT_KEY]"
				'Frequency' ": [$hotspot_freq_text GHz]"
				'Channel' ": [$hotspot_channel_text]"
				'802.11n' ": [$hotspot_n_text] WiFi 4 support"
				'802.11ac' ": [$hotspot_ac_text] WiFi 5 support"
				'802.11ax' ": [$hotspot_ax_text] WiFi 6 support"
			)
		else
			local reconnect_text='Off'
			(( $CURRENT_IFACE_WIFI_AUTO_RECONNECT )) && reconnect_text='On'
			description+="SSID    : $CURRENT_IFACE_WIFI_SSID | $CURRENT_IFACE_WIFI_BITRATE Mbit | Strength: $CURRENT_IFACE_WIFI_SIGNAL\nAddress : $CURRENT_IFACE_IP | Gateway: $CURRENT_IFACE_GATEWAY | DNS: $DNS_CURRENT"
			G_WHIP_MENU_ARRAY+=(
				'Scan' ': Scan and configure SSIDs'
				'' '●─ DHCP/STATIC IP '
				'Change Mode' ": [${CURRENT_IFACE_MODE^^}]"
			)
			[[ $CURRENT_IFACE_MODE == 'static' ]] && G_WHIP_MENU_ARRAY+=(
				'Copy' ': Copy current address to static'
				'Static IP' ": [$CURRENT_IFACE_IP_STATIC]"
				'Static Gateway' ": [$CURRENT_IFACE_GATEWAY_STATIC]"
				'Static DNS' ": [$CURRENT_IFACE_DNS_STATIC]"
			)
		fi
		G_WHIP_MENU_ARRAY+=(
			'' '●─ Additional Options '
			'Country' ": [$CURRENT_WIFI_COUNTRYCODE]"
			'Auto Reconnect' ": [$reconnect_text]"
			'Boot Mode' ": [${CURRENT_IFACE_BOOT_MODE#allow-}]"
			'' '●─ Toggle State '
		)
		if (( $CURRENT_IFACE_HOTSPOT ))
		then
			G_WHIP_MENU_ARRAY+=(
				'State' ": $hotspot_state_text"
				'Uninstall' ': Uninstall WiFi Hotspot via dietpi-software'
			)
		else
			G_WHIP_MENU_ARRAY+=(
				'Disable' ': Disable WiFi adapter'
				'Remove' ': Remove this WiFi adapter'\''s configuration entirely'
			)
		fi
		G_WHIP_MENU_ARRAY+=(
			'' '●─ Apply '
			'Apply' ': Save all changes and restart this interface'
		)
		G_WHIP_MENU "$description" || { Return_From_Submenu "iface:$iface"; return 0; }
		case $G_WHIP_RETURNED_VALUE in
			'Scan') /boot/dietpi/func/dietpi-wifidb -i "$iface";;
			'Change Mode') [[ $CURRENT_IFACE_MODE == 'dhcp' ]] && CURRENT_IFACE_MODE='static' || CURRENT_IFACE_MODE='dhcp'; [[ $CURRENT_IFACE_MODE == 'static' ]] && G_WHIP_MSG 'When using STATIC IP, please ensure only one SSID entry exists in the scan menu.';;
			'Copy') Copy_Current_To_Static;;
			'Static IP') Change_StaticIp;;
			'Static Gateway') Change_StaticGateway;;
			'Static DNS') Change_StaticDns;;
			'Country') Change_WifiCountryCode;;
			'Auto Reconnect')
				if (( $CURRENT_IFACE_WIFI_AUTO_RECONNECT ))
				then
					G_EXEC systemctl disable --now dietpi-wifi-monitor
				else
					G_EXEC systemctl enable --now dietpi-wifi-monitor
				fi
			;;
			'Boot Mode') Change_BootMode;;
			'Disable') G_WHIP_YESNO 'Would you like to disable this WiFi adapter?' && CURRENT_IFACE_ENABLED=0 && G_EXEC systemctl disable --now dietpi-wifi-monitor && Apply_Current_Interface 1 && Return_From_Submenu "iface:$iface";;
			'Remove') G_WHIP_YESNO 'Would you like to remove this WiFi adapter'\''s configuration entirely?\n\nUnlike "Disable", this removes the DietPi drop-in config file, so the interface can be freshly reconfigured later.' && { G_EXEC_NOEXIT=1 G_EXEC systemctl disable --now dietpi-wifi-monitor; Remove_Interface_Config"$iface"; Return_From_Submenu "iface:$iface"; };;
			'Apply')
				if (( $CURRENT_IFACE_HOTSPOT ))
				then
					Apply_Current_Interface 1
				else
					G_WHIP_YESNO 'WiFi will connect to the strongest configured SSID that is secure. Save all changes and restart this WiFi interface now?' && Apply_Current_Interface 1
				fi
			;;
			'SSID') G_WHIP_DEFAULT_ITEM=$HOTSPOT_SSID; G_WHIP_INPUTBOX 'Please enter an SSID for your WiFi hotspot:' && HOTSPOT_SSID=$G_WHIP_RETURNED_VALUE;;
			'Key')
				G_WHIP_INPUTBOX_REGEX='.{8}'
				G_WHIP_INPUTBOX_REGEX_TEXT='at least 8 characters long'
				G_WHIP_DEFAULT_ITEM=$HOTSPOT_KEY
				G_WHIP_INPUTBOX 'Please enter a key/password with a minimum of 8 characters for your WiFi hotspot:' || return 0
				HOTSPOT_KEY=$G_WHIP_RETURNED_VALUE
			;;
			'Frequency') HOTSPOT_5G=$(( ! $HOTSPOT_5G )); (( $HOTSPOT_5G && ! $HOTSPOT_WIFI5 && ! $HOTSPOT_WIFI6 )) && HOTSPOT_WIFI4=1;;
			'Channel')
				if (( $HOTSPOT_5G ))
				then
					G_WHIP_DEFAULT_ITEM=$HOTSPOT_5G_CHANNEL
					G_WHIP_INPUTBOX 'Please enter a 5 GHz WiFi channel for your hotspot:' && HOTSPOT_5G_CHANNEL=$G_WHIP_RETURNED_VALUE
				else
					local channel_mhz=2412
					G_WHIP_MENU_ARRAY=()
					for ((i=1; i<=13; i++))
					do
						G_WHIP_MENU_ARRAY+=("$i" ": $channel_mhz MHz")
						((channel_mhz+=5))
					done
					G_WHIP_DEFAULT_ITEM=$HOTSPOT_CHANNEL
					G_WHIP_MENU 'Please select a 2.4 GHz WiFi channel for your hotspot:' && HOTSPOT_CHANNEL=$G_WHIP_RETURNED_VALUE
				fi
			;;
			'802.11n') HOTSPOT_WIFI4=$(( ! $HOTSPOT_WIFI4 )); (( $HOTSPOT_WIFI4 || $HOTSPOT_WIFI5 || $HOTSPOT_WIFI6 )) || HOTSPOT_5G=0;;
			'802.11ac') HOTSPOT_WIFI5=$(( ! $HOTSPOT_WIFI5 )); (( $HOTSPOT_WIFI5 )) && HOTSPOT_5G=1; (( $HOTSPOT_WIFI4 || $HOTSPOT_WIFI5 || $HOTSPOT_WIFI6 )) || HOTSPOT_5G=0;;
			'802.11ax') HOTSPOT_WIFI6=$(( ! $HOTSPOT_WIFI6 )); (( $HOTSPOT_WIFI4 || $HOTSPOT_WIFI5 || $HOTSPOT_WIFI6 )) || HOTSPOT_5G=0;;
			'State')
				if (( $CURRENT_IFACE_HOTSPOT_ACTIVE ))
				then
					G_EXEC systemctl stop hostapd
				else
					G_EXEC systemctl start hostapd
				fi
			;;
			'Uninstall') G_WHIP_YESNO 'Would you like to uninstall the WiFi Hotspot via dietpi-software?' && { export G_INIT_ALLOW_CONCURRENT=1; /boot/dietpi/dietpi-software uninstall 60 61; unset -v G_INIT_ALLOW_CONCURRENT; Return_From_Submenu "iface:$iface"; };;
			*) :;;
		esac
	fi
}

Input()
{
	while (( $# ))
	do
		case $1 in
			'main') COMMAND='menu'; NEXT_MENU='main';;
			'country') COMMAND='menu' NEXT_MENU='country';;
			'proxy')
				if (( $# == 1 ))
				then
					COMMAND='menu'
					NEXT_MENU='proxy'
				else
					COMMAND='proxy'
					shift
					ACTION_VALUE=$1
					shift
					ACTION_EXTRA=$1
				fi
			;;
			'apply')
				COMMAND='apply'
				shift
				APPLY_IFACE=$1
				[[ $APPLY_IFACE ]] || Error "Missing interface name for 'apply'.$USAGE"
			;;
			'remove')
				COMMAND='remove'
				shift
				ACTION_VALUE=$1
				[[ $ACTION_VALUE ]] || Error "Missing interface name for 'remove'.$USAGE"
			;;
			'--enable') APPLY_ENABLE=1;;
			'--disable') APPLY_ENABLE=0;;
			'--dhcp') APPLY_MODE='dhcp';;
			'--static') APPLY_MODE='static';;
			'--ip') shift; APPLY_IP=$1;;
			'--gateway') shift; APPLY_GATEWAY=$1;;
			'--dns') shift; APPLY_DNS=$1;;
			'--copy-current') APPLY_COPY_CURRENT=1;;
			'--hotplug') APPLY_BOOT_MODE='hotplug';;
			'--auto') APPLY_BOOT_MODE='auto';;
			'--client') APPLY_ROLE='client';;
			'--hotspot') APPLY_ROLE='hotspot';;
			'--ssid') shift; APPLY_SSID=$1;;
			'--key') shift; APPLY_KEY=$1;;
			'--freq') shift; APPLY_FREQ=$1;;
			'--channel') shift; APPLY_CHANNEL=$1;;
			'--wifi4') shift; APPLY_WIFI4=$1;;
			'--wifi5') shift; APPLY_WIFI5=$1;;
			'--wifi6') shift; APPLY_WIFI6=$1;;
			'--no-restart') APPLY_RESTART=0;;
			'--force') APPLY_FORCE=1;;
			'-h'|'--help'|'help') echo "$USAGE"; exit 0;;
			*)
				if [[ $COMMAND == 'menu' && $NEXT_MENU == 'main' ]]
				then
					NEXT_MENU="iface:$1"
				else
					Error "Invalid input ($1). Aborting ...$USAGE"
				fi
			;;
		esac
		shift
	done
}

Apply_From_CLI()
{
	[[ $APPLY_IFACE ]] || Error "Missing interface name for 'apply'.$USAGE"
	(( $APPLY_FORCE )) || [[ -d /sys/class/net/$APPLY_IFACE ]] || Error "Network interface '$APPLY_IFACE' was not detected."
	Load_Interface_State "$APPLY_IFACE"
	[[ $APPLY_ENABLE ]] && CURRENT_IFACE_ENABLED=$APPLY_ENABLE
	[[ $APPLY_MODE ]] && CURRENT_IFACE_MODE=$APPLY_MODE
	[[ $APPLY_BOOT_MODE ]] && CURRENT_IFACE_BOOT_MODE=$APPLY_BOOT_MODE
	(( $APPLY_COPY_CURRENT )) && Copy_Current_To_Static
	if [[ $APPLY_IP ]]
	then
		CURRENT_IFACE_IP_STATIC=$APPLY_IP
		[[ $CURRENT_IFACE_IP_STATIC == */* ]] || CURRENT_IFACE_IP_STATIC+='/24'
	fi
	[[ $APPLY_GATEWAY ]] && CURRENT_IFACE_GATEWAY_STATIC=$APPLY_GATEWAY
	[[ $APPLY_DNS ]] && CURRENT_IFACE_DNS_STATIC=$APPLY_DNS
	if [[ $CURRENT_IFACE_TYPE == 'wifi' && $APPLY_ROLE ]]
	then
		if [[ $APPLY_ROLE == 'hotspot' ]]
		then
			CURRENT_IFACE_HOTSPOT=1
			CURRENT_IFACE_MODE='static'
			[[ $APPLY_IP ]] || CURRENT_IFACE_IP_STATIC='192.168.42.1/24'
			Load_Hotspot_Settings
		else
			CURRENT_IFACE_HOTSPOT=0
		fi
	fi
	[[ $APPLY_SSID ]] && HOTSPOT_SSID=$APPLY_SSID
	[[ $APPLY_KEY ]] && HOTSPOT_KEY=$APPLY_KEY
	if [[ $APPLY_FREQ == '5' ]]
	then
		HOTSPOT_5G=1

	elif [[ $APPLY_FREQ == '2.4' ]]
	then
		HOTSPOT_5G=0
	fi
	if [[ $APPLY_CHANNEL ]]
	then
		if (( $HOTSPOT_5G ))
		then
			HOTSPOT_5G_CHANNEL=$APPLY_CHANNEL
		else
			HOTSPOT_CHANNEL=$APPLY_CHANNEL
		fi
	fi
	[[ $APPLY_WIFI4 == [01] ]] && HOTSPOT_WIFI4=$APPLY_WIFI4
	[[ $APPLY_WIFI5 == [01] ]] && HOTSPOT_WIFI5=$APPLY_WIFI5
	[[ $APPLY_WIFI6 == [01] ]] && HOTSPOT_WIFI6=$APPLY_WIFI6
	Apply_Current_Interface "$APPLY_RESTART" || exit 1
}

Remove_Interface_Config()
{
	local iface=$1
	ifdown --force "$iface" 2> /dev/null
	[[ -f /etc/network/interfaces.d/$iface.conf ]] && G_EXEC rm "/etc/network/interfaces.d/$iface.conf"
	Remove_Interface_From_Main_File "$iface"
	return 0
}

Remove_From_CLI(){ Remove_Interface_Config "$ACTION_VALUE"; }

Proxy_From_CLI()
{
	Load_Proxy_Vars
	case $ACTION_VALUE in
		'enable') PROXY_ENABLED=1;;
		'disable') PROXY_ENABLED=0;;
		'address') PROXY_ADDRESS=$ACTION_EXTRA;;
		'port') PROXY_PORT=$ACTION_EXTRA;;
		'username') PROXY_USERNAME=$ACTION_EXTRA;;
		'password') PROXY_PASSWORD=$ACTION_EXTRA;;
		*) Error "Invalid proxy action ($ACTION_VALUE).$USAGE";;
	esac
	Apply_Proxy_Settings
}

Menu_Loop()
{
	[[ $NEXT_MENU == $ENTRY_MENU ]] && G_WHIP_BUTTON_CANCEL_TEXT='Exit' || G_WHIP_BUTTON_CANCEL_TEXT='Back'
	case $NEXT_MENU in
		'main') PRESERVE_SELECTED_SETTINGS=0; Menu_Main;; # load CURRENT_IFACE_* settings from config files again when entering this menu
		'iface:'*) Menu_Interface "${NEXT_MENU#iface:}"; PRESERVE_SELECTED_SETTINGS=1;; # do not override changed CURRENT_IFACE_* settings from values in config files while in this menu
		'country') Load_Interface_State "${WIFI_INTERFACES[0]:-wlan0}"; Change_WifiCountryCode; return 1;; # called via NEXT_MENU from CLI only
		'proxy') Menu_Proxy;;
		'exit') return 1;;
		*) NEXT_MENU='main';;
	esac
	return 0
}

Input "$@"

case $COMMAND in
	'apply') Apply_From_CLI; exit 0;;
	'remove') Remove_From_CLI; exit 0;;
	'proxy') Proxy_From_CLI; exit 0;;
	'menu') :;;
	*) Error "Unknown command ($COMMAND).$USAGE";;
esac

ENTRY_MENU=$NEXT_MENU
while Menu_Loop; do :; done

exit 0
}
