#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Boot Order Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - filename /DietPi/dietpi/dietpi-boot_order
	#////////////////////////////////////

	#/////////////////////////////////////////////////////////////////////////////////////
	# MENUS
	#/////////////////////////////////////////////////////////////////////////////////////
	WHIP_BACKTITLE='DietPi AutoBoot'
	WHIP_TITLE='------- DietPi - AutoBoot Preference -------'
	CHOICE=0
	OPTION=0
	TARGETMENUID=0

	AUTO_BOOT_INDEX=0

	#TARGETMENUID=0
	Menu_Main(){

		#existing boot flag
		AUTO_BOOT_INDEX=$(cat /DietPi/dietpi/.auto_boot_index)
		
		# 0=Console / 1=Kodi / 2=DesktopLXDE / 3=RetroPie / 4=OpenTyrian
		declare -a option_name=(
		"Console"
		"Kodi"
		"Desktop(LXDE)"
		"RetroPie"
		"OpenTyrian"
		"DietPi-Cloudshell"
		)

		current_boot="${option_name[$AUTO_BOOT_INDEX]}"

		OPTION=$(whiptail --title "$WHIP_TITLE" --menu " Current AutoBoot Option: $current_boot" --cancel-button "Back" --backtitle "$WHIP_BACKTITLE" --default-item "$AUTO_BOOT_INDEX" 14 50 5 \
		"0" "${option_name[0]}" \
		"1" "${option_name[1]}" \
		"2" "${option_name[2]}" \
		"3" "${option_name[3]}" \
		"4" "${option_name[4]}" \
		"5" "${option_name[5]}" 3>&1 1>&2 2>&3)

		CHOICE=$?
		if (( $CHOICE == 0 )); then
		
			#Apply Selected boot option
			AUTO_BOOT_INDEX=$OPTION
			
			#Set new Index Trigger
			echo -e "$AUTO_BOOT_INDEX" > /DietPi/dietpi/.auto_boot_index
			
			#Use auto login
			if (( $AUTO_BOOT_INDEX > 0 )); then
				cp /DietPi/dietpi/conf/inittab_desktop /etc/inittab	
				sed -i '/exec \/sbin\/getty -8 38400 tty1/c\exec \/sbin\/getty -8 38400 tty1 -a root' /etc/init/tty1.conf
			else
				#Reset to Server
				cp /DietPi/dietpi/conf/inittab_server /etc/inittab
				sed -i '/exec \/sbin\/getty -8 38400 tty1/c\exec \/sbin\/getty -8 38400 tty1' /etc/init/tty1.conf
			fi
		else
			#Exit
			TARGETMENUID=-1
		fi
		
		#delete[] arrays
		unset option_name
	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#Start Menu
	while (( $TARGETMENUID > -1 )); do

		#Clear Screen buffer
		clear
		
		if (( $TARGETMENUID == 0 )); then
			Menu_Main
		fi
	done

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}