#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Boot Order Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - filename /DietPi/dietpi/dietpi-boot_order
	#
	# Usage:
	# - dietpi-boot_order   (menu system)
	# - dietpi-boot_order int (set value only)
	#////////////////////////////////////
	
	#Grab Input (valid interger)
	INPUT=-1
	if [[ $1 =~ ^-?[0-9]+$ ]]; then
		INPUT=$1
	fi
	
	DISTRO=$(sed -n 3p /DietPi/dietpi/.hw_model)

	#/////////////////////////////////////////////////////////////////////////////////////
	# MENUS
	#/////////////////////////////////////////////////////////////////////////////////////
	WHIP_BACKTITLE='DietPi AutoBoot'
	WHIP_TITLE='------- DietPi - AutoBoot Preference -------'
	CHOICE=0
	OPTION=0
	TARGETMENUID=0

	AUTO_BOOT_INDEX=0

	Apply_Boot_Index(){

		#Save boot index.
		echo -e "$AUTO_BOOT_INDEX" > /DietPi/dietpi/.auto_boot_index
		
		#Enable auto login
		if (( $AUTO_BOOT_INDEX > 0 )); then

			#Deb wheezy
			if (( $DISTRO == 1 )); then
				cp /DietPi/dietpi/conf/inittab_desktop /etc/inittab
			#U 14.04
			elif (( $DISTRO == 2 )); then
				sed -i '/exec \/sbin\/getty -8 38400 tty1/c\exec \/sbin\/getty -8 38400 tty1 -a root' /etc/init/tty1.conf
			fi

		#Disable auto login
		else

			#Deb wheezy
			if (( $DISTRO == 1 )); then
				cp /DietPi/dietpi/conf/inittab_server /etc/inittab
			#U 14.04
			elif (( $DISTRO == 2 )); then
				sed -i '/exec \/sbin\/getty -8 38400 tty1/c\exec \/sbin\/getty -8 38400 tty1' /etc/init/tty1.conf
			fi

		fi
	}
	
	#TARGETMENUID=0
	Menu_Main(){

		#existing boot flag
		AUTO_BOOT_INDEX=$(cat /DietPi/dietpi/.auto_boot_index)
		
		# 0=Console / 1=Kodi / 2=DesktopLXDE / 3=RetroPie / 4=OpenTyrian
		declare -a option_name=(
		"Console"
		"Kodi"
		"Desktop(LXDE)"
		"RetroPie"
		"OpenTyrian"
		"DietPi-Cloudshell"
		)

		current_boot="${option_name[$AUTO_BOOT_INDEX]}"

		OPTION=$(whiptail --title "$WHIP_TITLE" --menu " Current AutoBoot Option: $current_boot" --cancel-button "Back" --backtitle "$WHIP_BACKTITLE" --default-item "$AUTO_BOOT_INDEX" 14 50 6 \
		"0" "${option_name[0]}" \
		"1" "${option_name[1]}" \
		"2" "${option_name[2]}" \
		"3" "${option_name[3]}" \
		"4" "${option_name[4]}" \
		"5" "${option_name[5]}" 3>&1 1>&2 2>&3)

		CHOICE=$?
		if (( $CHOICE == 0 )); then
		
			#Apply Selected boot option
			AUTO_BOOT_INDEX=$OPTION

			Apply_Boot_Index

		else
			#Exit
			TARGETMENUID=-1
		fi
		
		#delete[] arrays
		unset option_name
	}

	
	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#Start Menu
	if (( $INPUT == -1 )); then

		while (( $TARGETMENUID > -1 )); do

			#Clear Screen buffer
			clear
			
			if (( $TARGETMENUID == 0 )); then
				Menu_Main
			fi
		done

	#Apply boot index
	elif (( $INPUT > -1 )); then

		AUTO_BOOT_INDEX=$INPUT
		Apply_Boot_Index

	fi

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}