#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Stress Test
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Tests system stability.
	#	Runs a 100% cpu thread for each core
	#	Reads from SD card
	#	Writes to /tmp (ram)
	#
	# Usage:
	#////////////////////////////////////
	
	FP_TEMP="/tmp/.dietpi-stress_test"
	
	Run_Stress(){
		for ((i=0; i<$(nproc); i++))
		do
			nice yes > /dev/null &
		done
		dd if=/dev/mmcblk0 of=/dev/null bs=4M &
		
		#while true do
		dd if=/dev/null of="$FP_TEMP" bs 4M count=1
		rm "$FP_TEMP"
		#done
	
	}
	
	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////

	Run_Stress &
	
	#stress running
	while running
		#Print CPU info
		/DietPi/dietpi/dietpi-cpu_info
		#-----------------------------------------------------------------------------------
		#Print
		echo -e ""
		echo -e " \e[38;5;93m─────────────────────────────────────────────────────\e[0m\n \e[1mDietPi Stress Test\e[0m\n\e[38;5;93m─────────────────────────────────────────────────────\e[0m"

		sleep 1
	done
	
	
	#destroy
	killall yes
	killall dd
	rm "$FP_TEMP"	


	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}