#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Cloudshell
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - TBA
	#////////////////////////////////////
	
	#Update screen
	RUN_UPDATE=1
	
	#Screen modes
	SCREEN_MODE=0
	
	#Refresh (seconds)
	REFRESH_RATE=5
	
	#Settings file location
	FILEPATH_SETTINGS="/DietPi/dietpi/.dietpi-cloudshell"
	if [ ! -f "$FILEPATH_SETTINGS" ]; then
		#generate new file
		echo -e "generate file"
	fi
	
	
	#/////////////////////////////////////////////////////////////////////////////////////
	# Update Screens
	#/////////////////////////////////////////////////////////////////////////////////////
	Update_Screen_0(){
		clear
		echo -e "Test 0"
	}

	Update_Screen_1(){
		echo -e "Test 1"
	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# MAIN
	#/////////////////////////////////////////////////////////////////////////////////////
	
	#Print to another tty
	#clear > /dev/tty0
	#echo -e '1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15' > /dev/tty0
	
	#-----------------------------------------------------------------------------------
	#Init
	#prevent sleep
	setterm -blank 0 -powersave off

	#set font
	setfont Lat15-Fixed18

	#-----------------------------------------------------------------------------------
	#Loop
	while (( $RUN_UPDATE == 1 )); do
		
		if (( $SCREEN_MODE == 0 )); then
			Update_Screen_0
		elif (( $SCREEN_MODE == 1 )); then
			Update_Screen_1
		fi
	
		sleep $REFRESH_RATE
	done

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}