#!/bin/bash
{
	#////////////////////////////////////
	# DietPi RAMLOG Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - NB: requires /etc/fstab mounting /var/log as tmpfs (Ram)
	# - Saves /var/log directory structure and filenames during shutdown to "$FILEPATH_X_LIST"
	# - Loads and generates /var/log directory structure and filenames during boot from "$FILEPATH_X_LIST"
	#
	# Usage:
	# - Called from /DietPi/dietpi/conf/dietpi-service
	# - /DietPi/dietpi/dietpi-ramlog 0				= Startup Phase (loads /var/log structure)
	# - /DietPi/dietpi/dietpi-ramlog 1				= Shutdown Phase (saves /var/log structure)
	#////////////////////////////////////

	INPUT=0

	if [[ $1 =~ ^-?[0-9]+$ ]]; then
		INPUT=$1
	fi

	FILEPATH_DIRECTORY_LIST='/DietPi/dietpi/.dietpi-ramlog_logfile_dir'
	FILEPATH_FILE_LIST='/DietPi/dietpi/.dietpi-ramlog_logfile_name'

	#/////////////////////////////////////////////////////////////////////////////////////
	#Funcs
	#/////////////////////////////////////////////////////////////////////////////////////
	Apply_Unique_Logfile_Permissions(){

		# - Pihole (www-data user:group)
		chown www-data:www-data /var/log/pihole.log &> /dev/null
		chown -R mongodb:mongodb /var/log/mongodb &> /dev/null

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	#Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#Startup Phase (loads /var/log directory structure and filenames)
	if (( $INPUT == 0 )); then

		echo -e "DietPi-Ramlog: Starting"

		#Load existing dir structure from a previous shutdown
		if [ -f "$FILEPATH_DIRECTORY_LIST" ]; then
			while read line
			do
				mkdir -p "$line" &> /dev/null
				echo -e "$line generated"
			done < "$FILEPATH_DIRECTORY_LIST"

			rm "$FILEPATH_DIRECTORY_LIST"

		#Create a default dir structure
		else
			mkdir -p /var/log/apt &> /dev/null
			mkdir -p /var/log/fsck &> /dev/null
			mkdir -p /var/log/news &> /dev/null
			mkdir -p /var/log/samba &> /dev/null
			mkdir -p /var/log/ntpstats &> /dev/null

		fi

		#Load existing filenames from a previous shutdown. Generate blank file.
		if [ -f "$FILEPATH_FILE_LIST" ]; then
			while read line
			do
				#Do not generate blank file if it already exists.
				# - This prevents non-DietPi-Ramlog modes (none/full) from clearing contents.
				if [ ! -f "$line" ]; then
					echo -e "" > "$line" &> /dev/null
					echo -e "$line generated"
				fi

			done < "$FILEPATH_FILE_LIST"

			rm "$FILEPATH_FILE_LIST"
		fi

		#Set permissions for /var/log directory
		chmod -R 775 /var/log

		#Apply any unique permission for software based log files.
		Apply_Unique_Logfile_Permissions

		echo -e "DietPi-Ramlog: Completed"

	#Shutdown Phase (saves /var/log directory structure and filenames)
	elif (( $INPUT == 1 )); then

		echo -e "DietPi-Ramlog: Stopping"

		#Save log directory structure
		find /var/log -type d > "$FILEPATH_DIRECTORY_LIST"
		#Save log file names
		find /var/log -type f > "$FILEPATH_FILE_LIST"

		echo -e "DietPi-Ramlog: Completed"

	fi
	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}