#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Survey Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - http://fuzon.co.uk/phpbb/viewtopic.php?f=8&t=20
	# - Sends DietPi statistics to FTP server (eg: what programs are installed, hardware model)
	# - Allows the DietPi project to focus on areas based on popularity.
	# - No private data is sent. Noone can indentify you.
	# - Runs when user installs software using dietpi-software 
	# 
	# You can opt out of dietpi-survey by running:
	# echo -e "0" > /boot/dietpi/.dietpi-survey
	# echo -e "1" >> /boot/dietpi/.dietpi-survey
	#
	# File Sent format:
	# $SOURCE_FILENAME.txt
	#////////////////////////////////////
	SURVEY_VERSION=2
	SURVEY_SENTCOUNT=1

	UNIQUE_ID="x"
	SEND_DATA=1

	DIETPI_VERSION=$(cat /boot/dietpi/.version)
	HW_MODEL=$(sed -n 1p /boot/dietpi/.hw_model)

	FTP_ADDR="fuzon.co.uk"
	FTP_USER="dietpi-survey"
	FTP_PASS="raspberry13"

	SOURCE_FILENAME="filename"

	Update_FileName_Format(){
		SOURCE_FILENAME="$UNIQUE_ID-$DIETPI_VERSION-$HW_MODEL".txt
	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////

	#Read data from .dietpi-survey file
	if [ -f /boot/dietpi/.dietpi-survey ]; then
		SEND_DATA=$(sed -n 1p /boot/dietpi/.dietpi-survey)
		SURVEY_SENTCOUNT=$(sed -n 2p /boot/dietpi/.dietpi-survey)
	#Create new file
	else
		echo -e "1" >> /boot/dietpi/.dietpi-survey
		echo -e "1" >> /boot/dietpi/.dietpi-survey
	fi

	#Get unique ID by using eth0 mac address
	if (( $(ifconfig | grep -ci -m1 'eth0') == 1 )); then
		UNIQUE_ID=$(ifconfig | grep eth0 | awk '{print $NF}' | sed 's/://g')
	#Get unique ID by using wlan0 mac address
	elif (( $(ifconfig | grep -ci -m1 'wlan0') == 1 )); then
		UNIQUE_ID=$(ifconfig | grep wlan0 | awk '{print $NF}' | sed 's/://g')
	#No Network hardware found, unable to use MAC address as UUID, abort.
	else
		SEND_DATA=0
	fi

	#create file and send over FTP
	if (( $SEND_DATA == 1 )); then
		
		#Grab filename to use
		Update_FileName_Format

		#Generate text file for upload
		cd /boot/dietpi
		
		#START of File -----------------------------------------------------

		echo -e "-------------------------" >> "$SOURCE_FILENAME"
		echo -e "DietPi-Survey V$SURVEY_VERSION" >> "$SOURCE_FILENAME"
		echo -e "-------------------------" >> "$SOURCE_FILENAME"

		echo -e "Upload Count   : $SURVEY_SENTCOUNT" >> "$SOURCE_FILENAME"
		echo -e "DietPi Version : $(cat /boot/dietpi/.version)" >> "$SOURCE_FILENAME"
		echo -e "Hardware Index : $(sed -n 1p /boot/dietpi/.hw_model)" >> "$SOURCE_FILENAME"
		echo -e "Hardware Name  : $(sed -n 2p /boot/dietpi/.hw_model)" >> "$SOURCE_FILENAME"
		echo -e "Distro Index   : $(sed -n 3p /boot/dietpi/.hw_model)" >> "$SOURCE_FILENAME"
		echo -e "Autoboot Index : $(cat /boot/dietpi/.auto_boot_index)" >> "$SOURCE_FILENAME"
		echo -e "Country        : $(curl -s http://whatismycountry.com/ | sed -n 's|.*,\(.*\)</h3>|\1|p')" >> "$SOURCE_FILENAME"
		echo -e "Hostname       : $(cat /etc/hostname)" >> "$SOURCE_FILENAME"
		echo -e "\n" >> "$SOURCE_FILENAME"


		echo -e "-------------------------" >> "$SOURCE_FILENAME"
		echo -e "DietPi-Software Installed" >> "$SOURCE_FILENAME"
		echo -e "-------------------------" >> "$SOURCE_FILENAME"
		cat /boot/dietpi/.installed >> "$SOURCE_FILENAME"
		echo -e "\n" >> "$SOURCE_FILENAME"

		echo -e "-------------------------" >> "$SOURCE_FILENAME"
		echo -e "FileSystem" >> "$SOURCE_FILENAME"
		echo -e "-------------------------" >> "$SOURCE_FILENAME"
		df -h >> "$SOURCE_FILENAME"
		echo -e "\n" >> "$SOURCE_FILENAME"
		
		#END of File -----------------------------------------------------

		/boot/dietpi/func/check_connection 5 2 "http://$FTP_ADDR"
		if (( $? == 0 )); then
			#upload to server
			wput --timeout=10th-4 --tries=1 --waitretry=2 -q -B -u "$SOURCE_FILENAME" ftp://"$FTP_USER":"$FTP_PASS"@"$FTP_ADDR"
			#wput --timeout=10th-4 --tries=1 --waitretry=2 -B -u test ftp://dietpi-survey:raspberry13@fuzon.co.uk
		fi		
		
		#clear generated temp file
		rm "$SOURCE_FILENAME"
		
		#Update .dietpi-survey file
		((SURVEY_SENTCOUNT++))
		rm /boot/dietpi/.dietpi-survey
		echo -e "$SEND_DATA" >> /boot/dietpi/.dietpi-survey
		echo -e "$SURVEY_SENTCOUNT" >> /boot/dietpi/.dietpi-survey
		
		cd ~/
	fi

	#Run whole script in a function. Loads into memory, allows for online file patching.
	exit
}