#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Finalise
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Preps the system for saving an image file, and, setting up for 1st use.
	#////////////////////////////////////

	#/////////////////////////////////////////////////////////////////////////////////////
	#Obtain Pi/Odroid Model
	#/////////////////////////////////////////////////////////////////////////////////////

	/DietPi/dietpi/dietpi-obtain_hw_model

	HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)
	HW_MODEL_DESCRIPTION=$(sed -n 2p /DietPi/dietpi/.hw_model)
	DISTRO=$(sed -n 3p /DietPi/dietpi/.hw_model)

	#////////////////////////////////////
	#Stop services
	/DietPi/dietpi/dietpi-services stop

	#Disable services
	/DietPi/dietpi/dietpi-services disable

	#////////////////////////////////////
	#Unmount Drives
	umount /dev/sda[1-9]

	#////////////////////////////////////
	#Remove Bash History file
	rm ~/.bash_history

	#Nano histroy file
	rm ~/.nano_history

	#////////////////////////////////////
	# Clean Apt + cache
	#Make sure apt-get_update thread is finished
	/DietPi/dietpi/dietpi-apt-get_update 1

	#Remove packages
	apt-get purge openssh-client rsync -y

	#Clear cache
	apt-get clean
	rm /var/lib/apt/lists/* -vf

	#////////////////////////////////////
	#Delete documentation folders
	rm -R /usr/share/man
	rm -R /usr/share/doc
	rm -R /usr/share/doc-base
	#rm -R /usr/share/calendar

	#////////////////////////////////////
	#Remove Swapfile (saves 100mb in final image)
	dphys-swapfile swapoff
	dphys-swapfile uninstall
	rm /var/swap
	rm /mnt/usb_1/.swapfile

	#Set swapsize back to 100mb & /var/swap
	echo -e "CONF_SWAPSIZE=100" > /etc/dphys-swapfile
	echo -e "CONF_SWAPFILE=/var/swap" >> /etc/dphys-swapfile

	# Prevent it from running on next boot (reenabled after filesystem setup)
	sed -i '/\/sbin\/dphys-swapfile setup/c\#\/sbin\/dphys-swapfile setup' /etc/init.d/dphys-swapfile
	sed -i '/\/sbin\/dphys-swapfile swapon/c\#\/sbin\/dphys-swapfile swapon' /etc/init.d/dphys-swapfile

	#////////////////////////////////////
	# Disable Autologin/Autostart
	if (( $DISTRO == 1 )); then
		cp /DietPi/dietpi/conf/inittab_server /etc/inittab

	elif (( $DISTRO == 3 )); then
		rm /etc/systemd/system/getty@tty1.service.d/autologin.conf &> /dev/null
	fi

	#////////////////////////////////////
	#Copy fstab conf
	cp /DietPi/dietpi/conf/fstab /etc/fstab

	#VM
	if (( $HW_MODEL == 20 )); then
		cp /DietPi/dietpi/conf/fstab_vm /etc/fstab
	fi

	#////////////////////////////////////
	#Copy Network Interface conf (auto up is disabled for all adapters)
	cp /DietPi/dietpi/conf/network_interfaces /etc/network/interfaces

	#Set Hostname
	cat << _EOF_ > /etc/hosts
127.0.0.1 localhost
127.0.1.1 DietPi
_EOF_

	cat << _EOF_ > /etc/hostname
DietPi
_EOF_

	#////////////////////////////////////
	#Set Pi cmdline.txt back to normal
	# - Remove root delay
	sed -i "s/ rootdelay=10//g" /boot/cmdline.txt

	#////////////////////////////////////
	# Set Pi Config.txt back to normal
	sed -i '/hdmi_safe=/c\#hdmi_safe=1' /DietPi/config.txt
	sed -i '/hdmi_force_hotplug=/c\#hdmi_force_hotplug=1' /DietPi/config.txt
	sed -i '/hdmi_group=/c\#hdmi_group=1' /DietPi/config.txt
	sed -i '/hdmi_mode=/c\#hdmi_mode=1' /DietPi/config.txt
	sed -i '/hdmi_drive=/c\#hdmi_drive=2' /DietPi/config.txt

	sed -i '/config_hdmi_boost=/c\#config_hdmi_boost=4' /DietPi/config.txt

	sed -i '/disable_overscan=/c\disable_overscan=1' /DietPi/config.txt

	sed -i '/framebuffer_width=/c\framebuffer_width=1280' /DietPi/config.txt
	sed -i '/framebuffer_height=/c\framebuffer_height=720' /DietPi/config.txt

	sed -i '/start_x=/c\start_x=0' /DietPi/config.txt
	sed -i '/disable_camera_led=/c\disable_camera_led=0' /DietPi/config.txt

	sed -i '/max_usb_current=/c\max_usb_current=0' /DietPi/config.txt

	sed -i '/gpu_mem_256=/c\gpu_mem_256=16' /DietPi/config.txt
	sed -i '/gpu_mem_512=/c\gpu_mem_512=16' /DietPi/config.txt
	sed -i '/gpu_mem_1024=/c\gpu_mem_1024=16' /DietPi/config.txt

	/DietPi/dietpi/func/dietpi-rpi_i2c_control -1

	sed -i '/temp_limit=/c\temp_limit=65' /DietPi/config.txt
	sed -i '/initial_turbo=/c\initial_turbo=20' /DietPi/config.txt
	sed -i '/force_turbo=/c\force_turbo=0' /DietPi/config.txt
	sed -i '/over_voltage=/c\#over_voltage=0' /DietPi/config.txt
	sed -i '/arm_freq=/c\#arm_freq=900' /DietPi/config.txt
	sed -i '/core_freq=/c\#core_freq=250' /DietPi/config.txt
	sed -i '/sdram_freq=/c\#sdram_freq=400' /DietPi/config.txt

	sed -i '/arm_freq_min=/c\#arm_freq_min=700' /DietPi/config.txt
	sed -i '/core_freq_min=/c\#core_freq_min=250' /DietPi/config.txt
	sed -i '/sdram_freq_min=/c\#sdram_freq_min=400' /DietPi/config.txt

	#////////////////////////////////////
	# ODROID's - Set boot.ini back to normal
	sed -i '/setenv hdmioutput /c\setenv hdmioutput "1"' /DietPi/boot.ini
	sed -i '/setenv vpu /c\setenv vpu "0"' /DietPi/boot.ini
	sed -i '/setenv m /c\setenv m "720p"' /DietPi/boot.ini
	sed -i '/setenv disableuhs/c\setenv disableuhs "disableuhs"' /DietPi/boot.ini

	#////////////////////////////////////
	# Set dietpi.txt back to normal
	#Network
	sed -i '/^Ethernet_Enabled=/c\Ethernet_Enabled=1' /DietPi/dietpi.txt
	sed -i '/^Wifi_Enabled=/c\Wifi_Enabled=0' /DietPi/dietpi.txt
	sed -i '/^Wifi_SSID=/c\Wifi_SSID=FuzonWifi' /DietPi/dietpi.txt
	sed -i '/^Wifi_KEY=/c\Wifi_KEY=MyAccessKey' /DietPi/dietpi.txt
	sed -i '/^Use_Static=/c\Use_Static=0' /DietPi/dietpi.txt
	sed -i '/^Static_IP=/c\Static_IP=192.168.0.100' /DietPi/dietpi.txt
	sed -i '/^Static_Mask=/c\Static_Mask=255.255.255.0' /DietPi/dietpi.txt
	sed -i '/^Static_Gateway=/c\Static_Gateway=192.168.0.1' /DietPi/dietpi.txt
	sed -i '/^Static_DNS=/c\Static_DNS=8.8.8.8' /DietPi/dietpi.txt

	sed -i '/^Hostname=/c\Hostname=DietPi' /DietPi/dietpi.txt

	#DietPi-Automation
	rm /root/DietPi-Automation.log
	sed -i "/^AUTO_AutoLogin=/c\AUTO_AutoLogin=0" /DietPi/dietpi.txt
	sed -i "/^AUTO_Install_Index=/c\AUTO_Install_Index=0" /DietPi/dietpi.txt

	sed -i "/^AUTO_SkipLicensePrompt=/c\AUTO_SkipLicensePrompt=0" /DietPi/dietpi.txt
	sed -i "/^AUTO_DietpiSoftware_SkipUpdateRebootPrompt=/c\AUTO_DietpiSoftware_SkipUpdateRebootPrompt=0" /DietPi/dietpi.txt
	sed -i "/^AUTO_DietpiSoftware_SkipQuestions=/c\AUTO_DietpiSoftware_SkipQuestions=0" /DietPi/dietpi.txt
	sed -i "/^AUTO_DietpiSoftware_SkipUsbDrive=/c\AUTO_DietpiSoftware_SkipUsbDrive=0" /DietPi/dietpi.txt
	sed -i "/^AUTO_DietpiSoftware_IgnoreErrors=/c\AUTO_DietpiSoftware_IgnoreErrors=0" /DietPi/dietpi.txt

	sed -i "/^AUTO_DietpiSoftware_SSHServerIndex=/c\AUTO_DietpiSoftware_SSHServerIndex=-1" /DietPi/dietpi.txt
	sed -i "/^AUTO_DietpiSoftware_FileServerIndex=/c\AUTO_DietpiSoftware_FileServerIndex=0" /DietPi/dietpi.txt
	sed -i "/^AUTO_DietpiSoftware_LoggingIndex=/c\AUTO_DietpiSoftware_LoggingIndex=-1" /DietPi/dietpi.txt

	sed -i "/^AUTO_AutoStartTarget=/c\AUTO_AutoStartTarget=0" /DietPi/dietpi.txt

	sed -i "/^AUTO_Timezone=/c\AUTO_Timezone=Europe/London" /DietPi/dietpi.txt
	sed -i "/^AUTO_Locale=/c\AUTO_Locale=en_GB" /DietPi/dietpi.txt
	sed -i "/^AUTO_KeyboardLayout=/c\AUTO_KeyboardLayout=gb" /DietPi/dietpi.txt

	sed -i "/^AUTO_CustomScriptURL=/c\AUTO_CustomScriptURL=0" /DietPi/dietpi.txt

	# Development Settings
	sed -i "/^gitbranch=/c\gitbranch=master" /DietPi/dietpi.txt

	#DietPi-Config specific
	sed -i "/^rpi_hdmi_output=/c\rpi_hdmi_output=1" /DietPi/dietpi.txt

	if (( $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors | grep -ci -m1 'ondemand') == 1 )); then
		sed -i "/^cpu_governor=/c\cpu_governor=ondemand" /DietPi/dietpi.txt
	elif (( $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors | grep -ci -m1 'interactive') == 1 )); then
		sed -i "/^cpu_governor=/c\cpu_governor=interactive" /DietPi/dietpi.txt
	else
		sed -i "/^cpu_governor=/c\cpu_governor=performance" /DietPi/dietpi.txt
	fi

	sed -i '/^cpu_usage_throttle_up=/c\cpu_usage_throttle_up=50' /DietPi/dietpi.txt
	sed -i '/^cpu_max_frequency=/c\cpu_max_frequency=0' /DietPi/dietpi.txt

	sed -i "/^cpu_ondemand_sampling_rate=/c\cpu_ondemand_sampling_rate=100000" /DietPi/dietpi.txt
	sed -i "/^cpu_ondemand_sampling_down_factor=/c\cpu_ondemand_sampling_down_factor=20" /DietPi/dietpi.txt

	sed -i '/^SambaClient_ComputerName=/c\SambaClient_ComputerName=computername' /DietPi/dietpi.txt
	sed -i '/^SambaClient_ShareName=/c\SambaClient_ShareName=sharename' /DietPi/dietpi.txt
	sed -i '/^SambaClient_Username=/c\SambaClient_Username=username' /DietPi/dietpi.txt
	sed -i '/^SambaClient_Password=/c\SambaClient_Password=password' /DietPi/dietpi.txt

	sed -i '/^curlftpfs_clientaddress=/c\curlftpfs_clientaddress=192.168.0.100' /DietPi/dietpi.txt
	sed -i '/^curlftpfs_clientusername=/c\curlftpfs_clientusername=username' /DietPi/dietpi.txt
	sed -i '/^curlftpfs_clientpassword=/c\curlftpfs_clientpassword=password' /DietPi/dietpi.txt

	sed -i '/^dietpi_check_for_updates=/c\dietpi_check_for_updates=1' /DietPi/dietpi.txt
	sed -i '/^ntpd_update_mode=/c\ntpd_update_mode=2' /DietPi/dietpi.txt

	/DietPi/dietpi/dietpi-cpu_set

	#////////////////////////////////////
	#Delete all log files
	/DietPi/dietpi/dietpi-logclear 2

	#Clear DietPi-Ramlog storage
	rm -R /etc/dietpi/dietpi-ramlog/storage

	#ntp delete drift file
	rm /var/lib/ntp/ntp.drift

	#////////////////////////////////////
	# Remove/Reset DietPi generated files
	rm /DietPi/dietpi/.*

	#Remove server_version / patch_file (downloads fresh from dietpi-update)
	rm /DietPi/dietpi/patch_file
	rm /DietPi/dietpi/server_version

	#////////////////////////////////////
	#SET DIETPI VERSION CODE
	echo 104 > /DietPi/dietpi/.version

	#Remove backup/sync
	rm -R /mnt/dietpi-backup
	rm -R /mnt/dietpi-sync

	#.dietpi-autostart_index Console
	echo 0 > /DietPi/dietpi/.dietpi-autostart_index

	#Create our update file (used on 1st run to check for DietPi updates)
	echo -1 > /DietPi/dietpi/.update_stage

	#////////////////////////////////////
	#Set Init .install_stage to -3 (first boot)
	echo -3 > /DietPi/dietpi/.install_stage
	# - VM - skip filesystem partition resize
	if (( $HW_MODEL == 20 )); then
		echo -e "-2" > /DietPi/dietpi/.install_stage
	fi

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}