#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Finalise
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Preps the system for saving an image file, and, setting up for 1st use.
	#////////////////////////////////////

	#Force en_GB Locale for whole script. Prevents incorrect parsing with non-english locales.
	LANG=en_GB.UTF-8

	IMAGE_VERSION=115

	#/////////////////////////////////////////////////////////////////////////////////////
	#Obtain Pi/Odroid Model
	#/////////////////////////////////////////////////////////////////////////////////////

	/DietPi/dietpi/dietpi-obtain_hw_model

	HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)
	DISTRO=$(sed -n 3p /DietPi/dietpi/.hw_model)

	#////////////////////////////////////
	#Stop services
	/DietPi/dietpi/dietpi-services stop

	#Disable services
	/DietPi/dietpi/dietpi-services disable

	#////////////////////////////////////
	#Unmount Drives
	umount /dev/sda[1-9]

	#////////////////////////////////////
	#Remove Bash History file
	rm ~/.bash_history

	#Nano histroy file
	rm ~/.nano_history

	#////////////////////////////////////
	# Clean Apt + cache
	#Make sure apt-get_update thread is finished
	/DietPi/dietpi/dietpi-apt-get_update 1

	#Remove packages
	apt-get purge openssh-client openssh-server rsync -y
	apt-get autoremove -y --purge

	#Install dropbear
	apt-get install -y dropbear
	# - set to start on next boot
	sed -i '/NO_START=1/c\NO_START=0' /etc/default/dropbear

	#Clear cache
	apt-get clean
	rm /var/lib/apt/lists/* -vf

	#////////////////////////////////////
	#Delete documentation folders
	rm -R /usr/share/man
	rm -R /usr/share/doc
	rm -R /usr/share/doc-base
	#rm -R /usr/share/calendar

	#////////////////////////////////////
	#Disable/Remove Swapfile (saves 100mb in final image)
	/DietPi/dietpi/func/dietpi-set_dphys-swapfile 0 /var/swap
	# - Reset config
	echo -e "CONF_SWAPSIZE=100" > /etc/dphys-swapfile
	echo -e "CONF_SWAPFILE=/var/swap" >> /etc/dphys-swapfile

	#////////////////////////////////////
	# Disable Autologin/Autostart
	if (( $DISTRO == 1 )); then
		cp /DietPi/dietpi/conf/inittab_server /etc/inittab

	elif (( $DISTRO == 3 )); then
		rm /etc/systemd/system/getty@tty1.service.d/autologin.conf &> /dev/null
	fi

	#////////////////////////////////////
	#Copy fstab conf
	cp /DietPi/dietpi/conf/fstab /etc/fstab

	#VM
	if (( $HW_MODEL == 20 )); then
		cp /DietPi/dietpi/conf/fstab_vm /etc/fstab
	fi

	#////////////////////////////////////
	#Copy Network Interface conf (auto up is disabled for all adapters)
	cp /DietPi/dietpi/conf/network_interfaces /etc/network/interfaces

	#Set Hostname
	cat << _EOF_ > /etc/hosts
127.0.0.1 localhost
127.0.1.1 DietPi
_EOF_

	cat << _EOF_ > /etc/hostname
DietPi
_EOF_

	#////////////////////////////////////
	#Set Pi cmdline.txt back to normal
	# - Remove root delay
	sed -i "s/ rootdelay=10//g" /boot/cmdline.txt

	#////////////////////////////////////
	# Set Pi Config.txt back to normal
	wget https://raw.githubusercontent.com/Fourdee/DietPi/testing/config.txt -O /DietPi/config.txt

	/DietPi/dietpi/func/dietpi-rpi_i2c_control -1

	#////////////////////////////////////
	# ODROID's - Set boot.ini back to normal
	if (( $HW_MODEL == 10 )); then
		wget https://raw.githubusercontent.com/Fourdee/DietPi/testing/boot_c1.ini -O /DietPi/boot.ini
	elif (( $HW_MODEL == 11 )); then
		wget https://raw.githubusercontent.com/Fourdee/DietPi/testing/boot_xu4.ini -O /DietPi/boot.ini
	elif (( $HW_MODEL == 12 )); then
		wget https://raw.githubusercontent.com/Fourdee/DietPi/testing/boot_c2.ini -O /DietPi/boot.ini
	fi

	#////////////////////////////////////
	# Set dietpi.txt back to normal

	wget https://raw.githubusercontent.com/Fourdee/DietPi/testing/dietpi.txt -O /DietPi/dietpi.txt

	#DietPi-Automation
	rm /root/DietPi-Automation.log
	rm /boot/Automation_Format_My_Usb_Drive

	if (( $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors | grep -ci -m1 'ondemand') == 1 )); then
		sed -i "/^cpu_governor=/c\cpu_governor=ondemand" /DietPi/dietpi.txt
	elif (( $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors | grep -ci -m1 'interactive') == 1 )); then
		sed -i "/^cpu_governor=/c\cpu_governor=interactive" /DietPi/dietpi.txt
	else
		sed -i "/^cpu_governor=/c\cpu_governor=performance" /DietPi/dietpi.txt
	fi

	# - C1 | Override default to interactive: https://github.com/Fourdee/DietPi/issues/248
	if (( $HW_MODEL == 10 )); then
		sed -i "/^cpu_governor=/c\cpu_governor=interactive" /DietPi/dietpi.txt
	fi

	/DietPi/dietpi/dietpi-cpu_set

	#////////////////////////////////////
	#Disable soundcards
	/DietPi/dietpi/func/dietpi-set_soundcard none

	#////////////////////////////////////
	#Delete all log files
	/DietPi/dietpi/dietpi-logclear 2

	#Clear DietPi-Ramlog storage
	rm -R /etc/dietpi/dietpi-ramlog/storage

	#ntp delete drift file
	rm /var/lib/ntp/ntp.drift

	#////////////////////////////////////
	# Remove/Reset DietPi generated files
	rm /DietPi/dietpi/.*

	#Remove server_version / patch_file (downloads fresh from dietpi-update)
	rm /DietPi/dietpi/patch_file
	rm /DietPi/dietpi/server_version

	#////////////////////////////////////
	#SET DIETPI VERSION CODE
	echo -e "$IMAGE_VERSION" > /DietPi/dietpi/.version
	echo -e "$IMAGE_VERSION" > /etc/.dietpi_image_version

	#Remove backup/sync
	rm -R /mnt/dietpi-backup
	rm -R /mnt/dietpi-sync

	#.dietpi-autostart_index Console
	echo 0 > /DietPi/dietpi/.dietpi-autostart_index

	#Create our update file (used on 1st run to check for DietPi updates)
	echo -1 > /DietPi/dietpi/.update_stage

	#////////////////////////////////////
	#Set Init .install_stage to -3 (first boot)
	echo -3 > /DietPi/dietpi/.install_stage
	# - VM - skip filesystem partition resize
	if (( $HW_MODEL == 20 )); then
		echo -e "-2" > /DietPi/dietpi/.install_stage
	fi

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}