#!/bin/bash
{
	#////////////////////////////////////
	# DietPi logclear Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	#////////////////////////////////////
	
	TEMP_LOGLIST_FILEPATH="/tmp/logclear_temp"

	LOGGING_MODE=-1
	if [ -f /boot/dietpi/.installed ]; then
		LOGGING_MODE=$(cat /boot/dietpi/.installed | grep 'INDEX_LOGGING_CURRENT ' | awk '{print $2}')
	fi
	
	#////////////////////////////////////
	# Run
	#////////////////////////////////////
	
	#----------------------------------------------------------------
	#MODE 0 = None , do nothing.

	#----------------------------------------------------------------
	#MODE -1 | Clear all logs in /var/log by overwriting them.
	if (( $LOGGING_MODE == -1 )); then

		#Find existing logs and read their filepath into an array
		find /var/log -type f > "$TEMP_LOGLIST_FILEPATH"
		readarray -t ARRAY_LOG_FILEPATH < "$TEMP_LOGLIST_FILEPATH"
		
		#Process Logfiles
		for ((i=0; i<${#ARRAY_LOG_FILEPATH[@]}; i++))
		do
			#Clear log files by overwriting them.
			echo -e "" > "${ARRAY_LOG_FILEPATH[$i]}"

		done
		
		#Remove temp files
		rm "$TEMP_LOGLIST_FILEPATH" &> /dev/null

		#delete[] array
		unset ARRAY_LOG_FILEPATH

	#----------------------------------------------------------------
	#MODE -2 = Add current log files data to /"$HOME"/logbackup/*. Then clear.
	elif (( $LOGGING_MODE == -2 )); then

		#Find existing logs and read their filepath into an array
		find /var/log -type f > "$TEMP_LOGLIST_FILEPATH"
		readarray -t ARRAY_LOG_FILEPATH < "$TEMP_LOGLIST_FILEPATH"
		
		#Process Logfiles
		for ((i=0; i<${#ARRAY_LOG_FILEPATH[@]}; i++))
		do
			#Do we have any data to write? Check size of file.
			if (( $(stat -c%s "${ARRAY_LOG_FILEPATH[$i]}") > 1 )); then
			
				filename=$(echo -e ${ARRAY_LOG_FILEPATH[$i]} | sed 's/\/var\/log\///g')

				#Generate filepaths
				if [ ! -f "$HOME/logfile_storage/$filename" ]; then

					#This is a little "hack" to automatically generate the required subdirectories.
					# EG: /this/is/my/logfile.txt | will create the folders /this/is/my
					mkdir -p "$HOME/logfile_storage/$filename"
					rm -R "$HOME/logfile_storage/$filename"
				fi

				#Write current logfile contents to existing.
				cat "${ARRAY_LOG_FILEPATH[$i]}" >> "$HOME"/logfile_storage/"$filename"
			fi
			
			#Clear log files by overwriting them.
			echo -e "" > "${ARRAY_LOG_FILEPATH[$i]}"

		done

		#Remove temp files
		rm "$TEMP_LOGLIST_FILEPATH" &> /dev/null

		#delete[] array
		unset ARRAY_LOG_FILEPATH
	fi
	#----------------------------------------------------------------
	#MODE -3 = Logrotate, do nothing

	#----------------------------------------------------------------
	exit
	#----------------------------------------------------------------
}