#!/bin/bash
{
	#////////////////////////////////////
	# DietPi logclear Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Deletes all logs in /var/log - recursive
	# - Touches /var/log/ramlog
	#////////////////////////////////////

	#////////////////////////////////////
	# Run
	#////////////////////////////////////
	find /var/log -type f -delete
	touch /var/log/ramlog

	#Run whole script in a function. Loads into memory, allows for online file patching.
	exit
}