#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Login Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - filename /boot/dietpi/login
	# - activates on login /root/.bashrc
	# - requires /boot/dietpi/.install_stage to have a value of 0 for it to run /boot/dietpi/dietpi-software (active after /dietpi/boot has completed filesystem expansion)
	#////////////////////////////////////

	#/////////////////////////////////////////////////////////////////////////////////////
	#Obtain Pi version 1/2 & Obtain Pi Model Description
	#/////////////////////////////////////////////////////////////////////////////////////
	HW_MODEL=$(sed -n 1p /tmp/.hw_model)
	HW_MODEL_DESCRIPTION=$(sed -n 2p /tmp/.hw_model)
	DISTRO=$(sed -n 3p /tmp/.hw_model)

	#/////////////////////////////////////////////////////////////////////////////////////
	#Obtain DietPi unique files data
	#/////////////////////////////////////////////////////////////////////////////////////
	# see /boot/dietpi/boot for info
	DIETPI_INSTALL_STAGE=$(cat /boot/dietpi/.install_stage)

	# 0=console / 1=kodi-standalone / 2=startx lxde / 3=emulationstation
	AUTO_BOOT_INDEX=$(cat /boot/dietpi/.auto_boot_index)

	DIETPI_VERSION=$(cat /tmp/.version)

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	
	# SCP connection exit path. Fix for dumb or unset TERM provided by tdaitx
	export TERM=${TERM:-dumb}
	if [ "$TERM" = "dumb" ]; then
		exit
	fi
	
	#Normal Login
	if (( $DIETPI_INSTALL_STAGE == 1 )); then

		#Boot to specific Program
		if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
			#Kodi
			if (( $AUTO_BOOT_INDEX == 1 )); then
				#Debian
				if (( $DISTRO == 1 )); then
					kodi-standalone
				#Ubuntu
				elif (( $DISTRO == 2 )); then
					xinit kodi-standalone
				fi
			#Desktop LXDE
			elif (( $AUTO_BOOT_INDEX == 2 )); then
				#Debian
				if (( $DISTRO == 1 )); then
					startx
				#Ubuntu
				elif (( $DISTRO == 2 )); then
					startx
				fi
			#RetroPie/Emulation station
			elif (( $AUTO_BOOT_INDEX == 3 )); then
				#emulationstation - can no longer be run as root
				/opt/retropie/supplementary/emulationstation/emulationstation
			#OpenTyrian
			elif (( $AUTO_BOOT_INDEX == 4 )); then
				/usr/local/games/opentyrian/run
			fi
		#console
		else
			/tmp/dietpi-banner 1
		fi
	#Run DietPi-Software (1st run setup)
	elif (( $DIETPI_INSTALL_STAGE == 0 )); then

		#Run GPL compliance prompt
		if (( $(cat /boot/dietpi.txt | grep 'AUTO_SkipLicensePrompt=' | sed 's/AUTO_SkipLicensePrompt=//g') == 0 )); then
			whiptail --title "DietPi - GPLv2 License" --msgbox "This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 2 of the License, or any later version.\n\nThis program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this program.  If not, see http://www.gnu.org/licenses/" --backtitle "DietPi - GPLv2 Compliance" 18 70
		fi

		#Check if DietPi-Software is already running, else run it
		dietpi_software_running=$(ps aux | grep -ci -m1 '/boot/dietpi/[d]ietpi-software')
		if (( $dietpi_software_running == 0 )); then
			#Start DietPi-Software
			/boot/dietpi/dietpi-software
		else
			/tmp/dietpi-banner 0
			echo -e "DietPi-Software is already running. Please complete the setup before continuing."
		fi

	#DietPi finishing up bootloader.
	elif (( $DIETPI_INSTALL_STAGE == -1 )); then
		/tmp/dietpi-banner 0
		echo -e " >> DietPi System prep is nearly completed: \n Please run /boot/dietpi/login after a few seconds"	

	#DietPi running filesystem prep	
	else
		/tmp/dietpi-banner 0
		echo -e " >> Filesystem prep has not yet completed: \n Please wait for the system to reboot "	
	fi

	#Run whole script in a function. Loads into memory, allows for online file patching.
	exit
}
