#!/bin/bash
#////////////////////////////////////
# DietPi Patch File Script
#
#////////////////////////////////////
# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
#
#////////////////////////////////////
#
# Info:
# - Patches version changes to hosts filesystem, where applicable
#////////////////////////////////////

#/////////////////////////////////////////////////////////////////////////////////////
#VERSION CODE
#/////////////////////////////////////////////////////////////////////////////////////
VERSION_CURRENT=$1
VERSION_SERVER=$2

#/////////////////////////////////////////////////////////////////////////////////////
#Obtain Pi/Odroid Model
#/////////////////////////////////////////////////////////////////////////////////////

HW_MODEL=$(sed -n 1p /boot/dietpi/.hw_model)
HW_MODEL_DESCRIPTION=$(sed -n 2p /boot/dietpi/.hw_model)
DISTRO=$(sed -n 3p /boot/dietpi/.hw_model)

#/////////////////////////////////////////////////////////////////////////////////////
# Main Loop
#/////////////////////////////////////////////////////////////////////////////////////
#Info
echo -e "Patching $VERSION_CURRENT to $VERSION_SERVER"

if [ "$VERSION_CURRENT" = 25 ]; then
	echo -e "25 > 26 patch"
	
	rm /boot/dietpi/conf/fstab_odroidc1_ubuntu
	
	#remove ipv6 from proftpd
	if [ -f /etc/proftpd/proftpd.conf ]; then
		sed -i '/UseIPv6/c\UseIPv6 off' /etc/proftpd/proftpd.conf
	fi
	
	#remove php.ini (not used)
	rm /boot/dietpi/conf/php.ini
	rm /boot/dietpi/conf/php-apc.ini
	
elif [ "$VERSION_CURRENT" = 26 ]; then
	echo -e "26 > 27 patch"
	
	#Ubuntu
	if (( $DISTRO == 2 )); then
	
		# Sort out Language
		locale-gen --no-purge --lang en_US.UTF-8
		
		# Set Swappiness
		if (($(cat //etc/sysctl.conf | grep -ci -m1 'vm.swappiness') == 0)); then
			echo -e "vm.swappiness = 1" >> /etc/sysctl.conf
		fi
	fi
elif [ "$VERSION_CURRENT" = 27 ]; then
	echo -e "27 > 28 patch"
fi

sleep 2