#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Patch File Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Online patching for client system.
	# - Runs from dietpi-update
	#
	# Usage:
	# - /DietPi/dietpi/patch_file $G_DIETPI_VERSION_SUB
	#////////////////////////////////////

	INPUT=$1

	#Import DietPi-Globals ---------------------------------------------------------------
	/DietPi/dietpi/func/dietpi-obtain_hw_model # Always update
	. /DietPi/dietpi/func/dietpi-globals
	G_PROGRAM_NAME='DietPi-Patchfile'
	export G_PROMPT_BACKUP_DISABLED=1 # prevent backup user request prompts during patching
	G_INIT
	#Import DietPi-Globals ---------------------------------------------------------------

	#Grab + export input (export is pre v6.14 required)
	export G_DIETPI_VERSION_SUB=$INPUT

	#/////////////////////////////////////////////////////////////////////////////////////
	#Pre-v6.17: Switch to new branch and versioning system
	if (( $G_DIETPI_VERSION_SUB < 17 )) && [[ ! $(sed -n 6p /DietPi/dietpi/.version) ]]; then

		# - Switch from obsolete testing to new dev branch
		BRANCH_INFO=''
		if grep -q '^[[:blank:]]*DEV_GITBRANCH=testing$' /DietPi/dietpi.txt; then

			G_CONFIG_INJECT 'DEV_GITBRANCH=' 'DEV_GITBRANCH=dev' /DietPi/dietpi.txt
			BRANCH_INFO=' branch and'

		fi

		# - Addition of RC version
		G_VERSIONDB_SAVE

		# - As loaded pre-v6.17 dietpi-update will overwrite .version to previous 2 line system, we need to rerun dietpi-update.
		#	- Remove DietPi-Update and DietPi-Patchfile working directories do allow concurrent execution
		cd /tmp
		rm -R /tmp/DietPi-Update /tmp/DietPi-Patchfile
		#	- Inform user to avoid confusion
		echo ''
		G_DIETPI-NOTIFY 0 "DietPi has applied a new$BRANCH_INFO versioning system to the device. To allow DietPi-Update to use this new system, it will now restart.\n"
		#	- Apply update forcefully, since user has already chosen to do so
		/DietPi/dietpi/dietpi-update 1
		#	- Kill parental dietpi-update instance and exit this script to avoid obsolete update finish
		kill $PPID
		exit

	fi

	#/////////////////////////////////////////////////////////////////////////////////////
	#Incremental patch system:
	Incremental_Patch_System(){

		if (( $G_DIETPI_VERSION_SUB == -1 )); then

			#-------------------------------------------------------------------------------
			#Asus TB G_HW_MODEL change
			if [[ -r /etc/.dietpi_hw_model_identifier ]] &&
				(( $(sed -n 1p /etc/.dietpi_hw_model_identifier) == 100 )); then

				G_HW_MODEL=52
				echo $G_HW_MODEL > /etc/.dietpi_hw_model_identifier
				/DietPi/dietpi/func/dietpi-obtain_hw_model

			fi
			#-------------------------------------------------------------------------------
			#bash.bashrc removal of any outstanding dietpi entries (moved to globals). Just incase I missed any manually during PREP...
			sed -i '/#DietPi_Entries/Q' /etc/bash.bashrc
			sed -i '/#Apply system locale/Q' /etc/bash.bashrc
			sed -i '/#DietPi Additions/Q' /etc/bash.bashrc
			#-------------------------------------------------------------------------------
			#Fix doubled and renamed config files:
			#https://github.com/Fourdee/DietPi/commit/68148cec6b49afc787deca638456e1c4689e1cab#diff-8370b86e635383d521462994afe04a2d
			[[ -f /etc/apt/apt.conf.d/99force-ipv ]] && rm /etc/apt/apt.conf.d/99force-ipv
			[[ -f /etc/sysctl.d/97-dietpi.conf ]] && rm /etc/sysctl.d/97-dietpi.conf
			#-------------------------------------------------------------------------------
			#Core_ENV update: https://github.com/Fourdee/DietPi/pull/1419
			#	consoleblank disable x86_64
			if [[ -f /etc/default/grub ]]; then

				G_CONFIG_INJECT 'GRUB_CMDLINE_LINUX_DEFAULT=' 'GRUB_CMDLINE_LINUX_DEFAULT="consoleblank=0 quiet"' /etc/default/grub
				G_CONFIG_INJECT 'GRUB_CMDLINE_LINUX=' 'GRUB_CMDLINE_LINUX="net.ifnames=0"' /etc/default/grub
				G_CONFIG_INJECT 'GRUB_TIMEOUT=' 'GRUB_TIMEOUT=0' /etc/default/grub
				update-grub

			fi
			#-------------------------------------------------------------------------------
			#Remove -dev keyring
			apt-mark auto debian-keyring
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 0 )); then

			#-------------------------------------------------------------------------------
			#Reinstalls:
			#	Kodi: https://github.com/Fourdee/DietPi/issues/1428
			#	Fail2Ban: https://github.com/Fourdee/DietPi/issues/1431
			#	Tonido: https://github.com/Fourdee/DietPi/issues/1432
			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/dietpi-software reinstall 31 73 134
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 1 )); then

			#-------------------------------------------------------------------------------
			#locale rework/reset: https://github.com/Fourdee/DietPi/issues/1430#issuecomment-364763302
			[[ -f /etc/environment ]] && mv /etc/environment /mnt/dietpi_userdata/environment.bak
			> /etc/environment

			/DietPi/dietpi/func/dietpi-set_software locale en_GB.UTF-8

			G_WHIP_MSG 'Notice (locale):\n\nTo resolve broken locales, they have been reset to "en_GB.UTF-8".\n\nIf you had a different locale configured on this system, please use "dietpi-config" at a later date to re-configure.\n\nIn relation to that, DietPi does not use "/etc/environment" anymore, thus it is cleaned. In case you manually edited it, a backup was created: /mnt/dietpi_userdata/environment.bak'
			#------------------------------------------------------------------------------
			#Removed control from DietPi-Services: https://github.com/Fourdee/DietPi/issues/1501
			systemctl enable dnsmasq &> /dev/null
			systemctl enable openvpn &> /dev/null
			systemctl start dnsmasq &> /dev/null
			systemctl start openvpn &> /dev/null
			#-------------------------------------------------------------------------------
			#CertBot fixes: https://github.com/Fourdee/DietPi/issues/734#issuecomment-361774084
			# - "/DietPi/dietpi/dietpi-letsencrypt 1" will run on v6.2 -> v6.3, avoid double execution!
			if [[ -f /etc/letsencrypt/live/*/cert.pem ]] && (( $G_DISTRO > 3 )); then

				if grep -q '^aSOFTWARE_INSTALL_STATE\[83\]=2' /DietPi/dietpi/.installed; then

					certbot renew --force-renewal -a webroot -w /var/www/ -i apache

				elif grep -q '^aSOFTWARE_INSTALL_STATE\[85\]=2' /DietPi/dietpi/.installed; then

					certbot renew --force-renewal -a webroot -w /var/www/ -i nginx

				elif grep -q '^aSOFTWARE_INSTALL_STATE\[158\]=2' /DietPi/dietpi/.installed; then

					certbot renew --force-renewal --preferred-challenges http

				fi

			fi
			#-------------------------------------------------------------------------------
			#https://dietpi.com/phpbb/viewtopic.php?f=11&t=2772&p=10646#p10646
			rm /etc/apt/sources.list.d/openmediavault.list &> /dev/null
			#-------------------------------------------------------------------------------
			#DietPi-Software removals: https://github.com/Fourdee/DietPi/issues/1491
			if [[ -f /DietPi/dietpi/.installed ]]; then

				sed -i '/^aSOFTWARE_INSTALL_STATE\[100\]=/c\aSOFTWARE_INSTALL_STATE\[100\]=0' /DietPi/dietpi/.installed #grashopper (now pijuice)
				sed -i '/^aSOFTWARE_INSTALL_STATE\[106\]=/c\aSOFTWARE_INSTALL_STATE\[106\]=0' /DietPi/dietpi/.installed #raspcontrol (now ntp)
				if grep -qi '^aSOFTWARE_INSTALL_STATE\[170\]=2' /DietPi/dietpi/.installed; then

					sed -i '/^aSOFTWARE_INSTALL_STATE\[106\]=/c\aSOFTWARE_INSTALL_STATE\[106\]=2' /DietPi/dietpi/.installed #ntp (replaces raspcontrol)
					sed -i '/^aSOFTWARE_INSTALL_STATE\[170\]=/c\aSOFTWARE_INSTALL_STATE\[170\]=0' /DietPi/dietpi/.installed #ntp (now 106)

				fi

			fi
			#-------------------------------------------------------------------------------
			#Nodered lacks homedir, create it: https://github.com/Fourdee/DietPi/issues/1446#issuecomment-366370800
			if grep -qi '^nodered:' /etc/passwd &&
				[[ ! -d /home/nodered ]]; then

				mkdir -p /home/nodered
				chown -R nodered:nodered /home/nodered

			fi
			#-------------------------------------------------------------------------------
			#Reinstalls:
			#	NetData 1.9
			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/dietpi-software reinstall 65
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 2 )); then

			#-------------------------------------------------------------------------------
			#Switch from rc.local to own postboot script: https://github.com/Fourdee/DietPi/issues/1376
			G_WHIP_MSG 'DietPi will not use "/etc/rc.local" for its own scripts anymore.\n\nHowever, in case you manually added something, we safe a backup to "/mnt/dietpi_userdata/rc.local.bak", from where you can copy & paste back to the cleaned "/etc/rc.local".\n\nIt will work as before.'
			[[ -f /etc/rc.local ]] && mv /etc/rc.local /mnt/dietpi_userdata/rc.local.bak
			cat << _EOF_ > /etc/rc.local
#!/bin/sh -e
#
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to disable this script please use systemd to control the service:
# systemctl disable rc-local.service
#
# By default this script does nothing.

exit 0
_EOF_
			chmod +x /etc/rc.local

			cat << _EOF_ > /etc/systemd/system/rc-local.service
[Unit]
Description=rc.local backwards compatibility
Requires=dietpi-boot.service dietpi-ramdisk.service
After=dietpi-boot.service dietpi-ramdisk.service dietpi-ramlog.service dietpi-postboot.service

[Service]
Type=idle
RemainAfterExit=yes
ExecStart=/bin/bash -c '/etc/rc.local'
StandardOutput=tty

[Install]
WantedBy=multi-user.target
_EOF_

			systemctl enable rc-local.service
			systemctl enable dietpi-postboot

			if (( $G_DIETPI_INSTALL_STAGE == 1 )) && grep -q '^aSOFTWARE_INSTALL_STATE\[168\]=2' /DietPi/dietpi/.installed; then

				[[ -d /var/lib/dietpi/postboot.d ]] || mkdir /var/lib/dietpi/postboot.d
				cat << _EOF_ > /var/lib/dietpi/postboot.d/moode
#!/bin/bash
#moOde additions
SQLDB=/var/local/www/db/moode-sqlite3.db

# set cpu govenor
RESULT=\$(sqlite3 \$SQLDB "select value from cfg_system where param='cpugov'")
echo "\$RESULT" | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

/usr/bin/udisks-glue > /dev/null 2>&1
/var/www/command/worker.php > /dev/null 2>&1
_EOF_

			fi
			#-------------------------------------------------------------------------------
			G_DIETPI-NOTIFY 2 'Reducing getty count and resource usage:'
			systemctl mask getty-static
			#-------------------------------------------------------------------------------
			# - Meveric, update repo to use our EU mirror: https://github.com/Fourdee/DietPi/issues/1519#issuecomment-368234302
			sed -i 's@https://oph.mdrjr.net/meveric@http://fuzon.co.uk/meveric@' /etc/apt/sources.list.d/meveric* &> /dev/null
			#-------------------------------------------------------------------------------
			#Remove any existing apt recommends settings, before applying ours: https://github.com/Fourdee/DietPi/issues/1482#issuecomment-368031044
			rm /etc/apt/apt.conf.d/*recommends* &> /dev/null

			G_ERROR_HANDLER_COMMAND='/etc/apt/apt.conf.d/99-dietpi-norecommends'
			cat << _EOF_ > $G_ERROR_HANDLER_COMMAND
APT::Install-Recommends "false";
APT::Install-Suggests "false";
#APT::AutoRemove::RecommendsImportant "false";
#APT::AutoRemove::SuggestsImportant "false";
_EOF_
			G_ERROR_HANDLER_EXITCODE=$?
			G_ERROR_HANDLER
			#-------------------------------------------------------------------------------
			#Reinstalls:
			#	Shairport-sync 3.1.7
			# 	RPi Cam
			#	Aria2 for .conf addition: https://github.com/Fourdee/DietPi/issues/1575#issuecomment-370248708
			#	Sonarr/Radarr: https://github.com/Fourdee/DietPi/issues/1566#issuecomment-369334473
			if (( $G_DIETPI_INSTALL_STAGE == 1 )); then

				# - RPi cam pre-patch
				mv /var/www/dietpicam /var/www/rpicam &> /dev/null
				mv $G_FP_DIETPI_USERDATA/dietpicam $G_FP_DIETPI_USERDATA/rpicam &> /dev/null
				rm /var/www/rpicam/media &> /dev/null

				/DietPi/dietpi/dietpi-software reinstall 37 59 132 144 145

			fi
			#-------------------------------------------------------------------------------
			#Add certificate combining for Lighttpd to CertBot auto renewal: https://github.com/Fourdee/DietPi/pull/1553
			if [[ -f /DietPi/dietpi/.dietpi-letsencrypt ]]; then

				# - Switch Minio to new certbot.service.d/ hook:
				if (( $G_DISTRO > 3 )) && grep -q '^aSOFTWARE_INSTALL_STATE\[158\]=2' /DietPi/dietpi/.installed; then

					[[ -f /etc/systemd/system/certbot.service ]] && rm /etc/systemd/system/certbot.service

				fi
				# - Overall settings and config renewal:
				/DietPi/dietpi/dietpi-letsencrypt 1
				# - Stop services, started during dietpi-letsencrypt execution:
				/DietPi/dietpi/dietpi-services stop

			fi
			#-------------------------------------------------------------------------------
			#Sparky SBC kernel patches: Pro-Ject-S2 dac DSD native support on sparky, also other few dac ids.
			if (( $G_HW_MODEL == 70 )); then

				G_RUN_CMD wget https://raw.githubusercontent.com/sparky-sbc/sparky-test/master/pro-ject-s2/snd-usb-audio.ko -O /lib/modules/$(uname -r)/kernel/sound/usb/snd-usb-audio.ko
				G_RUN_CMD wget https://raw.githubusercontent.com/sparky-sbc/sparky-test/master/pro-ject-s2/snd-usbmidi-lib.ko -O /lib/modules/$(uname -r)/kernel/sound/usb/snd-usbmidi-lib.ko

			fi
			#-------------------------------------------------------------------------------
			#GNU key management required for some APT installs via additional repos: https://github.com/Fourdee/DietPi/issues/1388
			G_AGI dirmngr
			#-------------------------------------------------------------------------------
			# Odroids FFmpeg decendency fix: https://github.com/Fourdee/DietPi/issues/1556#issuecomment-369463910
			if (( $G_HW_MODEL > 9 && $G_HW_MODEL < 15 )); then

				rm /etc/apt/preferences.d/meveric*
				cat << _EOF_ > /etc/apt/preferences.d/backports
Package: *
Pin: release a=jessie-backports
Pin: origin "fuzon.co.uk"
Pin-Priority: 99

Package: *
Pin: release a=jessie-backports
Pin: origin "oph.mdrjr.net"
Pin-Priority: 99
_EOF_

			fi
			#-------------------------------------------------------------------------------
			# Subsonic 5 replaced with Airsonic: https://github.com/Fourdee/DietPi/issues/1585
			sed -i '/^aSOFTWARE_INSTALL_STATE\[33\]=/c\aSOFTWARE_INSTALL_STATE\[33\]=0' /DietPi/dietpi/.installed &> /dev/null
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 3 )); then

			#-------------------------------------------------------------------------------
			#Service updates: https://dietpi.com/phpbb/viewtopic.php?f=11&t=1148&p=11322#p11322
			$(which mkdir) -p /var/tmp/dietpi/logs
			#-------------------------------------------------------------------------------
			#Fix microcode installation based on image creation CPU instead of image target CPU: https://github.com/Fourdee/DietPi/pull/1596
			if (( $G_HW_ARCH == 10 )); then

				if grep -qi 'vendor_id.*intel' /proc/cpuinfo; then

					dpkg-query -s amd64-microcode &> /dev/null && apt-mark auto amd64-microcode
					G_AGI intel-microcode

				elif grep -qi 'vendor_id.*amd' /proc/cpuinfo; then

					dpkg-query -s intel-microcode &> /dev/null && apt-mark auto intel-microcode
					G_AGI amd64-microcode

				fi

			fi
			#-------------------------------------------------------------------------------
			#Reinstalls
			#	UrBackupServer
			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/dietpi-software reinstall 111
			#-------------------------------------------------------------------------------
			#Cron minutely support: https://github.com/Fourdee/DietPi/pull/1578
			mkdir -p /etc/cron.minutely

			if ! grep -qi 'cron.minutely' /etc/crontab; then

				cat << _EOF_ >> /etc/crontab
#*/0 * * * *   root    cd / && run-parts --report /etc/cron.minutely
_EOF_

			fi
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 4 )); then

			#-------------------------------------------------------------------------------
			#Removal of dphys-swapfile, switch to our own swapfile control system: https://github.com/Fourdee/DietPi/issues/1602
			sed -i '/[[:space:]]dphys-swapfile[[:space:]]/d' /etc/fstab
			local swap_size=0
			local swap_location='/var/swap'
			if [[ -f /etc/dphys-swapfile ]]; then

				swap_size=$(grep -m1 '^[[:blank:]]*CONF_SWAPSIZE=' /etc/dphys-swapfile | sed 's/^[^=]*=//')
				swap_location="$(grep -m1 '^[[:blank:]]*CONF_SWAPFILE=' /etc/dphys-swapfile | sed 's/^[^=]*=//')"

			fi

			sed -i "/^[[:blank:]]*AUTO_SETUP_SWAPFILE_SIZE=/c\AUTO_SETUP_SWAPFILE_SIZE=$swap_size" /DietPi/dietpi.txt
			sed -i "/^[[:blank:]]*AUTO_SETUP_SWAPFILE_LOCATION=/c\AUTO_SETUP_SWAPFILE_LOCATION=$swap_location" /DietPi/dietpi.txt

			#Re-Apply swap to set /tmp tmpfs size: https://github.com/Fourdee/DietPi/issues/1027#issuecomment-369435049
			# + Force auto swapfile size https://github.com/Fourdee/DietPi/issues/1593#issuecomment-371516418
			/DietPi/dietpi/func/dietpi-set_dphys-swapfile 1

			G_AGP dphys-swapfile
			#-------------------------------------------------------------------------------
			#Reinstalls
			#	Shairport-sync: https://github.com/Fourdee/DietPi/issues/1620#issuecomment-373086888
			#	Squeezebox server:
			#	AmiBerry 2.18: https://github.com/Fourdee/DietPi/issues/1410#issuecomment-374060452
			#	Mopidy: https://github.com/Fourdee/DietPi/issues/1625
			#	MPD: https://github.com/Fourdee/DietPi/issues/1614
			if (( $G_DIETPI_INSTALL_STAGE == 1 )); then

				$(which killall) -w squeezeboxserver &> /dev/null
				rm /var/lib/dietpi/dietpi-software/services/squeezeboxserver.service &> /dev/null

				/DietPi/dietpi/dietpi-software reinstall 35 37 118 128

			fi
			#-------------------------------------------------------------------------------
			#RPi 3 B+: Set correct disabled clocks for B+ (scraped by dietpi-config > overclocking)
			if grep -qi 'RPi 3 Model B+' /DietPi/dietpi/.hw_model; then

				sed -i '/arm_freq=/c\#arm_freq=1400' /DietPi/config.txt
				sed -i '/sdram_freq=/c\#sdram_freq=500' /DietPi/config.txt

			fi
			#-------------------------------------------------------------------------------
			#sudoers and sysctl adjustments moved to *.d/ files: https://github.com/Fourdee/DietPi/pull/1635
			cat << _EOF_ > /etc/sudoers.d/dietpi
dietpi ALL=NOPASSWD: ALL
_EOF_
			sed -i '/dietpi/d' /etc/sudoers
			#Our config must not start with '99-' to assure priority higher than '99-sysctl.conf'
			# - New config is installed automatically via v6.9 update system.
			[[ -f /etc/sysctl.d/99-dietpi.conf ]] && rm /etc/sysctl.d/99-dietpi.conf
			#-------------------------------------------------------------------------------
			# - RPi resolve gettext error: https://github.com/Fourdee/DietPi/issues/1631#issuecomment-373965406
			rm /etc/profile.d/wifi-country.sh &> /dev/null
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 5 )); then

			#-------------------------------------------------------------------------------
			#RPi APT mirror fix: https://github.com/Fourdee/DietPi/issues/1659
			if (( $G_HW_MODEL < 10 )); then

				G_AGDUG
				/DietPi/dietpi/func/dietpi-set_software apt-mirror 'http://raspbian.raspberrypi.org/raspbian'
				G_AGUP

			fi
			#-------------------------------------------------------------------------------
			#Remove minutely running "make_nas_processes_faster" cron job, present on images with preinstalled OMV: https://github.com/Fourdee/DietPi/issues/1654
			rm /etc/cron.d/make_nas_processes_faster &> /dev/null
			#-------------------------------------------------------------------------------
			#Add Dropbear ecdsa and dss host keys, if missing: https://github.com/Fourdee/DietPi/issues/1670
			if (( $G_DIETPI_INSTALL_STAGE == 1 )) && grep -q '^aSOFTWARE_INSTALL_STATE\[104\]=2' /DietPi/dietpi/.installed; then

				[[ -f /etc/dropbear/dropbear_ecdsa_host_key ]] || dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key &> /dev/null
				[[ -f /etc/dropbear/dropbear_dss_host_key ]] || dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key &> /dev/null

			fi
			#-------------------------------------------------------------------------------
			#Reinstall firmware-misc-nonfree by default (ralink): https://github.com/Fourdee/DietPi/issues/1675
			if dpkg-query -s wpasupplicant &> /dev/null; then

				if (( $G_DISTRO == 3 )); then

					G_AGI firmware-ralink

				else

					G_AGI firmware-misc-nonfree

				fi

			elif (( $G_HW_ARCH == 10 && $G_HW_MODEL != 20 )); then

				G_AGI firmware-misc-nonfree

			fi
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 6 )); then

			#-------------------------------------------------------------------------------
			#Add nodered (if installed) to gpio group: https://github.com/Fourdee/DietPi/issues/1687
			usermod -a -G gpio nodered &> /dev/null
			#-------------------------------------------------------------------------------
			#Deluge systemd service update: https://github.com/Fourdee/DietPi/issues/1658
			# + Service fix for in v6.6 https://github.com/Fourdee/DietPi/issues/1689#issuecomment-379024795
			if [[ -f /var/lib/dietpi/dietpi-software/services/deluge.service ||
				-f /etc/systemd/system/deluged.service ]]; then

				#New services
				cat << _EOF_ > /etc/systemd/system/deluged.service
[Unit]
Description=DietPi Deluged Service

[Service]
Type=simple
ExecStart=$(which deluged) -d -l /var/log/deluged.log -L warning

[Install]
WantedBy=multi-user.target
_EOF_

				cat << _EOF_ > /etc/systemd/system/deluge-web.service
[Unit]
Description=DietPi Deluge-web Service

[Service]
Type=simple #forking causes systemd-tty-ask-password-agent hang
ExecStart=$(which deluge-web) -l /var/log/deluge-web.log -L warning

[Install]
WantedBy=multi-user.target
_EOF_

				/DietPi/dietpi/dietpi-services dietpi_controlled

				[[ -f /var/lib/dietpi/dietpi-software/services/deluge.service ]] && rm /var/lib/dietpi/dietpi-software/services/deluge.service

				# - Enable service run:
				G_CONFIG_INJECT 'ENABLE_DELUGED=' 'ENABLE_DELUGED=1' /etc/default/deluged

			fi
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 7 )); then

			#-------------------------------------------------------------------------------
			#Uninstalls:
			#	Removal of fbset on new installs: https://github.com/Fourdee/DietPi/issues/1716
			(( $G_DIETPI_INSTALL_STAGE <= 0 )) && apt-mark auto fbset
			#-------------------------------------------------------------------------------
			#Reinstalls:
			#	XRDP: https://github.com/Fourdee/DietPi/issues/1727#issuecomment-383858979
			#	AmiBerry 2.19: https://github.com/Fourdee/DietPi/issues/1707
			#	Pi-SPC
			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/dietpi-software reinstall 29 108 166
			#-------------------------------------------------------------------------------
			#Pi-hole: Enable FTLDNS support by removing pihole-FTL from DietPi control: https://github.com/Fourdee/DietPi/pull/1714
			systemctl enable pihole-FTL 2> /dev/null
			#-------------------------------------------------------------------------------
			#Remove allo Piano firmware, if not chosen as soundcard, to allow installation on demand: https://github.com/Fourdee/DietPi/issues/1656
			if ( (( $G_HW_MODEL < 10 )) && ! grep -q 'allo-piano-dac' /DietPi/config.txt ) ||
				( (( $G_HW_MODEL == 70 )) && ! grep -q 'allo-piano-dac' /etc/modules ); then

				rm -R /lib/firmware/allo &> /dev/null

			fi
			#-------------------------------------------------------------------------------
			#RPi add FB depth 16: https://github.com/Fourdee/DietPi/issues/1716
			if (( $G_HW_MODEL < 10 )) &&
				! grep -q 'framebuffer_depth=' /DietPi/config.txt; then

				echo -e "\n#framebuffer_depth=16" >> /DietPi/config.txt

			fi
			#-------------------------------------------------------------------------------
			#RPi UART: https://github.com/Fourdee/DietPi/issues/1759
			if [[ -f /DietPi/config.txt ]]; then

				local serial_state=$(grep -m1 '^[[:blank:]]*CONFIG_SERIAL_CONSOLE_ENABLE=' /DietPi/dietpi.txt | sed 's/^.*=//')
				G_CONFIG_INJECT 'enable_uart=' "enable_uart=$serial_state" /DietPi/config.txt

			fi
			#-------------------------------------------------------------------------------
			#pre-create postboot dir for all systems
			mkdir -p /var/lib/dietpi/postboot.d
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 8 )); then

			#-------------------------------------------------------------------------------
			#Verify v6.8+ .dietpi-process_tool file format, else remove it (recreated)
			if [[ -f '/DietPi/dietpi/.dietpi-process_tool' ]] &&
				! grep -qm1 '^aname_save' /DietPi/dietpi/.dietpi-process_tool; then

				G_DIETPI-NOTIFY 2 'Detected invalid .dietpi-process_tool save file. It has been reset to support updated v6.8 DietPi-Process_Tool codebase'
				rm /DietPi/dietpi/.dietpi-process_tool
				rm /boot/dietpi/.dietpi-process_tool

			fi
			#-------------------------------------------------------------------------------
			#NTP removal, switch to systemd:
			killall -w /DietPi/dietpi/func/run_ntpd &> /dev/null
			killall -w ntpd &> /dev/null

			G_AGP ntp
			sed -i '/^aSOFTWARE_INSTALL_STATE\[106\]=/c\aSOFTWARE_INSTALL_STATE\[106\]=0' /DietPi/dietpi/.installed &> /dev/null
			/DietPi/dietpi/func/dietpi-set_software ntpd-mode $(grep -m1 '^[[:blank:]]*CONFIG_NTP_MODE=' /DietPi/dietpi.txt | sed 's/^.*=//')
			systemctl daemon-reload
			/DietPi/dietpi/func/run_ntpd
			#-------------------------------------------------------------------------------
			#Move DietPi globals and login scripts into new /etc/bashrc.d location to load on all interactive shells:
			mkdir -p /etc/bashrc.d
			G_CONFIG_INJECT '.*/etc/bashrc\.d/.*' 'for i in /etc/bashrc.d/*.sh; do [ -r "$i" ] && . $i; done' /etc/bash.bashrc
			sed -i '/\/DietPi/d' /root/.bashrc #should already be removed, failsafe start clean
			for i in /home/*/.bashrc; do sed -i '/\/DietPi/d' $i; done #should already be removed, failsafe start clean
			rm /etc/profile.d/99-dietpi* &> /dev/null
			# - Enable bash-completion for non-login shells:
			#	- NB: It is called twice on login shells then, but breaks directly if called already once.
			ln -sf /etc/profile.d/bash_completion.sh /etc/bashrc.d/dietpi-bash_completion.sh
			#-------------------------------------------------------------------------------
			#Sparky unmute fix (re: @sudeep)
			#	v2: https://github.com/Fourdee/DietPi/pull/1779
			if (( $G_HW_MODEL == 70 )) && grep -qi 'CONFIG_SOUNDCARD=usb-dac' /DietPi/dietpi.txt; then

				cat << _EOF_ > /var/lib/dietpi/postboot.d/sparky_unmute.sh
#!/bin/bash
for x in \`amixer controls | grep layback\`
do

    amixer cset "\${x}" 100% &> /dev/null

done
alsactl store &> /dev/null
_EOF_

			fi
			#-------------------------------------------------------------------------------
			#Reinstalls
			#	RPi (apply to all) LXDE missing icons under pcmanfm reinstall: https://github.com/Fourdee/DietPi/issues/1558#issuecomment-390328173
			# 	SubSonic/AirSonic
			#	Cava
			#	CloudPrint
			#	TightVNC/VNC4/RealVNC: https://github.com/Fourdee/DietPi/pull/1798#issuecomment-392594878
			#	Xserver: https://github.com/Fourdee/DietPi/issues/1823
			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/dietpi-software reinstall 23 33 34 119 137 27 28 120 6
			#-------------------------------------------------------------------------------
			#Sickrage service update: https://github.com/Fourdee/DietPi/issues/1762
			if [[ -f /etc/systemd/system/sickrage.service ]]; then

				cat << _EOF_ > /etc/systemd/system/sickrage.service
[Unit]
Description=SickRage

[Service]
User=root
Group=root
Type=forking
GuessMainPID=no
TimeoutSec=infinity
TimeoutStopSec=20
Restart=always
ExecStart=/usr/bin/python /etc/sickrage/SickBeard.py -q --daemon --nolaunch --datadir=$G_FP_DIETPI_USERDATA/sickrage

[Install]
WantedBy=multi-user.target
_EOF_

			fi
			#-------------------------------------------------------------------------------
			#Initially allow non-root users to obtain network details as well: https://github.com/Fourdee/DietPi/commit/15c0d495c33d3091e219c87bb2d09a22f8d27e9c
			[[ -f /DietPi/dietpi/.network ]] && chmod 666 /DietPi/dietpi/.network
			[[ -f /boot/dietpi/.network ]] && chmod 666 /boot/dietpi/.network
			#-------------------------------------------------------------------------------
			#Re-Run set uid for sudo: https://github.com/Fourdee/DietPi/issues/794#issuecomment-392335392
			chmod 4755 $(which sudo)
			#-------------------------------------------------------------------------------
			#Removal due to changed file locations: https://github.com/Fourdee/DietPi/pull/1802
			rm /DietPi/dietpi/func/dietpi-set_core_environment &> /dev/null
			rm /boot/dietpi/func/dietpi-set_core_environment &> /dev/null
			rm /DietPi/dietpi/conf/cron.daily_dietpi &> /dev/null
			rm /boot/dietpi/conf/cron.daily_dietpi &> /dev/null
			rm /DietPi/dietpi/conf/cron.hourly_dietpi &> /dev/null
			rm /boot/dietpi/conf/cron.hourly_dietpi &> /dev/null
			rm /var/lib/dietpi/fs_partition_resize.sh &> /dev/null
			rm /var/lib/dietpi/dietpi-software/services/kill-ssh-user-sessions-before-network.sh &> /dev/null
			#-------------------------------------------------------------------------------
			#Offer to change global and unix user passwords to make users aware of the existance or "dietpi" and how the dietpi.txt password is used.
			#	If already installed only, else, dietpi-software will handle this on first run, after the update
			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/func/dietpi-set_software passwords

		elif (( $G_DIETPI_VERSION_SUB == 9 )); then

			#-------------------------------------------------------------------------------
			#Switch to IP commands, removal of net-tools: https://github.com/Fourdee/DietPi/pull/1839
			# - Only apply, if HomeAssistant is not installed, as it depends on net-tools: https://github.com/Fourdee/DietPi/issues/1911
			if [[ -f '/DietPi/dietpi/.installed' ]] &&
				grep -q '^aSOFTWARE_INSTALL_STATE\[157\]=2' /DietPi/dietpi/.installed; then

				echo 'HA installed, avoid net-tools removal' &> /dev/null

			else

				G_AGP net-tools
				G_WHIP_MSG '"net-tools" package is no longer required for DietPi systems and has been flagged as such in APT. "ifconfig" can be replaced with "ip a", or, you can reinstall "net-tools" package as needed.'

			fi
			#-------------------------------------------------------------------------------
			#Reinstalls
			#	GMrender: https://dietpi.com/phpbb/viewtopic.php?f=11&t=3900&p=12985#p12985
			# 	Xserver (ASUSTB GPU)
			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/dietpi-software reinstall 163 6
			#-------------------------------------------------------------------------------
			#DietPi-Backup rewrite, no longer supports older backups: https://github.com/Fourdee/DietPi/issues/1851
			if [[ -f '/DietPi/dietpi/.dietpi-backup_settings' ]]; then

				G_WHIP_MSG 'DietPi-Backup has been re-written to improve support for custom include/exclude options. It also removes the option for userdata backups, as this is now included by default.\n\nNB: Existing backups are no longer supported and cannot be restored. We highly recommend removing the older backup (eg: "rm -R /mnt/dietpi-backup"), then, create a new backup.'

			fi
			#-------------------------------------------------------------------------------
			#Fix Apache2 logging to "/error.log" instead of "/var/log/apache2/error.log": https://github.com/Fourdee/DietPi/commit/c991bd7dc579dbdc7c239e4c887b0962fa204006
			if [[ -d /etc/apache2/sites-available ]]; then

				for vhost in /etc/apache2/sites-available/*.conf
				do

					[[ -f $vhost ]] && sed -Ei '\|^[[:blank:]]*ErrorLog[[:blank:]]+/error\.log|c\	ErrorLog \$\{APACHE_LOG_DIR\}/error\.log' $vhost

				done

			fi
			#-------------------------------------------------------------------------------
			#Disable "initial_turbo" option for RPi within config.txt, as it currently prevents CPU throttle down: https://github.com/Fourdee/DietPi/issues/1836
			if [[ -f /DietPi/config.txt ]] && grep -q '^[[:blank:]]*initial_turbo' /DietPi/config.txt; then

				sed -i '/^[[:blank:]]*initial_turbo/d' /DietPi/config.txt
				echo -e '\n# Initial turbo currently leads to CPU not being throttled down by CPU governor: https://github.com/Fourdee/DietPi/issues/1836\n#initial_turbo=20' >> /DietPi/config.txt

			fi
			#-------------------------------------------------------------------------------
			#Remove config.txt for non-RPi devices: https://github.com/Fourdee/DietPi/pull/1863
			if (( $G_HW_MODEL >= 10 )); then

				[[ -f /DietPi/config.txt ]] && rm /DietPi/config.txt
				[[ -f /boot/config.txt ]] && rm /boot/config.txt

			fi
			#-------------------------------------------------------------------------------
			#Removal of NTP from dietpi-software
			sed -i '/^aSOFTWARE_INSTALL_STATE\[106\]=/c\aSOFTWARE_INSTALL_STATE\[106\]=0' /DietPi/dietpi/.installed &> /dev/null
			#	Cleared for roon extension manager addition
			sed -i '/^aSOFTWARE_INSTALL_STATE\[86\]=/c\aSOFTWARE_INSTALL_STATE\[86\]=0' /DietPi/dietpi/.installed &> /dev/null
			#	Cleared for ubooquity addition
			sed -i '/^aSOFTWARE_INSTALL_STATE\[80\]=/c\aSOFTWARE_INSTALL_STATE\[80\]=0' /DietPi/dietpi/.installed &> /dev/null
			#	Moode cleared
			sed -i '/^aSOFTWARE_INSTALL_STATE\[168\]=/c\aSOFTWARE_INSTALL_STATE\[168\]=0' /DietPi/dietpi/.installed &> /dev/null
			#-------------------------------------------------------------------------------
			#Unused and replaced with dietpi-fs_partition_resize.service
			rm /etc/systemd/system/dietpi-fs_expand.service &> /dev/null
			#-------------------------------------------------------------------------------
			#ASUS TB fonts broken as /usr/share/font removed but pkg's still exist, need to also do a fresh PREP on this image
			if (( $G_HW_MODEL == 52 )); then

				if (( $G_DIETPI_INSTALL_STAGE <= 0 )); then

					apt-mark auto fonts-dejavu-core libfontconfig1 libfreetype6 fontconfig-config fontconfig xserver-*

				elif dpkg-query -s libfreetype6 &> /dev/null; then

					G_AGI --reinstall fonts-dejavu-core libfontconfig1 libfreetype6 fontconfig-config fontconfig

				fi

			fi
			#-------------------------------------------------------------------------------
			#Reset DietPi-Survey settings file due to rework with v6.9 and v6.10
			# - pre-v6.17 dietpi-update rerun assures, dietpi-survey is called after update has finished
			[[ -f /DietPi/dietpi/.dietpi-survey ]] && rm /DietPi/dietpi/.dietpi-survey
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 10 )); then

			#-------------------------------------------------------------------------------
			echo 0 &> /dev/null
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 11 )); then

			#-------------------------------------------------------------------------------
			#Software removals:
			#	JRiver: https://github.com/Fourdee/DietPi/issues/1080#issuecomment-403489246
			sed -i '/^aSOFTWARE_INSTALL_STATE\[148\]=/c\aSOFTWARE_INSTALL_STATE\[148\]=0' /DietPi/dietpi/.installed &> /dev/null
			#-------------------------------------------------------------------------------
			#ASUS TB WiFi: https://github.com/Fourdee/DietPi/issues/1760
			(( $G_HW_MODEL == 52 )) && G_CONFIG_INJECT '8723bs' '8723bs' /etc/modules
			#-------------------------------------------------------------------------------
			#Software reinstalls:
			#	https://github.com/Fourdee/DietPi/issues/1877#issuecomment-403421942
			#	Items which run as own user:
			#	YMPD
			#	MPD
			#	minidlna
			#	AirSonic
			#	Sickrage
			#	Sonarr
			#	Radarr
			#	NZBget
			#	RoonBridge
			#	RoonServer
			#	GMrender
			#	PlexPy
			#	Koel
			#	O!MPD: https://github.com/Fourdee/DietPi/issues/1934#issuecomment-406059462
			#	 - NO REINSTALL: due to many changes, or, too much risk for existing user settings, fresh installs only
			#		CubeRite
			#		qBitTorrent
			#		tonido
			if (( $G_DIETPI_INSTALL_STAGE == 1 )); then

				#Moved to userdata folder, pre-reinstall to keep existing settings
				if [[ -d '/etc/sickrage' ]]; then

					G_RUN_CMD mv /etc/sickrage/* $G_FP_DIETPI_USERDATA/sickrage/
					rm -R /etc/sickrage

					G_WHIP_MSG "INFO:\n\nSickrage has been moved to the DietPi userdata directory:\n\n - /etc/sickrage > $G_FP_DIETPI_USERDATA/sickrage"

				fi

				if [[ -d '/root/.config/NzbDrone' ]]; then

					G_RUN_CMD mv /root/.config/NzbDrone $G_FP_DIETPI_USERDATA/sonarr
					G_WHIP_MSG "INFO:\n\nSonarr userdata has been moved to the DietPi userdata directory:\n\n - /root/.config/NzbDrone > $G_FP_DIETPI_USERDATA/sonarr"

				fi

				if [[ -d '/root/.config/Radarr' ]]; then

					G_RUN_CMD mv /root/.config/Radarr $G_FP_DIETPI_USERDATA/radarr
					G_WHIP_MSG "INFO:\n\nRadarr userdata has been moved to the DietPi userdata directory:\n\n - /root/.config/Radarr > $G_FP_DIETPI_USERDATA/radarr"

				fi

				if [[ -d $HOME/.config/deluge ]]; then

					mkdir -p $G_FP_DIETPI_USERDATA/deluge/.config/deluge
					G_RUN_CMD mv $HOME/.config/deluge/* $G_FP_DIETPI_USERDATA/deluge/.config/deluge/
					rm -R $HOME/.config/deluge
					G_WHIP_MSG "INFO:\n\nDeluge userdata has been moved to the DietPi userdata directory:\n\n - /root/.config/deluge > $G_FP_DIETPI_USERDATA/deluge"

				fi

				/DietPi/dietpi/dietpi-software reinstall 32 128 39 33 116 144 145 149 121 154 163 146 143 129

				#	O!MPD requires libary refresh by end user
				if grep -q '^aSOFTWARE_INSTALL_STATE\[129\]=2' /DietPi/dietpi/.installed; then

					G_WHIP_MSG 'O!MPD configuration has been updated.\n\nOnce the DietPi update is completed, and system is rebooted, please manually update the O!MPD database via the web interface.\n\n - O!MPD web interface > Settings > Update'

				fi

			fi
			#-------------------------------------------------------------------------------
			#Increase /var/log max size to 50MB, if lower than 50MB: https://github.com/pi-hole/pi-hole/issues/2270#issuecomment-405109135
			if df | grep '^tmpfs.*/var/log' &> /dev/null; then

				local var_log_size_new=50

				if (( $(grep -m1 '^[[:blank:]]*AUTO_SETUP_RAMLOG_MAXSIZE=' /DietPi/dietpi.txt | sed 's/^[^=]*=//') < $var_log_size_new )); then

					sed -i "/^[[:blank:]]*AUTO_SETUP_RAMLOG_MAXSIZE=/c\AUTO_SETUP_RAMLOG_MAXSIZE=$var_log_size_new" /DietPi/dietpi.txt

				fi

				sed -i '/[[:space:]]\/var\/log[[:space:]]/d' /etc/fstab
				cat << _EOF_ >> /etc/fstab
tmpfs /var/log tmpfs defaults,size=${var_log_size_new}m,noatime,nodev,nosuid,mode=1777 0 0
_EOF_

			fi
			#-------------------------------------------------------------------------------
			# - ARM64 packages no longer available: https://github.com/Fourdee/DietPi/issues/1915
			(( $G_DISTRO < 4 && $G_HW_ARCH == 3 )) && sed -i '/debian-security/d' /etc/apt/sources.list
			#-------------------------------------------------------------------------------
			#Fix Xserver uninstall issus by not purging dependencies, but leaving them for autoremove: https://github.com/Fourdee/DietPi/pull/1930/files
			local dpkg_list="$(dpkg --get-selections)"
			grep -q '^xinit[[:space:]]' <<< "$dpkg_list" && apt-mark auto xauth x11-common
			grep -q '^mesa-utils-extra[[:space:]]' <<< "$dpkg_list" && apt-mark auto libgles2-mesa
			#-------------------------------------------------------------------------------
			#Reinstall net-tools as dependency, if HomeAssistant is installed. Thanks to @lupa18 for reporting this: https://github.com/Fourdee/DietPi/issues/1911
			if (( $G_DIETPI_INSTALL_STAGE == 1 )) && grep -q '^aSOFTWARE_INSTALL_STATE\[157\]=2' /DietPi/dietpi/.installed; then

				G_AGI net-tools

			fi
			#-------------------------------------------------------------------------------
			#Removal of CurlFTPFS from dietpi-software
			sed -i '/^aSOFTWARE_INSTALL_STATE\[2\]=/c\aSOFTWARE_INSTALL_STATE\[2\]=0' /DietPi/dietpi/.installed &> /dev/null
			#-------------------------------------------------------------------------------
			#/var/lib/dietpi/dietpi-ramlog/storage moved to /var/tmp/dietpi/logs/dietpi-ramlog_store https://github.com/Fourdee/DietPi/pull/1919
			#automatically generated during ramlog, remove old location only
			rm -R /var/lib/dietpi/dietpi-ramlog/storage &> /dev/null
			#-------------------------------------------------------------------------------
			#Reinstall "netbase", in case of installed NFS client and/or server, to reenable NFSv3 support: https://github.com/Fourdee/DietPi/issues/1898
			if (( $G_DIETPI_INSTALL_STAGE == 1 )); then

				if grep -q '^aSOFTWARE_INSTALL_STATE\[109\]=2' /DietPi/dietpi/.installed ||
					grep -q '^aSOFTWARE_INSTALL_STATE\[110\]=2' /DietPi/dietpi/.installed; then

					G_AGI netbase

				fi

			fi
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 12 )); then

			#-------------------------------------------------------------------------------
			#Move Koel from /var/www to /mnt/dietpi_userdata: https://github.com/Fourdee/DietPi/pull/1954
			if [[ -d '/var/www/koel' ]]; then

				G_RUN_CMD mv /var/www/koel $G_FP_DIETPI_USERDATA/koel
				chown -R koel:dietpi $G_FP_DIETPI_USERDATA/koel
				[[ -f /etc/systemd/system/koel.service ]] && sed -i 's|/var/www|/mnt/dietpi_userdata|g' /etc/systemd/system/koel.service
				G_WHIP_MSG "INFO:\n\nKoel has been moved to the DietPi userdata directory:\n\n - /var/www/koel > $G_FP_DIETPI_USERDATA/koel"

			fi
			#-------------------------------------------------------------------------------
			#Mask systemd-logind as new default, if libpam-systemd is not installed: https://github.com/Fourdee/DietPi/issues/1767
			if ! dpkg-query -s 'libpam-systemd' &> /dev/null; then

				systemctl stop systemd-logind &> /dev/null
				systemctl disable systemd-logind &> /dev/null
				systemctl mask systemd-logind

			fi
			#-------------------------------------------------------------------------------
			# - Disable cron.minutely, if unused to reduce cron executions and logs
			(( $(find /etc/cron.minutely/ | wc -l) > 2 )) || sed -i '\|cron\.minutely|s|^\*/[0-9]*[[:blank:]]|#*/0 |' /etc/crontab
			#-------------------------------------------------------------------------------
			#Remove "ntfs-3g" respectively "hfsplus", if no attached drive requires it.
			local fs_list=$(lsblk -nro FSTYPE)
			grep -q 'ntfs' <<< $fs_list || apt-mark auto ntfs-3g
			grep -q 'hfs' <<< $fs_list || apt-mark auto hfsplus
			#-------------------------------------------------------------------------------
			#Pine 64, WiFi module: https://github.com/Fourdee/DietPi/issues/1995#issuecomment-410931618
			(( $G_HW_MODEL == 40 )) && G_CONFIG_INJECT '8723bs' '8723bs' /etc/modules
			#-------------------------------------------------------------------------------
			#Autoremove all marked packages during all patches with a single final call
			G_AGA
			#-------------------------------------------------------------------------------
			#DietPi-Services custom includes has changed
			local fp_old='/DietPi/dietpi/.dietpi-services_include'
			local fp_new='/DietPi/dietpi/.dietpi-services_include_exclude'
			if [[ -f $fp_old ]]; then

				# - generate the new file, if not done already
				[[ ! -f $fp_new ]] && /DietPi/dietpi/dietpi-services stop cron

				# - Transfer existing entries over
				while read line
				do

					[[ $line != '#'* ]] && echo "+ $line" >> $fp_new

				done < $fp_old

				G_WHIP_MSG "DietPi-Services custom includes has changed.\n\nYour previous items from\n - $fp_old\nhave been transfered to the new system\n - $fp_new.\n\nPlease see the new file $fp_new for more information."

				rm $fp_old

			fi
			#-------------------------------------------------------------------------------
			# - NZBget Umask: https://github.com/Fourdee/DietPi/issues/1999
			# - qBitTorrent: https://github.com/Fourdee/DietPi/issues/1957
			if [[ -f $G_FP_DIETPI_USERDATA/nzbget/nzbget.conf ]]; then

				G_CONFIG_INJECT 'UMask=' 'UMask=0002' $G_FP_DIETPI_USERDATA/nzbget/nzbget.conf

			fi
			#-------------------------------------------------------------------------------
			#Assure absence of dhcpcd5, if dhclient (isc-dhcp-client) is active: https://github.com/Fourdee/DietPi/issues/1560#issuecomment-370136642
			pgrep 'dhclient' &> /dev/null && G_AGP dhcpcd5
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 13 )); then

			#-------------------------------------------------------------------------------
			#Encrypt and secure GLOBAL_PW used by DietPi-Software: https://github.com/Fourdee/DietPi/issues/2021
			if [[ ! -r '/var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin' ]]; then

				local pw_dietpi_software="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_GLOBAL_PASSWORD=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
				# - Failsafe, should never occur.
				[[ $pw_dietpi_software ]] || pw_dietpi_software='dietpi'

				G_CONFIG_INJECT 'AUTO_SETUP_GLOBAL_PASSWORD=' 'AUTO_SETUP_GLOBAL_PASSWORD=Password has been encrypted and secured on rootFS' /DietPi/dietpi.txt

				mkdir -p /var/lib/dietpi/dietpi-software #should already exist, failsafe
				echo "$pw_dietpi_software" | openssl enc -base64 -e -aes-256-cbc -nosalt -pass pass:DietPiRocks! > /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin

				unset pw_dietpi_software

			fi
			/DietPi/dietpi/func/dietpi-set_software setpermissions
			#-------------------------------------------------------------------------------
			#BruteFIR removal
			sed -i '/^aSOFTWARE_INSTALL_STATE\[38\]=/c\aSOFTWARE_INSTALL_STATE\[38\]=0' /DietPi/dietpi/.installed &> /dev/null
			#-------------------------------------------------------------------------------
			# - Recreate machine-id: https://github.com/Fourdee/DietPi/issues/2015
			rm /etc/machine-id &> /dev/null
			rm /var/lib/dbus/machine-id &> /dev/null
			systemd-machine-id-setup
			#-------------------------------------------------------------------------------
			#Sparky SBC, WiFi rtl8812au driver: https://github.com/sparky-sbc/sparky-test/tree/master/rtl8812au
			if (( $G_HW_MODEL == 70 )); then

				G_RUN_CMD wget https://raw.githubusercontent.com/sparky-sbc/sparky-test/master/rtl8812au/rtl8812au_sparky.tar
				mkdir -p rtl8812au_sparky
				tar -xvf rtl8812au_sparky.tar -C rtl8812au_sparky
				chmod +x -R rtl8812au_sparky
				cd rtl8812au_sparky
				G_RUN_CMD ./install.sh
				cd ..
				rm -R rtl8812au_sparky*

			fi
			#-------------------------------------------------------------------------------
			#Reinstalls:
			#	NAA: https://dietpi.com/phpbb/viewtopic.php?f=11&t=4420&p=13914#p13914
			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/dietpi-software reinstall 124
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 14 )); then

			#-------------------------------------------------------------------------------
			#Reinstall fake-hwclock: https://github.com/Fourdee/DietPi/issues/2035#issuecomment-416345155
			G_AGI fake-hwclock
			#-------------------------------------------------------------------------------
			#Disable net offload for devices which are prone to stability issues with it enabled (@carlosedp): https://github.com/Fourdee/DietPi/issues/2028#issue-352323603
			for file in /etc/network/if-up.d/*
			do

				if [[ -f $file && $file != *'dietpi-disable_offload' ]] &&
					grep -qi '\$ETHTOOL -K "\$IFACE" rx off tx off' $file; then

					rm $file

				fi

			done
			chmod +x /etc/network/if-up.d/dietpi-disable_offload
			#-------------------------------------------------------------------------------
			#Sparky kernel update: https://github.com/sparky-sbc/sparky-test/tree/master/dsd-marantz
			if (( $G_HW_MODEL == 70 )); then

				#	patches
				G_RUN_CMD wget https://raw.githubusercontent.com/sparky-sbc/sparky-test/master/dsd-marantz/snd-usb-audio.ko -O /lib/modules/3.10.38/kernel/sound/usb/snd-usb-audio.ko
				G_RUN_CMD wget https://raw.githubusercontent.com/sparky-sbc/sparky-test/master/dsd-marantz/snd-usbmidi-lib.ko -O /lib/modules/3.10.38/kernel/sound/usb/snd-usbmidi-lib.ko

			fi
			#-------------------------------------------------------------------------------
			#Reinstalls:
			#	MPD: https://github.com/Fourdee/DietPi/issues/2032#issuecomment-415559451
			# 	PlexPy: https://github.com/Fourdee/DietPi/issues/2047
			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/dietpi-software reinstall 128 146
			#-------------------------------------------------------------------------------
			#Update DietPi-Sync save file to new format
			if [[ -f /DietPi/dietpi/.dietpi-sync_settings ]] && ! grep -q '^FP_SOURCE=' /DietPi/dietpi/.dietpi-sync_settings; then

				cp /DietPi/dietpi/.dietpi-sync_settings /DietPi/dietpi/.dietpi-sync_settings_bk
				cat << _EOF_ > /DietPi/dietpi/.dietpi-sync_settings
FP_SOURCE=$(sed -n 1p /DietPi/dietpi/.dietpi-sync_settings_bk)
FP_TARGET=$(sed -n 2p /DietPi/dietpi/.dietpi-sync_settings_bk)
SYNC_DELETE_MODE=$(sed -n 3p /DietPi/dietpi/.dietpi-sync_settings_bk)
SYNC_COMPRESSION=$(sed -n 4p /DietPi/dietpi/.dietpi-sync_settings_bk)
SYNC_CRONDAILY=$(sed -n 5p /DietPi/dietpi/.dietpi-sync_settings_bk)
_EOF_

			fi
			#-------------------------------------------------------------------------------
			#Preboot script addition
			systemctl enable dietpi-preboot.service
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 15 )); then

			#-------------------------------------------------------------------------------
			#Move to new WiFi cred array system and db store: https://github.com/Fourdee/DietPi/issues/368
			if [[ ! -f /var/lib/dietpi/dietpi-wifi.db ]]; then

				cat << _EOF_ > /var/lib/dietpi/dietpi-wifi.db
aWIFI_SSID[0]="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_NET_WIFI_SSID=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
aWIFI_KEY[0]="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_NET_WIFI_KEY=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
aWIFI_KEYMGR[0]="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_NET_WIFI_KEYMGR=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
aWIFI_PROTO[0]="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_NET_WIFI_PROTO=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
aWIFI_PAIRWISE[0]="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_NET_WIFI_PAIRWISE=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
aWIFI_AUTH_ALG[0]="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_NET_WIFI_AUTH_ALG=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
aWIFI_EAP[0]="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_NET_WIFI_EAP=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
aWIFI_IDENTITY[0]="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_NET_WIFI_IDENTITY=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
aWIFI_PASSWORD[0]="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_NET_WIFI_PASSWORD=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
aWIFI_PHASE1[0]="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_NET_WIFI_PHASE1=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
aWIFI_PHASE2[0]="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_NET_WIFI_PHASE2=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
aWIFI_CERT[0]="$(grep -m1 '^[[:blank:]]*AUTO_SETUP_NET_WIFI_CERT=' /DietPi/dietpi.txt | sed 's/^[^=]*=//')"
_EOF_

				# - Apply + init the remaninder of array (5) + set permissions on file
				/DietPi/dietpi/func/dietpi-wifidb 1

			fi
			#-------------------------------------------------------------------------------
			#Fix rare WiFi interface start issue: https://github.com/Fourdee/DietPi/issues/2074
			sed -i '\|^[[:blank:]]ifconfig "$IFACE" up$|c\\t/sbin/ip link set dev "$IFACE" up' /etc/network/if-pre-up.d/wireless-tools &> /dev/null
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 16 )); then

			#-------------------------------------------------------------------------------
			#Survey/BugReport SFTP uploads, add cert for access: https://github.com/Fourdee/DietPi/issues/2022
			# - Switch to "ssh.dietpi.com" die to Cloudflare: https://github.com/Fourdee/DietPi/issues/2022
			#	- On v6.15 this was missing in PREP, thus images created meanwhile, so redo with v6.17 patch:
			mkdir -p /root/.ssh
			>> /root/.ssh/known_hosts
			sed -i '/^dietpi.com/d' /root/.ssh/known_hosts
			sed -i '/^185.101.93.93/d' /root/.ssh/known_hosts
			G_CONFIG_INJECT 'ssh.dietpi.com[[:blank:]]' 'ssh.dietpi.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDE6aw3r6aOEqendNu376iiCHr9tGBIWPgfrLkzjXjEsHGyVSUFNnZt6pftrDeK7UX+qX4FxOwQlugG4fymOHbimRCFiv6cf7VpYg1Ednquq9TLb7/cIIbX8a6AuRmX4fjdGuqwmBq3OG7ZksFcYEFKt5U4mAJIaL8hXiM2iXjgY02LqiQY/QWATsHI4ie9ZOnwrQE+Rr6mASN1BVFuIgyHIbwX54jsFSnZ/7CdBMkuAd9B8JkxppWVYpYIFHE9oWNfjh/epdK8yv9Oo6r0w5Rb+4qaAc5g+RAaknHeV6Gp75d2lxBdCm5XknKKbGma2+/DfoE8WZTSgzXrYcRlStYN' /root/.ssh/known_hosts
			#-------------------------------------------------------------------------------
			#Rock64, remove HW accell config, as its not currently functional: https://github.com/Fourdee/DietPi/issues/2086
			(( $G_HW_MODEL == 43 )) && rm /etc/X11/xorg.conf.d/20-armsoc.conf &> /dev/null
			#-------------------------------------------------------------------------------
			# - Convert and remove old dietpi.txt entry (this includes the comment):
			if grep -q 'CONFIG_PREFER_IPVERSION' /DietPi/dietpi.txt; then

				! grep -q '^[[:blank:]]*CONFIG_PREFER_IPVERSION=ipv4' /DietPi/dietpi.txt && G_CONFIG_INJECT 'CONFIG_PREFER_IPV4=' 'CONFIG_PREFER_IPV4=0' /DietPi/dietpi.txt
				sed -i '/CONFIG_PREFER_IPVERSION/d' /DietPi/dietpi.txt

			fi
			#-------------------------------------------------------------------------------
			#Update IPv6 handling: https://github.com/Fourdee/DietPi/issues/2027
			# - Advice user to re-enable IPv6 on kernel level
			if [[ ! -d /proc/sys/net/ipv6 ]]; then

				G_WHIP_MENU_ARRAY=(

					0 ': Re-enable IPv6 on kernel level, disable via sysctl instead (Recommended)'
					1 ': Keep IPv6 disabled on kernel level, I know what I am doing!'

				)
				G_WHIP_DEFAULT_ITEM=0
				G_WHIP_MENU '[WARNING] IPv6 is disabled via kernel module blacklist or boot cmd line.\n
This feature was previously offered via DietPi-Config and has since been removed.\n
Since more and more software requires and expects IPv6 kernel settings to be available. If you keep the current settings, this might lead to APT install errors and/or general system instability.\n
We strongly recommend you select "0 : Re-enable IPv6 on kernel level". By doing so, IPv6 will remain disabled for the interfaces at sysctl level, and, no IPv6 addresses will be assigned to your network devices.\n\nTLDR: Select option "0" :)'
				if (( ! $? )) && (( ! $G_WHIP_RETURNED_VALUE )); then

					# - Remove kernel module blacklisting
					rm /etc/modprobe.d/99-dietpi-blacklist-ipv6.conf &> /dev/null
					# - Failsafe: Comment "blacklist ipv6" entries in all other sysctl config files
					local i=''
					for i in /etc/modprobe.d/*
					do

						[[ -f $i ]] && sed -i 's/^[[:blank:]]*blacklist[[:blank:]]ipv6/#&/' $i

					done

					# - Remove boot cmd line entry
					# -- RPi
					if (( $G_HW_MODEL < 10 )); then

						# Separatly remove with leading and trailing blank, since we don't know, if it's first or last argument and we must not remove both blanks
						sed -i '/^[[:blank:]]*root=/s/[[:blank:]]ipv6.disable=1//' /boot/cmdline.txt
						sed -i '/^[[:blank:]]*root=/s/ipv6.disable=1[[:blank:]]//' /boot/cmdline.txt

					# -- Odroid
					elif (( $G_HW_MODEL < 15 )); then

						sed -i '/^[[:blank:]]*setenv boot/s/[[:blank:]]ipv6.disable=1//' /DietPi/boot.ini
						sed -i '/^[[:blank:]]*setenv boot/s/ipv6.disable=1[[:blank:]]//' /DietPi/boot.ini

					# -- x86
					elif (( $G_HW_ARCH == 10 )); then

						sed -i '/^[[:blank:]]*GRUB_CMDLINE_LINUX_DEFAULT="/s/[[:blank:]]ipv6.disable=1//' /etc/default/grub
						sed -i '/^[[:blank:]]*GRUB_CMDLINE_LINUX_DEFAULT="/s/ipv6.disable=1[[:blank:]]//' /etc/default/grub
						update-grub

					fi

					# - Disable IPv6 via sysctl
					echo -e 'net.ipv6.conf.all.disable_ipv6=1\nnet.ipv6.conf.default.disable_ipv6=1' > /etc/sysctl.d/dietpi-disable_ipv6.conf
					G_CONFIG_INJECT 'CONFIG_ENABLE_IPV6=' 'CONFIG_ENABLE_IPV6=0' /DietPi/dietpi.txt
					# -- Do not prefer IPv4, if IPv6 is disabled anyway
					/DietPi/dietpi/func/dietpi-set_hardware preferipv4 0

				fi

			fi
			#-------------------------------------------------------------------------------
			#Reinstalls:
			#	MPD
			#	Chromium: Update kiosk mode autostart script: https://github.com/Fourdee/DietPi/issues/2158
			if (( $G_DIETPI_INSTALL_STAGE == 1 )); then

				/DietPi/dietpi/dietpi-software reinstall 113 128

				#Run Transmission and Plex Media Server as "dietpi" group: https://github.com/Fourdee/DietPi/issues/2067#issuecomment-427579779
				if grep -q '^aSOFTWARE_INSTALL_STATE\[44\]=2' /DietPi/dietpi/.installed; then

					mkdir -p /etc/systemd/system/transmission-daemon.service.d
					echo -e '[Service]\nGroup=dietpi' >> /etc/systemd/system/transmission-daemon.service.d/dietpi-group.conf
					G_CONFIG_INJECT '\"umask\":' '    "umask": 7,' /etc/transmission-daemon/settings.json

				fi
				if grep -q '^aSOFTWARE_INSTALL_STATE\[42\]=2' /DietPi/dietpi/.installed; then

					mkdir -p /etc/systemd/system/plexmediaserver.service.d
					echo -e '[Service]\nGroup=dietpi' >> /etc/systemd/system/plexmediaserver.service.d/dietpi-group.conf

				fi

			fi
			#-------------------------------------------------------------------------------
			#Now part of rootfs: https://github.com/Fourdee/DietPi/issues/2103
			chmod +x /var/lib/dietpi/services/dietpi-wifi-monitor.sh
			#-------------------------------------------------------------------------------
			#Sparky SBC update USB network script:
			if (( $G_HW_MODEL == 70 )); then

				# - Disable onboard ETH if adapter found
				cat << _EOF_ > /etc/systemd/system/sparky_eth_controller.service
[Unit]
Description=Sparky auto detect and set onboard ETH/USB ETH
After=network.target networking.service

[Service]
Type=simple
RemainAfterExit=yes
ExecStart=/bin/bash -c '/usr/local/bin/sparky_eth_controller.sh'

[Install]
WantedBy=multi-user.target
_EOF_

				systemctl enable sparky_eth_controller.service

				cat << _EOF_ > /usr/local/bin/sparky_eth_controller.sh
#!/bin/bash
#We need to wait until USB eth is established on USB bus. This takes much longer than onboard init and network.target network-pre.target
sleep 20
# - Set USB ETH if found
if ip a | grep -qi 'eth1'; then

	echo 'blacklist ethernet' > /etc/modprobe.d/disable_sparkysbc_ethernet.conf
	rm /etc/udev/rules.d/70-persistent-net.rules &> /dev/null
	rm /etc/udev/rules.d/70-persistant-net.rules &> /dev/null
	reboot

# - Enable onboard ETH if no adapter found
elif ! ip a | grep -qi 'eth0'; then

	rm /etc/modprobe.d/disable_sparkysbc_ethernet.conf &> /dev/null
	rm /etc/udev/rules.d/70-persistent-net.rules &> /dev/null
	rm /etc/udev/rules.d/70-persistant-net.rules &> /dev/null
	reboot

fi
_EOF_

				chmod +x /usr/local/bin/sparky_eth_controller.sh

			fi
			systemctl daemon-reload
			#-------------------------------------------------------------------------------
			#Failsafe, assure /var/tmp 777 permissions: https://github.com/Fourdee/DietPi/issues/1144#issuecomment-425758727
			chmod 777 /var/tmp
			#-------------------------------------------------------------------------------
			#Remove obsolete EMR patch file and redo removal of obsolete script files, as they were not removed from disk: https://github.com/Fourdee/DietPi/pull/2123#issuecomment-428121908
			for i in /DietPi/dietpi /boot/dietpi
			do

				[[ -f $i/conf/deluge.service ]] && rm $i/conf/deluge.service
				[[ -f $i/dietpi-obtain_hw_model ]] && rm $i/dietpi-obtain_hw_model
				[[ -f $i/dietpi-cpu_set ]] && rm $i/dietpi-cpu_set
				[[ -f $i/.patch_emr ]] && rm $i/.patch_emr
				[[ -f $i/dietpi-ramlog ]] && rm $i/dietpi-ramlog
				[[ -f $i/dietpi-ramdisk ]] && rm $i/dietpi-ramdisk
				[[ -f $i/dietpi-logclear ]] && rm $i/dietpi-logclear
				[[ -f $i/dietpi-banner ]] && rm $i/dietpi-banner
				[[ -f $i/pre-patch_file ]] && rm $i/pre-patch_file

			done
			#-------------------------------------------------------------------------------
			#Remove www-data under sudo without PW: https://github.com/Fourdee/DietPi/issues/2121
			sed -i '/^www-data ALL=NOPASSWD: ALL/d' /etc/sudoers
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 17 )); then

			#-------------------------------------------------------------------------------
			# - Remove mysql.service as we use mariadb.service, both cannot exist: https://github.com/Fourdee/DietPi/issues/1913#issuecomment-441343798
			if [[ -f /etc/init.d/mysql ]] && (( $G_DISTRO >= 4 )); then

				G_DIETPI-NOTIFY 2 'Switching from /etc/init.d/mysql to mariadb.service'

				killall -w mariadb &> /dev/null #failsafe
				killall -w mysqld &> /dev/null #failsafe
				systemctl stop mysql
				rm /etc/init.d/mysql
				systemctl daemon-reload

			fi
			#-------------------------------------------------------------------------------
			#Workarounds
			# - Workaround for NanoPi Fire3 with tty1 disabled: https://github.com/Fourdee/DietPi/issues/2225
			if (( $G_HW_MODEL == 62 )) && dmesg | grep -qi 'NanoPi Fire3'; then

				chvt 2
				cat << _EOF_ > /var/lib/dietpi/postboot.d/fire3_tty2
#!/bin/bash
chvt 2
_EOF_

			fi
			#-------------------------------------------------------------------------------
			#Reinstalls:
			#	OMPD: https://github.com/Fourdee/DietPi/issues/2156#issue-372201367
			#	MyMPD: https://github.com/Fourdee/DietPi/issues/2156#issue-372201367
			#	RoonBridge: https://community.roonlabs.com/t/dietpi-allo-units-not-getting-the-roonbridge-b167-update-from-b164/52503/10?u=dan_knight
			#	Radarr/lidarr/sonarr/jacket: https://github.com/Fourdee/DietPi/issues/2219
			#	Mosquitto: https://github.com/Fourdee/DietPi/issues/2243#issuecomment-439492463
			if (( $G_DIETPI_INSTALL_STAGE == 1 )); then

				/DietPi/dietpi/dietpi-software reinstall 121 129 148 106 144 145 147 123
				# - Switch to "mariadb" systemd service on Stretch+: https://github.com/Fourdee/DietPi/pull/2196
				if (( $G_DISTRO > 3 )) && grep -q '^aSOFTWARE_INSTALL_STATE\[88\]=2' /DietPi/dietpi/.installed; then

					G_WHIP_MSG '[ INFO ] Switch from "mysql" to "mariadb" service\n
On Stretch (and above) systems, DietPi-Services will use the pre-installed "mariadb" systemd service now, instead of the obsolete "mysql" init.d service.\n
You will not face any practical differences, since both services start the same MariaDB binary. In case you manually want to handle the service, use "systemctl start|stop|restart mariadb" from now on.'

				fi

			fi
			#-------------------------------------------------------------------------------
			#systemd-logind required for shutdown options: https://github.com/Fourdee/DietPi/issues/2155#issuecomment-437702869
			if (( $G_DIETPI_INSTALL_STAGE == 1 )) && grep -q '^aSOFTWARE_INSTALL_STATE\[31\]=2' /DietPi/dietpi/.installed; then

				systemctl unmask systemd-logind

			fi
			#-------------------------------------------------------------------------------
			#Patch Odroid LCD: https://github.com/Fourdee/DietPi/issues/2256
			if [[ -f /etc/systemd/system/odroid-lcd35.service ]]; then

				/DietPi/dietpi/func/dietpi-set_hardware lcdpanel odroid-lcd35

			fi
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 18 )); then

			#-------------------------------------------------------------------------------
			#conf moved to github
			local afp_config_remove=(

				'smb.conf'
				'vsftpd.conf'
				'xorg_c1.conf'
				'xorg_c2.conf'
				'xorg_xu4.conf'
				'raspimjpeg.service'
				'proftpd.conf'
				'phpsysinfo.ini'
				'opentyrian_run'
				'openbazaar-server.service' #Not actually used in dps...
				'kodi_udev'
				'haproxy_init'
				'nginx.sites-dietpi.pydio.config'
				'nginx.sites-dietpi.owncloud.config'
				'nginx.sites-dietpi.nextcloud.config'
				'nginx.site-available-default'
				'nginx.conf'
				'minidlna.conf'
				'lighttpd.pydio.conf'
				'apache.pydio.conf'
				'lighttpd.nextcloud.conf'
				'deluge_web.conf'
				'deluge.conf'
				'apache.ownnextcloud.conf'
				'apache2_jessie.conf'
				'squeezelite.service'
				'roonbridge.service'
				'netdata.service'

			)

			for i in "${!afp_config_remove[@]}"
			do

				rm /DietPi/dietpi/conf/${afp_config_remove[$i]} /boot/dietpi/conf/${afp_config_remove[$i]} &> /dev/null

			done

			unset afp_config_remove
			#-------------------------------------------------------------------------------
			#conf renaming: https://github.com/Fourdee/DietPi/pull/2312/files
			# - Apache
			if [[ -f /etc/apache2/sites-available/owncloud.conf ]]; then

				a2dissite owncloud
				mv /etc/apache2/sites-available/owncloud.conf /etc/apache2/sites-available/dietpi-owncloud.conf
				a2ensite dietpi-owncloud

			fi
			if [[ -f /etc/apache2/sites-available/nextcloud.conf ]]; then

				a2dissite nextcloud
				mv /etc/apache2/sites-available/nextcloud.conf /etc/apache2/sites-available/dietpi-nextcloud.conf
				a2ensite dietpi-nextcloud

			fi
			if [[ -f /etc/apache2/sites-available/rutorrent.conf ]]; then

				a2dissite rutorrent
				mv /etc/apache2/sites-available/rutorrent.conf /etc/apache2/sites-available/dietpi-rutorrent.conf
				a2ensite dietpi-rutorrent

			fi
			# - Nginx
			[[ -f /etc/nginx/sites-dietpi/owncloud.config ]] && mv /etc/nginx/sites-dietpi/owncloud.config /etc/nginx/sites-dietpi/dietpi-owncloud.conf
			[[ -f /etc/nginx/sites-dietpi/nextcloud.config ]] && mv /etc/nginx/sites-dietpi/nextcloud.config /etc/nginx/sites-dietpi/dietpi-nextcloud.conf
			[[ -f /etc/nginx/sites-dietpi/rutorrent.config ]] && mv /etc/nginx/sites-dietpi/rutorrent.config /etc/nginx/sites-dietpi/dietpi-rutorrent.conf
			#	- Failsafe and custom entries
			for i in /etc/nginx/sites-dietpi/*.config
			do

				[[ -f $i ]] || break
				mv $i ${i%ig}

			done
			#	- Apply to Nginx vhost
			#	- Move to v6.19 => v6.20 patch for users, which update directly from v6.19.5 to v6.20
			#grep -q 'include /etc/nginx/sites-dietpi/\*\.config;' /etc/nginx/sites-available/default &> /dev/null && G_CONFIG_INJECT 'include /etc/nginx/sites-dietpi/\*\.config;' 'include /etc/nginx/sites-dietpi/*.conf;' /etc/nginx/sites-available/default
			# - Kodi input rules
			[[ -f /etc/udev/rules.d/99-input.rules ]] && mv /etc/udev/rules.d/99-input.rules /etc/udev/rules.d/99-dietpi-kodi.rules
			#-------------------------------------------------------------------------------
			#Asus TB 2.0.8 image, fix corrupt characters in desktops
			if (( $G_HW_MODEL == 52 )) && dpkg --get-selections | grep -q 'fonts-dejavu-core'; then

				G_AGI --reinstall libfreetype6 fonts-dejavu-core
				G_RUN_CMD fc-cache -r -v

			fi
			#-------------------------------------------------------------------------------
			#Switch to udev rule for WiFi powersaving disable
			rm /etc/systemd/system/wifi_disable_powersave.service &> /dev/null
			systemctl daemon-reload
			#-------------------------------------------------------------------------------
			# - Reinstalls
			#	Chromium: https://github.com/Fourdee/DietPi/issues/2298
			#	Allo GUI: https://github.com/Fourdee/DietPi/issues/2305
			#	GMrender: Due to Allo GUI service enable failure.
			#	Xorg: XU4 conf
			#	Pydio: https://github.com/Fourdee/DietPi/issues/2308
			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/dietpi-software reinstall 48 113 160 163 6
			#-------------------------------------------------------------------------------

		elif (( $G_DIETPI_VERSION_SUB == 19 )); then

			#-------------------------------------------------------------------------------
			#Apply Nginx vhost patch: https://github.com/Fourdee/DietPi/pull/2327
			#	- Moved from v6.18 => v6.19 patch for users, which update directly from v6.19.5 to v6.20
			grep -q 'include /etc/nginx/sites-dietpi/\*\.config;' /etc/nginx/sites-available/default &> /dev/null && G_CONFIG_INJECT 'include /etc/nginx/sites-dietpi/\*\.config;' 'include /etc/nginx/sites-dietpi/*.conf;' /etc/nginx/sites-available/default
			#-------------------------------------------------------------------------------
			#Migrate Blynk to new dir structure: https://github.com/Fourdee/DietPi/issues/2322
			if (( $G_DIETPI_INSTALL_STAGE == 1 )) && grep -q '^aSOFTWARE_INSTALL_STATE\[131\]=2' /DietPi/dietpi/.installed &&
				[[ -d $G_FP_DIETPI_USERDATA/blynk && ! -d $G_FP_DIETPI_USERDATA/blynk/data ]]; then

				mv $G_FP_DIETPI_USERDATA/blynk $G_FP_DIETPI_USERDATA/blynk_bak
				mv /etc/blynkserver $G_FP_DIETPI_USERDATA/blynk
				mv $G_FP_DIETPI_USERDATA/blynk/server.jar $G_FP_DIETPI_USERDATA/blynk/blynkserver.jar
				mv $G_FP_DIETPI_USERDATA/blynk_bak/server.properties $G_FP_DIETPI_USERDATA/blynk/
				mv $G_FP_DIETPI_USERDATA/blynk_bak $G_FP_DIETPI_USERDATA/blynk/data
				G_CONFIG_INJECT 'data.folder=' "data.folder=$G_FP_DIETPI_USERDATA/blynk/data" $G_FP_DIETPI_USERDATA/blynk/server.properties

			fi
			#-------------------------------------------------------------------------------
			# - Reinstalls
			#	Blynk: Apply new run user, update binary (jar)
			#	Deluge: https://github.com/Fourdee/DietPi/issues/2339
			(( $G_DIETPI_INSTALL_STAGE == 1 )) && /DietPi/dietpi/dietpi-software reinstall 131 45
			#-------------------------------------------------------------------------------
			#Docker fix on RPi due to faulty current "docker-ce" repo version: https://github.com/Fourdee/DietPi/issues/2282
			local dpkg_out=''
			if (( G_HW_MODEL < 10 )) && dpkg_out="$(dpkg-query -s 'docker-ce' 2>&1)"; then

  				echo 'Package: docker-ce
Pin: version 5:18.09.0~3-0~raspbian-stretch
Pin-Priority: -1' > /etc/apt/preferences.d/dietpi-docker_fix

  				if grep -q '5:18.09.0~3-0~raspbian-stretch' <<< "$dpkg_out"; then

  					G_DIETPI-NOTIFY 2 'Docker: Downgrading your "docker-ce" package to the last working version'
					G_AGI docker-ce=18.06.1~ce~3-0~raspbian
					G_AGA

  				fi

  			fi
			#-------------------------------------------------------------------------------
			#DietPi file renaming/removal:
			# - autologin.conf: https://github.com/Fourdee/DietPi/pull/2343
			# - README.md: https://github.com/Fourdee/DietPi/pull/2341
			[[ -f /etc/systemd/system/getty@tty1.service.d/autologin.conf ]] && mv /etc/systemd/system/getty@tty1.service.d/autologin.conf /etc/systemd/system/getty@tty1.service.d/dietpi-autologin.conf
			[[ -f /boot/README.md ]] && mv /boot/README.md /boot/dietpi-README.md
			# - Possible leftover from PREP:
			[[ -f /DietPi/dietpi/pre-patch_file ]] && rm /DietPi/dietpi/pre-patch_file
			[[ -f /boot/dietpi/pre-patch_file ]] && rm /boot/dietpi/pre-patch_file
			#-------------------------------------------------------------------------------
			#.dietpi-autostart_index removal, if zero: https://github.com/Fourdee/DietPi/pull/2343
			[[ -f /DietPi/dietpi/.dietpi-autostart_index ]] && [[ $(</DietPi/dietpi/.dietpi-autostart_index) == 0 ]] && rm /DietPi/dietpi/.dietpi-autostart_index && [[ -f /boot/dietpi/.dietpi-autostart_index ]] && rm /boot/dietpi/.dietpi-autostart_index
			#-------------------------------------------------------------------------------

		fi

		#-------------------------------------------------------------------------------
		#NB: all if statements must contain at least one command. Prevents bash having a hissy fit :)
		#	The fastest dummy command is ":", which really does nothing ;).
		#-------------------------------------------------------------------------------

	}

	#-------------------------------------------------------------------------------
	#Run
	Incremental_Patch_System
	#-------------------------------------------------------------------------------
	sleep 0.25
	#-------------------------------------------------------------------------------
	exit
	#-------------------------------------------------------------------------------

}
