#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Patch File Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Online patching for hosts filesystem.
	# - Runs from dietpi-update
	#
	# Usage:
	# - /DietPi/dietpi/patch_file iCurrentVersion iServerVersion
	#////////////////////////////////////

	#/////////////////////////////////////////////////////////////////////////////////////
	#VERSION CODE
	#/////////////////////////////////////////////////////////////////////////////////////
	VERSION_CURRENT=$1
	VERSION_SERVER=$2
	
	#/////////////////////////////////////////////////////////////////////////////////////
	#Obtain Pi/Odroid Model
	#/////////////////////////////////////////////////////////////////////////////////////
	
	HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)
	HW_MODEL_DESCRIPTION=$(sed -n 2p /DietPi/dietpi/.hw_model)
	DISTRO=$(sed -n 3p /DietPi/dietpi/.hw_model)
	
	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#Info
	echo -e "Patching $VERSION_CURRENT to $VERSION_SERVER"

	if (( $VERSION_CURRENT == 70 )); then
		echo -e "70 > 71 patch"
		#-------------------------------------------------------------------------------
		#Update DietPi Service
		update-rc.d -f dietpi-service remove
		rm /etc/init.d/dietpi-service
		cp /DietPi/dietpi/conf/dietpi-service /etc/init.d/dietpi-service
		chmod +x /etc/init.d/dietpi-service
		update-rc.d dietpi-service defaults 80 01
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 71 )); then
		echo -e "71 > 72 patch"
		#-------------------------------------------------------------------------------
		#DietPi-Software | Added DietPi optimized installation option for "Grasshopper" (Web App to control Bticino MyHome).
		#-------------------------------------------------------------------------------
		#Update CPU alias
		sed -i "/alias cpu=/c\alias cpu='/DietPi/dietpi/dietpi-cpu_info'" /etc/bash.bashrc
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 72 )); then
		echo -e "72 > 73 patch"
		#-------------------------------------------------------------------------------
		#Patch for DietPicam /root installs (media cannot be located in /root folder)
		if [ -f /DietPi/dietpi/.installed ]; then
			if (( $(cat /DietPi/dietpi/.installed | grep -m1 'DIETPICAM ' | awk '{print $2}') == 2 )) && 
				[ -d /root/dietpicam ]; then

				rm -R /root/dietpicam
				
				mkdir -p /dietpicam
				rm -R /var/www/dietpicam/media
				ln -s /dietpicam /var/www/dietpicam/media
				chown -R www-data:www-data /dietpicam
				chmod -R 777 /dietpicam
			fi
		fi
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 73 )); then
		echo -e "73 > 74 patch"
		#-------------------------------------------------------------------------------
		#Force fakeclock to use the current time (this prevents fakeclock from setting the correct time when user changes tzdata)
		sed -i "/FORCE=/c\FORCE=force" /etc/default/fake-hwclock
		#-------------------------------------------------------------------------------
		#Set dietpicam installations to 128mb GPU (for rpi v1 devices).
		if [ -f /DietPi/dietpi/.installed ]; then
			if (( $(cat /DietPi/dietpi/.installed | grep -m1 'DIETPICAM ' | awk '{print $2}') == 2 )); then

				if (( $HW_MODEL == 0 )); then
					gpu_mem_current=$(grep -m1 'gpu_mem_256=' /DietPi/config.txt  | sed 's/gpu_mem_256=//g')
				elif (( $HW_MODEL == 1 )); then
					gpu_mem_current=$(grep -m1 'gpu_mem_512=' /DietPi/config.txt  | sed 's/gpu_mem_512=//g')
				elif (( $HW_MODEL == 2 )); then
					gpu_mem_current=$(grep -m1 'gpu_mem_1024=' /DietPi/config.txt  | sed 's/gpu_mem_1024=//g')
				fi
				
				if (( $gpu_mem_current < 128 )); then
					sed -i '/gpu_mem_256=/c\gpu_mem_256=128' /DietPi/config.txt
					sed -i '/gpu_mem_512=/c\gpu_mem_512=128' /DietPi/config.txt
					sed -i '/gpu_mem_1024=/c\gpu_mem_1024=128' /DietPi/config.txt
				fi
			fi
		fi
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 74 )); then
		echo -e "74 > 75 patch"
		#-------------------------------------------------------------------------------
		#Ensure dpkg isnt locked (wait for apt-get update to finish)
		/DietPi/dietpi/dietpi-apt-get_update 1
		
		#Removal of ramlog
		apt-get purge ramlog -y

		update-rc.d -f ramlog remove
		update-rc.d -f ramlog.uninst remove
		rm /etc/init.d/ramlog*

		#New install, remove additional packages required by ramlog
		if [ ! -f /DietPi/dietpi/.installed ]; then
			apt-get purge rsync lsof -y
		fi
		apt-get autoremove --purge -y
		#-------------------------------------------------------------------------------
		#Add tmpfs /var/log to FStab (to replace ramlog)
		sed -i '/DietPi/a tmpfs                   /var/log                tmpfs   size=10m,noatime,nodev,nosuid,mode=1777  0 0' /etc/fstab
		#-------------------------------------------------------------------------------
		#Update DietPi Service
		update-rc.d -f dietpi-service remove
		rm /etc/init.d/dietpi-service
		cp /DietPi/dietpi/conf/dietpi-service /etc/init.d/dietpi-service
		chmod +x /etc/init.d/dietpi-service
		update-rc.d dietpi-service defaults 00 80
		#-------------------------------------------------------------------------------
		# Create installation information inside client mount locations.
		if (( $(df | grep -ci -m1 '/mnt/samba') == 0 )); then
			echo -e "Samba client can be installed and setup by DietPi-Config.\nSimply run: dietpi-config 8" > /mnt/samba/readme.txt
		fi

		if (( $(df | grep -ci -m1 '/mnt/ftp_client') == 0 )); then
			echo -e "FTP client mount can be installed and setup by DietPi-Config.\nSimply run: dietpi-config 8" > /mnt/ftp_client/readme.txt
		fi
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 75 )); then
		echo -e "75 > 76 patch"
		#-------------------------------------------------------------------------------
		#Re-apply DietPi-Ramlog (did a whoopsie in v74 patch....)
		if [ -f /DietPi/dietpi/.installed ]; then
			TEMP_VAR=$(cat "/DietPi/dietpi/.installed" | grep -m1 'INDEX_LOGGING_CURRENT ' | awk '{print $2}')
			if (( $TEMP_VAR == -1 )) || (( $TEMP_VAR == -2 )); then
				sed -i '/\/var\/log/c\tmpfs                   \/var\/log                tmpfs   size=10m,noatime,nodev,nosuid,mode=1777  0 0' /etc/fstab
			else
				sed -i '/\/var\/log/c\#\/var\/log DietPi Ramlog Disabled' /etc/fstab
			fi
		else
			sed -i '/\/var\/log/c\tmpfs                   \/var\/log                tmpfs   size=10m,noatime,nodev,nosuid,mode=1777  0 0' /etc/fstab
		fi
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 76 )); then
		echo -e "76 > 77 patch"
		#-------------------------------------------------------------------------------
		#Remove conf files converted to EOF inside dietpi-scripts
		rm /DietPi/dietpi/conf/dietpi-bugreport_template.txt
		#-------------------------------------------------------------------------------
		#DietPi-Software
		if [ -f /DietPi/dietpi/.installed ]; then

			#Additions
			if (( $(dpkg -l | grep -ci -m1 'sudo ') == 1 )); then
				echo -e "SUDO_AUTH 2" >> /DietPi/dietpi/.installed
			else
				echo -e "SUDO_AUTH 0" >> /DietPi/dietpi/.installed
			fi
			
			echo -e "RASPCONTROL 0" >> /DietPi/dietpi/.installed
			echo -e "LINUXDASH 0" >> /DietPi/dietpi/.installed
			echo -e "FILESERVER_VSFTPD 0" >> /DietPi/dietpi/.installed
			
			#Apache 2 (disable access log, reduce error log level)
			if (( $(cat /DietPi/dietpi/.installed | grep -m1 'WEBSERVER_APACHE ' | awk '{print $2}') == 2 )); then
				sed -i "/CustomLog /c\        #CustomLog "'${APACHE_LOG_DIR}'"/access.log combined" /etc/apache2/sites-available/*
				sed -i "/LogLevel /c\        LogLevel error" /etc/apache2/sites-available/*
				sed -i "/LogLevel /c\LogLevel error" /etc/apache2/apache2.conf
			fi
		
		fi
		
		#-------------------------------------------------------------------------------
		#Removals
		rm /boot/dietpi/conf/apache2_p1.conf
		rm /boot/dietpi/conf/apache2_p2.conf
		
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 77 )); then
		echo -e "77 > 78 patch"
		#-------------------------------------------------------------------------------
		#Disable overwriting to boot files when starting dietpi-ramdisk
		#Inform the user for their file locations in RamDisk
		sed -i '1 i\#Modifcations to /boot/* files, will not be saved when powered on.\n#Please ensure you edit from the DietPi-RamDisk location /DietPi/*\n' /DietPi/dietpi.txt
		sed -i '1 i\#Modifcations to /boot/* files, will not be saved when powered on.\n#Please ensure you edit from the DietPi-RamDisk location /DietPi/*\n' /DietPi/config.txt
		sed -i '1 i\#Modifcations to /boot/* files, will not be saved when powered on.\n#Please ensure you edit from the DietPi-RamDisk location /DietPi/*\n' /DietPi/boot.ini
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 78 )); then
		echo -e "78 > 79 patch"
		#-------------------------------------------------------------------------------
		#Owncloud with SD card patch (change data dir to /owncloud)
		if  [ -f /DietPi/dietpi/.installed ] &&
			(( $(cat /DietPi/dietpi/.installed | grep -m1 'OWNCLOUD ' | awk '{print $2}') == 2 )) &&
			[ ! -f /DietPi/dietpi/.owncloud_root_data_patched ] &&
			[ -d /root/owncloud ]; then
		
			rm -R /root/owncloud
			rm -R /var/lib/owncloud/data
			mkdir /owncloud
			chown -R www-data:www-data /owncloud
			ln -fs /owncloud /var/lib/owncloud/data

		fi

		rm /DietPi/dietpi/.owncloud_root_data_patched &> /dev/null
		#-------------------------------------------------------------------------------
		#RPi change from deadline to noop scheduler
		if (( $DISTRO == 1 )); then
			sed -i 's/deadline/noop/g' /boot/cmdline.txt
		fi
		#-------------------------------------------------------------------------------
		#Fully disable ipv6 system-wide
		rm /etc/modprobe.d/ipv6.conf &> /dev/null
		echo "net.ipv6.conf.all.disable_ipv6=1" > /etc/sysctl.d/disable_ipv6.conf
		echo 'blacklist ipv6' >> /etc/modprobe.d/blacklist
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 79 )); then
		echo -e "79 > 80 patch"
		#-------------------------------------------------------------------------------
		#IPV6 is still enabled, clean up and apply working method.
		rm /etc/sysctl.d/disable_ipv6.conf &> /dev/null
		rm /etc/modprobe.d/blacklist &> /dev/null
		rm /etc/modprobe.d/blacklist-ipv6 &> /dev/null
		rm /etc/modprobe.d/disable_ipv6.conf &> /dev/null

		echo 'blacklist ipv6' > /etc/modprobe.d/blacklist-ipv6.conf

		echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
		echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf
		echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf
		
		##Odroid C1, need to also modify boot settings to disable ipv6
		##http://forum.odroid.com/viewtopic.php?f=112&t=8287#p64645
		#sed -i "s/rootwait /ipv6.disable=1 rootwait /g" /DietPi/boot.ini
		#sed -i "s/rootwait /ipv6.disable=1 rootwait /g" /media/boot/boot.ini
		# Turns out, this doesnt work, IPV6 is still enabled in ifconfig -a...
		#-------------------------------------------------------------------------------
		#Generate unique Dropbear host-key: ( http://fuzon.co.uk/phpbb/viewtopic.php?f=9&t=37#p156 )
		if (( $( dpkg -l | grep -ci -m1 'dropbear ') == 1 )); then
			rm /etc/dropbear/*key
			#Private
			dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key
		fi
		#-------------------------------------------------------------------------------
		#DietPi check for updates flag
		if (( $( cat /DietPi/dietpi.txt | grep -ci -m1 'dietpi_check_for_updates=') == 0 )); then
			sed -i '/curlftpfs_clientpassword=/a #DietPi check for updates (allows dietpi to check for updates on a daily basis and boot using a <1kb file download.)\ndietpi_check_for_updates=1' /DietPi/dietpi.txt
		fi

		#update cron.daily
		cp /DietPi/dietpi/conf/cron.daily_dietpi /etc/cron.daily/dietpi
		chmod +x /etc/cron.daily/dietpi
		#-------------------------------------------------------------------------------
		#PiHole Addition
		if [ -f /DietPi/dietpi/.installed ]; then
			echo -e "PIHOLE 0" >> /DietPi/dietpi/.installed
		fi
		#-------------------------------------------------------------------------------
		#updated script (now obtains active network adapter)
		chmod -R +x /DietPi/dietpi
		/DietPi/dietpi/func/obtain_network_details
		#-------------------------------------------------------------------------------
		#WEBSERVER_PHPMYADMIN has changed to WEBSERVER_MYADMINPHP
		if [ -f /DietPi/dietpi/.installed ]; then
			sed -i 's/WEBSERVER_PHPMYADMIN /WEBSERVER_MYADMINPHP /g' /DietPi/dietpi/.installed
		fi
		#-------------------------------------------------------------------------------
		#Verify and remove ramlog if still installed
		# - This is required as patch 74 could of encounted dpkg being locked due to background dietpi-apt-get_update.
		# - This prevented ramlog from being uninstalled.
		#Removal of ramlog
		if (( $( dpkg -l | grep -ci -m1 'ramlog ') == 1 )); then
			apt-get purge ramlog -y

			update-rc.d -f ramlog remove
			update-rc.d -f ramlog.uninst remove
			rm /etc/init.d/ramlog*
		fi

		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 80 )); then
		echo -e "80 > 81 patch"
		#-------------------------------------------------------------------------------
		#Files removed from DietPi
		rm /DietPi/dietpi/conf/apache2_p1.conf &> /dev/null
		rm /DietPi/dietpi/conf/apache2_p2.conf &> /dev/null
		rm /DietPi/dietpi/conf/xorg_c1.conf &> /dev/null
		rm /DietPi/dietpi/func/find_network_index &> /dev/null
		rm /DietPi/dietpi/conf/phpinfo.php &> /dev/null
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 81 )); then
		echo -e "81 > 82 patch"
		#-------------------------------------------------------------------------------
		#Left over from v81 passwd change script
		rm /root/passwd &> /dev/null
		#-------------------------------------------------------------------------------
		#DietPi-Software Additions
		if [ -f /DietPi/dietpi/.installed ]; then
			#SubSonic Addition (but not available)
			echo -e "SUBSONIC 0" >> /DietPi/dietpi/.installed
			#webiopi Addition
			echo -e "WEBIOPI 0" >> /DietPi/dietpi/.installed
			#Weaved Addition
			echo -e "WEAVED 0" >> /DietPi/dietpi/.installed
		fi
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 82 )); then
		echo -e "82 > 83 patch"
		#-------------------------------------------------------------------------------
		#Removals
		rm /DietPi/dietpi/conf/asound_c1.conf
		rm /DietPi/dietpi/conf/asound_hifiberry.conf

		rm /DietPi/dietpi/conf/apache2_c1.conf
		rm /DietPi/dietpi/conf/apache2_c1_000-default
		rm /DietPi/dietpi/conf/apache2_c1_mpmevent
		rm /DietPi/dietpi/conf/apache2_c1_mpmprefork
		rm /DietPi/dietpi/conf/apache2_c1_mpmworker

		rm /DietPi/dietpi/conf/mpd_c1.conf
		rm /DietPi/dietpi/conf/mpd_rpi.conf
		#-------------------------------------------------------------------------------
		#8192cu disable power mgr (resolves edimax wifi no route)
		echo -e "options 8192cu rtw_power_mgnt=0" > /etc/modprobe.d/8192cu.conf
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 83 )); then
		echo -e "83 > 84 patch"
		#-------------------------------------------------------------------------------
		# Pi-Hole Automated DietPi image.
		# Increase swap size to 500MB
		if (( $( cat /DietPi/dietpi.txt | grep -ci -m1 'AUTO_Install_Index=3') == 1 )); then

			dphys-swapfile swapoff
			echo -e "CONF_SWAPSIZE=500" > /etc/dphys-swapfile
			dphys-swapfile setup
			dphys-swapfile swapon

		fi
		#-------------------------------------------------------------------------------
		#xu4 image, final touches
		if (( $HW_MODEL == 11 )); then

			update-rc.d -f ondemand remove
			update-rc.d -f ntp remove
			rm /etc/init.d/ondemand
			rm /etc/init.d/ntp

		fi
		#-------------------------------------------------------------------------------
		#DietPi-Software Additions
		if [ -f /DietPi/dietpi/.installed ]; then

			echo -e "DIETPICLOUDSHELL 0" >> /DietPi/dietpi/.installed

		fi
		#-------------------------------------------------------------------------------
		#Ondemand tweaks (lower sample rate 100ms to 25ms, and, increase duration to 1second)
		sed -i '/cpu_ondemand_sampling_rate=/c\cpu_ondemand_sampling_rate=25000' /DietPi/dietpi.txt
		sed -i '/cpu_ondemand_sampling_down_factor=/c\cpu_ondemand_sampling_down_factor=40' /DietPi/dietpi.txt
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 84 )); then
		echo -e "84 > 85 patch"
		#-------------------------------------------------------------------------------
		#DietPi.txt cpu_max_freq
		if (( $( cat /DietPi/dietpi.txt | grep -ci -m1 'cpu_max_frequency=') == 0 )); then
			sed -i '/cpu_usage_throttle_up=/a #Limit the max cpu frequency (Mhz) for all cores. | 0=disabled | Useful for lowering temp/power usage on your device.\ncpu_max_frequency=0' /DietPi/dietpi.txt
		fi
		#-------------------------------------------------------------------------------
		#further ondemand tweaks (2 second down throttle)
		sed -i '/cpu_ondemand_sampling_down_factor=/c\cpu_ondemand_sampling_down_factor=80' /DietPi/dietpi.txt
		#-------------------------------------------------------------------------------
		#Odroid's CPU GOVS, change from ondemand to interactive. Resolves issue with broken C1 ondemand, and, performs miles better than ondemand.
		if (( $HW_MODEL >= 10 )); then
			if (( $(cat /DietPi/dietpi.txt | grep -ci -m1 'cpu_governor=ondemand') == 1 )); then
				sed -i "/cpu_governor=/c\cpu_governor=interactive" /DietPi/dietpi.txt
				#apply
				/DietPi/dietpi/dietpi-cpu_set
			fi
		fi
		#-------------------------------------------------------------------------------
		#DietPi-Software Additions
		if [ -f /DietPi/dietpi/.installed ]; then

			echo -e "HAPROXY 0" >> /DietPi/dietpi/.installed

		fi
		#-------------------------------------------------------------------------------
		#DietPi-Cloudshell v2
		#Remove old config
		rm /DietPi/dietpi/.dietpi-cloudshell &> /dev/null
		#-------------------------------------------------------------------------------
		#XU4 image missing curl
		if (( $HW_MODEL == 11 )); then
			/DietPi/dietpi/dietpi-apt-get_update 1
			apt-get install curl --no-install-recommends -y
		fi
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 85 )); then
		echo -e "85 > 86 patch"
		#-------------------------------------------------------------------------------
		#PIhole (we've changed dnsmasq user to www-data)
		if [ -f /DietPi/dietpi/.installed ]; then
			if (( $(cat /DietPi/dietpi/.installed | grep -m1 'PIHOLE ' | awk '{print $2}') == 2 )); then
				sed -i '/DNSMASQ_USER=/c\DNSMASQ_USER="www-data"' /etc/init.d/dnsmasq
				chown www-data:www-data /var/log/pihole.log				
				#Delete dnsmasq user
				userdel -f dnsmasq
			fi
		fi
		#-------------------------------------------------------------------------------
		
	elif (( $VERSION_CURRENT == 86 )); then
		echo -e "86 > 87 patch"
		#-------------------------------------------------------------------------------
		#Increase /var/log max size to 20mb
		# - Check /var/log exists, and, has tmpfs filesystem.
		if (( $(cat /etc/fstab | grep '/var/log' | grep -ci -m1 'tmpfs') == 1 )); then
			sed -i '/\/var\/log/c\tmpfs                   \/var\/log                tmpfs   defaults,size=20m,noatime,nodev,nosuid,mode=1777  0 0' /etc/fstab
		fi
		#add defaults, to /DietPi mount also
		sed -i '/\/DietPi/c\tmpfs                   \/DietPi                tmpfs   defaults,size=10m,noatime,nodev,nosuid,mode=1777  0 0' /etc/fstab
		#-------------------------------------------------------------------------------

	elif (( $VERSION_CURRENT == 87 )); then
		echo -e "87 > 88 patch"
		#-------------------------------------------------------------------------------
		#-------------------------------------------------------------------------------

	fi

		#-------------------------------------------------------------------------------
		# If we need to apt-get anything, wait for apt-get update thread to finish.
		#/DietPi/dietpi/dietpi-apt-get_update 1
		#-------------------------------------------------------------------------------
	sleep 1
	#-------------------------------------------------------------------------------
	exit
	#-------------------------------------------------------------------------------
}