#!/bin/dash
{
	#////////////////////////////////////
	# DietPi PostBoot Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location: /boot/dietpi/postboot
	# - Run on boot from dietpi-postboot.service after dietpi-preboot.service and optionally after network
	#////////////////////////////////////

	read -r G_DIETPI_INSTALL_STAGE < /boot/dietpi/.install_stage

	# Pre-installed image, 1st run
	if [ "$G_DIETPI_INSTALL_STAGE" = 10 ]
	then
		# Create swap file
		/boot/dietpi/func/dietpi-set_swapfile

		# Run survey
		/boot/dietpi/dietpi-survey

		# Continue with normal boot
		echo 2 > /boot/dietpi/.install_stage
	fi

	# Regular boot
	if [ "$G_DIETPI_INSTALL_STAGE" = 2 ] || [ "$G_DIETPI_INSTALL_STAGE" = 10 ]
	then
		# Run network time sync and check for DietPi updates if chosen, both in background
		if grep -q '^[[:blank:]]*CONFIG_CHECK_DIETPI_UPDATES=1' /boot/dietpi.txt
		then
			# Network time sync is included in every dietpi-update call
			/boot/dietpi/dietpi-update 2 > /dev/null 2>&1 &
		else
			/boot/dietpi/func/run_ntpd > /dev/null 2>&1 &
		fi
	fi

	# Execute optional user scripts
	for f in /var/lib/dietpi/postboot.d/*
	do
		# shellcheck disable=2015
		[ "${f##*/}" != 'readme.txt' ] && [ -f "$f" ] || continue
		[ -x "$f" ] || chmod +x "$f"
		echo "\e[90m[\e[0m INFO \e[90m] DietPi-PostBoot | Running user script: ${f##*/}\e[0m"
		"$f" || echo "\e[90m[\e[31mFAILED\e[90m] DietPi-PostBoot |\e[0m User script ${f##*/} failed with exit code: $?"
	done

	# Print DietPi login banner if no autologin selected
	if [ ! -f '/etc/systemd/system/getty@tty1.service.d/dietpi-autologin.conf' ]
	then
		echo
		/boot/dietpi/func/dietpi-banner 0
		# Print default login credentials only on first boot
		[ "$G_DIETPI_INSTALL_STAGE" = 2 ] || echo '\n Default Login:\n Username = root\n Password = dietpi (or custom dietpi.txt entry)'
		echo '\n Please hit <return> to login\n'
	fi

	#-----------------------------------------------------------------------------------
	exit 0
	#-----------------------------------------------------------------------------------
}
