#!/bin/bash
{
	#////////////////////////////////////
	# DietPi PostBoot Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Filename: /{DietPi,boot}/dietpi/postboot
	# - Finishes boog logs
	# - DietPi-Update check and DietPi-Services start on regular boot
	# - Executes optional user scripts from: /var/lib/dietpi/postboot.d/
	#////////////////////////////////////

	# Safe boot time to log
	mawk '{print $1 " Seconds"}' /proc/uptime > /var/log/boottime &

	# Move all boot logs to disk
	mv /tmp/dietpi-*.log /var/tmp/dietpi/logs/ &

	# Regular boot
	if (( $(</DietPi/dietpi/.install_stage) == 2 )); then

		# - Check for DietPi updates if chosen
		if grep -qi '^[[:blank:]]*CONFIG_CHECK_DIETPI_UPDATES=1' /DietPi/dietpi.txt; then

			/DietPi/dietpi/dietpi-update 2 &> /dev/null &

		fi

		# - Start DietPi controlled services
		/DietPi/dietpi/dietpi-services start

	fi

	# Execute optional user scripts
	for f in /var/lib/dietpi/postboot.d/*
	do

		[[ -f $f ]] || continue
		[[ -x $f ]] || chmod +x $f
		echo "DietPi-PostBoot | Running user script: ${f##*/}"
		$f

	done

	# Print DietPi login banner if no autologin selected
	if [[ ! -f '/etc/systemd/system/getty@tty1.service.d/dietpi-autologin.conf' ]]; then

		echo -e '\n'
		/DietPi/dietpi/func/dietpi-banner 0
		echo -e ' Default Login:\n Username = root\n Password = dietpi\n\n Please login to continue\n'

	fi

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}
