#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Pre-patch script
	#
	#////////////////////////////////////
	# Created by MichaIng / micha@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Online pre-patching for client system for changes made to update system and critical bug fixes
	# - Runs from dietpi-update as very first update step
	# - In case of failure, returns related pre-patch ID as exit code
	# - NB: Keep this script as simple as possible, do not load/call dietpi-globals, to allow fixing most kinds of DietPi code issues!
	#
	# Usage:
	# - ./pre-patch_file $G_DIETPI_VERSION_SUB
	#////////////////////////////////////

	EXIT_CODE=0

	echo -e '\n \e[38;5;154mDietPi-Pre-patch\e[0m
\e[90m─────────────────────────────────────────────────────
 Mode: \e[0mApplying critical pre-patches\n'

	# Grab input, being failsafe when applying to $G_DIETPI_VERSION_SUB
	if [[ $1 =~ ^-?[0-9]+$ ]]; then

		G_DIETPI_VERSION_SUB=$1

	else

		echo -e "\e[90m[\e[0m\e[31mFAILED\e[0m\e[90m]\e[0m No valid input used: $1"
		EXIT_CODE=1

	fi

	#///////////////////////////////////////////////////////////////////////////////
	# Main loop
	#///////////////////////////////////////////////////////////////////////////////

	until (( $EXIT_CODE ))
	do

		#-------------------------------------------------------------------------------
		# Pre-patch 1: RAMlog 0 free space check due to issues with failing DietPi cron jobs in v6.11
		if (( $G_DIETPI_VERSION_SUB < 12 && $(df -B1M --output=avail /var/log | sed -n 2p) < 2 )); then

			echo -e '\e[90m[\e[0m INFO \e[90m]\e[0m Pre-patch 1 | Clearing /var/log files to free up RAMlog space (<2MB) before update will continue'
			/DietPi/dietpi/func/dietpi-logclear 1 || { EXIT_CODE=1; break; }

		fi
		#-------------------------------------------------------------------------------
		# Pre-patch 2: https://github.com/MichaIng/DietPi/pull/2490
		if (( $G_DIETPI_VERSION_SUB < 21 )) && [[ -f /etc/mysql/mariadb.conf.d/99-dietpi-4byte.cnf ]] &&
			grep -qi 'buster' /etc/os-release; then

			echo -e '\e[90m[\e[0m INFO \e[90m]\e[0m Pre-patch 2 | Patching /etc/mysql/mariadb.conf.d/99-dietpi-4byte.cnf for MariaDB v10.3/Buster support'
			sed -i '/innodb_large_prefix/d' /etc/mysql/mariadb.conf.d/99-dietpi-4byte.cnf || { EXIT_CODE=2; break; }
			sed -i '/innodb_file_format/d' /etc/mysql/mariadb.conf.d/99-dietpi-4byte.cnf || { EXIT_CODE=2; break; }

		fi	
		#-------------------------------------------------------------------------------
		# Pre-patch 3: https://github.com/MichaIng/DietPi/issues/2213
		if (( $G_DIETPI_VERSION_SUB < 22 )) &&
			GLOBAL_PW=$(openssl enc -d -a -aes-256-cbc -nosalt -pass pass:'DietPiRocks!' -in /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin 2> /dev/null); then

			echo -e '\e[90m[\e[0m INFO \e[90m]\e[0m Pre-patch 3 | Storing global DietPi-Software password with enhanced security'
			grep -qi 'buster' /etc/os-release && pbkdf2='-iter 10000' || pbkdf2=''
			openssl enc -e -a -md sha256 -aes-256-cbc $pbkdf2 -salt -pass pass:'DietPiRocks!' -out /var/lib/dietpi/dietpi-software/.GLOBAL_PW.bin <<< $GLOBAL_PW || { EXIT_CODE=3; break; }

		fi
		#-------------------------------------------------------------------------------
		# Pre-patch 4: https://github.com/MichaIng/DietPi/issues/2656
		if (( $G_DIETPI_VERSION_SUB < 23 )) &&  [[ -f /etc/apt/preferences.d/dietpi-wireguard ]]; then

			echo -e '\e[90m[\e[0m INFO \e[90m]\e[0m Pre-patch 4 | Hardening Debian Sid repo usage to prevent accidental distro upgrades but allow auto-upgrades for WireGuard packages'
			echo -e 'Package: *\nPin: release n=sid\nPin-Priority: -1\n
Package: wireguard wireguard-dkms wireguard-tools\nPin: release n=sid\nPin-Priority: 100' > /etc/apt/preferences.d/dietpi-wireguard || { EXIT_CODE=4; break; }

		fi
		#-------------------------------------------------------------------------------
		# Finished
		echo -e '\e[90m[\e[0m  \e[32mOK\e[0m  \e[90m]\e[0m Successfully applied critical pre-patches\n'
		break
		#-------------------------------------------------------------------------------

	done

	#-------------------------------------------------------------------------------
	exit $EXIT_CODE
	#-------------------------------------------------------------------------------
}
