#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Patch File Script
	#
	#////////////////////////////////////
	# Created by MichaIng / micha@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Online pre-patching for client system.
	# - Runs from dietpi-update as very first update step
	# - NB: Keep this script as simple as possible, do not load/call dietpi-globals, to allow fixing most kinds of DietPi code issues!
	#
	# Usage:
	# - /DietPi/dietpi/pre-patch_file $G_DIETPI_VERSION_SUB
	#////////////////////////////////////

	# Grab input, being failsafe when applying to $G_DIETPI_VERSION_SUB
	INPUT=$1
	[[ $INPUT =~ ^-?[0-9]+$ ]] || INPUT=$(sed -n 2p /DietPi/dietpi/.version)
	[[ $INPUT =~ ^-?[0-9]+$ ]] || INPUT=$(sed -n 2p /boot/dietpi/.version)
	[[ $INPUT =~ ^-?[0-9]+$ ]] || INPUT=0
	export G_DIETPI_VERSION_SUB=$INPUT

	EXIT_CODE=0

	#///////////////////////////////////////////////////////////////////////////////
	#Pre-patch system
	#	For changes made to update and critical bug fixes
	#///////////////////////////////////////////////////////////////////////////////

	echo -e '[ INFO ] Running pre-patch\n\e[90m─────────────────────────────────────────────────────\e[0m'

	#-------------------------------------------------------------------------------
	#RAMlog 0 free space check due to issues with failing DietPi cron jobs in v6.11
	if (( $G_DIETPI_VERSION_SUB < 12 && $(df -B1M --output=avail /var/log | sed -n 2p) < 2 )); then

		echo -e '[ WARN ] Clearing /var/log files to free up space before patching (<2MB)'
		/DietPi/dietpi/func/dietpi-logclear 1

	fi
	#-------------------------------------------------------------------------------

	echo -e "[ INFO ] Finished pre-patch with exit code: $EXIT_CODE"

	#-------------------------------------------------------------------------------
	exit $EXIT_CODE
	#-------------------------------------------------------------------------------
}
