#!/bin/dash
{
	#////////////////////////////////////
	# DietPi PreBoot Script
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location: /boot/dietpi/preboot
	# - Runs on boot from dietpi-preboot.service before network and dietpi-postboot.service
	#////////////////////////////////////

	# Obtain hardware info: Do on every boot since some contained info can change, especially when allowing RPi SD card swap
	/boot/dietpi/func/dietpi-obtain_hw_model
	. /boot/dietpi/.hw_model

	# Apply CPU governor and settings on physical machines
	[ "$G_HW_MODEL" = 20 ] || [ "$G_HW_MODEL" = 75 ] || /boot/dietpi/func/dietpi-set_cpu

	#-----------------------------------------------------------------------------------
	exit 0
	#-----------------------------------------------------------------------------------
}
