#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Cron.Hourly script
	#
	#////////////////////////////////////
	#
	# Info:
	# - Location /etc/cron.hourly/dietpi
	#
	#////////////////////////////////////

	if [[ -f '/DietPi/dietpi/.installed' ]]; then

		LOGGING_MODE=$(grep -m1 '^[[:blank:]]*INDEX_LOGGING_CURRENT=' /DietPi/dietpi/.installed | sed 's/^[^=]*=//')

	fi
	LOGGING_MODE=${LOGGING_MODE:-0}

	#----------------------------------------------------------------
	# Main Loop
	#----------------------------------------------------------------
	# Time sync update, if mode 3 (hourly) is detected
	if grep -qi '^[[:blank:]]*CONFIG_NTP_MODE=3' /DietPi/dietpi.txt; then

		/DietPi/dietpi/func/run_ntpd 1 &> /dev/null &

	fi
	#----------------------------------------------------------------
	# Logging
	# - Clear all log files.
	if (( $LOGGING_MODE == -1 )); then

		/DietPi/dietpi/func/dietpi-logclear 1 &> /dev/null

	# - Update current log files data to /$HOME/logfile_storage/*. Then clear.
	elif (( $LOGGING_MODE == -2 )); then

		/DietPi/dietpi/func/dietpi-logclear 0 &> /dev/null

	fi
	#----------------------------------------------------------------
	exit
	#----------------------------------------------------------------
}
