#!/bin/dash
echo 'update-initramfs: Converting to U-Boot format'
mkimage -A arm64 -O linux -T ramdisk -C gzip -n uInitrd -d "$2" "/boot/uInitrd-$1"
ln -sf "uInitrd-$1" /boot/uInitrd
# Cleanup
rm -f /boot/uImage /boot/.next
exit 0
