#!/bin/dash
echo 'update-initramfs: Converting to U-Boot format' >&2
mkimage -A arm64 -O linux -T ramdisk -C gzip -n uInitrd -d $2 /boot/uInitrd-$1 > /dev/null
ln -sf uInitrd-$1 /boot/uInitrd > /dev/null 2>&1
exit 0
