#!/bin/dash

# Skip if initramfs-tools is not installed
[ -x '/usr/sbin/update-initramfs' ] || exit 0

# Passing the kernel version is required
version="$1"
if [ -z "$version" ]
then
	echo "W: initramfs-tools: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number" >&2
	exit 0
fi

# Avoid running multiple times
if [ "$DEB_MAINT_PARAMS" ]
then
	eval set -- "$DEB_MAINT_PARAMS"
	[ "$1" = 'upgrade' ] || exit 0
fi

# Delete unused initramfs images
files="$(find /boot -maxdepth 1 -name 'initrd.img-*' -o -name 'uInitrd-*')"
for f in $files
do
	[ -d "/lib/modules/${f#*-}" ] || continue
	echo "Removing obsolete initramfs image: $f"
	rm "$f"
done

exit 0
