#!/bin/bash
# Created by Micha / micha@dietpi.com / dietpi.com

#-----------------------------------------------------------
#Globals - benchmarks
#-----------------------------------------------------------
aHW_NAME=()
aHW_NAME[0]='Raspberry Pi 1'
aHW_NAME[1]='Raspberry Pi 1/Zero'
aHW_NAME[2]='Raspberry Pi 2'
aHW_NAME[3]='Raspberry Pi 3/3+'
aHW_NAME[10]='Odroid C1'
aHW_NAME[11]='Odroid XU3/XU4/HC1/HC2'
aHW_NAME[12]='Odroid C2'
aHW_NAME[13]='Odroid U3'
aHW_NAME[14]='Odroid N1'
aHW_NAME[20]='VM x64 (VMware VirtualBox)'
aHW_NAME[21]='x86_64 native (PC)'
aHW_NAME[22]='Generic device (eg: unknown to DietPi)'
aHW_NAME[30]='OrangePi PC'
aHW_NAME[31]='OrangePi One'
aHW_NAME[32]='OrangePi Zero (H2+)'
aHW_NAME[33]='OrangePi Lite'
aHW_NAME[34]='OrangePi Plus'
aHW_NAME[35]='OrangePi Zero Plus 2 (H3/H5)'
aHW_NAME[36]='OrangePi Win'
aHW_NAME[37]='OrangePi Prime'
aHW_NAME[38]='OrangePi PC 2'
aHW_NAME[39]='LeMaker Guitar'
aHW_NAME[40]='Pine A64'
aHW_NAME[41]='OrangePi PC Plus'
aHW_NAME[42]='RockPro64'
aHW_NAME[43]='Rock64'
aHW_NAME[50]='BananaPi M2+ (sinovoip)'
aHW_NAME[51]='BananaPi Pro (Lemaker)'
aHW_NAME[52]='Asus Tinker Board'
aHW_NAME[53]='BananaPi (sinovoip)'
aHW_NAME[60]='NanoPi Neo'
aHW_NAME[61]='NanoPi M2/T2'
aHW_NAME[62]='NanoPi M3/T3/F3'
aHW_NAME[63]='NanoPi M1/T1'
aHW_NAME[64]='NanoPi NEO Air'
aHW_NAME[65]='NanoPi NEO 2'
aHW_NAME[66]='NanoPi M1 Plus'
aHW_NAME[67]='NanoPi K1 Plus'
aHW_NAME[68]='NanoPC T4'
aHW_NAME[69]='Firefly RK3399'
aHW_NAME[70]='Sparky SBC'
aHW_NAME[71]='Beagle Bone Black'

G_HW_MODEL_MAX=71

aBENCH_INDEX=()

#[$HW_MODEL,${aBENCH_INDEX[$HW_MODEL]}]
declare -A aBENCH_CPU
declare -A aBENCH_ROOTFS_WRITE
declare -A aBENCH_ROOTFS_READ
declare -A aBENCH_RAM_WRITE
declare -A aBENCH_RAM_READ
declare -A aBENCH_CPU_TEMP_START
declare -A aBENCH_CPU_TEMP_END

#Results
BENCH_RESULTS_CPU_SCALE=2
BENCH_RESULTS_CPUTEMP_SCALE=0
BENCH_RESULTS_FILESYSTEM_SCALE=1
aBENCH_RESULT_CPU_MIN=()
aBENCH_RESULT_CPU_MAX=()
aBENCH_RESULT_CPU_AVG=()

aBENCH_RESULT_ROOTFS_WRITE_MIN=()
aBENCH_RESULT_ROOTFS_WRITE_MAX=()
aBENCH_RESULT_ROOTFS_WRITE_AVG=()

aBENCH_RESULT_ROOTFS_READ_MIN=()
aBENCH_RESULT_ROOTFS_READ_MAX=()
aBENCH_RESULT_ROOTFS_READ_AVG=()

aBENCH_RESULT_RAM_WRITE_MIN=()
aBENCH_RESULT_RAM_WRITE_MAX=()
aBENCH_RESULT_RAM_WRITE_AVG=()

aBENCH_RESULT_RAM_READ_MIN=()
aBENCH_RESULT_RAM_READ_MAX=()
aBENCH_RESULT_RAM_READ_AVG=()

aBENCH_RESULT_CPU_TEMP_START_MIN=()
aBENCH_RESULT_CPU_TEMP_START_MAX=()
aBENCH_RESULT_CPU_TEMP_START_AVG=()

aBENCH_RESULT_CPU_TEMP_END_MIN=()
aBENCH_RESULT_CPU_TEMP_END_MAX=()
aBENCH_RESULT_CPU_TEMP_END_AVG=()

#-----------------------------------------------------------
#Globals - Survey
#-----------------------------------------------------------
SURVEY_COUNT_TOTAL=0
SURVEY_COUNT_EMPTY=0

aSURVEY_VERSION=()
aSURVEY_SENTCOUNT=()
declare -A aDIETPI_VERSION
declare -A aDEVICE_NAME
declare -A aCPU_ARCH
aCPU_COUNT=()
declare -A aDISTRO_VERSION
declare -A aAUTOSTART_OPTION
declare -A aSOFTWARE
# v6.10 additions
aAUTO_SETUP_AUTOMATED=(
	[0]=0
	[1]=0
)
declare -A aNETWORK_INTERFACE

# Pre v6.10: Convert cpu arch index to name array
aCPU_NAME=(
	[1]='armv6l'
	[2]='armv7l'
	[3]='aarch64'
	[10]='x86_64'
)

# Convert autostart index to name array
aAUTOSTART_NAME=(
	[0]='Console manual login'
	[1]='Kodi'
	[2]='Desktop auto login'
	[3]='RetroPie'
	[4]='OpenTyrian'
	[5]='DietPi-Cloudshell'
	[6]='AmiBerry fast boot'
	[7]='Console auto login'
	[8]='AmiBerry standard boot'
	[9]='DXX-Rebith'
	[10]='CAVA Spectrum'
	[11]='Chromium'
	[12]='NULL'
	[13]='NULL'
	[14]='Custom'
	[15]='JRiver'
	[16]='Desktop LightDM login'
)

# Convert software index to title array
aSOFTWARE_NAME=(
	[0]='OpenSSH Client'
	[1]='Samba Client'
	[2]='Curlftpfs'
	[3]='MC'
	[4]='ViFM'
	[5]='ALSA'
	[6]='Xserver'
	[7]='FFmpeg'
	[8]='Java'
	[9]='Node.js'
	[10]='iftop'
	[11]='IPTraf'
	[12]='Iperf'
	[13]='MTR-Tiny'
	[14]='nLoad'
	[15]='tcpdump'
	[16]='Build-Essentials'
	[17]='Git Client'
	[18]='Emacs'
	[19]='Jed'
	[20]='Vim'
	[21]='Vim-Tiny'
	[22]='QuiteRSS'
	[23]='LXDE'
	[24]='MATE'
	[25]='XFCE'
	[26]='GNUStep'
	[27]='TightVNC Server'
	[28]='VNC4 Server'
	[29]='XRDP'
	[30]='NoMachine'
	[31]='Kodi'
	[32]='YMPD'
	[33]='AirSonic'
	[34]='SubSonic 6'
	[35]='SqueezeBox'
	[36]='SqueezeLite'
	[37]='Shairport Sync'
	[38]='BruteFIR'
	[39]='ReadyMedia'
	[40]='Ampache'
	[41]='Emby Server'
	[42]='Plex Media Server'
	[43]='Murmur'
	[44]='Transmission'
	[45]='Deluge'
	[46]='qBitTorrent'
	[47]='ownCloud'
	[48]='Pydio'
	[49]='Gogs'
	[50]='Syncthing'
	[51]='OpenTyrian'
	[52]='Cuberite'
	[53]='MineOS'
	[54]='Forums'
	[55]='Wordpress'
	[56]='Image Gallery'
	[57]='BaiKal'
	[58]='OpenBazaar'
	[59]='RPi Cam Control'
	[60]='WiFi Hotspot'
	[61]='Tor Hotspot'
	[62]='DietPi-Cloudshell'
	[63]='LinuxDash'
	[64]='PhpSysInfo'
	[65]='NetData'
	[66]='RPi-Monitor'
	[67]='NoIp'
	[68]='Remot3.it'
	[69]='RPi.GPIO'
	[70]='WiringPi'
	[71]='WebIOPi'
	[72]='I2c'
	[73]='Fail2Ban'
	[74]='InfluxDB'
	[75]='LASP'
	[76]='LAMP'
	[77]='Grafana'
	[78]='LESP'
	[79]='LEMP'
	[80]='NULL'
	[81]='LLSP'
	[82]='LLMP'
	[83]='Apache2'
	[84]='Lighttpd'
	[85]='Nginx'
	[86]='NULL'
	[87]='SQlite'
	[88]='MariaDB'
	[89]='PHP'
	[90]='phpMyAdmin'
	[91]='Redis'
	[92]='CertBot'
	[93]='Pi-hole'
	[94]='ProFTP'
	[95]='vsFTPD'
	[96]='Samba'
	[97]='OpenVPN'
	[98]='HaProxy'
	[99]='EmonPi'
	[100]='PiJuice'
	[101]='Log Rotate'
	[102]='Rsyslog'
	[103]='DietPi-Ramlog'
	[104]='Dropbear'
	[105]='OpenSSH Server'
	[106]='NTP'
	[107]='rTorrent'
	[108]='AmiBerry'
	[109]='NFS'
	[110]='NFS Client'
	[111]='UrBackup server'
	[112]='DXX-Rebirth'
	[113]='Chromium'
	[114]='Nextcloud'
	[115]='Webmin'
	[116]='SickRage'
	[117]='PiVPN'
	[118]='Mopidy'
	[119]='CAVA'
	[120]='RealVNC Server'
	[121]='Roon Bridge'
	[122]='Node-Red'
	[123]='Mosquitto '
	[124]='NAA daemon'
	[125]='Tomcat8'
	[126]='LibSSL1.0.0'
	[127]='NeoVim'
	[128]='MPD'
	[129]='O!MPD'
	[130]='Python Pip'
	[131]='Blynk Server'
	[132]='Aria2'
	[133]='YaCy'
	[134]='Tonido'
	[135]='IceCast'
	[136]='MotionEye'
	[137]='CloudPrint'
	[138]='VirtualHere'
	[139]='SABnzbd'
	[140]='SDL2'
	[141]='Spotify Connect Web'
	[142]='CouchPotato'
	[143]='Koel'
	[144]='Sonarr'
	[145]='Radarr'
	[146]='Tautulli'
	[147]='Jackett'
	[148]='JRiver MC'
	[149]='NZBget'
	[150]='Mono'
	[151]='Nvidia'
	[152]='Avahi-Daemon'
	[153]='OctoPrint'
	[154]='Roon Server'
	[155]='HTPC Manager'
	[156]='Steam'
	[157]='Home Assistant'
	[158]='Minio'
	[159]='Allo'
	[160]='Allo_update'
	[161]='FuguHub'
	[162]='Docker'
	[163]='Gmediarender'
	[164]='Nukkit'
	[165]='Gitea'
	[166]='PI-SPC'
	[167]='Raspotify'
	[168]='moOde'
	[169]='Google AIY'
)

# - v6.10 software index changes
aSOFTWARE_NAME6_10=()
for i in ${!aSOFTWARE_NAME[@]}
do

	aSOFTWARE_NAME6_10[$i]="${aSOFTWARE_NAME[$i]}"

done
#aSOFTWARE_NAME6_10[2]='NULL' # CurlTMPFS Removed but not marked as removed => v6.12
aSOFTWARE_NAME6_10[80]='Ubooquity'
aSOFTWARE_NAME6_10[86]='Roon Extension Manager'
aSOFTWARE_NAME6_10[106]='NULL' # NTP
aSOFTWARE_NAME6_10[168]='NULL' # Moode

# - v6.11 hotfix
aSOFTWARE_NAME6_11=()
for i in ${!aSOFTWARE_NAME6_10[@]}
do

	aSOFTWARE_NAME6_11[$i]="${aSOFTWARE_NAME6_10[$i]}"

done

# - v6.12
aSOFTWARE_NAME6_12=()
for i in ${!aSOFTWARE_NAME6_11[@]}
do

	aSOFTWARE_NAME6_12[$i]="${aSOFTWARE_NAME6_11[$i]}"

done
aSOFTWARE_NAME6_12[2]='NULL' # CurlTMPFS
aSOFTWARE_NAME6_12[148]='NULL' # JRiver

# - v6.13
aSOFTWARE_NAME6_13=()
for i in ${!aSOFTWARE_NAME6_12[@]}
do

	aSOFTWARE_NAME6_13[$i]="${aSOFTWARE_NAME6_12[$i]}"

done
aSOFTWARE_NAME6_13[2]='Folding@Home'
aSOFTWARE_NAME6_13[106]='Lidarr'

# - v6.14
aSOFTWARE_NAME6_14=()
for i in ${!aSOFTWARE_NAME6_13[@]}
do

	aSOFTWARE_NAME6_14[$i]="${aSOFTWARE_NAME6_13[$i]}"

done
aSOFTWARE_NAME6_14[38]='FreshRSS'

# - v6.15
aSOFTWARE_NAME6_15=()
for i in ${!aSOFTWARE_NAME6_14[@]}
do

	aSOFTWARE_NAME6_15[$i]="${aSOFTWARE_NAME6_14[$i]}"

done
aSOFTWARE_NAME6_12[148]='myMPD'

# - v6.16
aSOFTWARE_NAME6_16=()
for i in ${!aSOFTWARE_NAME6_15[@]}
do

        aSOFTWARE_NAME6_16[$i]="${aSOFTWARE_NAME6_15[$i]}"

done

# - v6.17 testing
aSOFTWARE_NAME6_17=()
for i in ${!aSOFTWARE_NAME6_16[@]}
do

	aSOFTWARE_NAME6_17[$i]="${aSOFTWARE_NAME6_16[$i]}"

done

#-----------------------------------------------------------
#Main
#-----------------------------------------------------------
# Copy files to RAM to speed up grep
#mkdir -p /tmp/dietpi-survey_report
#cp /home/dietpi-survey/survey/*.txt /tmp/dietpi-survey_report/ # /etc/cron.minutely/dietpi-survey_report: line 310: /bin/cp: Argument list too long
[[ -e /tmp/dietpi-survey_report ]] && rm -R /tmp/dietpi-survey_report
cp -R /home/dietpi-survey/survey /tmp/dietpi-survey_report

#DEBUG | ONLY MY UPLOAD for testing
for file in /tmp/dietpi-survey_report/*.txt
do

	# Filled and empty survey files
	((SURVEY_COUNT_TOTAL++))
	if [[ ! -s $file ]]; then

		((SURVEY_COUNT_EMPTY++))
		continue

	fi

	# v6.10+: files can be sourced:
	if grep -q '^#!/bin/bash' $file; then

		. $file

		# - Add bench to array
		if [[ $BENCH_HW_MODEL ]]; then

			if [[ ! ${aBENCH_INDEX[$BENCH_HW_MODEL]} ]]; then

				aBENCH_INDEX[$BENCH_HW_MODEL]=0

			fi

			aBENCH_CPU[$BENCH_HW_MODEL,${aBENCH_INDEX[$BENCH_HW_MODEL]}]=$BENCH_CPU
			aBENCH_ROOTFS_WRITE[$BENCH_HW_MODEL,${aBENCH_INDEX[$BENCH_HW_MODEL]}]=$BENCH_ROOTFS_WRITE
			aBENCH_ROOTFS_READ[$BENCH_HW_MODEL,${aBENCH_INDEX[$BENCH_HW_MODEL]}]=$BENCH_ROOTFS_READ
			aBENCH_RAM_WRITE[$BENCH_HW_MODEL,${aBENCH_INDEX[$BENCH_HW_MODEL]}]=$BENCH_RAM_WRITE
			aBENCH_RAM_READ[$BENCH_HW_MODEL,${aBENCH_INDEX[$BENCH_HW_MODEL]}]=$BENCH_RAM_READ
			aBENCH_CPU_TEMP_START[$BENCH_HW_MODEL,${aBENCH_INDEX[$BENCH_HW_MODEL]}]=$BENCH_CPU_TEMP_START
			aBENCH_CPU_TEMP_END[$BENCH_HW_MODEL,${aBENCH_INDEX[$BENCH_HW_MODEL]}]=$BENCH_CPU_TEMP_END

			((aBENCH_INDEX[$BENCH_HW_MODEL]++))
			unset BENCH_HW_MODEL

		fi

		continue

	fi

	# pre v6.10: Files need to be scraped:

	# Reset variables
	survey_version=0
	survey_sendcount=0
	dietpi_version='0.0'
	device_name='NULL'
	cpu_arch=0
	cpu_count=0
	distro_version='NULL'
	autostart_option=-1
	software_list=''
	software=''

	# Survey versions
	#survey_version=$(grep -m1 '^DietPi-Survey v' $file)
	#((aSURVEY_VERSION[${survey_version##* v}]++))
	# - Can only be v5 on pre v6.10
	((aSURVEY_VERSION[5]++))

	# Upload count numbers
	survey_sendcount=$(grep -m1 '^Upload Count' $file)
	((aSURVEY_SENTCOUNT[${survey_sendcount##* : }]++))

	# DietPi versions
	#dietpi_version=$(grep -m1 '^DietPi Version' $file)
	# As survey runs on v6.9 currently within patch file, the version string is still at v6.8. Currently manual edit is needed, on v6.10 survey will run on dietpi-update after version string increase.
	#dietpi_version=${dietpi_version/6.8/6.9}
	#((aDIETPI_VERSION[${dietpi_version##* : }]++))
	# - Can only be v6.9
	((aDIETPI_VERSION[6.9]++))

	# Device name
	device_name=$(grep -m1 '^Hardware Name' $file)
	((aDEVICE_NAME[${device_name##* : }]++))

	# CPU architecture
	cpu_arch=$(grep -m1 '^CPU Arch Index' $file)
	((aCPU_ARCH[${aCPU_NAME[${cpu_arch##* : }]}]++))

	# CPU core count
	cpu_count=$(grep -m1 '^CPU Count' $file)
	((aCPU_COUNT[${cpu_count##* : }]++))

	# Distro version
	distro_version=$(grep -m1 '^Distro Name' $file)
	((aDISTRO_VERSION[${distro_version##* : }]++))

	# Autostart option
	autostart_option=$(grep -m1 '^Autoboot Index' $file)
	((aAUTOSTART_OPTION[${aAUTOSTART_NAME[${autostart_option##* : }]}]++))

	# Installed software
	software_list=$(grep '^aSOFTWARE_INSTALL_STATE\[' $file)
	while read software
	do

		software=${software##*[}
		((aSOFTWARE[${aSOFTWARE_NAME[${software%%]*}]}]++))

	done <<< "$software_list"

done

SURVEY_SENTCOUNT_TOTAL=0
for i in ${!aSURVEY_SENTCOUNT[@]}
do

	SURVEY_SENTCOUNT_TOTAL=$(( $SURVEY_SENTCOUNT_TOTAL + $i*${aSURVEY_SENTCOUNT[$i]} ))

done

#Bench Results, HW_MODEL array:
for (( i=0; i<=$G_HW_MODEL_MAX; i++ ))
do

	if [[ ${aBENCH_INDEX[$i]} ]]; then

		#init results
		aBENCH_RESULT_CPU_MIN[$i]=10000
		aBENCH_RESULT_CPU_MAX[$i]=0
		aBENCH_RESULT_CPU_AVG[$i]=0

		aBENCH_RESULT_ROOTFS_WRITE_MIN[$i]=10000
		aBENCH_RESULT_ROOTFS_WRITE_MAX[$i]=0
		aBENCH_RESULT_ROOTFS_WRITE_AVG[$i]=0

		aBENCH_RESULT_ROOTFS_READ_MIN[$i]=10000
		aBENCH_RESULT_ROOTFS_READ_MAX[$i]=0
		aBENCH_RESULT_ROOTFS_READ_AVG[$i]=0

		aBENCH_RESULT_RAM_WRITE_MIN[$i]=10000
		aBENCH_RESULT_RAM_WRITE_MAX[$i]=0
		aBENCH_RESULT_RAM_WRITE_AVG[$i]=0

		aBENCH_RESULT_RAM_READ_MIN[$i]=10000
		aBENCH_RESULT_RAM_READ_MAX[$i]=0
		aBENCH_RESULT_RAM_READ_AVG[$i]=0

		aBENCH_RESULT_CPU_TEMP_START_MIN[$i]=10000
		aBENCH_RESULT_CPU_TEMP_START_MAX[$i]=0
		aBENCH_RESULT_CPU_TEMP_START_AVG[$i]=0

		aBENCH_RESULT_CPU_TEMP_END_MIN[$i]=10000
		aBENCH_RESULT_CPU_TEMP_END_MAX[$i]=0
		aBENCH_RESULT_CPU_TEMP_END_AVG[$i]=0

		#echo ${aBENCH_INDEX[$i]}
		for (( j=0; j<${aBENCH_INDEX[$i]}; j++ ))
		do

			# echo -e "aBENCH_CPU[$i,$j] ${aBENCH_CPU[$i,$j]}"
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_CPU_SCALE; ${aBENCH_CPU[$i,$j]} < ${aBENCH_RESULT_CPU_MIN[$i]}") )); then

				aBENCH_RESULT_CPU_MIN[$i]=${aBENCH_CPU[$i,$j]}

			fi
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_CPU_SCALE; ${aBENCH_CPU[$i,$j]} > ${aBENCH_RESULT_CPU_MAX[$i]}") )); then

				aBENCH_RESULT_CPU_MAX[$i]=${aBENCH_CPU[$i,$j]}

			fi

			# - Count up averages
			aBENCH_RESULT_CPU_AVG[$i]=$(bc -l <<< "${aBENCH_CPU[$i,$j]} + ${aBENCH_RESULT_CPU_AVG[$i]}")

			# echo -e "aBENCH_ROOTFS_WRITE[$i,$j] ${aBENCH_ROOTFS_WRITE[$i,$j]}"
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_FILESYSTEM_SCALE; ${aBENCH_ROOTFS_WRITE[$i,$j]} < ${aBENCH_RESULT_ROOTFS_WRITE_MIN[$i]}") )); then

				aBENCH_RESULT_ROOTFS_WRITE_MIN[$i]=${aBENCH_ROOTFS_WRITE[$i,$j]}

			fi
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_FILESYSTEM_SCALE; ${aBENCH_ROOTFS_WRITE[$i,$j]} > ${aBENCH_RESULT_ROOTFS_WRITE_MAX[$i]}") )); then

				aBENCH_RESULT_ROOTFS_WRITE_MAX[$i]=${aBENCH_ROOTFS_WRITE[$i,$j]}

			fi

			# - Count up averages
			aBENCH_RESULT_ROOTFS_WRITE_AVG[$i]=$(bc -l <<< "${aBENCH_ROOTFS_WRITE[$i,$j]} + ${aBENCH_RESULT_ROOTFS_WRITE_AVG[$i]}")

			# echo -e "aBENCH_ROOTFS_READ[$i,$j] ${aBENCH_ROOTFS_READ[$i,$j]}"
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_FILESYSTEM_SCALE; ${aBENCH_ROOTFS_READ[$i,$j]} < ${aBENCH_RESULT_ROOTFS_READ_MIN[$i]}") )); then

				aBENCH_RESULT_ROOTFS_READ_MIN[$i]=${aBENCH_ROOTFS_READ[$i,$j]}

			fi
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_FILESYSTEM_SCALE; ${aBENCH_ROOTFS_READ[$i,$j]} > ${aBENCH_RESULT_ROOTFS_READ_MAX[$i]}") )); then

				aBENCH_RESULT_ROOTFS_READ_MAX[$i]=${aBENCH_ROOTFS_READ[$i,$j]}

			fi

			# - Count up averages
			aBENCH_RESULT_ROOTFS_READ_AVG[$i]=$(bc -l <<< "${aBENCH_ROOTFS_READ[$i,$j]} + ${aBENCH_RESULT_ROOTFS_READ_AVG[$i]}")

			# echo -e "aBENCH_RAM_WRITE[$i,$j] ${aBENCH_RAM_WRITE[$i,$j]}"
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_FILESYSTEM_SCALE; ${aBENCH_RAM_WRITE[$i,$j]} < ${aBENCH_RESULT_RAM_WRITE_MIN[$i]}") )); then

				aBENCH_RESULT_RAM_WRITE_MIN[$i]=${aBENCH_RAM_WRITE[$i,$j]}

			fi
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_FILESYSTEM_SCALE; ${aBENCH_RAM_WRITE[$i,$j]} > ${aBENCH_RESULT_RAM_WRITE_MAX[$i]}") )); then

				aBENCH_RESULT_RAM_WRITE_MAX[$i]=${aBENCH_RAM_WRITE[$i,$j]}

			fi

			# - Count up averages
			aBENCH_RESULT_RAM_WRITE_AVG[$i]=$(bc -l <<< "${aBENCH_RAM_WRITE[$i,$j]} + ${aBENCH_RESULT_RAM_WRITE_AVG[$i]}")

			# echo -e "aBENCH_RAM_READ[$i,$j] ${aBENCH_RAM_READ[$i,$j]}"
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_FILESYSTEM_SCALE; ${aBENCH_RAM_READ[$i,$j]} < ${aBENCH_RESULT_RAM_READ_MIN[$i]}") )); then

				aBENCH_RESULT_RAM_READ_MIN[$i]=${aBENCH_RAM_READ[$i,$j]}

			fi
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_FILESYSTEM_SCALE; ${aBENCH_RAM_READ[$i,$j]} > ${aBENCH_RESULT_RAM_READ_MAX[$i]}") )); then

				aBENCH_RESULT_RAM_READ_MAX[$i]=${aBENCH_RAM_READ[$i,$j]}

			fi

			# - Count up averages
			aBENCH_RESULT_RAM_READ_AVG[$i]=$(bc -l <<< "${aBENCH_RAM_READ[$i,$j]} + ${aBENCH_RESULT_RAM_READ_AVG[$i]}")

			# echo -e "aBENCH_CPU_TEMP_START[$i,$j] ${aBENCH_CPU_TEMP_START[$i,$j]}"
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_CPUTEMP_SCALE; ${aBENCH_CPU_TEMP_START[$i,$j]} < ${aBENCH_RESULT_CPU_TEMP_START_MIN[$i]}") )); then

				aBENCH_RESULT_CPU_TEMP_START_MIN[$i]=${aBENCH_CPU_TEMP_START[$i,$j]}

			fi
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_CPUTEMP_SCALE; ${aBENCH_CPU_TEMP_START[$i,$j]} > ${aBENCH_RESULT_CPU_TEMP_START_MAX[$i]}") )); then

				aBENCH_RESULT_CPU_TEMP_START_MAX[$i]=${aBENCH_CPU_TEMP_START[$i,$j]}

			fi

			# - Count up averages
			aBENCH_RESULT_CPU_TEMP_START_AVG[$i]=$(bc -l <<< "${aBENCH_CPU_TEMP_START[$i,$j]} + ${aBENCH_RESULT_CPU_TEMP_START_AVG[$i]}")

			# echo -e "aBENCH_CPU_TEMP_END[$i,$j] ${aBENCH_CPU_TEMP_END[$i,$j]}"
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_CPUTEMP_SCALE; ${aBENCH_CPU_TEMP_END[$i,$j]} < ${aBENCH_RESULT_CPU_TEMP_END_MIN[$i]}") )); then

				aBENCH_RESULT_CPU_TEMP_END_MIN[$i]=${aBENCH_CPU_TEMP_END[$i,$j]}

			fi
			if (( $(bc -l <<< "scale=$BENCH_RESULTS_CPUTEMP_SCALE; ${aBENCH_CPU_TEMP_END[$i,$j]} > ${aBENCH_RESULT_CPU_TEMP_END_MAX[$i]}") )); then

				aBENCH_RESULT_CPU_TEMP_END_MAX[$i]=${aBENCH_CPU_TEMP_END[$i,$j]}

			fi

			# - Count up averages
			aBENCH_RESULT_CPU_TEMP_END_AVG[$i]=$(bc -l <<< "${aBENCH_CPU_TEMP_END[$i,$j]} + ${aBENCH_RESULT_CPU_TEMP_END_AVG[$i]}")

			# - DEBUG
			# echo ${aBENCH_ROOTFS_WRITE[$i,$j]}
			# echo ${aBENCH_ROOTFS_READ[$i,$j]}
			# echo ${aBENCH_RAM_WRITE[$i,$j]}
			# echo ${aBENCH_RAM_READ[$i,$j]}
			# echo ${aBENCH_CPU_TEMP_START[$i,$j]}
			# echo ${aBENCH_CPU_TEMP_END[$i,$j]}
			# - DEBUG

			# - Work out averages
			if (( $j == ${aBENCH_INDEX[$i]} - 1 )); then

				aBENCH_RESULT_CPU_AVG[$i]=$(bc -l <<< "scale=$BENCH_RESULTS_CPU_SCALE; ${aBENCH_RESULT_CPU_AVG[$i]} / ${aBENCH_INDEX[$i]}")
				aBENCH_RESULT_ROOTFS_WRITE_AVG[$i]=$(bc -l <<< "scale=$BENCH_RESULTS_FILESYSTEM_SCALE; ${aBENCH_RESULT_ROOTFS_WRITE_AVG[$i]} / ${aBENCH_INDEX[$i]}")
				aBENCH_RESULT_ROOTFS_READ_AVG[$i]=$(bc -l <<< "scale=$BENCH_RESULTS_FILESYSTEM_SCALE; ${aBENCH_RESULT_ROOTFS_READ_AVG[$i]} / ${aBENCH_INDEX[$i]}")
				aBENCH_RESULT_RAM_WRITE_AVG[$i]=$(bc -l <<< "scale=$BENCH_RESULTS_FILESYSTEM_SCALE; ${aBENCH_RESULT_RAM_WRITE_AVG[$i]} / ${aBENCH_INDEX[$i]}")
				aBENCH_RESULT_RAM_READ_AVG[$i]=$(bc -l <<< "scale=$BENCH_RESULTS_FILESYSTEM_SCALE; ${aBENCH_RESULT_RAM_READ_AVG[$i]} / ${aBENCH_INDEX[$i]}")
				aBENCH_RESULT_CPU_TEMP_START_AVG[$i]=$(bc -l <<< "scale=$BENCH_RESULTS_CPUTEMP_SCALE; ${aBENCH_RESULT_CPU_TEMP_START_AVG[$i]} / ${aBENCH_INDEX[$i]}")
				aBENCH_RESULT_CPU_TEMP_END_AVG[$i]=$(bc -l <<< "scale=$BENCH_RESULTS_CPUTEMP_SCALE; ${aBENCH_RESULT_CPU_TEMP_END_AVG[$i]} / ${aBENCH_INDEX[$i]}")

				#DEBUG
				# echo -e "aBENCH_RESULT_CPU_AVG $i = ${aBENCH_RESULT_CPU_AVG[$i]}"
				# echo -e "aBENCH_RESULT_ROOTFS_WRITE_AVG $i = ${aBENCH_RESULT_ROOTFS_WRITE_AVG[$i]}"
				# echo -e "aBENCH_RESULT_ROOTFS_READ_AVG $i = ${aBENCH_RESULT_ROOTFS_READ_AVG[$i]}"
				# echo -e "aBENCH_RESULT_RAM_WRITE_AVG $i = ${aBENCH_RESULT_RAM_WRITE_AVG[$i]}"
				# echo -e "aBENCH_RESULT_RAM_READ_AVG $i = ${aBENCH_RESULT_RAM_READ_AVG[$i]}"
				# echo -e "aBENCH_RESULT_CPU_TEMP_START_AVG $i = ${aBENCH_RESULT_CPU_TEMP_START_AVG[$i]}"
				# echo -e "aBENCH_RESULT_CPU_TEMP_END_AVG $i = ${aBENCH_RESULT_CPU_TEMP_END_AVG[$i]}"
				#DEBUG

			fi

		done

	fi

done

cat << _EOF_ > /var/www/survey/index.html
<html>
	<head>
		<style>
			body {
				font-size: 18px;
				color: white;
				background-color: black;
				font-family: Verdana, Arial, Helvetica, sans-serif;
			}
			th, td {
				padding: 5px;
			}
			table, th, td {
				font-size: 14px;
				border: 1px solid grey;
			}
		</style>
	</head>
	<body>
		<h2>DietPi-Survey report page:</h2>
		<i>Last update: $(TZ=UTC date "+%Y-%m-%d %T UTC")</i>
		<br>
		<table>
			<tr><td>Total user count</td><td align="right">$SURVEY_COUNT_TOTAL</td></tr>
			<tr><td>Users opted in</td><td align="right">$(( $SURVEY_COUNT_TOTAL - $SURVEY_COUNT_EMPTY ))</td></tr>
			<tr><td>Users opted out</td><td align="right">$SURVEY_COUNT_EMPTY</td></tr>
		</table>

		<h4>DietPi-Survey versions:</h4>
		<table>
			$(for i in ${!aSURVEY_VERSION[@]}; do echo "<tr><td>DietPi-Survey v$i</td><td align=\"right\">	${aSURVEY_VERSION[$i]}</td></tr>"; done | sort -nrk 1.24 -t '	')
		</table>

		<h4>DietPi-Survey upload counts:</h4>
		<table>
			<tr><td>Overall upload count</td><td align="right">$SURVEY_SENTCOUNT_TOTAL</td></tr>
			<tr><th>Upload count</th><th>by user count</th></tr>
			$(for i in ${!aSURVEY_SENTCOUNT[@]}; do echo "<tr><td>$i</td><td align=\"right\">	${aSURVEY_SENTCOUNT[$i]}</td></tr>"; done | sort -nrk 1.9 -t '	')
		</table>

		<h4>DietPi versions:</h4>
		<table>
			$(for i in ${!aDIETPI_VERSION[@]}; do echo "<tr><td>DietPi v$i</td><td align=\"right\">	${aDIETPI_VERSION[$i]}</td></tr>"; done | sort -nrk 1.20 -t '	')
		</table>

		<h4>Devices:</h4>
		<table>
			$(for i in "${!aDEVICE_NAME[@]}"; do echo "<tr><td>$i</td><td align=\"right\">	${aDEVICE_NAME[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
		</table>

                <h4>CPU architectures:</h4>
                <table>
                        $(for i in ${!aCPU_ARCH[@]}; do echo "<tr><td>$i</td><td align=\"right\">	${aCPU_ARCH[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
                </table>

                <h4>CPU core counts:</h4>
                <table>
                        $(for i in ${!aCPU_COUNT[@]}; do echo "<tr><td>$i Core(s)</td><td align=\"right\">	${aCPU_COUNT[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
                </table>

		<h4>Distro versions:</h4>
		<table>
			$(for i in ${!aDISTRO_VERSION[@]}; do echo "<tr><td>$i</td><td align=\"right\">	${aDISTRO_VERSION[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
		</table>

		<h4>Autostart options:</h4>
		<table>
			$(for i in "${!aAUTOSTART_OPTION[@]}"; do echo "<tr><td>$i</td><td align=\"right\">	${aAUTOSTART_OPTION[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
		</table>

		<h4>DietPi-Automation:</h4>
		<table>
			<tr><td>Used by</td><td align="right">${aAUTO_SETUP_AUTOMATED[1]} of $((${aAUTO_SETUP_AUTOMATED[1]} + ${aAUTO_SETUP_AUTOMATED[0]})) users</td></tr>
		</table>

		<h4>Network interfaces:</h4>
		<table>
			$(for i in ${!aNETWORK_INTERFACE[@]}; do echo "<tr><td>$i</td><td align=\"right\">	${aNETWORK_INTERFACE[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
		</table>

		<h4>Installed software titles:</h4>
		<table>
			$(for i in "${!aSOFTWARE[@]}"; do echo "<tr><td>$i</td><td align=\"right\">	${aSOFTWARE[$i]}</td></tr>"; done | sort -nrk 2 -t '	')
		</table>



		<h4 id="benchmark">DietPi-Benchmarks | CPU:</h4>
		<table>

			<tr>

				<td colspan="2">

				</td>
				<td colspan="3" bgcolor="#5B5B5B">
					CPU time (seconds, lower is faster):
				</td>
				<td colspan="3" bgcolor="#5B5B5B">
					CPU idle temp ('c):
				</td>
				<td colspan="3" bgcolor="#5B5B5B">
					CPU full load temp ('c):
				</td>

			</td>

			<tr>
				<td bgcolor="#5B5B5B">
					Device:
				</td>
				<td bgcolor="#5B5B5B">
					Total benchmarks:
				</td>
				<td bgcolor="#4C5100">
					Average:
				</td>
				<td bgcolor="#135100">
					Fastest:
				</td>
				<td bgcolor="#510000">
					Slowest:
				</td>
				<td bgcolor="#4C5100">
					Average:
				</td>
				<td bgcolor="#135100">
					Min:
				</td>
				<td bgcolor="#510000">
					Max:
				</td>
				<td bgcolor="#4C5100">
					Average:
				</td>
				<td bgcolor="#135100">
					Min:
				</td>
				<td bgcolor="#510000">
					Max:
				</td>

			</tr>
			$(for i in "${!aBENCH_INDEX[@]}"; do echo "<tr><td>${aHW_NAME[$i]}</td> <td>${aBENCH_INDEX[$i]}</td> <td>${aBENCH_RESULT_CPU_AVG[$i]}</td> <td>${aBENCH_RESULT_CPU_MIN[$i]}</td> <td>${aBENCH_RESULT_CPU_MAX[$i]}</td> <td>${aBENCH_RESULT_CPU_TEMP_START_AVG[$i]}</td> <td>${aBENCH_RESULT_CPU_TEMP_START_MIN[$i]}</td> <td>${aBENCH_RESULT_CPU_TEMP_START_MAX[$i]}</td> <td>${aBENCH_RESULT_CPU_TEMP_END_AVG[$i]}</td> <td>${aBENCH_RESULT_CPU_TEMP_END_MIN[$i]}</td> <td>${aBENCH_RESULT_CPU_TEMP_END_MAX[$i]}</td>    </tr>"; done)
		</table>

		<h4>DietPi-Benchmarks | IO (Filesystem & RAM):</h4>
		<table>

			<tr>

				<td colspan="2">

				</td>
				<td colspan="3" bgcolor="#5B5B5B">
					RootFS write (MB/s):
				</td>
				<td colspan="3" bgcolor="#5B5B5B">
					RootFS read (MB/s):
				</td>
				<td colspan="3" bgcolor="#5B5B5B">
					RAM write (MB/s):
				</td>
				<td colspan="3" bgcolor="#5B5B5B">
					RAM read (MB/s):
				</td>

			</td>

			<tr>
				<td bgcolor="#5B5B5B">
					Device:
				</td>
				<td bgcolor="#5B5B5B">
					Total benchmarks:
				</td>
				<td bgcolor="#4C5100">
					Average:
				</td>
				<td bgcolor="#135100">
					Best:
				</td>
				<td bgcolor="#510000">
					Worst:
				</td>
				<td bgcolor="#4C5100">
					Average:
				</td>
				<td bgcolor="#135100">
					Best:
				</td>
				<td bgcolor="#510000">
					Worst:
				</td>
				<td bgcolor="#4C5100">
					Average:
				</td>
				<td bgcolor="#135100">
					Best:
				</td>
				<td bgcolor="#510000">
					Worst:
				</td>
				<td bgcolor="#4C5100">
					Average:
				</td>
				<td bgcolor="#135100">
					Best:
				</td>
				<td bgcolor="#510000">
					Worst:
				</td>

			</tr>
			$(for i in "${!aBENCH_INDEX[@]}"; do echo "<tr><td>${aHW_NAME[$i]}</td> <td>${aBENCH_INDEX[$i]}</td> <td>${aBENCH_RESULT_ROOTFS_WRITE_AVG[$i]}</td> <td>${aBENCH_RESULT_ROOTFS_WRITE_MAX[$i]}</td> <td>${aBENCH_RESULT_ROOTFS_WRITE_MIN[$i]}</td> <td>${aBENCH_RESULT_ROOTFS_READ_AVG[$i]}</td> <td>${aBENCH_RESULT_ROOTFS_READ_MAX[$i]}</td> <td>${aBENCH_RESULT_ROOTFS_READ_MIN[$i]}</td> <td>${aBENCH_RESULT_RAM_WRITE_AVG[$i]}</td> <td>${aBENCH_RESULT_RAM_WRITE_MAX[$i]}</td> <td>${aBENCH_RESULT_RAM_WRITE_MIN[$i]}</td> <td>${aBENCH_RESULT_RAM_READ_AVG[$i]}</td> <td>${aBENCH_RESULT_RAM_READ_MAX[$i]}</td> <td>${aBENCH_RESULT_RAM_READ_MAX[$i]}</td>    </tr>"; done)
		</table>

	</body>
</html>
_EOF_

# Clean up tmp ramfs
rm -R /tmp/dietpi-survey_report
