#!/bin/bash
{
# DietPi-Update incremental patches to apply system and software migrations and fixes
# Created by MichaIng / micha@dietpi.com / https://dietpi.com/
# License: GPLv2 / https://github.com/MichaIng/DietPi#license

# Remove obsolete udev rule, as WiFi power saving is disabled via /etc/network/intefaces > "wireless-power off" > /etc/network/if-pre-up.d/wireless-tools (wireless-tools package) when the WiFi interface is configured.
[[ -f '/etc/udev/rules.d/10-wifi-disable-powermanagement.rules' ]] && rm -v /etc/udev/rules.d/10-wifi-disable-powermanagement.rules
# Remove DietPi-NordVPN, as it has been replaced with DietPi-VPN
[[ -f '/boot/dietpi/misc/dietpi-nordvpn' ]] && rm -v /boot/dietpi/misc/dietpi-nordvpn
[[ -d '/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/' ]] && mv -v /var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/ /var/lib/dietpi/dietpi-vpn
[[ -f '/var/lib/dietpi/dietpi-vpn/settings_dietpi.conf' ]] && . /var/lib/dietpi/dietpi-vpn/settings_dietpi.conf
cp -v "/etc/openvpn/ovpn_$PROTOCOL/$VPN_SERVER" '/etc/openvpn/client.ovpn'
systemctl disable --now dietpi-nordvpn ; systemctl enable --now dietpi-vpn
unset VPN_SERVER PROTOCOL VPN_PASSWORD VPN_USERNAME

exit 0
}
