#!/bin/bash
{
# DietPi-Update pre-patches that need to run before new scripts are downloaded and/or before APT upgrades
# Created by MichaIng / micha@dietpi.com / https://dietpi.com/
# License: GPLv2 / https://github.com/MichaIng/DietPi#license

# Load DietPi-Globals
. /boot/dietpi/func/dietpi-globals
readonly G_PROGRAM_NAME='DietPi-Pre-patches'
G_CHECK_ROOT_USER
G_CHECK_ROOTFS_RW
G_INIT

# Use DietPi version from inputs to reapply pre-patches on updater internal subversion decrease
[[ $1 ]] && G_DIETPI_VERSION_CORE=$1
[[ $2 ]] && G_DIETPI_VERSION_SUB=$2

# IMPORTANT: This script can be called with DietPi v6.17, hence assure compatibility!
# - Pre-v6.29: Create G_EXEC as G_RUN_CMD wrapper
declare -F G_EXEC > /dev/null || G_EXEC(){ G_RUN_CMD "$@"; }

# v7.0: Update Jellyfin APT repo key: https://dietpi.com/phpbb/viewtopic.php?t=8703
if [[ -f '/etc/apt/trusted.gpg.d/dietpi-jellyfin.gpg' && $(date -u '+%Y%m%d' -r '/etc/apt/trusted.gpg.d/dietpi-jellyfin.gpg') -lt 20201216 ]]
then
	G_DIETPI-NOTIFY 2 'Updating Jellyfin APT repo key: https://dietpi.com/phpbb/viewtopic.php?t=8703'
	G_EXEC curl -sSfLO 'https://repo.jellyfin.org/jellyfin_team.gpg.key'
	G_EXEC gpg --dearmor -o /etc/apt/trusted.gpg.d/dietpi-jellyfin.gpg --yes jellyfin_team.gpg.key
	G_EXEC rm jellyfin_team.gpg.key
fi

# v7.1: Update Ondrej's PHP APT repo key: https://github.com/MichaIng/DietPi/issues/4219
if apt-key list '95BD4743' 2> /dev/null | grep -q 'expire[sd]: 2021-'
then
	G_DIETPI-NOTIFY 2 'Updating PHP APT repo key: https://github.com/MichaIng/DietPi/issues/4219'
	G_EXEC apt-key del '95BD4743'
	G_EXEC curl -sSfL 'https://packages.sury.org/php/apt.gpg' -o /etc/apt/trusted.gpg.d/dietpi-php.gpg
	# Clean APT cache and remove lists: https://dietpi.com/phpbb/viewtopic.php?t=8972
	# Use manual method as "dietpi-set_software apt-cache clean" has been added with v6.25 while this script can be called with earlier code.
	G_EXEC apt-get clean
	G_EXEC rm -Rf /{var/lib,tmp}/apt/lists
fi

# v7.2: Update InfluxDB APT repo key: https://github.com/MichaIng/DietPi/issues/4341
if [[ -f '/etc/apt/trusted.gpg.d/dietpi-influxdb.gpg' && $(date -u '+%Y%m%d' -r '/etc/apt/trusted.gpg.d/dietpi-influxdb.gpg') -lt 20210504 ]]
then
	G_DIETPI-NOTIFY 2 'Updating InfluxDB APT repo key: https://github.com/MichaIng/DietPi/issues/4341'
	G_EXEC curl -sSfLO 'https://repos.influxdata.com/influxdb.key'
	G_EXEC gpg --dearmor -o /etc/apt/trusted.gpg.d/dietpi-influxdb.gpg --yes influxdb.key
	G_EXEC rm influxdb.key
fi

# v7.2: Rename Bitwarden_RS into vaultwarden: https://github.com/MichaIng/DietPi/issues/4325
if [[ -d '/mnt/dietpi_userdata/bitwarden_rs' ]]
then
	G_WHIP_BUTTON_OK_TEXT='Continue'
	G_WHIP_BUTTON_CANCEL_TEXT='Cancel'
	if G_WHIP_YESNO '[ INFO ] Bitwarden_RS detected
\nDue to user confusion and to avoid any possible trademark/brand issues with the official Bitwarden server, Bitwarden_RS has been renamed to vaultwarden by its author: https://github.com/dani-garcia/vaultwarden/discussions/1642
\nTo be able to continue providing support for vaultwarden, DietPi-Update will force a re-installation. This process can take 30 minutes up to several hours, especially on slower SBCs like RPi Zero and similar, like it was on the initial Bitwarden_RS install you did.
\nContinue DietPi-Update now, if you are ok with the re-installation of vaultwarden and grab yourself a coffee or tea. If not, you are ok to cancel the update process and return later.
\nNB: All your passwords, data and config will be preserved by the re-installation process.'
	then
		G_DIETPI-NOTIFY 2 'vaultwarden will be reinstalled during DietPi-Update incremental patches.'
	else
		G_DIETPI-NOTIFY 2 'DietPi-Update aborted by user.'
		exit 1
	fi
fi

# v7.4: On Stretch, migrate Armbian APT repository to Buster, but limit to install kernel, dtb, bootloader and firmware packages: https://github.com/MichaIng/DietPi/issues/4564
if [[ $G_DISTRO -lt 5 && -f '/etc/apt/sources.list.d/armbian.list' && ! -f '/etc/apt/preferences.d/dietpi-armbian' ]]
then
	G_DIETPI-NOTIFY 2 'Since Armbian dropped support for Debian Stretch, kernel, device tree, bootloader and firmware packages will be pulled from the Buster suite instead.'
	G_EXEC eval "echo 'deb https://apt.armbian.com/ buster main' > /etc/apt/sources.list.d/armbian.list"
	G_EXEC eval "echo -e '# Only allow install of kernel, device tree, bootloader and firmware packages from Armbian Buster suite on Debian Stretch systems:
Package: linux-image-* linux-headers-* linux-dtb-* linux-u-boot-* armbian-firmware\nPin: origin apt.armbian.com\nPin-Priority: 500
\nPackage: *\nPin: origin apt.armbian.com\nPin-Priority: -1' > /etc/apt/preferences.d/dietpi-armbian"
fi

# v7.4
if getent passwd debian-transmission > /dev/null && ! getent group debian-transmission > /dev/null
then
	G_DIETPI-NOTIFY 2 'Recreating the "debian-transmission" group for the "debian-transmission" user to prevent Transmission package upgrade issues: https://github.com/MichaIng/DietPi/issues/4244'
	G_EXEC groupadd -r debian-transmission
	G_EXEC usermod -aG debian-transmission debian-transmission

fi

# v7.6
if [[ $G_HW_MODEL -le 9 && -f '/etc/apt/preferences.d/dietpi-lxde' ]] && ! grep -q ' lx\*$' /etc/apt/preferences.d/dietpi-lxde
then
	G_DIETPI-NOTIFY 2 'Updating the Raspberry Pi desktop package blocks'
	G_EXEC sed -i '/^Package:/c\Package: openbox* obconf* libob* pcmanfm* libfm* libgtk* lx*' /etc/apt/preferences.d/dietpi-lxde
fi

# v7.7
if (( $G_DIETPI_VERSION_CORE < 7 || ( $G_DIETPI_VERSION_CORE == 7 && $G_DIETPI_VERSION_SUB < 7 ) )) && [[ $G_HW_ARCH == 10 && $(findmnt -Ufnro FSTYPE -M /boot) == 'vfat' ]]
then
	G_DIETPI-NOTIFY 2 'Creating kernel upgrade hook to remove existing files from /boot FAT partition before installing the new files: https://github.com/MichaIng/DietPi/issues/4788'
	G_EXEC mkdir -p /etc/kernel/preinst.d
	cat << '_EOF_' > /etc/kernel/preinst.d/dietpi
#!/bin/sh -e
# Remove old kernel files if existing: https://github.com/MichaIng/DietPi/issues/4788
{
# Fail if the package name was not passed, which is done when being invoked by dpkg
if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]
then
        echo 'DPKG_MAINTSCRIPT_PACKAGE was not set, this script must be invoked by dpkg.'
        exit 1
fi
# Loop through files in /boot, shipped by the package, and remove them, if existing
for file in $(dpkg -L "$DPKG_MAINTSCRIPT_PACKAGE" | grep '^/boot/')
do
        [ ! -f "$file" ] || rm "$file"
done
}
_EOF_
	G_EXEC chmod +x /etc/kernel/preinst.d/dietpi
fi

# v7.7
if [[ -f '/etc/apt/sources.list.d/armbian.list' ]] && grep -q 'https://apt.armbian.com' /etc/apt/sources.list.d/armbian.list
then
	G_DIETPI-NOTIFY 2 'Connecting to apt.armbian.com via plain HTTP until their router handles HTTPS redirects reliably'
	G_EXEC sed -i 's|https://apt.armbian.com|http://apt.armbian.com|' /etc/apt/sources.list.d/armbian.list
fi

# v7.7
if (( $G_DIETPI_VERSION_CORE < 7 || ( $G_DIETPI_VERSION_CORE == 7 && $G_DIETPI_VERSION_SUB < 7 ) ))
then
	G_DIETPI-NOTIFY 2 'Connecting to Mosquitto and Webmin repositories via plain HTTP once until latest OpenSSL has been installed: https://github.com/MichaIng/DietPi/issues/4795'
	G_EXEC sed -Ei 's#https://(repo.mosquitto.org|download.webmin.com)#http://\1#' /etc/apt/sources.list
	[[ $(find /etc/apt/sources.list/*.list 2> /dev/null) ]] && G_EXEC sed -Ei 's#https://(repo.mosquitto.org|download.webmin.com)#http://\1#' /etc/apt/sources.list.d/*.list

	# Add execute permissions to kernel/initramfs hooks
	[[ -f '/etc/initramfs/post-update.d/99-dietpi-uboot' && ! -x '/etc/initramfs/post-update.d/99-dietpi-uboot' ]] && G_EXEC chmod +x /etc/initramfs/post-update.d/99-dietpi-uboot
	[[ -f '/etc/kernel/preinst.d/dietpi-initramfs_cleanup' && ! -x '/etc/kernel/preinst.d/dietpi-initramfs_cleanup' ]] && G_EXEC chmod +x /etc/kernel/preinst.d/dietpi-initramfs_cleanup
fi

# v7.5: Perform Debian suite change once, if the installed APT version does not allow it by default yet
if (( $G_DIETPI_VERSION_CORE < 7 || ( $G_DIETPI_VERSION_CORE == 7 && $G_DIETPI_VERSION_SUB < 5 ) )) && dpkg --compare-versions "$(dpkg-query -Wf '${VERSION}' apt)" lt 1.8.2.3
then
	G_DIETPI-NOTIFY 2 'Debian Bullseye has been released, so we accept the repository suite change once.'
	G_EXEC apt-get -o 'Acquire::AllowReleaseInfoChange::Suite=true' -q update
fi

# v8.0: ARMv6: Remove Mosquitto repository: https://github.com/MichaIng/DietPi/issues/5140
if (( $G_HW_ARCH == 1 )) && (( $G_DIETPI_VERSION_CORE < 8 || ( $G_DIETPI_VERSION_CORE == 8 && $G_DIETPI_VERSION_SUB < 0 ) )) && [[ -f '/etc/apt/sources.list.d/dietpi-mosquitto.list' ]]
then
	G_DIETPI-NOTIFY 2 'Removing Mosquitto APT repository as the latest builds are not compatible with ARMv6: https://github.com/MichaIng/DietPi/issues/5140'
	G_EXEC rm /etc/apt/sources.list.d/dietpi-mosquitto.list
	[[ -f '/etc/apt/trusted.gpg.d/dietpi-mosquitto.gpg' ]] && G_EXEC rm /etc/apt/trusted.gpg.d/dietpi-mosquitto.gpg
fi

# v8.2: Remove immutable flag from MS VSCode repo and key, when present, else the "raspberrypi-sys-mods" package and our own patch cannot remove them: https://github.com/MichaIng/DietPi/issues/5267
if (( $G_HW_MODEL < 10 )) && (( $G_DIETPI_VERSION_CORE < 8 || ( $G_DIETPI_VERSION_CORE == 8 && $G_DIETPI_VERSION_SUB < 2 ) ))
then
	[[ -f '/etc/apt/trusted.gpg.d/microsoft.gpg' && $(lsattr /etc/apt/trusted.gpg.d/microsoft.gpg 2> /dev/null) == *'i'* ]] && G_EXEC chattr -i /etc/apt/trusted.gpg.d/microsoft.gpg
	[[ -f '/etc/apt/sources.list.d/vscode.list' && $(lsattr /etc/apt/sources.list.d/vscode.list 2> /dev/null) == *'i'* ]] && G_EXEC chattr -i /etc/apt/sources.list.d/vscode.list
fi

# v8.2: https://github.com/MichaIng/DietPi/commit/c52e812
# shellcheck disable=SC2016
if (( $G_DIETPI_VERSION_CORE < 8 || ( $G_DIETPI_VERSION_CORE == 8 && $G_DIETPI_VERSION_SUB < 2 ) )) && grep -q 'chmod -R g-w "DietPi-\$G_GITBRANCH"' /boot/dietpi/dietpi-update
then
	GITBRANCH_TARGET=$(sed -n '/^[[:blank:]]*DEV_GITBRANCH=/{s/^[^=]*=//p;q}' /boot/dietpi.txt)
	[[ $GITBRANCH_TARGET == "$G_GITBRANCH" ]] || G_EXEC ln -s '/tmp/DietPi-Update/DietPi-'{"$GITBRANCH_TARGET","$G_GITBRANCH"}
fi

# v8.3: https://forum.armbian.com/topic/20133-nanopi-neo3-dtb-gone-since-linux-dtb-current-rockchip64-22021/
if (( $G_DIETPI_VERSION_CORE < 8 || ( $G_DIETPI_VERSION_CORE == 8 && $G_DIETPI_VERSION_SUB < 3 ) )) && (( $G_HW_MODEL == 56 ))
then
	G_DIETPI-NOTIFY 2 'Switching on NanoPi NEO3 to NanoPi R2 rev00 device tree to prevent unbootable system, since the NEO3 device tree has been removed with lastet Armbian kernel: https://forum.armbian.com/topic/20133-nanopi-neo3-dtb-gone-since-linux-dtb-current-rockchip64-22021/'
	G_EXEC sed -i 's/rk3328-nanopi-neo3-rev02.dtb/rk3328-nanopi-r2-rev00.dtb/' /boot/armbianEnv.txt
fi

# v8.4/v8.5: https://github.com/MichaIng/DietPi/issues/5467
if (( $G_DIETPI_VERSION_CORE < 8 || ( $G_DIETPI_VERSION_CORE == 8 && $G_DIETPI_VERSION_SUB < 5 ) )) && (( $G_DISTRO > 5 )) && dpkg-query -s systemd-timesyncd &> /dev/null && [[ $(apt-mark showauto systemd-timesyncd) ]]
then
	G_DIETPI-NOTIFY 2 'Marking systemd-timesyncd as manually installed to prevent its autoremoval'
	G_EXEC apt-mark manual systemd-timesyncd
fi

# v8.6
if (( $G_DIETPI_VERSION_CORE < 8 || ( $G_DIETPI_VERSION_CORE == 8 && $G_DIETPI_VERSION_SUB < 6 ) )) && [[ -f '/etc/kernel/postinst.d/dietpi-initramfs_cleanup' ]]
then
	G_DIETPI-NOTIFY 2 'Updating initramfs cleanup script'
	cat << '_EOF_' > /etc/kernel/postinst.d/dietpi-initramfs_cleanup
#!/bin/dash
echo 'Removing obsolete initramfs images'
find /boot -maxdepth 1 -name 'initrd.img-*' -o -name 'uInitrd-*' | while read -r f
do
	[ ! -d "/lib/modules/${f#*-}" ] || continue
	rm -v "$f"
done
exit 0
_EOF_
	G_EXEC chmod +x /etc/kernel/postinst.d/dietpi-initramfs_cleanup
	[[ -d '/etc/kernel/postrm.d' ]] || G_EXEC mkdir /etc/kernel/postrm.d
	G_EXEC ln -sf /etc/kernel/post{inst,rm}.d/dietpi-initramfs_cleanup
fi

# v8.7
if (( $G_DIETPI_VERSION_CORE < 8 || ( $G_DIETPI_VERSION_CORE == 8 && $G_DIETPI_VERSION_SUB < 7 ) )) && [[ -f '/etc/apt/sources.list.d/dietpi-tailscale.list' && ! -f '/etc/apt/trusted.gpg.d/dietpi-tailscale.gpg' ]]
then
	G_DIETPI-NOTIFY 2 'Removing invalid Tailscale APT list'
	G_EXEC rm /etc/apt/sources.list.d/dietpi-tailscale.list
fi

exit 0
}
