#!/bin/bash
# shellcheck disable=SC2034
# Available DietPi version
G_REMOTE_VERSION_CORE=8
G_REMOTE_VERSION_SUB=15
G_REMOTE_VERSION_RC=2
# Minimum DietPi version to allow update
G_MIN_VERSION_CORE=6
G_MIN_VERSION_SUB=14
# Alternative Git branch to automatically migrate to when DietPi version is too low
G_OLD_VERSION_BRANCH='pre-v6.14'
# Minimum Debian version to allow update
G_MIN_DEBIAN=5
# Alternative Git branch to automatically migrate to when Debian version is too low
G_OLD_DEBIAN_BRANCH='stretch'
# Live patches
G_LIVE_PATCH_DESC=('Fix some software installs after recent kernel upgrade on RPi 4 with 32-bit OS/userland')
# shellcheck disable=SC2016
G_LIVE_PATCH_COND=('[[ $G_HW_MODEL == 4 && $(dpkg --print-architecture) == armhf ]] && ! grep -q '\''\[\[ $G_HW_ARCH == 3 && $(dpkg --print-architecture) == armhf ]] && G_HW_ARCH=2 G_HW_ARCH_NAME=armv7l'\'' /boot/dietpi/dietpi-software')
# shellcheck disable=SC2016
G_LIVE_PATCH=('sed -i '\''/declare -A aSOFTWARE_AVAIL_G_DISTRO/a\\t[[ $G_HW_ARCH == 3 && $(dpkg --print-architecture) == armhf ]] && G_HW_ARCH=2 G_HW_ARCH_NAME=armv7l'\'' /boot/dietpi/dietpi-software')
