#!/bin/bash
# shellcheck disable=SC2034
# Available DietPi version
G_REMOTE_VERSION_CORE=8
G_REMOTE_VERSION_SUB=14
G_REMOTE_VERSION_RC=-1
# Minimum DietPi version to allow update
G_MIN_VERSION_CORE=6
G_MIN_VERSION_SUB=14
# Alternative Git branch to automatically migrate to when DietPi version is too low
G_OLD_VERSION_BRANCH='pre-v6.14'
# Minimum Debian version to allow update
G_MIN_DEBIAN=5
# Alternative Git branch to automatically migrate to when Debian version is too low
G_OLD_DEBIAN_BRANCH='stretch'
# Live patches
G_LIVE_PATCH_DESC=(
	[0]='Fix Portainer and Roon Extension Manager installs: https://github.com/MichaIng/DietPi/issues/6065'
	[1]='Fix PHP install on Bookworm by moving to PHP 8.2'
)
# shellcheck disable=SC2016
G_LIVE_PATCH_COND=(
	[0]='! grep -q '\''systemctl start docker\.socket'\'' /boot/dietpi/dietpi-software'
	[1]='[[ $G_DISTRO == 7 ]] && grep -q "PHP_VERSION='\''8\.1'\''" /boot/dietpi/dietpi-software'
)
G_LIVE_PATCH=(
	[0]='sed -i '\''/^			G_EXEC systemctl unmask docker/a\			G_EXEC systemctl start docker.socket'\'' /boot/dietpi/dietpi-software'
	[1]='sed -i "s/PHP_VERSION='\''8\.1'\''/PHP_VERSION='\''8.2'\''/" /boot/dietpi/dietpi-software; sed -i '\''s/php8\.1-fpm/php8.2-fpm/'\'' /boot/dietpi/dietpi-services'
)
