#!/bin/dash
#////////////////////////////////////
# DietPi OpenTyrian Run Script
#
#////////////////////////////////////
# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
#
# Info:
# - Starts OpenTyrian
# - Starts X if not already running
#
# Usage:
# run
#////////////////////////////////////
FP_DIR='/usr/games/opentyrian'

# Xserver already running
if pgrep Xorg &> /dev/null; then

	$FP_DIR/opentyrian -t $FP_DIR/data

# No X (init X server)
else

	xinit $FP_DIR/opentyrian -t $FP_DIR/data

fi
