#!/bin/bash
{
	#////////////////////////////////////
	# DietPi NordVPN
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - GUI to setup a NordVPN connection
	# - Automatically starts service during boot
	# Usage:
	# - /DietPi/dietpi/misc/dietpi-nordvpn
	#////////////////////////////////////

	# Import DietPi-Globals --------------------------------------------------------------
	. /DietPi/dietpi/func/dietpi-globals
	G_PROGRAM_NAME='DietPi-NordVPN'
	G_CHECK_ROOT_USER
	G_CHECK_ROOTFS_RW
	G_INIT
	# Import DietPi-Globals --------------------------------------------------------------

	FP_SETTINGS_DIETPI='/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/settings_dietpi.conf'
	FP_SETTINGS_OVPN='/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/settings_ovpn.conf'
	FP_SETTINGS_UP='/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/up.sh'
	FP_SETTINGS_DOWN='/var/lib/dietpi/dietpi-software/installed/dietpi-nordvpn/down.sh'
	NORDVPN_USERNAME=''
	NORDVPN_PASSWORD=''
	NORDVPN_SERVER=''
	PROTOCOL='udp'

	NET_DEV='tun0'
	NORDVPN_SERVICE=0
	NORDVPN_CONNECTED=0
	MAX_WAIT_FOR_CONNECTION=5
	WAN_IP=''

	Update_Wan_Ip(){ WAN_IP=$(curl -sLm 2 https://dietpi.com/myip.php 2>&1); }

	Init(){

		# Check installed
		until grep -q 'aSOFTWARE_INSTALL_STATE\[171\]=2' /DietPi/dietpi/.installed
		do

			if G_WHIP_YESNO "$G_PROGRAM_NAME is not installed, would you like to install it now?"; then

				/DietPi/dietpi/dietpi-software install 171

			else

				TARGETMENUID=-1 #Exit path without save.
				break

			fi

		done

		# Check service exists
		[[ -f '/lib/systemd/system/dietpi-nordvpn.service' ]] && NORDVPN_SERVICE=1

		Read_Settings

	}

	Check_Connected(){

		NORDVPN_CONNECTED=0
		#systemctl status dietpi-nordvpn | grep -qi 'initialization sequence completed'
		ip r s dev $NET_DEV &>/dev/null && NORDVPN_CONNECTED=1

		return $(( ! $NORDVPN_CONNECTED ))

	}

	Read_Settings(){ [[ -f $FP_SETTINGS_DIETPI ]] && . $FP_SETTINGS_DIETPI; }

	Save_Settings(){

		if [[ ! $NORDVPN_SERVER || ! $NORDVPN_USERNAME || ! $NORDVPN_PASSWORD ]]; then

			G_WHIP_MSG '[FAILED] You need to enter your NordVPN username + password and select a server, before settings can be applied.'
			return 1

		fi

		(( $NORDVPN_SERVICE )) && systemctl stop dietpi-nordvpn

		cat << _EOF_ > $FP_SETTINGS_OVPN
${NORDVPN_USERNAME//\'/\'\\\'\'}
${NORDVPN_PASSWORD//\'/\'\\\'\'}
_EOF_

		cat << _EOF_ > $FP_SETTINGS_DIETPI
NORDVPN_USERNAME='${NORDVPN_USERNAME//\'/\'\\\'\'}'
NORDVPN_PASSWORD='${NORDVPN_PASSWORD//\'/\'\\\'\'}'
NORDVPN_SERVER='$NORDVPN_SERVER'
PROTOCOL='$PROTOCOL'
_EOF_

		local fp_ovpn="/etc/openvpn/ovpn_$PROTOCOL/$NORDVPN_SERVER"
		G_CONFIG_INJECT 'auth-user-pass([[:blank:]]|$)' "auth-user-pass $FP_SETTINGS_OVPN" $fp_ovpn
		[[ -f $FP_SETTINGS_UP || -f $FP_SETTINGS_DOWN ]] && G_CONFIG_INJECT 'script-security[[:blank:]]' 'script-security 2' $fp_ovpn 'auth[[:blank:]]' || sed -i '/^[[:blank:]]*script-security[[:blank:]]/d' $fp_ovpn
		[[ -f $FP_SETTINGS_UP ]] && G_CONFIG_INJECT 'route-up[[:blank:]]' "route-up $FP_SETTINGS_UP" $fp_ovpn 'auth[[:blank:]]' || sed -i '/^[[:blank:]]*up[[:blank:]]/d' $fp_ovpn
		[[ -f $FP_SETTINGS_DOWN ]] && G_CONFIG_INJECT 'route-pre-down[[:blank:]]' "route-pre-down $FP_SETTINGS_DOWN" $fp_ovpn 'auth[[:blank:]]' || sed -i '/^[[:blank:]]*down[[:blank:]]/d' $fp_ovpn

		chmod 600 $FP_SETTINGS_OVPN $FP_SETTINGS_DIETPI $fp_ovpn
		chown root:root $FP_SETTINGS_OVPN $FP_SETTINGS_DIETPI $fp_ovpn

		cat << _EOF_ > /lib/systemd/system/dietpi-nordvpn.service
[Unit]
Description=NordVPN (DietPi)
After=network.target dietpi-boot.service

[Service]
ExecStart=$(command -v openvpn) $fp_ovpn

[Install]
WantedBy=multi-user.target
_EOF_
		systemctl daemon-reload
		NORDVPN_SERVICE=1
		G_RUN_CMD systemctl restart dietpi-nordvpn

		for (( i=1; i<=$MAX_WAIT_FOR_CONNECTION; i++ ))
		do

			Check_Connected && break

			G_DIETPI-NOTIFY 2 "Waiting for connection ($i/$MAX_WAIT_FOR_CONNECTION)"
			sleep 1

		done

		(( $NORDVPN_CONNECTED )) || G_WHIP_MSG "Connection failed/time out: $NORDVPN_SERVER\n\nPlease verify account details are correct.\n\nIf problems persist, please check the status of 'systemctl status dietpi-nordvpn -l'"

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Whip
	#/////////////////////////////////////////////////////////////////////////////////////
	TARGETMENUID=0
	LAST_SELECTED_NAME='Username'

	Menu_Exit(){

		G_WHIP_SIZE_X_MAX=50
		G_WHIP_YESNO "Exit $G_PROGRAM_NAME?" && TARGETMENUID=-1 # Exit

	}

	# TARGETMENUID=0
	Menu_Main(){

		Update_Wan_Ip

		local text_status="Status:\n - WAN IP: $WAN_IP\n"
		if (( $NORDVPN_SERVICE )) && Check_Connected; then

			text_status+=" - Connected : $NORDVPN_SERVER\n"

			local net_rx_byte=0
			local net_tx_byte=0
			local net_rx_mb='N/A'
			local net_tx_mb='N/A'

			if [[ -f /sys/class/net/$NET_DEV/statistics/rx_bytes && -f /sys/class/net/$NET_DEV/statistics/tx_bytes ]]; then

				net_rx_byte=$(</sys/class/net/$NET_DEV/statistics/rx_bytes)
				disable_error=1 G_CHECK_VALIDINT "$net_rx_byte" 0 && net_rx_mb="$(( $net_rx_byte / 1024 / 1024 )) MiB"

				net_tx_byte=$(</sys/class/net/$NET_DEV/statistics/tx_bytes)
				disable_error=1 G_CHECK_VALIDINT "$net_tx_byte" 0 && net_tx_mb="$(( $net_tx_byte / 1024 / 1024 )) MiB"

			fi

			text_status+=" - Usage     : Sent = $net_tx_mb | Recieved = $net_rx_mb"

		else

			(( $NORDVPN_SERVICE )) && text_status+=' - Disconnected' || text_status+=' - Not configured'
			text_status+='\n - NordVPN subscription: https://go.nordvpn.net/aff_c?offer_id=15&aff_id=5305&url_id=902'

		fi

		G_WHIP_MENU_ARRAY=('' '●─ Global Options ')
		G_WHIP_MENU_ARRAY+=('Username' ": [$NORDVPN_USERNAME]")
		G_WHIP_MENU_ARRAY+=('Password' ": [${NORDVPN_PASSWORD//?/*}]")
		G_WHIP_MENU_ARRAY+=('Server' ": [$NORDVPN_SERVER]")
		if (( $NORDVPN_SERVICE )); then

			local autostart_enabled=0 autostart_text='Off'
			systemctl -q is-enabled dietpi-nordvpn && { autostart_enabled=1 autostart_text='On'; }
			G_WHIP_MENU_ARRAY+=('Auto start' ": [$autostart_text]")

			G_WHIP_MENU_ARRAY+=('Refresh' ': Update VPN connection status')
			(( $NORDVPN_CONNECTED )) && G_WHIP_MENU_ARRAY+=('Disconnect' '')

		fi
		G_WHIP_MENU_ARRAY+=('' '●─ Connection Up and Down Scripts ')
		G_WHIP_MENU_ARRAY+=('Edit Up' ': This script gets executed right after the VPN is connected')
		G_WHIP_MENU_ARRAY+=('Edit Down' ': This script gets executed right after the VPN is disconnected')
		G_WHIP_MENU_ARRAY+=('' '●─ Save Settings ')
		G_WHIP_MENU_ARRAY+=('Apply' ': Save settings and restart VPN connection')

		G_WHIP_DEFAULT_ITEM=$LAST_SELECTED_NAME
		G_WHIP_BUTTON_CANCEL_TEXT='Exit'
		if G_WHIP_MENU "$text_status"; then

			LAST_SELECTED_NAME=$G_WHIP_RETURNED_VALUE

			if [[ $G_WHIP_RETURNED_VALUE == 'Apply' ]]; then

				Save_Settings

			elif [[ $G_WHIP_RETURNED_VALUE == 'Edit Up' ]]; then

				[[ -f $FP_SETTINGS_UP ]] || echo -e '#!/bin/bash\n# Clear this file completely, including line breaks, to have it removed.' > $FP_SETTINGS_UP
				nano $FP_SETTINGS_UP
				(( $(stat -c %s $FP_SETTINGS_UP) )) && chmod 700 $FP_SETTINGS_UP || rm $FP_SETTINGS_UP

			elif [[ $G_WHIP_RETURNED_VALUE == 'Edit Down' ]]; then

				[[ -f $FP_SETTINGS_DOWN ]] || echo -e '#!/bin/bash\n# Clear this file completely, including line breaks, to have it removed.' > $FP_SETTINGS_DOWN
				nano $FP_SETTINGS_DOWN
				(( $(stat -c %s $FP_SETTINGS_DOWN) )) && chmod 700 $FP_SETTINGS_DOWN || rm $FP_SETTINGS_DOWN

			elif [[ $G_WHIP_RETURNED_VALUE == 'Auto start' ]]; then

				if (( $autostart_enabled )); then

					G_RUN_CMD systemctl disable dietpi-nordvpn

				else

					G_RUN_CMD systemctl enable dietpi-nordvpn

				fi

			elif [[ $G_WHIP_RETURNED_VALUE == 'Username' ]]; then

				G_WHIP_DEFAULT_ITEM=$NORDVPN_USERNAME
				G_WHIP_INPUTBOX 'Please enter your NordVPN username:' && NORDVPN_USERNAME=$G_WHIP_RETURNED_VALUE

			elif [[ $G_WHIP_RETURNED_VALUE == 'Password' ]]; then

				G_WHIP_PASSWORD 'Please enter your NordVPN password:' && NORDVPN_PASSWORD=$result
				unset result

			elif [[ $G_WHIP_RETURNED_VALUE == 'Disconnect' ]]; then

				G_RUN_CMD systemctl stop dietpi-nordvpn
				LAST_SELECTED_NAME='Refresh'

			elif [[ $G_WHIP_RETURNED_VALUE == 'Server' ]]; then

				# - Select protocol
				G_WHIP_MENU_ARRAY=(

					'UDP' ': Recommended'
					'TCP' ''

				)

				G_WHIP_DEFAULT_ITEM=$PROTOCOL
				G_WHIP_MENU 'Please select the connection protocol type:' && PROTOCOL=${G_WHIP_RETURNED_VALUE,,}

				# - Select server
				G_DIETPI-NOTIFY 2 'Populating NordVPN server list, please wait...'
				cd /etc/openvpn/ovpn_$PROTOCOL
				G_WHIP_MENU_ARRAY=()
				for i in *.ovpn
				do

					G_WHIP_MENU_ARRAY+=("$i" '')

				done
				cd /tmp/$G_PROGRAM_NAME

				G_WHIP_DEFAULT_ITEM=$NORDVPN_SERVER
				G_WHIP_MENU 'Please select a NordVPN server to use:' && NORDVPN_SERVER=$G_WHIP_RETURNED_VALUE

			fi

		else

			Menu_Exit

		fi

	}

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	Init
	#-----------------------------------------------------------------------------------
	while (( $TARGETMENUID >= 0 ))
	do

		Menu_Main

	done
	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}
