#!/bin/bash
{
	#////////////////////////////////////
	# DietPi funtime Script
	#
	#////////////////////////////////////
	# Created by Dan Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Does absolutetly nothing useful, except:
	# - LOOKS COOL!
	#
	# Usage:
	# - Called from bordum, or, /boot/dietpi/misc/dietpi-funtime
	#////////////////////////////////////

	count=0
	mode=0
	
	passes=0
	MAX_PASSES=4

	MAX_COUNT=26
	((MAX_COUNT--))
	declare -a marker=(
	'#                         '
	' #                        '
	'  #                       '
	'   #                      '
	'    #                     '
	'     #                    '
	'      #                   '
	'       #                  '
	'        #                 '
	'         #                '
	'          #               '
	'           #              '
	'            #             '
	'             #            '
	'              #           '
	'               #          '
	'                #         '
	'                 #        '
	'                  #       '
	'                   #      '
	'                    #     '
	'                     #    '
	'                      #   '
	'                       #  '
	'                        # '
	'                         #'

	)

	while (( $passes < $MAX_PASSES ))
	do
		if (( $mode == 0 )); then
			((count++))
			if (( $count == $MAX_COUNT )); then
				mode=1
				((passes++))
			fi
		elif (( $mode == 1 )); then
			((count--))
			if (( $count == 0 )); then
				mode=0
				((passes++))
			fi
		fi
		echo -ne "\e[38;5;93m ${marker[$count]}\r"
		#echo -e "${marker[$count]}\r"
		sleep 0.03

	done

	unset marker
	
	#Put colours back to normal
	echo -e "\e[0m"

	exit

}
