#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Kodi run script:
	#
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel_haze@hotmail.com / fuzon.co.uk
	#
	#////////////////////////////////////
	#
	# Info:
	# - Runs Kodi for various hw models
	# - Fixes black screen hangs when exiting Kodi on RPi
	#
	# Usage:
	# - /DietPi/dietpi/misc/start_kodi
	# - startkodi (if alias is created in /etc/bash.bashrc)
	#////////////////////////////////////

	#/////////////////////////////////////////////////////////////////////////////////////
	#Globals
	#/////////////////////////////////////////////////////////////////////////////////////
	HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)
	DISTRO=$(sed -n 3p /DietPi/dietpi/.hw_model)

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	#Raspberry Pi - + fix for black screen on exit
	if (( $HW_MODEL < 10 )); then

		kodi-standalone
		fbset -depth 8 &> /dev/null
		fbset -depth 16 &> /dev/null
		xrefresh &> /dev/null

	#Everything else
	#-----------------------------------------------------------------------------------
	else

		#From Desktop
		if [ "$DISPLAY" ]; then
			kodi
		else
			xinit kodi-standalone
		fi

	fi

	#-----------------------------------------------------------------------------------
	#exit
	exit
	#-----------------------------------------------------------------------------------
}