#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Kodi run script:
	#
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Runs Kodi for various hw models
	# - Fixes black screen hangs when exiting Kodi on RPi
	#
	# Usage:
	# - /DietPi/dietpi/misc/start_kodi
	#////////////////////////////////////
	#Import DietPi-Globals ---------------------------------------------------------------
	# G_HW_MODEL required only
	G_HW_MODEL=$(sed -n 1p /DietPi/dietpi/.hw_model)
	##Import DietPi-Globals ---------------------------------------------------------------

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	#-----------------------------------------------------------------------------------
	#Raspberry Pi
	if (( $G_HW_MODEL < 10 )); then

		kodi-standalone

	#Everything else
	#-----------------------------------------------------------------------------------
	else

		#From Desktop
		if [[ $DISPLAY ]]; then

			#C2 fix for stuttering and laggy audio: https://github.com/Fourdee/DietPi/issues/399#issuecomment-229413994
			if (( $G_HW_MODEL == 12 )); then

				killall -w xcompmgr
				xcompmgr -a &
				sleep 2

			fi

			kodi

		else

			xinit kodi-standalone

		fi

	fi

	#-----------------------------------------------------------------------------------
	exit
	#-----------------------------------------------------------------------------------
}
