#!/bin/bash
{
	#////////////////////////////////////
	# DietPi Kodi run script:
	#
	#////////////////////////////////////
	# Created by Daniel Knight / daniel.knight@dietpi.com / dietpi.com
	#
	#////////////////////////////////////
	#
	# Info:
	# - Runs Kodi for various HW models
	# - Fixes black screen hangs when exiting Kodi on RPi
	#
	# Usage:
	# - /boot/dietpi/misc/start_kodi
	#////////////////////////////////////
	# Import DietPi-Globals --------------------------------------------------------------
	# G_HW_MODEL required only
	. /boot/dietpi/.hw_model
	# Import DietPi-Globals --------------------------------------------------------------

	#/////////////////////////////////////////////////////////////////////////////////////
	# Main Loop
	#/////////////////////////////////////////////////////////////////////////////////////
	# RPi + Odroid N2
	if (( $G_HW_MODEL < 10 || $G_HW_MODEL == 15 )); then

		kodi --standalone

	# Everything else
	# - From desktop
	elif [[ $DISPLAY ]]; then

		# C2 fix for stuttering and laggy audio: https://github.com/MichaIng/DietPi/issues/399#issuecomment-229413994
		if (( $G_HW_MODEL == 12 )); then

			killall -w xcompmgr
			xcompmgr -a &
			sleep 2

		fi

		kodi

	# - From console
	else

		xinit kodi-standalone

	fi

	#-------------------------------------------------------------------------------------
	exit
	#-------------------------------------------------------------------------------------
}
